#!/usr/bin/env python3
"""Inject myList / foodCat* / delete confirm keys into all non-fr/en ARBs."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "lib" / "l10n"

# Curated UI strings (short labels) — source: EN sense, native wording.
TRANSLATIONS: dict[str, dict[str, str]] = {
    "de": {
        "myList": "Meine Liste",
        "engagementsListName": "Verpflichtungen",
        "listCopySuffix": " (Kopie)",
        "deleteListConfirmEmpty": "„{name}“ wird gelöscht.",
        "deleteListConfirmWithItems": "„{name}“ enthält {count} Artikel. Alles wird gelöscht.",
        "foodCatFruits": "Obst",
        "foodCatVegetables": "Gemüse",
        "foodCatMushrooms": "Pilze",
        "foodCatDairy": "Milchprodukte & Eier",
        "foodCatMeat": "Fleisch",
        "foodCatDeli": "Wurstwaren",
        "foodCatFish": "Fisch & Meeresfrüchte",
        "foodCatBakery": "Bäckerei",
        "foodCatDrinks": "Getränke",
        "foodCatGrocery": "Vorrat",
        "foodCatSnacks": "Snacks",
        "foodCatDesserts": "Desserts",
        "foodCatSweets": "Süßwaren",
        "foodCatFrozen": "Tiefkühl",
        "foodCatHygiene": "Körperpflege",
        "foodCatHousehold": "Haushalt",
        "foodCatPets": "Haustiere",
        "foodCatBaby": "Baby",
        "foodCatOther": "Sonstiges",
    },
    "es": {
        "myList": "Mi lista",
        "engagementsListName": "Compromisos",
        "listCopySuffix": " (copia)",
        "deleteListConfirmEmpty": "Se eliminará «{name}».",
        "deleteListConfirmWithItems": "«{name}» tiene {count} artículo(s). Todo se eliminará.",
        "foodCatFruits": "Fruta",
        "foodCatVegetables": "Verduras",
        "foodCatMushrooms": "Setas",
        "foodCatDairy": "Lácteos y huevos",
        "foodCatMeat": "Carne",
        "foodCatDeli": "Charcutería",
        "foodCatFish": "Pescado y marisco",
        "foodCatBakery": "Panadería",
        "foodCatDrinks": "Bebidas",
        "foodCatGrocery": "Despensa",
        "foodCatSnacks": "Snacks",
        "foodCatDesserts": "Postres",
        "foodCatSweets": "Dulces",
        "foodCatFrozen": "Congelados",
        "foodCatHygiene": "Cuidado personal",
        "foodCatHousehold": "Hogar",
        "foodCatPets": "Mascotas",
        "foodCatBaby": "Bebé",
        "foodCatOther": "Otros",
    },
    "it": {
        "myList": "La mia lista",
        "engagementsListName": "Impegni",
        "listCopySuffix": " (copia)",
        "deleteListConfirmEmpty": "«{name}» verrà eliminata.",
        "deleteListConfirmWithItems": "«{name}» ha {count} articolo/i. Tutto verrà eliminato.",
        "foodCatFruits": "Frutta",
        "foodCatVegetables": "Verdura",
        "foodCatMushrooms": "Funghi",
        "foodCatDairy": "Latticini e uova",
        "foodCatMeat": "Carne",
        "foodCatDeli": "Salumi",
        "foodCatFish": "Pesce e frutti di mare",
        "foodCatBakery": "Panetteria",
        "foodCatDrinks": "Bevande",
        "foodCatGrocery": "Dispensa",
        "foodCatSnacks": "Snack",
        "foodCatDesserts": "Dessert",
        "foodCatSweets": "Dolciumi",
        "foodCatFrozen": "Surgelati",
        "foodCatHygiene": "Cura personale",
        "foodCatHousehold": "Casa",
        "foodCatPets": "Animali",
        "foodCatBaby": "Neonato",
        "foodCatOther": "Altro",
    },
    "pt": {
        "myList": "A minha lista",
        "engagementsListName": "Compromissos",
        "listCopySuffix": " (cópia)",
        "deleteListConfirmEmpty": "«{name}» será eliminada.",
        "deleteListConfirmWithItems": "«{name}» tem {count} artigo(s). Tudo será eliminado.",
        "foodCatFruits": "Fruta",
        "foodCatVegetables": "Legumes",
        "foodCatMushrooms": "Cogumelos",
        "foodCatDairy": "Laticínios e ovos",
        "foodCatMeat": "Carne",
        "foodCatDeli": "Charcutaria",
        "foodCatFish": "Peixe e marisco",
        "foodCatBakery": "Padaria",
        "foodCatDrinks": "Bebidas",
        "foodCatGrocery": "Despensa",
        "foodCatSnacks": "Snacks",
        "foodCatDesserts": "Sobremesas",
        "foodCatSweets": "Doces",
        "foodCatFrozen": "Congelados",
        "foodCatHygiene": "Higiene pessoal",
        "foodCatHousehold": "Casa",
        "foodCatPets": "Animais",
        "foodCatBaby": "Bebé",
        "foodCatOther": "Outro",
    },
    "nl": {
        "myList": "Mijn lijst",
        "engagementsListName": "Afspraken",
        "listCopySuffix": " (kopie)",
        "deleteListConfirmEmpty": "“{name}” wordt verwijderd.",
        "deleteListConfirmWithItems": "“{name}” heeft {count} artikel(en). Alles wordt verwijderd.",
        "foodCatFruits": "Fruit",
        "foodCatVegetables": "Groenten",
        "foodCatMushrooms": "Paddenstoelen",
        "foodCatDairy": "Zuivel & eieren",
        "foodCatMeat": "Vlees",
        "foodCatDeli": "Vleeswaren",
        "foodCatFish": "Vis & zeevruchten",
        "foodCatBakery": "Bakkerij",
        "foodCatDrinks": "Dranken",
        "foodCatGrocery": "Voorraad",
        "foodCatSnacks": "Snacks",
        "foodCatDesserts": "Desserts",
        "foodCatSweets": "Snoep",
        "foodCatFrozen": "Diepvries",
        "foodCatHygiene": "Persoonlijke verzorging",
        "foodCatHousehold": "Huishouden",
        "foodCatPets": "Huisdieren",
        "foodCatBaby": "Baby",
        "foodCatOther": "Overig",
    },
    "pl": {
        "myList": "Moja lista",
        "engagementsListName": "Zobowiązania",
        "listCopySuffix": " (kopia)",
        "deleteListConfirmEmpty": "„{name}” zostanie usunięta.",
        "deleteListConfirmWithItems": "„{name}” ma {count} pozycji. Wszystko zostanie usunięte.",
        "foodCatFruits": "Owoce",
        "foodCatVegetables": "Warzywa",
        "foodCatMushrooms": "Grzyby",
        "foodCatDairy": "Nabiał i jajka",
        "foodCatMeat": "Mięso",
        "foodCatDeli": "Wędliny",
        "foodCatFish": "Ryby i owoce morza",
        "foodCatBakery": "Piekarnia",
        "foodCatDrinks": "Napoje",
        "foodCatGrocery": "Spiżarnia",
        "foodCatSnacks": "Przekąski",
        "foodCatDesserts": "Desery",
        "foodCatSweets": "Słodycze",
        "foodCatFrozen": "Mrożonki",
        "foodCatHygiene": "Higiena osobista",
        "foodCatHousehold": "Dom",
        "foodCatPets": "Zwierzęta",
        "foodCatBaby": "Niemowlę",
        "foodCatOther": "Inne",
    },
    "ru": {
        "myList": "Мой список",
        "engagementsListName": "Обязательства",
        "listCopySuffix": " (копия)",
        "deleteListConfirmEmpty": "«{name}» будет удалён.",
        "deleteListConfirmWithItems": "В «{name}» {count} позиц. Всё будет удалено.",
        "foodCatFruits": "Фрукты",
        "foodCatVegetables": "Овощи",
        "foodCatMushrooms": "Грибы",
        "foodCatDairy": "Молочные продукты и яйца",
        "foodCatMeat": "Мясо",
        "foodCatDeli": "Колбасы",
        "foodCatFish": "Рыба и морепродукты",
        "foodCatBakery": "Выпечка",
        "foodCatDrinks": "Напитки",
        "foodCatGrocery": "Бакалея",
        "foodCatSnacks": "Закуски",
        "foodCatDesserts": "Десерты",
        "foodCatSweets": "Сладости",
        "foodCatFrozen": "Заморозка",
        "foodCatHygiene": "Гигиена",
        "foodCatHousehold": "Дом",
        "foodCatPets": "Питомцы",
        "foodCatBaby": "Детское",
        "foodCatOther": "Другое",
    },
    "uk": {
        "myList": "Мій список",
        "engagementsListName": "Зобов’язання",
        "listCopySuffix": " (копія)",
        "deleteListConfirmEmpty": "«{name}» буде видалено.",
        "deleteListConfirmWithItems": "У «{name}» {count} позиц. Усе буде видалено.",
        "foodCatFruits": "Фрукти",
        "foodCatVegetables": "Овочі",
        "foodCatMushrooms": "Гриби",
        "foodCatDairy": "Молочні продукти та яйця",
        "foodCatMeat": "М’ясо",
        "foodCatDeli": "Ковбаси",
        "foodCatFish": "Риба та морепродукти",
        "foodCatBakery": "Випічка",
        "foodCatDrinks": "Напої",
        "foodCatGrocery": "Бакалія",
        "foodCatSnacks": "Снеки",
        "foodCatDesserts": "Десерти",
        "foodCatSweets": "Солодощі",
        "foodCatFrozen": "Заморозка",
        "foodCatHygiene": "Гігієна",
        "foodCatHousehold": "Дім",
        "foodCatPets": "Улюбленці",
        "foodCatBaby": "Дитяче",
        "foodCatOther": "Інше",
    },
    "ja": {
        "myList": "マイリスト",
        "engagementsListName": "約束・用事",
        "listCopySuffix": "（コピー）",
        "deleteListConfirmEmpty": "「{name}」を削除します。",
        "deleteListConfirmWithItems": "「{name}」には {count} 件あります。すべて削除されます。",
        "foodCatFruits": "果物",
        "foodCatVegetables": "野菜",
        "foodCatMushrooms": "きのこ",
        "foodCatDairy": "乳製品・卵",
        "foodCatMeat": "肉",
        "foodCatDeli": "加工肉",
        "foodCatFish": "魚介",
        "foodCatBakery": "パン・菓子パン",
        "foodCatDrinks": "飲み物",
        "foodCatGrocery": "食料品",
        "foodCatSnacks": "スナック",
        "foodCatDesserts": "デザート",
        "foodCatSweets": "スイーツ・菓子",
        "foodCatFrozen": "冷凍食品",
        "foodCatHygiene": "衛生・ケア",
        "foodCatHousehold": "生活用品",
        "foodCatPets": "ペット",
        "foodCatBaby": "ベビー",
        "foodCatOther": "その他",
    },
    "ko": {
        "myList": "내 목록",
        "engagementsListName": "약속·할 일",
        "listCopySuffix": " (복사본)",
        "deleteListConfirmEmpty": "“{name}”이(가) 삭제됩니다.",
        "deleteListConfirmWithItems": "“{name}”에 {count}개 항목이 있습니다. 모두 삭제됩니다.",
        "foodCatFruits": "과일",
        "foodCatVegetables": "채소",
        "foodCatMushrooms": "버섯",
        "foodCatDairy": "유제품·달걀",
        "foodCatMeat": "육류",
        "foodCatDeli": "가공육",
        "foodCatFish": "수산물",
        "foodCatBakery": "베이커리",
        "foodCatDrinks": "음료",
        "foodCatGrocery": "식료품",
        "foodCatSnacks": "스낵",
        "foodCatDesserts": "디저트",
        "foodCatSweets": "과자·당류",
        "foodCatFrozen": "냉동",
        "foodCatHygiene": "위생·케어",
        "foodCatHousehold": "생활용품",
        "foodCatPets": "반려동물",
        "foodCatBaby": "유아",
        "foodCatOther": "기타",
    },
    "zh": {
        "myList": "我的清单",
        "engagementsListName": "待办承诺",
        "listCopySuffix": "（副本）",
        "deleteListConfirmEmpty": "将删除“{name}”。",
        "deleteListConfirmWithItems": "“{name}”有 {count} 项，全部将被删除。",
        "foodCatFruits": "水果",
        "foodCatVegetables": "蔬菜",
        "foodCatMushrooms": "菌菇",
        "foodCatDairy": "乳品与蛋",
        "foodCatMeat": "肉类",
        "foodCatDeli": "熟食",
        "foodCatFish": "海鲜",
        "foodCatBakery": "烘焙",
        "foodCatDrinks": "饮料",
        "foodCatGrocery": "粮油干货",
        "foodCatSnacks": "零食",
        "foodCatDesserts": "甜点",
        "foodCatSweets": "糖果甜食",
        "foodCatFrozen": "冷冻",
        "foodCatHygiene": "个人护理",
        "foodCatHousehold": "家居清洁",
        "foodCatPets": "宠物",
        "foodCatBaby": "母婴",
        "foodCatOther": "其他",
    },
    "ar": {
        "myList": "قائمتي",
        "engagementsListName": "التزامات",
        "listCopySuffix": " (نسخة)",
        "deleteListConfirmEmpty": "سيتم حذف «{name}».",
        "deleteListConfirmWithItems": "«{name}» يحتوي على {count} عنصرًا. سيتم حذف الكل.",
        "foodCatFruits": "فواكه",
        "foodCatVegetables": "خضروات",
        "foodCatMushrooms": "فطر",
        "foodCatDairy": "ألبان وبيض",
        "foodCatMeat": "لحوم",
        "foodCatDeli": "لحوم معالجة",
        "foodCatFish": "أسماك ومأكولات بحرية",
        "foodCatBakery": "مخبوزات",
        "foodCatDrinks": "مشروبات",
        "foodCatGrocery": "بقالة",
        "foodCatSnacks": "وجبات خفيفة",
        "foodCatDesserts": "حلويات",
        "foodCatSweets": "سكريات",
        "foodCatFrozen": "مجمدات",
        "foodCatHygiene": "عناية شخصية",
        "foodCatHousehold": "منزل",
        "foodCatPets": "حيوانات أليفة",
        "foodCatBaby": "أطفال",
        "foodCatOther": "أخرى",
    },
    "he": {
        "myList": "הרשימה שלי",
        "engagementsListName": "התחייבויות",
        "listCopySuffix": " (עותק)",
        "deleteListConfirmEmpty": "«{name}» תימחק.",
        "deleteListConfirmWithItems": "ב«{name}» יש {count} פריטים. הכול יימחק.",
        "foodCatFruits": "פירות",
        "foodCatVegetables": "ירקות",
        "foodCatMushrooms": "פטריות",
        "foodCatDairy": "מוצרי חלב וביצים",
        "foodCatMeat": "בשר",
        "foodCatDeli": "נקניקים",
        "foodCatFish": "דגים ומאכלי ים",
        "foodCatBakery": "מאפים",
        "foodCatDrinks": "משקאות",
        "foodCatGrocery": "מזווה",
        "foodCatSnacks": "חטיפים",
        "foodCatDesserts": "קינוחים",
        "foodCatSweets": "ממתקים",
        "foodCatFrozen": "קפואים",
        "foodCatHygiene": "טיפוח",
        "foodCatHousehold": "בית",
        "foodCatPets": "חיות מחמד",
        "foodCatBaby": "תינוקות",
        "foodCatOther": "אחר",
    },
    "hi": {
        "myList": "मेरी सूची",
        "engagementsListName": "प्रतिबद्धताएँ",
        "listCopySuffix": " (प्रतिलिपि)",
        "deleteListConfirmEmpty": "“{name}” हटा दी जाएगी।",
        "deleteListConfirmWithItems": "“{name}” में {count} आइटम हैं। सब हटा दिया जाएगा।",
        "foodCatFruits": "फल",
        "foodCatVegetables": "सब्ज़ियाँ",
        "foodCatMushrooms": "मशरूम",
        "foodCatDairy": "डेयरी और अंडे",
        "foodCatMeat": "मांस",
        "foodCatDeli": "प्रोसेस्ड मीट",
        "foodCatFish": "मछली और समुद्री भोजन",
        "foodCatBakery": "बेकरी",
        "foodCatDrinks": "पेय",
        "foodCatGrocery": "किराना",
        "foodCatSnacks": "स्नैक्स",
        "foodCatDesserts": "मिठाइयाँ",
        "foodCatSweets": "मिठाई",
        "foodCatFrozen": "फ़्रोज़न",
        "foodCatHygiene": "व्यक्तिगत देखभाल",
        "foodCatHousehold": "घरेलू",
        "foodCatPets": "पालतू",
        "foodCatBaby": "शिशु",
        "foodCatOther": "अन्य",
    },
    "tr": {
        "myList": "Listem",
        "engagementsListName": "Taahhütler",
        "listCopySuffix": " (kopya)",
        "deleteListConfirmEmpty": "“{name}” silinecek.",
        "deleteListConfirmWithItems": "“{name}” içinde {count} öğe var. Hepsi silinecek.",
        "foodCatFruits": "Meyve",
        "foodCatVegetables": "Sebze",
        "foodCatMushrooms": "Mantar",
        "foodCatDairy": "Süt ürünleri ve yumurta",
        "foodCatMeat": "Et",
        "foodCatDeli": "Şarküteri",
        "foodCatFish": "Balık ve deniz ürünleri",
        "foodCatBakery": "Fırın",
        "foodCatDrinks": "İçecekler",
        "foodCatGrocery": "Kiler",
        "foodCatSnacks": "Atıştırmalık",
        "foodCatDesserts": "Tatlılar",
        "foodCatSweets": "Şekerlemeler",
        "foodCatFrozen": "Donuk",
        "foodCatHygiene": "Kişisel bakım",
        "foodCatHousehold": "Ev",
        "foodCatPets": "Evcil hayvan",
        "foodCatBaby": "Bebek",
        "foodCatOther": "Diğer",
    },
    "sv": {
        "myList": "Min lista",
        "engagementsListName": "Åtaganden",
        "listCopySuffix": " (kopia)",
        "deleteListConfirmEmpty": "“{name}” kommer att raderas.",
        "deleteListConfirmWithItems": "“{name}” har {count} artiklar. Allt raderas.",
        "foodCatFruits": "Frukt",
        "foodCatVegetables": "Grönsaker",
        "foodCatMushrooms": "Svamp",
        "foodCatDairy": "Mejeri & ägg",
        "foodCatMeat": "Kött",
        "foodCatDeli": "Chark",
        "foodCatFish": "Fisk & skaldjur",
        "foodCatBakery": "Bageri",
        "foodCatDrinks": "Drycker",
        "foodCatGrocery": "Skafferi",
        "foodCatSnacks": "Snacks",
        "foodCatDesserts": "Desserter",
        "foodCatSweets": "Godis",
        "foodCatFrozen": "Fryst",
        "foodCatHygiene": "Personlig vård",
        "foodCatHousehold": "Hushåll",
        "foodCatPets": "Husdjur",
        "foodCatBaby": "Baby",
        "foodCatOther": "Övrigt",
    },
    "da": {
        "myList": "Min liste",
        "engagementsListName": "Forpligtelser",
        "listCopySuffix": " (kopi)",
        "deleteListConfirmEmpty": "“{name}” slettes.",
        "deleteListConfirmWithItems": "“{name}” har {count} vare(r). Alt slettes.",
        "foodCatFruits": "Frugt",
        "foodCatVegetables": "Grøntsager",
        "foodCatMushrooms": "Svampe",
        "foodCatDairy": "Mejeri & æg",
        "foodCatMeat": "Kød",
        "foodCatDeli": "Pålæg",
        "foodCatFish": "Fisk & skaldyr",
        "foodCatBakery": "Bageri",
        "foodCatDrinks": "Drikkevarer",
        "foodCatGrocery": "Spisekammer",
        "foodCatSnacks": "Snacks",
        "foodCatDesserts": "Desserter",
        "foodCatSweets": "Slik",
        "foodCatFrozen": "Frost",
        "foodCatHygiene": "Personlig pleje",
        "foodCatHousehold": "Husholdning",
        "foodCatPets": "Kæledyr",
        "foodCatBaby": "Baby",
        "foodCatOther": "Andet",
    },
    "nb": {
        "myList": "Min liste",
        "engagementsListName": "Forpliktelser",
        "listCopySuffix": " (kopi)",
        "deleteListConfirmEmpty": "“{name}” vil bli slettet.",
        "deleteListConfirmWithItems": "“{name}” har {count} vare(r). Alt slettes.",
        "foodCatFruits": "Frukt",
        "foodCatVegetables": "Grønnsaker",
        "foodCatMushrooms": "Sopp",
        "foodCatDairy": "Meieriprodukter & egg",
        "foodCatMeat": "Kjøtt",
        "foodCatDeli": "Pålegg",
        "foodCatFish": "Fisk & sjømat",
        "foodCatBakery": "Bakeri",
        "foodCatDrinks": "Drikke",
        "foodCatGrocery": "Skafferi",
        "foodCatSnacks": "Snacks",
        "foodCatDesserts": "Desserter",
        "foodCatSweets": "Søtsaker",
        "foodCatFrozen": "Frossen",
        "foodCatHygiene": "Personlig pleie",
        "foodCatHousehold": "Husholdning",
        "foodCatPets": "Kjæledyr",
        "foodCatBaby": "Baby",
        "foodCatOther": "Annet",
    },
    "fi": {
        "myList": "Oma lista",
        "engagementsListName": "Sitoumukset",
        "listCopySuffix": " (kopio)",
        "deleteListConfirmEmpty": "“{name}” poistetaan.",
        "deleteListConfirmWithItems": "Listassa “{name}” on {count} tuotetta. Kaikki poistetaan.",
        "foodCatFruits": "Hedelmät",
        "foodCatVegetables": "Vihannekset",
        "foodCatMushrooms": "Sienet",
        "foodCatDairy": "Maitotuotteet & munat",
        "foodCatMeat": "Liha",
        "foodCatDeli": "Leikkeleet",
        "foodCatFish": "Kala & äyriäiset",
        "foodCatBakery": "Leipomo",
        "foodCatDrinks": "Juomat",
        "foodCatGrocery": "Kuiva-aineet",
        "foodCatSnacks": "Naposteltavat",
        "foodCatDesserts": "Jälkiruoat",
        "foodCatSweets": "Makeiset",
        "foodCatFrozen": "Pakasteet",
        "foodCatHygiene": "Hygienia",
        "foodCatHousehold": "Koti",
        "foodCatPets": "Lemmikit",
        "foodCatBaby": "Vauva",
        "foodCatOther": "Muu",
    },
    "cs": {
        "myList": "Můj seznam",
        "engagementsListName": "Závazky",
        "listCopySuffix": " (kopie)",
        "deleteListConfirmEmpty": "„{name}“ bude smazán.",
        "deleteListConfirmWithItems": "„{name}“ obsahuje {count} položek. Vše bude smazáno.",
        "foodCatFruits": "Ovoce",
        "foodCatVegetables": "Zelenina",
        "foodCatMushrooms": "Houby",
        "foodCatDairy": "Mléčné výrobky a vejce",
        "foodCatMeat": "Maso",
        "foodCatDeli": "Uzeniny",
        "foodCatFish": "Ryby a mořské plody",
        "foodCatBakery": "Pečivo",
        "foodCatDrinks": "Nápoje",
        "foodCatGrocery": "Spíž",
        "foodCatSnacks": "Svačiny",
        "foodCatDesserts": "Dezerty",
        "foodCatSweets": "Sladkosti",
        "foodCatFrozen": "Mražené",
        "foodCatHygiene": "Osobní péče",
        "foodCatHousehold": "Domácnost",
        "foodCatPets": "Mazlíčci",
        "foodCatBaby": "Miminko",
        "foodCatOther": "Ostatní",
    },
    "sk": {
        "myList": "Môj zoznam",
        "engagementsListName": "Záväzky",
        "listCopySuffix": " (kópia)",
        "deleteListConfirmEmpty": "„{name}“ bude vymazaný.",
        "deleteListConfirmWithItems": "„{name}“ obsahuje {count} položiek. Všetko bude vymazané.",
        "foodCatFruits": "Ovocie",
        "foodCatVegetables": "Zelenina",
        "foodCatMushrooms": "Huby",
        "foodCatDairy": "Mliečne výrobky a vajcia",
        "foodCatMeat": "Mäso",
        "foodCatDeli": "Údeniny",
        "foodCatFish": "Ryby a morské plody",
        "foodCatBakery": "Pečivo",
        "foodCatDrinks": "Nápoje",
        "foodCatGrocery": "Špajza",
        "foodCatSnacks": "Snacky",
        "foodCatDesserts": "Dezerty",
        "foodCatSweets": "Sladkosti",
        "foodCatFrozen": "Mrazené",
        "foodCatHygiene": "Osobná starostlivosť",
        "foodCatHousehold": "Domácnosť",
        "foodCatPets": "Domáce zvieratá",
        "foodCatBaby": "Bábätko",
        "foodCatOther": "Iné",
    },
    "hu": {
        "myList": "Saját listám",
        "engagementsListName": "Vállalások",
        "listCopySuffix": " (másolat)",
        "deleteListConfirmEmpty": "A(z) „{name}” törlésre kerül.",
        "deleteListConfirmWithItems": "A(z) „{name}” {count} tételt tartalmaz. Minden törlődik.",
        "foodCatFruits": "Gyümölcs",
        "foodCatVegetables": "Zöldség",
        "foodCatMushrooms": "Gomba",
        "foodCatDairy": "Tejtermékek és tojás",
        "foodCatMeat": "Hús",
        "foodCatDeli": "Felvágottak",
        "foodCatFish": "Hal és tengeri élőlények",
        "foodCatBakery": "Pékáru",
        "foodCatDrinks": "Italok",
        "foodCatGrocery": "Élelmiszer",
        "foodCatSnacks": "Snackek",
        "foodCatDesserts": "Desszertek",
        "foodCatSweets": "Édességek",
        "foodCatFrozen": "Fagyasztott",
        "foodCatHygiene": "Testápolás",
        "foodCatHousehold": "Háztartás",
        "foodCatPets": "Háziállatok",
        "foodCatBaby": "Baba",
        "foodCatOther": "Egyéb",
    },
    "ro": {
        "myList": "Lista mea",
        "engagementsListName": "Angajamente",
        "listCopySuffix": " (copie)",
        "deleteListConfirmEmpty": "„{name}” va fi ștearsă.",
        "deleteListConfirmWithItems": "„{name}” are {count} articol(e). Totul va fi șters.",
        "foodCatFruits": "Fructe",
        "foodCatVegetables": "Legume",
        "foodCatMushrooms": "Ciuperci",
        "foodCatDairy": "Lactate și ouă",
        "foodCatMeat": "Carne",
        "foodCatDeli": "Mezeluri",
        "foodCatFish": "Pește și fructe de mare",
        "foodCatBakery": "Panificație",
        "foodCatDrinks": "Băuturi",
        "foodCatGrocery": "Cămara",
        "foodCatSnacks": "Gustări",
        "foodCatDesserts": "Deserturi",
        "foodCatSweets": "Dulciuri",
        "foodCatFrozen": "Congelate",
        "foodCatHygiene": "Îngrijire personală",
        "foodCatHousehold": "Casă",
        "foodCatPets": "Animale",
        "foodCatBaby": "Bebeluș",
        "foodCatOther": "Altele",
    },
    "bg": {
        "myList": "Моят списък",
        "engagementsListName": "Ангажименти",
        "listCopySuffix": " (копие)",
        "deleteListConfirmEmpty": "„{name}“ ще бъде изтрит.",
        "deleteListConfirmWithItems": "„{name}“ има {count} артикула. Всичко ще бъде изтрито.",
        "foodCatFruits": "Плодове",
        "foodCatVegetables": "Зеленчуци",
        "foodCatMushrooms": "Гъби",
        "foodCatDairy": "Млечни и яйца",
        "foodCatMeat": "Месо",
        "foodCatDeli": "Колбаси",
        "foodCatFish": "Риба и морски дарове",
        "foodCatBakery": "Хлебни",
        "foodCatDrinks": "Напитки",
        "foodCatGrocery": "Килер",
        "foodCatSnacks": "Снакс",
        "foodCatDesserts": "Десерти",
        "foodCatSweets": "Сладкиши",
        "foodCatFrozen": "Замразени",
        "foodCatHygiene": "Лична хигиена",
        "foodCatHousehold": "Дом",
        "foodCatPets": "Домашни любимци",
        "foodCatBaby": "Бебе",
        "foodCatOther": "Друго",
    },
    "el": {
        "myList": "Η λίστα μου",
        "engagementsListName": "Δεσμεύσεις",
        "listCopySuffix": " (αντίγραφο)",
        "deleteListConfirmEmpty": "Η «{name}» θα διαγραφεί.",
        "deleteListConfirmWithItems": "Η «{name}» έχει {count} είδος/η. Όλα θα διαγραφούν.",
        "foodCatFruits": "Φρούτα",
        "foodCatVegetables": "Λαχανικά",
        "foodCatMushrooms": "Μανιτάρια",
        "foodCatDairy": "Γαλακτοκομικά & αυγά",
        "foodCatMeat": "Κρέας",
        "foodCatDeli": "Αλλαντικά",
        "foodCatFish": "Ψάρια & θαλασσινά",
        "foodCatBakery": "Αρτοποιείο",
        "foodCatDrinks": "Ποτά",
        "foodCatGrocery": "Παντοπωλείο",
        "foodCatSnacks": "Σνακ",
        "foodCatDesserts": "Επιδόρπια",
        "foodCatSweets": "Γλυκά",
        "foodCatFrozen": "Κατεψυγμένα",
        "foodCatHygiene": "Προσωπική φροντίδα",
        "foodCatHousehold": "Σπίτι",
        "foodCatPets": "Κατοικίδια",
        "foodCatBaby": "Μωρό",
        "foodCatOther": "Άλλο",
    },
    "ca": {
        "myList": "La meva llista",
        "engagementsListName": "Compromisos",
        "listCopySuffix": " (còpia)",
        "deleteListConfirmEmpty": "Se suprimirà «{name}».",
        "deleteListConfirmWithItems": "«{name}» té {count} article(s). Tot se suprimirà.",
        "foodCatFruits": "Fruites",
        "foodCatVegetables": "Verdures",
        "foodCatMushrooms": "Bolets",
        "foodCatDairy": "Lactis i ous",
        "foodCatMeat": "Carn",
        "foodCatDeli": "Embotits",
        "foodCatFish": "Peix i marisc",
        "foodCatBakery": "Fleca",
        "foodCatDrinks": "Begudes",
        "foodCatGrocery": "Rebost",
        "foodCatSnacks": "Aperitius",
        "foodCatDesserts": "Postres",
        "foodCatSweets": "Dolços",
        "foodCatFrozen": "Congelats",
        "foodCatHygiene": "Cura personal",
        "foodCatHousehold": "Llar",
        "foodCatPets": "Mascotes",
        "foodCatBaby": "Nadó",
        "foodCatOther": "Altres",
    },
    "gl": {
        "myList": "A miña lista",
        "engagementsListName": "Compromisos",
        "listCopySuffix": " (copia)",
        "deleteListConfirmEmpty": "Eliminarase «{name}».",
        "deleteListConfirmWithItems": "«{name}» ten {count} artigo(s). Eliminarase todo.",
        "foodCatFruits": "Froita",
        "foodCatVegetables": "Verduras",
        "foodCatMushrooms": "Cogomelos",
        "foodCatDairy": "Lácteos e ovos",
        "foodCatMeat": "Carne",
        "foodCatDeli": "Charcutaría",
        "foodCatFish": "Peixe e marisco",
        "foodCatBakery": "Panadería",
        "foodCatDrinks": "Bebidas",
        "foodCatGrocery": "Despensa",
        "foodCatSnacks": "Aperitivos",
        "foodCatDesserts": "Sobremesas",
        "foodCatSweets": "Doces",
        "foodCatFrozen": "Conxelados",
        "foodCatHygiene": "Coidado persoal",
        "foodCatHousehold": "Fogar",
        "foodCatPets": "Mascotas",
        "foodCatBaby": "Bebé",
        "foodCatOther": "Outros",
    },
    "eu": {
        "myList": "Nire zerrenda",
        "engagementsListName": "Konpromisoak",
        "listCopySuffix": " (kopia)",
        "deleteListConfirmEmpty": "«{name}» ezabatuko da.",
        "deleteListConfirmWithItems": "«{name}»-k {count} elementu ditu. Dena ezabatuko da.",
        "foodCatFruits": "Fruituak",
        "foodCatVegetables": "Barazkiak",
        "foodCatMushrooms": "Onddoak",
        "foodCatDairy": "Esnekiak eta arrautzak",
        "foodCatMeat": "Haragia",
        "foodCatDeli": "Urdaitegia",
        "foodCatFish": "Arraina eta itsaskia",
        "foodCatBakery": "Okindegia",
        "foodCatDrinks": "Edariak",
        "foodCatGrocery": "Despensa",
        "foodCatSnacks": "Pintxoak",
        "foodCatDesserts": "Postreak",
        "foodCatSweets": "Gozokiak",
        "foodCatFrozen": "Izoztuak",
        "foodCatHygiene": "Higiene pertsonala",
        "foodCatHousehold": "Etxea",
        "foodCatPets": "Maskotak",
        "foodCatBaby": "Haurtxoa",
        "foodCatOther": "Bestelakoak",
    },
    "hr": {
        "myList": "Moj popis",
        "engagementsListName": "Obveze",
        "listCopySuffix": " (kopija)",
        "deleteListConfirmEmpty": "„{name}“ će biti obrisan.",
        "deleteListConfirmWithItems": "„{name}“ ima {count} stavki. Sve će biti obrisano.",
        "foodCatFruits": "Voće",
        "foodCatVegetables": "Povrće",
        "foodCatMushrooms": "Gljive",
        "foodCatDairy": "Mliječni proizvodi i jaja",
        "foodCatMeat": "Meso",
        "foodCatDeli": "Mesni narezci",
        "foodCatFish": "Riba i morski plodovi",
        "foodCatBakery": "Pekara",
        "foodCatDrinks": "Pića",
        "foodCatGrocery": "Ostava",
        "foodCatSnacks": "Grickalice",
        "foodCatDesserts": "Deserti",
        "foodCatSweets": "Slatkiši",
        "foodCatFrozen": "Smrznuto",
        "foodCatHygiene": "Osobna njega",
        "foodCatHousehold": "Kućanstvo",
        "foodCatPets": "Kućni ljubimci",
        "foodCatBaby": "Bebe",
        "foodCatOther": "Ostalo",
    },
    "sr": {
        "myList": "Моја листа",
        "engagementsListName": "Обавезе",
        "listCopySuffix": " (копија)",
        "deleteListConfirmEmpty": "„{name}“ ће бити обрисана.",
        "deleteListConfirmWithItems": "„{name}“ има {count} ставк(е/и). Све ће бити обрисано.",
        "foodCatFruits": "Воће",
        "foodCatVegetables": "Поврће",
        "foodCatMushrooms": "Печурке",
        "foodCatDairy": "Млечни производи и јаја",
        "foodCatMeat": "Месо",
        "foodCatDeli": "Месне прерађевине",
        "foodCatFish": "Риба и морски плодови",
        "foodCatBakery": "Пекара",
        "foodCatDrinks": "Пића",
        "foodCatGrocery": "Остава",
        "foodCatSnacks": "Грицкалице",
        "foodCatDesserts": "Десерти",
        "foodCatSweets": "Слаткиши",
        "foodCatFrozen": "Смрзнуто",
        "foodCatHygiene": "Лична нега",
        "foodCatHousehold": "Домаћинство",
        "foodCatPets": "Кућни љубимци",
        "foodCatBaby": "Бебе",
        "foodCatOther": "Остало",
    },
    "sl": {
        "myList": "Moj seznam",
        "engagementsListName": "Obveznosti",
        "listCopySuffix": " (kopija)",
        "deleteListConfirmEmpty": "»{name}« bo izbrisan.",
        "deleteListConfirmWithItems": "»{name}« ima {count} artiklov. Vse bo izbrisano.",
        "foodCatFruits": "Sadje",
        "foodCatVegetables": "Zelenjava",
        "foodCatMushrooms": "Gobe",
        "foodCatDairy": "Mlečni izdelki in jajca",
        "foodCatMeat": "Meso",
        "foodCatDeli": "Mesnine",
        "foodCatFish": "Ribe in morski sadeži",
        "foodCatBakery": "Pekarna",
        "foodCatDrinks": "Pijače",
        "foodCatGrocery": "Shramba",
        "foodCatSnacks": "Prigrizki",
        "foodCatDesserts": "Slastice",
        "foodCatSweets": "Sladkarije",
        "foodCatFrozen": "Zamrznjeno",
        "foodCatHygiene": "Osebna nega",
        "foodCatHousehold": "Gospodinjstvo",
        "foodCatPets": "Hišni ljubljenčki",
        "foodCatBaby": "Dojenček",
        "foodCatOther": "Drugo",
    },
    "lt": {
        "myList": "Mano sąrašas",
        "engagementsListName": "Įsipareigojimai",
        "listCopySuffix": " (kopija)",
        "deleteListConfirmEmpty": "„{name}“ bus ištrintas.",
        "deleteListConfirmWithItems": "„{name}“ turi {count} prek(-ę/-es). Viskas bus ištrinta.",
        "foodCatFruits": "Vaisiai",
        "foodCatVegetables": "Daržovės",
        "foodCatMushrooms": "Grybai",
        "foodCatDairy": "Pieno produktai ir kiaušiniai",
        "foodCatMeat": "Mėsa",
        "foodCatDeli": "Mėsos gaminiai",
        "foodCatFish": "Žuvis ir jūros gėrybės",
        "foodCatBakery": "Kepykla",
        "foodCatDrinks": "Gėrimai",
        "foodCatGrocery": "Sandėliukas",
        "foodCatSnacks": "Užkandžiai",
        "foodCatDesserts": "Desertai",
        "foodCatSweets": "Saldumynai",
        "foodCatFrozen": "Šaldyti",
        "foodCatHygiene": "Asmens priežiūra",
        "foodCatHousehold": "Namai",
        "foodCatPets": "Augintiniai",
        "foodCatBaby": "Kūdikis",
        "foodCatOther": "Kita",
    },
    "lv": {
        "myList": "Mans saraksts",
        "engagementsListName": "Saistības",
        "listCopySuffix": " (kopija)",
        "deleteListConfirmEmpty": "“{name}” tiks dzēsts.",
        "deleteListConfirmWithItems": "“{name}” satur {count} vienību. Viss tiks dzēsts.",
        "foodCatFruits": "Augļi",
        "foodCatVegetables": "Dārzeņi",
        "foodCatMushrooms": "Sēnes",
        "foodCatDairy": "Piena produkti un olas",
        "foodCatMeat": "Gaļa",
        "foodCatDeli": "Desas",
        "foodCatFish": "Zivis un jūras veltes",
        "foodCatBakery": "Maizes izstrādājumi",
        "foodCatDrinks": "Dzērieni",
        "foodCatGrocery": "Pārtikas krājumi",
        "foodCatSnacks": "Uzkodas",
        "foodCatDesserts": "Desertī",
        "foodCatSweets": "Saldumi",
        "foodCatFrozen": "Saldēti",
        "foodCatHygiene": "Personīgā higiēna",
        "foodCatHousehold": "Mājsaimniecība",
        "foodCatPets": "Mājdzīvnieki",
        "foodCatBaby": "Zīdainis",
        "foodCatOther": "Cits",
    },
    "et": {
        "myList": "Minu nimekiri",
        "engagementsListName": "Kohustused",
        "listCopySuffix": " (koopia)",
        "deleteListConfirmEmpty": "“{name}” kustutatakse.",
        "deleteListConfirmWithItems": "“{name}” sisaldab {count} kirjet. Kõik kustutatakse.",
        "foodCatFruits": "Puuviljad",
        "foodCatVegetables": "Köögiviljad",
        "foodCatMushrooms": "Seened",
        "foodCatDairy": "Piimatooted ja munad",
        "foodCatMeat": "Liha",
        "foodCatDeli": "Vorstid",
        "foodCatFish": "Kala ja mereannid",
        "foodCatBakery": "Pagaritooted",
        "foodCatDrinks": "Joogid",
        "foodCatGrocery": "Sahver",
        "foodCatSnacks": "Snäkid",
        "foodCatDesserts": "Magustoidud",
        "foodCatSweets": "Maiustused",
        "foodCatFrozen": "Külmutatud",
        "foodCatHygiene": "Isiklik hügieen",
        "foodCatHousehold": "Kodu",
        "foodCatPets": "Lemmikloomad",
        "foodCatBaby": "Beebi",
        "foodCatOther": "Muu",
    },
    "id": {
        "myList": "Daftar saya",
        "engagementsListName": "Komitmen",
        "listCopySuffix": " (salinan)",
        "deleteListConfirmEmpty": "“{name}” akan dihapus.",
        "deleteListConfirmWithItems": "“{name}” punya {count} item. Semuanya akan dihapus.",
        "foodCatFruits": "Buah",
        "foodCatVegetables": "Sayuran",
        "foodCatMushrooms": "Jamur",
        "foodCatDairy": "Susu & telur",
        "foodCatMeat": "Daging",
        "foodCatDeli": "Deli",
        "foodCatFish": "Ikan & seafood",
        "foodCatBakery": "Roti",
        "foodCatDrinks": "Minuman",
        "foodCatGrocery": "Bahan dapur",
        "foodCatSnacks": "Camilan",
        "foodCatDesserts": "Dessert",
        "foodCatSweets": "Manisan",
        "foodCatFrozen": "Beku",
        "foodCatHygiene": "Perawatan diri",
        "foodCatHousehold": "Rumah tangga",
        "foodCatPets": "Hewan peliharaan",
        "foodCatBaby": "Bayi",
        "foodCatOther": "Lainnya",
    },
    "ms": {
        "myList": "Senarai saya",
        "engagementsListName": "Komitmen",
        "listCopySuffix": " (salinan)",
        "deleteListConfirmEmpty": "“{name}” akan dipadam.",
        "deleteListConfirmWithItems": "“{name}” ada {count} item. Semua akan dipadam.",
        "foodCatFruits": "Buah-buahan",
        "foodCatVegetables": "Sayur-sayuran",
        "foodCatMushrooms": "Cendawan",
        "foodCatDairy": "Tenusu & telur",
        "foodCatMeat": "Daging",
        "foodCatDeli": "Deli",
        "foodCatFish": "Ikan & makanan laut",
        "foodCatBakery": "Bakeri",
        "foodCatDrinks": "Minuman",
        "foodCatGrocery": "Barangan dapur",
        "foodCatSnacks": "Snek",
        "foodCatDesserts": "Pencuci mulut",
        "foodCatSweets": "Manisan",
        "foodCatFrozen": "Beku",
        "foodCatHygiene": "Penjagaan diri",
        "foodCatHousehold": "Isi rumah",
        "foodCatPets": "Haiwan peliharaan",
        "foodCatBaby": "Bayi",
        "foodCatOther": "Lain-lain",
    },
    "th": {
        "myList": "รายการของฉัน",
        "engagementsListName": "ข้อผูกพัน",
        "listCopySuffix": " (สำเนา)",
        "deleteListConfirmEmpty": "“{name}” จะถูกลบ",
        "deleteListConfirmWithItems": "“{name}” มี {count} รายการ ทุกอย่างจะถูกลบ",
        "foodCatFruits": "ผลไม้",
        "foodCatVegetables": "ผัก",
        "foodCatMushrooms": "เห็ด",
        "foodCatDairy": "นมและไข่",
        "foodCatMeat": "เนื้อสัตว์",
        "foodCatDeli": "ของชำเนื้อ",
        "foodCatFish": "ปลาและอาหารทะเล",
        "foodCatBakery": "เบเกอรี่",
        "foodCatDrinks": "เครื่องดื่ม",
        "foodCatGrocery": "ของแห้ง",
        "foodCatSnacks": "ของว่าง",
        "foodCatDesserts": "ของหวาน",
        "foodCatSweets": "ลูกกวาด",
        "foodCatFrozen": "แช่แข็ง",
        "foodCatHygiene": "ของใช้ส่วนตัว",
        "foodCatHousehold": "ของใช้ในบ้าน",
        "foodCatPets": "สัตว์เลี้ยง",
        "foodCatBaby": "เด็กทารก",
        "foodCatOther": "อื่นๆ",
    },
    "vi": {
        "myList": "Danh sách của tôi",
        "engagementsListName": "Cam kết",
        "listCopySuffix": " (bản sao)",
        "deleteListConfirmEmpty": "“{name}” sẽ bị xóa.",
        "deleteListConfirmWithItems": "“{name}” có {count} mục. Tất cả sẽ bị xóa.",
        "foodCatFruits": "Trái cây",
        "foodCatVegetables": "Rau",
        "foodCatMushrooms": "Nấm",
        "foodCatDairy": "Sữa & trứng",
        "foodCatMeat": "Thịt",
        "foodCatDeli": "Thực phẩm chế biến",
        "foodCatFish": "Hải sản",
        "foodCatBakery": "Bánh mì",
        "foodCatDrinks": "Đồ uống",
        "foodCatGrocery": "Thực phẩm khô",
        "foodCatSnacks": "Đồ ăn nhẹ",
        "foodCatDesserts": "Tráng miệng",
        "foodCatSweets": "Đồ ngọt",
        "foodCatFrozen": "Đông lạnh",
        "foodCatHygiene": "Chăm sóc cá nhân",
        "foodCatHousehold": "Gia dụng",
        "foodCatPets": "Thú cưng",
        "foodCatBaby": "Em bé",
        "foodCatOther": "Khác",
    },
}

META = {
    "deleteListConfirmEmpty": {
        "placeholders": {"name": {"type": "String"}},
    },
    "deleteListConfirmWithItems": {
        "placeholders": {
            "name": {"type": "String"},
            "count": {"type": "int"},
        },
    },
}


def main() -> None:
    en = json.loads((ROOT / "app_en.arb").read_text(encoding="utf-8"))
    keys = [
        k
        for k in TRANSLATIONS["de"]
        if not k.startswith("@")
    ]
    updated = 0
    for path in sorted(ROOT.glob("app_*.arb")):
        loc = path.stem.removeprefix("app_")
        if loc in ("fr", "en"):
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        src = TRANSLATIONS.get(loc)
        if src is None:
            raise SystemExit(f"Missing curated translations for {loc}")
        changed = False
        for key in keys:
            if key not in data:
                data[key] = src[key]
                changed = True
            if key in META and f"@{key}" not in data:
                data[f"@{key}"] = META[key]
                changed = True
        # Ensure foodCatUnclassified exists (already in template set for most)
        if "foodCatUnclassified" not in data and "foodCatUnclassified" in en:
            data["foodCatUnclassified"] = en["foodCatUnclassified"]
            changed = True
        if changed:
            path.write_text(
                json.dumps(data, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            updated += 1
            print(f"updated {path.name}")
    print(f"done, files touched: {updated}")


if __name__ == "__main__":
    main()
