#!/usr/bin/env python3
"""Generate prod_patches JSON for de, nl, da, sv, nb, fi."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "prod_patches"

# fmt: off
DE = {
    "prod_adoucissant": "Weichspüler",
    "prod_agneau": "Lamm",
    "prod_agrafeuse": "Tacker",
    "prod_agraves": "Agaven",
    "prod_algues_nori": "Nori-Algen",
    "prod_algues_wakame": "Wakame-Algen",
    "prod_allumettes": "Streichhölzer",
    "prod_ampoule": "Glühbirne",
    "prod_anchois": "Sardellen",
    "prod_andouille": "Andouille",
    "prod_aneth": "Dill",
    "prod_anneaux": "Ringe",
    "prod_apero_dinatoire": "Abendessensnacks",
    "prod_baies_de_goji": "Goji-Beeren",
    "prod_bain_de_bouche": "Mundwasser",
    "prod_bambou": "Bambus",
    "prod_batterie": "Batterie",
    "prod_biberon": "Babyflasche",
    "prod_biscottes": "Zwieback",
    "prod_biscuits_bio": "Bio-Kekse",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Foie-gras-Block",
    "prod_boissons": "Getränke",
    "prod_boudin_noir": "Blutwurst",
    "prod_boulangerie": "Bäckerei",
    "prod_boulettes": "Fleischbällchen",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Bolzen",
    "prod_briquet": "Feuerzeug",
    "prod_brochettes": "Spieße",
    "prod_bulots": "Wellhornschnecken",
    "prod_burin": "Meißel",
    "prod_canard": "Ente",
    "prod_capres": "Kapern",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Notizbuch",
    "prod_carrelage": "Fliesen",
    "prod_carte_recharge": "Aufladungskarte",
    "prod_cartes_postales": "Postkarten",
    "prod_cartouche_filtre": "Filterpatrone",
    "prod_caviar_daubergine": "Baba Ganoush",
    "prod_champignons": "Pilze",
    "prod_champignons_noirs": "Judasohr-Pilze",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Schlagsahne",
    "prod_charcuterie_artisanale": "Handwerkliche Wurstwaren",
    "prod_chauffage": "Heizung",
    "prod_chevilles": "Dübel",
    "prod_chewing_gum": "Kaugummi",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Milchschokolade",
    "prod_chocolat_bio": "Bio-Schokolade",
    "prod_chocolat_blanc": "Weiße Schokolade",
    "prod_chocolat_noir": "Zartbitterschokolade",
    "prod_chou_chinois": "Chinakohl",
    "prod_choucroute": "Sauerkraut",
    "prod_cidre": "Apfelwein",
    "prod_cigares": "Zigarren",
    "prod_cigarettes": "Zigaretten",
    "prod_citron": "Zitrone",
    "prod_citronnelle": "Zitronengras",
    "prod_clous": "Nägel",
    "prod_colle": "Kleber",
    "prod_colle_carrelage": "Fliesenkleber",
    "prod_collier": "Halskette",
    "prod_compote_bio": "Bio-Kompott",
    "prod_confiture_bio": "Bio-Marmelade",
    "prod_confiture_dabricot": "Aprikosenmarmelade",
    "prod_confiture_de_fraises": "Erdbeermarmelade",
    "prod_confiture_maison": "Hausgemachte Marmelade",
    "prod_coquillages": "Schalentiere",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Wattepads",
    "prod_couches": "Windeln",
    "prod_coulis": "Coulis",
    "prod_coupe": "Becher",
    "prod_crackers_sans_sel": "Ungesalzene Cracker",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Haken",
    "prod_curry_rouge": "Rotes Curry",
    "prod_curry_vert": "Grünes Curry",
    "prod_cutter": "Cuttermesser",
    "prod_digestif": "Digestif",
    "prod_douille": "Stecknuss",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Chicorée",
    "prod_enduit": "Spachtelmasse",
    "prod_engrais": "Dünger",
    "prod_enveloppes": "Umschläge",
    "prod_escalope": "Schnitzel",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Reispapier",
    "prod_fil_dentaire": "Zahnseide",
    "prod_filet": "Filet",
    "prod_fleurs": "Blumen",
    "prod_fondue_savoyarde": "Savoyarde Fondue",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Bauernkäse",
    "prod_fruits_bio": "Bio-Obst",
    "prod_fruits_de_mer": "Meeresfrüchte",
    "prod_galettes_de_riz": "Reiswaffeln",
    "prod_gel_douche": "Duschgel",
    "prod_gibier": "Wild",
    "prod_gommage": "Peeling",
    "prod_graines": "Samen",
    "prod_graines_de_chia": "Chiasamen",
    "prod_graines_de_lin": "Leinsamen",
    "prod_grattage": "Rubbellose",
    "prod_haricots": "Bohnen",
    "prod_herbes": "Kräuter",
    "prod_homard": "Hummer",
    "prod_huile_dolive_bio": "Bio-Olivenöl",
    "prod_infusion": "Kräutertee",
    "prod_interrupteur": "Lichtschalter",
    "prod_jambon_cru": "Rohschinken",
    "prod_javel": "Bleichmittel",
    "prod_joint": "Dichtung",
    "prod_joint_carrelage": "Fugenmasse",
    "prod_joint_torique": "O-Ring",
    "prod_journal": "Zeitung",
    "prod_jus": "Saft",
    "prod_jus_de_fruit_naturel": "Natürlicher Fruchtsaft",
    "prod_jus_de_raisin": "Traubensaft",
    "prod_jus_dorange": "Orangensaft",
    "prod_laine_de_verre": "Glaswolle",
    "prod_lait_bio": "Bio-Milch",
    "prod_lait_de_coco": "Kokosmilch",
    "prod_lait_en_poudre": "Milchpulver",
    "prod_lambris": "Wandverkleidung",
    "prod_lame_de_scie": "Sägeblatt",
    "prod_langoustines": "Langustinen",
    "prod_lapin": "Kaninchen",
    "prod_lard": "Speck",
    "prod_lasagnes": "Lasagne",
    "prod_lasure": "Lasur",
    "prod_lentilles_corail": "Rote Linsen",
    "prod_lime": "Feile",
    "prod_limette": "Limette",
    "prod_lingettes": "Feuchttücher",
    "prod_liquide_vaisselle": "Spülmittel",
    "prod_loto": "Lotto",
    "prod_madeleines": "Madeleines",
    "prod_magazine": "Zeitschrift",
    "prod_marteau": "Hammer",
    "prod_masque": "Gesichtsmaske",
    "prod_masse": "Vorschlaghammer",
    "prod_mastic": "Kitt",
    "prod_menthe": "Minze",
    "prod_miel_bio": "Bio-Honig",
    "prod_miel_du_producteur": "Honig vom Erzeuger",
    "prod_mouchoirs": "Taschentücher",
    "prod_muesli_barres": "Müsliriegel",
    "prod_muesli_bio": "Bio-Müsli",
    "prod_nectar": "Nektar",
    "prod_nems": "Frühlingsrollen",
    "prod_nettoyant_sol": "Bodenreiniger",
    "prod_niveau": "Wasserwaage",
    "prod_noix_de_cajou": "Cashewkerne",
    "prod_nouilles": "Nudeln",
    "prod_pain_bio": "Bio-Brot",
    "prod_pain_de_viande": "Fleischkäse",
    "prod_palets_bretons": "Bretonische Butterkekse",
    "prod_panneau_osb": "OSB-Platte",
    "prod_papier_de_verre": "Schleifpapier",
    "prod_parfum": "Parfüm",
    "prod_parquet": "Parkett",
    "prod_pastilles": "Pastillen",
    "prod_pate": "Pastete",
    "prod_pate_carbonara": "Carbonara",
    "prod_pates_carbonara": "Carbonara-Nudeln",
    "prod_paumelle": "Scharnier",
    "prod_peinture": "Farbe",
    "prod_perceuse": "Bohrmaschine",
    "prod_petit_dej": "Frühstück",
    "prod_petit_dejeuner": "Frühstück",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Batterie",
    "prod_pince": "Zange",
    "prod_pinceau": "Pinsel",
    "prod_pizza_maison": "Hausgemachte Pizza",
    "prod_planche": "Brett",
    "prod_plantes": "Pflanzen",
    "prod_plantes_aromatiques": "Aromatische Kräuter",
    "prod_poisson": "Fisch",
    "prod_poisson_frais": "Frischer Fisch",
    "prod_porc": "Schweinefleisch",
    "prod_pot": "Glas",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Suppe",
    "prod_poudre": "Pulver",
    "prod_poulet_fermier": "Freilandhähnchen",
    "prod_pousse_de_bambou": "Bambussprossen",
    "prod_pousses_de_soja": "Sojasprossen",
    "prod_presse": "Presse",
    "prod_prise": "Steckdose",
    "prod_produit_vitres": "Glasreiniger",
    "prod_produits_laitiers": "Milchprodukte",
    "prod_pruneaux": "Pflaumen",
    "prod_pull": "Pullover",
    "prod_punaises": "Reißzwecken",
    "prod_puree_d": "Püree",
    "prod_quinoa_bio": "Bio-Quinoa",
    "prod_raccord": "Anschluss",
    "prod_radiateur": "Heizkörper",
    "prod_raviolis_chinois": "Chinesische Teigtaschen",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Feuerzeuggas",
    "prod_rhum": "Rum",
    "prod_rideau": "Vorhang",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Basmatireis",
    "prod_riz_complet": "Vollkornreis",
    "prod_riz_glutineux": "Klebreis",
    "prod_robineterie": "Armaturen",
    "prod_rouleau": "Farbenroller",
    "prod_ruban_isolant": "Isolierband",
    "prod_sac_poubelle": "Müllbeutel",
    "prod_salade_composee": "Gemischter Salat",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Soße",
    "prod_sauce_fish": "Fischsoße",
    "prod_sauce_oyster": "Austernsoße",
    "prod_saucisson_sec": "Trockenwurst",
    "prod_scie": "Säge",
    "prod_seitan_bio": "Bio-Seitan",
    "prod_semoule": "Grieß",
    "prod_serrure": "Schloss",
    "prod_sirop": "Sirup",
    "prod_soda_light": "Light-Limo",
    "prod_soda_sans_alcool": "Limonade",
    "prod_sorbet": "Sorbet",
    "prod_soupe": "Suppe",
    "prod_soupe_miso": "Misosuppe",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Suppe",
    "prod_steak_de_soja": "Soja-Steak",
    "prod_tabac": "Tabak",
    "prod_tablette": "Tablette",
    "prod_tampons": "Tampons",
    "prod_tasseau": "Leiste",
    "prod_terreau": "Blumenerde",
    "prod_terrine": "Terrine",
    "prod_timbre": "Briefmarke",
    "prod_tisane": "Kräutertee",
    "prod_tofu_bio": "Bio-Tofu",
    "prod_tofu_soyeux": "Seidentofu",
    "prod_tournevis": "Schraubendreher",
    "prod_tringle": "Vorhangstange",
    "prod_tuyau": "Schlauch",
    "prod_vache_qui_rit": "The Laughing Cow",
    "prod_veau": "Kalbfleisch",
    "prod_vermicelles": "Vermicelli",
    "prod_vermicelles_de_riz": "Reisvermicelli",
    "prod_vernis": "Lack",
    "prod_verrue": "Warzenmittel",
    "prod_viande": "Fleisch",
    "prod_viande_hachee_2": "Hackfleisch",
    "prod_viandes_poissons": "Fleisch & Fisch",
    "prod_viennoiseries": "Feinbackwaren",
    "prod_vinaigre_de_riz": "Reisessig",
    "prod_vinaigrette": "Vinaigrette",
    "prod_vis": "Schrauben",
    "prod_visseuse": "Akku-Schrauber",
    "prod_volaille": "Geflügel",
    "prod_zeste": "Schale",
}

NL = {
    "prod_adoucissant": "Wasverzachter",
    "prod_agneau": "Lamsvlees",
    "prod_agrafeuse": "Nietmachine",
    "prod_agraves": "Agaves",
    "prod_algues_nori": "Nori-algen",
    "prod_algues_wakame": "Wakame-algen",
    "prod_allumettes": "Lucifers",
    "prod_ampoule": "Gloeilamp",
    "prod_anchois": "Ansjovis",
    "prod_andouille": "Andouille",
    "prod_aneth": "Dille",
    "prod_anneaux": "Ringen",
    "prod_apero_dinatoire": "Dinerhapjes",
    "prod_baies_de_goji": "Gojibessen",
    "prod_bain_de_bouche": "Mondwater",
    "prod_bambou": "Bamboe",
    "prod_batterie": "Batterij",
    "prod_biberon": "Babyfles",
    "prod_biscottes": "Beschuit",
    "prod_biscuits_bio": "Biologische koekjes",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Foie gras-blok",
    "prod_boissons": "Dranken",
    "prod_boudin_noir": "Bloedworst",
    "prod_boulangerie": "Bakkerij",
    "prod_boulettes": "Gehaktballetjes",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Bouten",
    "prod_briquet": "Aansteker",
    "prod_brochettes": "Spiesjes",
    "prod_bulots": "Wulk",
    "prod_burin": "Beitel",
    "prod_canard": "Eend",
    "prod_capres": "Kappertjes",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Notitieboek",
    "prod_carrelage": "Tegels",
    "prod_carte_recharge": "Opwaardeerkaart",
    "prod_cartes_postales": "Ansichtkaarten",
    "prod_cartouche_filtre": "Filterpatroon",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Champignons",
    "prod_champignons_noirs": "Judasoor",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Slagroom",
    "prod_charcuterie_artisanale": "Ambachtelijke vleeswaren",
    "prod_chauffage": "Verwarming",
    "prod_chevilles": "Pluggen",
    "prod_chewing_gum": "Kauwgom",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Melkchocolade",
    "prod_chocolat_bio": "Biologische chocolade",
    "prod_chocolat_blanc": "Witte chocolade",
    "prod_chocolat_noir": "Pure chocolade",
    "prod_chou_chinois": "Chinese kool",
    "prod_choucroute": "Zuurkool",
    "prod_cidre": "Cider",
    "prod_cigares": "Sigaren",
    "prod_cigarettes": "Sigaretten",
    "prod_citron": "Citroen",
    "prod_citronnelle": "Citroengras",
    "prod_clous": "Spijkers",
    "prod_colle": "Lijm",
    "prod_colle_carrelage": "Tegellijm",
    "prod_collier": "Ketting",
    "prod_compote_bio": "Biologische compote",
    "prod_confiture_bio": "Biologische jam",
    "prod_confiture_dabricot": "Abrikozenjam",
    "prod_confiture_de_fraises": "Aardbeienjam",
    "prod_confiture_maison": "Huisgemaakte jam",
    "prod_coquillages": "Schelpdieren",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Wattenschijfjes",
    "prod_couches": "Luiers",
    "prod_coulis": "Coulis",
    "prod_coupe": "Beker",
    "prod_crackers_sans_sel": "Ongezouten crackers",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Haak",
    "prod_curry_rouge": "Rode curry",
    "prod_curry_vert": "Groene curry",
    "prod_cutter": "Stanleymes",
    "prod_digestif": "Digestif",
    "prod_douille": "Dop",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Witlof",
    "prod_enduit": "Vulmiddel",
    "prod_engrais": "Meststof",
    "prod_enveloppes": "Enveloppen",
    "prod_escalope": "Escalope",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Rijstpapier",
    "prod_fil_dentaire": "Tandzijde",
    "prod_filet": "Filet",
    "prod_fleurs": "Bloemen",
    "prod_fondue_savoyarde": "Savoyaardse fondue",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Boerenkaas",
    "prod_fruits_bio": "Biologisch fruit",
    "prod_fruits_de_mer": "Zeevruchten",
    "prod_galettes_de_riz": "Rijstwafels",
    "prod_gel_douche": "Douchegel",
    "prod_gibier": "Wild",
    "prod_gommage": "Scrub",
    "prod_graines": "Zaden",
    "prod_graines_de_chia": "Chiazaad",
    "prod_graines_de_lin": "Lijnzaad",
    "prod_grattage": "Kraslot",
    "prod_haricots": "Bonen",
    "prod_herbes": "Kruiden",
    "prod_homard": "Kreeft",
    "prod_huile_dolive_bio": "Biologische olijfolie",
    "prod_infusion": "Kruidenthee",
    "prod_interrupteur": "Lichtschakelaar",
    "prod_jambon_cru": "Gedroogde ham",
    "prod_javel": "Bleekwater",
    "prod_joint": "Pakking",
    "prod_joint_carrelage": "Tegelvoeg",
    "prod_joint_torique": "O-ring",
    "prod_journal": "Krant",
    "prod_jus": "Sap",
    "prod_jus_de_fruit_naturel": "Natuurlijk vruchtensap",
    "prod_jus_de_raisin": "Druivensap",
    "prod_jus_dorange": "Sinaasappelsap",
    "prod_laine_de_verre": "Glaswol",
    "prod_lait_bio": "Biologische melk",
    "prod_lait_de_coco": "Kokosmelk",
    "prod_lait_en_poudre": "Melkpoeder",
    "prod_lambris": "Lambrisering",
    "prod_lame_de_scie": "Zaagblad",
    "prod_langoustines": "Langoustines",
    "prod_lapin": "Konijn",
    "prod_lard": "Spekvet",
    "prod_lasagnes": "Lasagne",
    "prod_lasure": "Beits",
    "prod_lentilles_corail": "Koraallengten",
    "prod_lime": "Vijl",
    "prod_limette": "Limoen",
    "prod_lingettes": "Doekjes",
    "prod_liquide_vaisselle": "Afwasmiddel",
    "prod_loto": "Loterij",
    "prod_madeleines": "Madeleines",
    "prod_magazine": "Tijdschrift",
    "prod_marteau": "Hamer",
    "prod_masque": "Gezichtsmasker",
    "prod_masse": "Voorhamer",
    "prod_mastic": "Kit",
    "prod_menthe": "Munt",
    "prod_miel_bio": "Biologische honing",
    "prod_miel_du_producteur": "Honing van de producent",
    "prod_mouchoirs": "Tissues",
    "prod_muesli_barres": "Mueslirepen",
    "prod_muesli_bio": "Biologische muesli",
    "prod_nectar": "Nectar",
    "prod_nems": "Loempia's",
    "prod_nettoyant_sol": "Vloerreiniger",
    "prod_niveau": "Waterpas",
    "prod_noix_de_cajou": "Cashewnoten",
    "prod_nouilles": "Noedels",
    "prod_pain_bio": "Biologisch brood",
    "prod_pain_de_viande": "Gehaktbrood",
    "prod_palets_bretons": "Bretonse boterkoekjes",
    "prod_panneau_osb": "OSB-plaat",
    "prod_papier_de_verre": "Schuurpapier",
    "prod_parfum": "Parfum",
    "prod_parquet": "Parket",
    "prod_pastilles": "Pastilles",
    "prod_pate": "Paté",
    "prod_pate_carbonara": "Carbonara",
    "prod_pates_carbonara": "Carbonara-pasta",
    "prod_paumelle": "Scharnier",
    "prod_peinture": "Verf",
    "prod_perceuse": "Boormachine",
    "prod_petit_dej": "Ontbijt",
    "prod_petit_dejeuner": "Ontbijt",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Batterij",
    "prod_pince": "Tang",
    "prod_pinceau": "Verfkwast",
    "prod_pizza_maison": "Huisgemaakte pizza",
    "prod_planche": "Plank",
    "prod_plantes": "Planten",
    "prod_plantes_aromatiques": "Kruidenplanten",
    "prod_poisson": "Vis",
    "prod_poisson_frais": "Verse vis",
    "prod_porc": "Varkensvlees",
    "prod_pot": "Pot",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Soep",
    "prod_poudre": "Poeder",
    "prod_poulet_fermier": "Scharrelkip",
    "prod_pousse_de_bambou": "Bamboescheuten",
    "prod_pousses_de_soja": "Taugé",
    "prod_presse": "Pers",
    "prod_prise": "Stopcontact",
    "prod_produit_vitres": "Glasreiniger",
    "prod_produits_laitiers": "Zuivel",
    "prod_pruneaux": "Pruimen",
    "prod_pull": "Trui",
    "prod_punaises": "Punaises",
    "prod_puree_d": "Puree",
    "prod_quinoa_bio": "Biologische quinoa",
    "prod_raccord": "Koppeling",
    "prod_radiateur": "Radiator",
    "prod_raviolis_chinois": "Chinese dumplings",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Aansteker navulling",
    "prod_rhum": "Rum",
    "prod_rideau": "Gordijn",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Basmatirijst",
    "prod_riz_complet": "Zilvervliesrijst",
    "prod_riz_glutineux": "Kleefrijst",
    "prod_robineterie": "Kraanwerk",
    "prod_rouleau": "Verfroller",
    "prod_ruban_isolant": "Isolatietape",
    "prod_sac_poubelle": "Vuilniszakken",
    "prod_salade_composee": "Gemengde salade",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Saus",
    "prod_sauce_fish": "Vissaus",
    "prod_sauce_oyster": "Oestersaus",
    "prod_saucisson_sec": "Gedroogde worst",
    "prod_scie": "Zaag",
    "prod_seitan_bio": "Biologische seitan",
    "prod_semoule": "Griesmeel",
    "prod_serrure": "Slot",
    "prod_sirop": "Siroop",
    "prod_soda_light": "Light frisdrank",
    "prod_soda_sans_alcool": "Frisdrank",
    "prod_sorbet": "Sorbet",
    "prod_soupe": "Soep",
    "prod_soupe_miso": "Misosoep",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Soep",
    "prod_steak_de_soja": "Sojasteak",
    "prod_tabac": "Tabak",
    "prod_tablette": "Tablet",
    "prod_tampons": "Tampons",
    "prod_tasseau": "Lat",
    "prod_terreau": "Potgrond",
    "prod_terrine": "Terrine",
    "prod_timbre": "Postzegel",
    "prod_tisane": "Kruidenthee",
    "prod_tofu_bio": "Biologische tofu",
    "prod_tofu_soyeux": "Zijden tofu",
    "prod_tournevis": "Schroevendraaier",
    "prod_tringle": "Gordijnroede",
    "prod_tuyau": "Slang",
    "prod_vache_qui_rit": "The Laughing Cow",
    "prod_veau": "Kalfsvlees",
    "prod_vermicelles": "Vermicelli",
    "prod_vermicelles_de_riz": "Rijstvermicelli",
    "prod_vernis": "Lak",
    "prod_verrue": "Wrattenmiddel",
    "prod_viande": "Vlees",
    "prod_viande_hachee_2": "Gehakt",
    "prod_viandes_poissons": "Vlees & vis",
    "prod_viennoiseries": "Viennoiserie",
    "prod_vinaigre_de_riz": "Rijstazijn",
    "prod_vinaigrette": "Vinaigrette",
    "prod_vis": "Schroeven",
    "prod_visseuse": "Accu-schroevendraaier",
    "prod_volaille": "Gevogelte",
    "prod_zeste": "Schil",
}

DA = {
    "prod_adoucissant": "Skyllemiddel",
    "prod_agneau": "Lammekød",
    "prod_agrafeuse": "Hæftemaskine",
    "prod_agraves": "Agave",
    "prod_algues_nori": "Nori-alger",
    "prod_algues_wakame": "Wakame-alger",
    "prod_allumettes": "Tændstikker",
    "prod_ampoule": "Pære",
    "prod_anchois": "Ansjoser",
    "prod_andouille": "Andouille",
    "prod_aneth": "Dild",
    "prod_anneaux": "Ringe",
    "prod_apero_dinatoire": "Middagssnacks",
    "prod_baies_de_goji": "Gojibær",
    "prod_bain_de_bouche": "Mundskyl",
    "prod_bambou": "Bambus",
    "prod_batterie": "Batteri",
    "prod_biberon": "Sutteflaske",
    "prod_biscottes": "Tvebak",
    "prod_biscuits_bio": "Økologiske kiks",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Foie gras-blok",
    "prod_boissons": "Drikkevarer",
    "prod_boudin_noir": "Blodpølse",
    "prod_boulangerie": "Bageri",
    "prod_boulettes": "Frikadeller",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Bolte",
    "prod_briquet": "Lighter",
    "prod_brochettes": "Spyd",
    "prod_bulots": "Almindelig konksnegl",
    "prod_burin": "Mejsel",
    "prod_canard": "And",
    "prod_capres": "Kapers",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Notesbog",
    "prod_carrelage": "Fliser",
    "prod_carte_recharge": "Optankningskort",
    "prod_cartes_postales": "Postkort",
    "prod_cartouche_filtre": "Filterpatron",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Svampe",
    "prod_champignons_noirs": "Træøre",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Pisket fløde",
    "prod_charcuterie_artisanale": "Håndlavet pålæg",
    "prod_chauffage": "Opvarmning",
    "prod_chevilles": "Rawlplugs",
    "prod_chewing_gum": "Tyggegummi",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Mælkechokolade",
    "prod_chocolat_bio": "Økologisk chokolade",
    "prod_chocolat_blanc": "Hvid chokolade",
    "prod_chocolat_noir": "Mørk chokolade",
    "prod_chou_chinois": "Kinakål",
    "prod_choucroute": "Surkål",
    "prod_cidre": "Cider",
    "prod_cigares": "Cigarer",
    "prod_cigarettes": "Cigaretter",
    "prod_citron": "Citron",
    "prod_citronnelle": "Citrongræs",
    "prod_clous": "Søm",
    "prod_colle": "Lim",
    "prod_colle_carrelage": "Fliseklæber",
    "prod_collier": "Halskæde",
    "prod_compote_bio": "Økologisk kompot",
    "prod_confiture_bio": "Økologisk syltetøj",
    "prod_confiture_dabricot": "Abrikossyltetøj",
    "prod_confiture_de_fraises": "Jordbærsyltetøj",
    "prod_confiture_maison": "Hjemmelavet syltetøj",
    "prod_coquillages": "Skaldyr",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Vatpinde",
    "prod_couches": "Bleer",
    "prod_coulis": "Coulis",
    "prod_coupe": "Kop",
    "prod_crackers_sans_sel": "Usaltede kiks",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Krog",
    "prod_curry_rouge": "Rød karry",
    "prod_curry_vert": "Grøn karry",
    "prod_cutter": "Kniv",
    "prod_digestif": "Digestif",
    "prod_douille": "Dop",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Endivie",
    "prod_enduit": "Spartelmasse",
    "prod_engrais": "Gødning",
    "prod_enveloppes": "Konvolutter",
    "prod_escalope": "Escalope",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Rispapir",
    "prod_fil_dentaire": "Tandtråd",
    "prod_filet": "Filet",
    "prod_fleurs": "Blomster",
    "prod_fondue_savoyarde": "Savoyard fondue",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Gårdsost",
    "prod_fruits_bio": "Økologisk frugt",
    "prod_fruits_de_mer": "Fisk og skaldyr",
    "prod_galettes_de_riz": "Riskager",
    "prod_gel_douche": "Showergel",
    "prod_gibier": "Vildt",
    "prod_gommage": "Scrub",
    "prod_graines": "Frø",
    "prod_graines_de_chia": "Chiafrø",
    "prod_graines_de_lin": "Hørfrø",
    "prod_grattage": "Skrabelod",
    "prod_haricots": "Bønner",
    "prod_herbes": "Urter",
    "prod_homard": "Hummer",
    "prod_huile_dolive_bio": "Økologisk olivenolie",
    "prod_infusion": "Urte-te",
    "prod_interrupteur": "Kontakt",
    "prod_jambon_cru": "Råskinke",
    "prod_javel": "Blegemiddel",
    "prod_joint": "Pakning",
    "prod_joint_carrelage": "Fugemasse",
    "prod_joint_torique": "O-ring",
    "prod_journal": "Avis",
    "prod_jus": "Saft",
    "prod_jus_de_fruit_naturel": "Naturlig frugtsaft",
    "prod_jus_de_raisin": "Druesaft",
    "prod_jus_dorange": "Appelsinjuice",
    "prod_laine_de_verre": "Glasuld",
    "prod_lait_bio": "Økologisk mælk",
    "prod_lait_de_coco": "Kokosmælk",
    "prod_lait_en_poudre": "Mælkepulver",
    "prod_lambris": "Panel",
    "prod_lame_de_scie": "Savklinge",
    "prod_langoustines": "Langoustines",
    "prod_lapin": "Kanin",
    "prod_lard": "Flæsk",
    "prod_lasagnes": "Lasagne",
    "prod_lasure": "Træbeskyttelse",
    "prod_lentilles_corail": "Røde linser",
    "prod_lime": "Fil",
    "prod_limette": "Lime",
    "prod_lingettes": "Servietter",
    "prod_liquide_vaisselle": "Opvaskemiddel",
    "prod_loto": "Lotteri",
    "prod_madeleines": "Madeleines",
    "prod_magazine": "Magasin",
    "prod_marteau": "Hammer",
    "prod_masque": "Ansigtsmaske",
    "prod_masse": "Forhammer",
    "prod_mastic": "Kit",
    "prod_menthe": "Mynte",
    "prod_miel_bio": "Økologisk honning",
    "prod_miel_du_producteur": "Producenthonning",
    "prod_mouchoirs": "Lommetørklæder",
    "prod_muesli_barres": "Müslibarre",
    "prod_muesli_bio": "Økologisk müsli",
    "prod_nectar": "Nektar",
    "prod_nems": "Forårsruller",
    "prod_nettoyant_sol": "Gulvrens",
    "prod_niveau": "Vaterpas",
    "prod_noix_de_cajou": "Cashewnødder",
    "prod_nouilles": "Nudler",
    "prod_pain_bio": "Økologisk brød",
    "prod_pain_de_viande": "Forloren hare",
    "prod_palets_bretons": "Bretonske småkager",
    "prod_panneau_osb": "OSB-plade",
    "prod_papier_de_verre": "Sandpapir",
    "prod_parfum": "Parfume",
    "prod_parquet": "Parket",
    "prod_pastilles": "Pastiller",
    "prod_pate": "Postej",
    "prod_pate_carbonara": "Carbonara",
    "prod_pates_carbonara": "Carbonara-pasta",
    "prod_paumelle": "Hængsel",
    "prod_peinture": "Maling",
    "prod_perceuse": "Boremaskine",
    "prod_petit_dej": "Morgenmad",
    "prod_petit_dejeuner": "Morgenmad",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Batteri",
    "prod_pince": "Tang",
    "prod_pinceau": "Pensel",
    "prod_pizza_maison": "Hjemmelavet pizza",
    "prod_planche": "Bræt",
    "prod_plantes": "Planter",
    "prod_plantes_aromatiques": "Krydderurter",
    "prod_poisson": "Fisk",
    "prod_poisson_frais": "Frisk fisk",
    "prod_porc": "Svinekød",
    "prod_pot": "Glas",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Suppe",
    "prod_poudre": "Pulver",
    "prod_poulet_fermier": "Fritgående kylling",
    "prod_pousse_de_bambou": "Bambusskud",
    "prod_pousses_de_soja": "Bønnespirer",
    "prod_presse": "Presse",
    "prod_prise": "Stikkontakt",
    "prod_produit_vitres": "Glasrens",
    "prod_produits_laitiers": "Mejeriprodukter",
    "prod_pruneaux": "Svesker",
    "prod_pull": "Trøje",
    "prod_punaises": "Tegnestifter",
    "prod_puree_d": "Mos",
    "prod_quinoa_bio": "Økologisk quinoa",
    "prod_raccord": "Samlestykke",
    "prod_radiateur": "Radiator",
    "prod_raviolis_chinois": "Kinesiske dumplings",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Lightergas",
    "prod_rhum": "Rom",
    "prod_rideau": "Gardin",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Basmatiris",
    "prod_riz_complet": "Brune ris",
    "prod_riz_glutineux": "Klisterris",
    "prod_robineterie": "Armaturer",
    "prod_rouleau": "Malerrulle",
    "prod_ruban_isolant": "Isoleringstape",
    "prod_sac_poubelle": "Skraldeposer",
    "prod_salade_composee": "Blandet salat",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Sauce",
    "prod_sauce_fish": "Fiskesauce",
    "prod_sauce_oyster": "Ostersauce",
    "prod_saucisson_sec": "Tørret pølse",
    "prod_scie": "Sav",
    "prod_seitan_bio": "Økologisk seitan",
    "prod_semoule": "Semulje",
    "prod_serrure": "Lås",
    "prod_sirop": "Sirup",
    "prod_soda_light": "Light sodavand",
    "prod_soda_sans_alcool": "Sodavand",
    "prod_sorbet": "Sorbet",
    "prod_soupe": "Suppe",
    "prod_soupe_miso": "Misosuppe",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Suppe",
    "prod_steak_de_soja": "Sojasteak",
    "prod_tabac": "Tobak",
    "prod_tablette": "Tablet",
    "prod_tampons": "Tamponer",
    "prod_tasseau": "Lægte",
    "prod_terreau": "Pottejord",
    "prod_terrine": "Terrine",
    "prod_timbre": "Frimærke",
    "prod_tisane": "Urte-te",
    "prod_tofu_bio": "Økologisk tofu",
    "prod_tofu_soyeux": "Silketofu",
    "prod_tournevis": "Skruetrækker",
    "prod_tringle": "Gardinstang",
    "prod_tuyau": "Slange",
    "prod_vache_qui_rit": "The Laughing Cow",
    "prod_veau": "Kalvekød",
    "prod_vermicelles": "Vermicelli",
    "prod_vermicelles_de_riz": "Risvermicelli",
    "prod_vernis": "Lak",
    "prod_verrue": "Vortebehandling",
    "prod_viande": "Kød",
    "prod_viande_hachee_2": "Hakket kød",
    "prod_viandes_poissons": "Kød & fisk",
    "prod_viennoiseries": "Wienerbrød",
    "prod_vinaigre_de_riz": "Riseddike",
    "prod_vinaigrette": "Vinaigrette",
    "prod_vis": "Skruer",
    "prod_visseuse": "Skruemaskine",
    "prod_volaille": "Fjerkræ",
    "prod_zeste": "Skal",
}

SV = {
    "prod_adoucissant": "Sköljmedel",
    "prod_agneau": "Lammkött",
    "prod_agrafeuse": "Häftapparat",
    "prod_agraves": "Agave",
    "prod_algues_nori": "Nori-alger",
    "prod_algues_wakame": "Wakame-alger",
    "prod_allumettes": "Tändstickor",
    "prod_ampoule": "Glödlampa",
    "prod_anchois": "Ansjovis",
    "prod_andouille": "Andouille",
    "prod_aneth": "Dill",
    "prod_anneaux": "Ringar",
    "prod_apero_dinatoire": "Middagssnacks",
    "prod_baies_de_goji": "Gojibär",
    "prod_bain_de_bouche": "Munskölj",
    "prod_bambou": "Bambu",
    "prod_batterie": "Batteri",
    "prod_biberon": "Nappflaska",
    "prod_biscottes": "Skorpor",
    "prod_biscuits_bio": "Ekologiska kex",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Foie gras-block",
    "prod_boissons": "Drycker",
    "prod_boudin_noir": "Blodpudding",
    "prod_boulangerie": "Bageri",
    "prod_boulettes": "Köttbullar",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Bultar",
    "prod_briquet": "Tändare",
    "prod_brochettes": "Spett",
    "prod_bulots": "Valthornssnäckor",
    "prod_burin": "Mejsel",
    "prod_canard": "Anka",
    "prod_capres": "Kapris",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Anteckningsbok",
    "prod_carrelage": "Kakel",
    "prod_carte_recharge": "Laddningskort",
    "prod_cartes_postales": "Vykort",
    "prod_cartouche_filtre": "Filterpatron",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Svamp",
    "prod_champignons_noirs": "Svart svamp",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Vispgrädde",
    "prod_charcuterie_artisanale": "Hantverkschark",
    "prod_chauffage": "Värme",
    "prod_chevilles": "Plugg",
    "prod_chewing_gum": "Tuggummi",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Mjölkchoklad",
    "prod_chocolat_bio": "Ekologisk choklad",
    "prod_chocolat_blanc": "Vit choklad",
    "prod_chocolat_noir": "Mörk choklad",
    "prod_chou_chinois": "Kinakål",
    "prod_choucroute": "Surkål",
    "prod_cidre": "Cider",
    "prod_cigares": "Cigarrer",
    "prod_cigarettes": "Cigaretter",
    "prod_citron": "Citron",
    "prod_citronnelle": "Citrongräs",
    "prod_clous": "Spik",
    "prod_colle": "Lim",
    "prod_colle_carrelage": "Kakellim",
    "prod_collier": "Halsband",
    "prod_compote_bio": "Ekologisk kompott",
    "prod_confiture_bio": "Ekologisk sylt",
    "prod_confiture_dabricot": "Aprikossylt",
    "prod_confiture_de_fraises": "Jordgubbssylt",
    "prod_confiture_maison": "Hemlagad sylt",
    "prod_coquillages": "Skaldjur",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Bomullsrondeller",
    "prod_couches": "Blöjor",
    "prod_coulis": "Coulis",
    "prod_coupe": "Kopp",
    "prod_crackers_sans_sel": "Osaltade kex",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Krok",
    "prod_curry_rouge": "Röd curry",
    "prod_curry_vert": "Grön curry",
    "prod_cutter": "Kniv",
    "prod_digestif": "Digestif",
    "prod_douille": "Hylsa",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Sallad/endiv",
    "prod_enduit": "Spackel",
    "prod_engrais": "Gödsel",
    "prod_enveloppes": "Kuvert",
    "prod_escalope": "Escalope",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Rispapper",
    "prod_fil_dentaire": "Tandtråd",
    "prod_filet": "Filé",
    "prod_fleurs": "Blommor",
    "prod_fondue_savoyarde": "Savoyard fondue",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Gårdsost",
    "prod_fruits_bio": "Ekologisk frukt",
    "prod_fruits_de_mer": "Skaldjur",
    "prod_galettes_de_riz": "Riskakor",
    "prod_gel_douche": "Duschgel",
    "prod_gibier": "Vilt",
    "prod_gommage": "Skrubb",
    "prod_graines": "Frön",
    "prod_graines_de_chia": "Chiafrön",
    "prod_graines_de_lin": "Linfrön",
    "prod_grattage": "Skraplott",
    "prod_haricots": "Bönor",
    "prod_herbes": "Örter",
    "prod_homard": "Hummer",
    "prod_huile_dolive_bio": "Ekologisk olivolja",
    "prod_infusion": "Örtte",
    "prod_interrupteur": "Strömbrytare",
    "prod_jambon_cru": "Rökt skinka",
    "prod_javel": "Blekmedel",
    "prod_joint": "Packning",
    "prod_joint_carrelage": "Fogmassa",
    "prod_joint_torique": "O-ring",
    "prod_journal": "Tidning",
    "prod_jus": "Juice",
    "prod_jus_de_fruit_naturel": "Naturlig fruktjuice",
    "prod_jus_de_raisin": "Druvjuice",
    "prod_jus_dorange": "Apelsinjuice",
    "prod_laine_de_verre": "Glasull",
    "prod_lait_bio": "Ekologisk mjölk",
    "prod_lait_de_coco": "Kokosmjölk",
    "prod_lait_en_poudre": "Mjölkpulver",
    "prod_lambris": "Panel",
    "prod_lame_de_scie": "Sågblad",
    "prod_langoustines": "Langoustines",
    "prod_lapin": "Kanin",
    "prod_lard": "Fläsk",
    "prod_lasagnes": "Lasagne",
    "prod_lasure": "Träskydd",
    "prod_lentilles_corail": "Röda linser",
    "prod_lime": "Fil",
    "prod_limette": "Lime",
    "prod_lingettes": "Servetter",
    "prod_liquide_vaisselle": "Diskmedel",
    "prod_loto": "Lotteri",
    "prod_madeleines": "Madeleines",
    "prod_magazine": "Tidning",
    "prod_marteau": "Hammare",
    "prod_masque": "Ansiktsmask",
    "prod_masse": "Slägga",
    "prod_mastic": "Kit",
    "prod_menthe": "Mynta",
    "prod_miel_bio": "Ekologisk honung",
    "prod_miel_du_producteur": "Producenthonung",
    "prod_mouchoirs": "Näsdukar",
    "prod_muesli_barres": "Müslibars",
    "prod_muesli_bio": "Ekologisk müsli",
    "prod_nectar": "Nektar",
    "prod_nems": "Vårrullar",
    "prod_nettoyant_sol": "Golvrengöring",
    "prod_niveau": "Vattenpass",
    "prod_noix_de_cajou": "Cashewnötter",
    "prod_nouilles": "Nudlar",
    "prod_pain_bio": "Ekologiskt bröd",
    "prod_pain_de_viande": "Köttfärslimpa",
    "prod_palets_bretons": "Bretonska småkakor",
    "prod_panneau_osb": "OSB-skiva",
    "prod_papier_de_verre": "Sandpapper",
    "prod_parfum": "Parfym",
    "prod_parquet": "Parkett",
    "prod_pastilles": "Pastiller",
    "prod_pate": "Paté",
    "prod_pate_carbonara": "Carbonara",
    "prod_pates_carbonara": "Carbonara-pasta",
    "prod_paumelle": "Gångjärn",
    "prod_peinture": "Färg",
    "prod_perceuse": "Borrmaskin",
    "prod_petit_dej": "Frukost",
    "prod_petit_dejeuner": "Frukost",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Batteri",
    "prod_pince": "Tång",
    "prod_pinceau": "Pensel",
    "prod_pizza_maison": "Hemgjord pizza",
    "prod_planche": "Bräda",
    "prod_plantes": "Växter",
    "prod_plantes_aromatiques": "Kryddörter",
    "prod_poisson": "Fisk",
    "prod_poisson_frais": "Färsk fisk",
    "prod_porc": "Fläskkött",
    "prod_pot": "Burk",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Soppa",
    "prod_poudre": "Pulver",
    "prod_poulet_fermier": "Frigående kyckling",
    "prod_pousse_de_bambou": "Bambuskott",
    "prod_pousses_de_soja": "Bön groddar",
    "prod_presse": "Press",
    "prod_prise": "Eluttag",
    "prod_produit_vitres": "Glasrengöring",
    "prod_produits_laitiers": "Mejeriprodukter",
    "prod_pruneaux": "Katrinplommon",
    "prod_pull": "Tröja",
    "prod_punaises": "Häftstift",
    "prod_puree_d": "Mos",
    "prod_quinoa_bio": "Ekologisk quinoa",
    "prod_raccord": "Rörkoppling",
    "prod_radiateur": "Element",
    "prod_raviolis_chinois": "Kinesiska dumplings",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Tändargas",
    "prod_rhum": "Rom",
    "prod_rideau": "Gardin",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Basmatiris",
    "prod_riz_complet": "Fullkornsris",
    "prod_riz_glutineux": "Klibbris",
    "prod_robineterie": "Blandare",
    "prod_rouleau": "Färgrulle",
    "prod_ruban_isolant": "Isoleringstejp",
    "prod_sac_poubelle": "Soppåsar",
    "prod_salade_composee": "Blandad sallad",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Sås",
    "prod_sauce_fish": "Fisksås",
    "prod_sauce_oyster": "Ostronsås",
    "prod_saucisson_sec": "Torkad korv",
    "prod_scie": "Såg",
    "prod_seitan_bio": "Ekologisk seitan",
    "prod_semoule": "Semolina",
    "prod_serrure": "Lås",
    "prod_sirop": "Sirap",
    "prod_soda_light": "Light läsk",
    "prod_soda_sans_alcool": "Läsk",
    "prod_sorbet": "Sorbet",
    "prod_soupe": "Soppa",
    "prod_soupe_miso": "Misosoppa",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Soppa",
    "prod_steak_de_soja": "Sojasteak",
    "prod_tabac": "Tobak",
    "prod_tablette": "Surfplatta",
    "prod_tampons": "Tamponger",
    "prod_tasseau": "Regel",
    "prod_terreau": "Blomjord",
    "prod_terrine": "Terrin",
    "prod_timbre": "Frimärke",
    "prod_tisane": "Örtte",
    "prod_tofu_bio": "Ekologisk tofu",
    "prod_tofu_soyeux": "Silkestofu",
    "prod_tournevis": "Skruvmejsel",
    "prod_tringle": "Gardinstång",
    "prod_tuyau": "Slang",
    "prod_vache_qui_rit": "The Laughing Cow",
    "prod_veau": "Kalvkött",
    "prod_vermicelles": "Vermicelli",
    "prod_vermicelles_de_riz": "Risvermicelli",
    "prod_vernis": "Lack",
    "prod_verrue": "Vårtmedel",
    "prod_viande": "Kött",
    "prod_viande_hachee_2": "Köttfärs",
    "prod_viandes_poissons": "Kött & fisk",
    "prod_viennoiseries": "Bakverk",
    "prod_vinaigre_de_riz": "Risvinäger",
    "prod_vinaigrette": "Vinaigrette",
    "prod_vis": "Skruvar",
    "prod_visseuse": "Skruvdragare",
    "prod_volaille": "Fjäderfä",
    "prod_zeste": "Skal",
}

NB = {
    "prod_adoucissant": "Skyllemiddel",
    "prod_agneau": "Lammekjøtt",
    "prod_agrafeuse": "Stiftemaskin",
    "prod_agraves": "Agave",
    "prod_algues_nori": "Nori-alger",
    "prod_algues_wakame": "Wakame-alger",
    "prod_allumettes": "Fyrstikker",
    "prod_ampoule": "Lyspære",
    "prod_anchois": "Ansjos",
    "prod_andouille": "Andouille",
    "prod_aneth": "Dill",
    "prod_anneaux": "Ringer",
    "prod_apero_dinatoire": "Middagssnacks",
    "prod_baies_de_goji": "Gojibær",
    "prod_bain_de_bouche": "Munnvann",
    "prod_bambou": "Bambus",
    "prod_batterie": "Batteri",
    "prod_biberon": "Tåteflaske",
    "prod_biscottes": "Kavring",
    "prod_biscuits_bio": "Økologiske kjeks",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Foie gras-blokk",
    "prod_boissons": "Drikkevarer",
    "prod_boudin_noir": "Blodpølse",
    "prod_boulangerie": "Bakeri",
    "prod_boulettes": "Kjøttboller",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Bolter",
    "prod_briquet": "Lighter",
    "prod_brochettes": "Grillspyd",
    "prod_bulots": "Knottsnegl",
    "prod_burin": "Meisel",
    "prod_canard": "And",
    "prod_capres": "Kapers",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Notatbok",
    "prod_carrelage": "Fliser",
    "prod_carte_recharge": "Påfyllingskort",
    "prod_cartes_postales": "Postkort",
    "prod_cartouche_filtre": "Filterpatron",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Sopp",
    "prod_champignons_noirs": "Treear-sopp",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Pisket fløte",
    "prod_charcuterie_artisanale": "Håndverks pålegg",
    "prod_chauffage": "Oppvarming",
    "prod_chevilles": "Plugg",
    "prod_chewing_gum": "Tyggis",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Melkechokolade",
    "prod_chocolat_bio": "Økologisk sjokolade",
    "prod_chocolat_blanc": "Hvit sjokolade",
    "prod_chocolat_noir": "Mørk sjokolade",
    "prod_chou_chinois": "Kinakål",
    "prod_choucroute": "Surkål",
    "prod_cidre": "Cider",
    "prod_cigares": "Sigarer",
    "prod_cigarettes": "Sigaretter",
    "prod_citron": "Sitron",
    "prod_citronnelle": "Sitrongress",
    "prod_clous": "Spiker",
    "prod_colle": "Lim",
    "prod_colle_carrelage": "Fliselim",
    "prod_collier": "Halskjede",
    "prod_compote_bio": "Økologisk kompott",
    "prod_confiture_bio": "Økologisk syltetøy",
    "prod_confiture_dabricot": "Aprikossyltetøy",
    "prod_confiture_de_fraises": "Jordbærsyltetøy",
    "prod_confiture_maison": "Hjemmelaget syltetøy",
    "prod_coquillages": "Skalldyr",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Bomullspads",
    "prod_couches": "Bleier",
    "prod_coulis": "Coulis",
    "prod_coupe": "Kopp",
    "prod_crackers_sans_sel": "Usaltede kjeks",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Krok",
    "prod_curry_rouge": "Rød karri",
    "prod_curry_vert": "Grønn karri",
    "prod_cutter": "Kniv",
    "prod_digestif": "Digestif",
    "prod_douille": "Dop",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Endiv",
    "prod_enduit": "Sparkel",
    "prod_engrais": "Gjødsel",
    "prod_enveloppes": "Konvolutter",
    "prod_escalope": "Escalope",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Rispapir",
    "prod_fil_dentaire": "Tanntråd",
    "prod_filet": "Filet",
    "prod_fleurs": "Blomster",
    "prod_fondue_savoyarde": "Savoyard fondue",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Gårdsost",
    "prod_fruits_bio": "Økologisk frukt",
    "prod_fruits_de_mer": "Sjømat",
    "prod_galettes_de_riz": "Riskaker",
    "prod_gel_douche": "Dusjgel",
    "prod_gibier": "Vilt",
    "prod_gommage": "Skrubb",
    "prod_graines": "Frø",
    "prod_graines_de_chia": "Chiafrø",
    "prod_graines_de_lin": "Linfrø",
    "prod_grattage": "Skrapelodd",
    "prod_haricots": "Bønner",
    "prod_herbes": "Urter",
    "prod_homard": "Hummer",
    "prod_huile_dolive_bio": "Økologisk olivenolje",
    "prod_infusion": "Urtete",
    "prod_interrupteur": "Bryter",
    "prod_jambon_cru": "Spekeskinke",
    "prod_javel": "Blekkemiddel",
    "prod_joint": "Pakning",
    "prod_joint_carrelage": "Fugemasse",
    "prod_joint_torique": "O-ring",
    "prod_journal": "Avis",
    "prod_jus": "Juice",
    "prod_jus_de_fruit_naturel": "Naturlig fruktjuice",
    "prod_jus_de_raisin": "Druejuice",
    "prod_jus_dorange": "Appelsinjuice",
    "prod_laine_de_verre": "Glassull",
    "prod_lait_bio": "Økologisk melk",
    "prod_lait_de_coco": "Kokosmelk",
    "prod_lait_en_poudre": "Melkepulver",
    "prod_lambris": "Panel",
    "prod_lame_de_scie": "Sagblad",
    "prod_langoustines": "Langoustines",
    "prod_lapin": "Kanin",
    "prod_lard": "Fett",
    "prod_lasagnes": "Lasagne",
    "prod_lasure": "Beis",
    "prod_lentilles_corail": "Røde linser",
    "prod_lime": "Fil",
    "prod_limette": "Lime",
    "prod_lingettes": "Servietter",
    "prod_liquide_vaisselle": "Oppvaskmiddel",
    "prod_loto": "Lotteri",
    "prod_madeleines": "Madeleines",
    "prod_magazine": "Magasin",
    "prod_marteau": "Hammer",
    "prod_masque": "Ansiktsmaske",
    "prod_masse": "Forhammer",
    "prod_mastic": "Kit",
    "prod_menthe": "Mynte",
    "prod_miel_bio": "Økologisk honning",
    "prod_miel_du_producteur": "Produsenthonning",
    "prod_mouchoirs": "Lommetørkler",
    "prod_muesli_barres": "Müslibar",
    "prod_muesli_bio": "Økologisk müsli",
    "prod_nectar": "Nektar",
    "prod_nems": "Vårruller",
    "prod_nettoyant_sol": "Gulvrens",
    "prod_niveau": "Vater",
    "prod_noix_de_cajou": "Cashewnøtter",
    "prod_nouilles": "Nudler",
    "prod_pain_bio": "Økologisk brød",
    "prod_pain_de_viande": "Kjøttkake",
    "prod_palets_bretons": "Bretonske småkaker",
    "prod_panneau_osb": "OSB-plate",
    "prod_papier_de_verre": "Sandpapir",
    "prod_parfum": "Parfyme",
    "prod_parquet": "Parkett",
    "prod_pastilles": "Pastiller",
    "prod_pate": "Postei",
    "prod_pate_carbonara": "Carbonara",
    "prod_pates_carbonara": "Carbonara-pasta",
    "prod_paumelle": "Hengsel",
    "prod_peinture": "Maling",
    "prod_perceuse": "Bormaskin",
    "prod_petit_dej": "Frokost",
    "prod_petit_dejeuner": "Frokost",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Batteri",
    "prod_pince": "Tang",
    "prod_pinceau": "Pensel",
    "prod_pizza_maison": "Hjemmelaget pizza",
    "prod_planche": "Brett",
    "prod_plantes": "Planter",
    "prod_plantes_aromatiques": "Krydderurter",
    "prod_poisson": "Fisk",
    "prod_poisson_frais": "Fersk fisk",
    "prod_porc": "Svinekjøtt",
    "prod_pot": "Glass",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Suppe",
    "prod_poudre": "Pulver",
    "prod_poulet_fermier": "Frittgående kylling",
    "prod_pousse_de_bambou": "Bambusskudd",
    "prod_pousses_de_soja": "Bønnespirer",
    "prod_presse": "Presse",
    "prod_prise": "Stikkontakt",
    "prod_produit_vitres": "Glassrens",
    "prod_produits_laitiers": "Meieriprodukter",
    "prod_pruneaux": "Svisker",
    "prod_pull": "Genser",
    "prod_punaises": "Tegnestifter",
    "prod_puree_d": "Mos",
    "prod_quinoa_bio": "Økologisk quinoa",
    "prod_raccord": "Rørkobling",
    "prod_radiateur": "Radiator",
    "prod_raviolis_chinois": "Kinesiske dumplings",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Lightergass",
    "prod_rhum": "Rom",
    "prod_rideau": "Gardin",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Basmatiris",
    "prod_riz_complet": "Brun ris",
    "prod_riz_glutineux": "Klebrig ris",
    "prod_robineterie": "Armaturer",
    "prod_rouleau": "Malerrull",
    "prod_ruban_isolant": "Isoleringstape",
    "prod_sac_poubelle": "Søppelsekker",
    "prod_salade_composee": "Blandet salat",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Saus",
    "prod_sauce_fish": "Fiskesaus",
    "prod_sauce_oyster": "Ostersaus",
    "prod_saucisson_sec": "Tørr pølse",
    "prod_scie": "Sag",
    "prod_seitan_bio": "Økologisk seitan",
    "prod_semoule": "Semule",
    "prod_serrure": "Lås",
    "prod_sirop": "Sirup",
    "prod_soda_light": "Light brus",
    "prod_soda_sans_alcool": "Brus",
    "prod_sorbet": "Sorbet",
    "prod_soupe": "Suppe",
    "prod_soupe_miso": "Misosuppe",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Suppe",
    "prod_steak_de_soja": "Sojasteik",
    "prod_tabac": "Tobakk",
    "prod_tablette": "Nettbrett",
    "prod_tampons": "Tamponger",
    "prod_tasseau": "Lekt",
    "prod_terreau": "Pottejord",
    "prod_terrine": "Terrin",
    "prod_timbre": "Frimerke",
    "prod_tisane": "Urtete",
    "prod_tofu_bio": "Økologisk tofu",
    "prod_tofu_soyeux": "Silketofu",
    "prod_tournevis": "Skrujern",
    "prod_tringle": "Gardinstang",
    "prod_tuyau": "Slange",
    "prod_vache_qui_rit": "The Laughing Cow",
    "prod_veau": "Kalvekjøtt",
    "prod_vermicelles": "Vermicelli",
    "prod_vermicelles_de_riz": "Risvermicelli",
    "prod_vernis": "Lakk",
    "prod_verrue": "Vortemiddel",
    "prod_viande": "Kjøtt",
    "prod_viande_hachee_2": "Kjøttdeig",
    "prod_viandes_poissons": "Kjøtt & fisk",
    "prod_viennoiseries": "Bakverk",
    "prod_vinaigre_de_riz": "Riseddik",
    "prod_vinaigrette": "Vinaigrette",
    "prod_vis": "Skruer",
    "prod_visseuse": "Skrutrekker",
    "prod_volaille": "Fjærfe",
    "prod_zeste": "Skall",
}

FI = {
    "prod_adoucissant": "Huuhteluaine",
    "prod_agneau": "Lammas",
    "prod_agrafeuse": "Niittari",
    "prod_agraves": "Agave",
    "prod_algues_nori": "Nori-levä",
    "prod_algues_wakame": "Wakame-levä",
    "prod_allumettes": "Tulitikut",
    "prod_ampoule": "Hehkulamppu",
    "prod_anchois": "Anjovis",
    "prod_andouille": "Andouille",
    "prod_aneth": "Tilli",
    "prod_anneaux": "Renkaat",
    "prod_apero_dinatoire": "Iltapalat",
    "prod_baies_de_goji": "Gojimarjat",
    "prod_bain_de_bouche": "Suuhuuhtelu",
    "prod_bambou": "Bambu",
    "prod_batterie": "Paristo",
    "prod_biberon": "Tuttipullo",
    "prod_biscottes": "Korppu",
    "prod_biscuits_bio": "Luomukeksit",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Foie gras -lohko",
    "prod_boissons": "Juomat",
    "prod_boudin_noir": "Mustamakkara",
    "prod_boulangerie": "Leipomo",
    "prod_boulettes": "Lihapullat",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Pultit",
    "prod_briquet": "Sytytin",
    "prod_brochettes": "Varras",
    "prod_bulots": "Merikotka",
    "prod_burin": "Lehti",
    "prod_canard": "Ankka",
    "prod_capres": "Kapris",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Muistikirja",
    "prod_carrelage": "Laattaa",
    "prod_carte_recharge": "Latauskortti",
    "prod_cartes_postales": "Postikortit",
    "prod_cartouche_filtre": "Suodatinpatruuna",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Sienet",
    "prod_champignons_noirs": "Korvasieni",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Vatkattu kerma",
    "prod_charcuterie_artisanale": "Artesaani-leikkeleet",
    "prod_chauffage": "Lämmitys",
    "prod_chevilles": "Tolpat",
    "prod_chewing_gum": "Purukumi",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Maitosuklaa",
    "prod_chocolat_bio": "Luomusuklaa",
    "prod_chocolat_blanc": "Valkosuklaa",
    "prod_chocolat_noir": "Tumma suklaa",
    "prod_chou_chinois": "Kiinankaali",
    "prod_choucroute": "Hapankaali",
    "prod_cidre": "Siideri",
    "prod_cigares": "Sikarit",
    "prod_cigarettes": "Tupakat",
    "prod_citron": "Sitruuna",
    "prod_citronnelle": "Sitrongrass",
    "prod_clous": "Naulat",
    "prod_colle": "Liima",
    "prod_colle_carrelage": "Laattaliima",
    "prod_collier": "Kaulakoru",
    "prod_compote_bio": "Luomuhedelmäsose",
    "prod_confiture_bio": "Luomuhillo",
    "prod_confiture_dabricot": "Aprikoosihillo",
    "prod_confiture_de_fraises": "Mansikkahillo",
    "prod_confiture_maison": "Kotihillo",
    "prod_coquillages": "Äyriäiset",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Vanulaput",
    "prod_couches": "Vaipat",
    "prod_coulis": "Coulis",
    "prod_coupe": "Kuppi",
    "prod_crackers_sans_sel": "Suolattomat keksit",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Koukku",
    "prod_curry_rouge": "Punainen curry",
    "prod_curry_vert": "Vihreä curry",
    "prod_cutter": "Leikkuri",
    "prod_digestif": "Digestif",
    "prod_douille": "Hylsy",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Endiivi",
    "prod_enduit": "Spackel",
    "prod_engrais": "Lannoite",
    "prod_enveloppes": "Kirjekuoret",
    "prod_escalope": "Escalope",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Riisipaperi",
    "prod_fil_dentaire": "Hammaslanka",
    "prod_filet": "Filee",
    "prod_fleurs": "Kukat",
    "prod_fondue_savoyarde": "Savoyard fondue",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Maatilan juusto",
    "prod_fruits_bio": "Luomuhedelmät",
    "prod_fruits_de_mer": "Merenelävät",
    "prod_galettes_de_riz": "Riisikakut",
    "prod_gel_douche": "Suihkugeeli",
    "prod_gibier": "Riista",
    "prod_gommage": "Kuorinta",
    "prod_graines": "Siemenet",
    "prod_graines_de_chia": "Chiasiemenet",
    "prod_graines_de_lin": "Pellavansiemenet",
    "prod_grattage": "Raaputusarpa",
    "prod_haricots": "Pavut",
    "prod_herbes": "Yrtit",
    "prod_homard": "Hummeri",
    "prod_huile_dolive_bio": "Luomuoliiviöljy",
    "prod_infusion": "Yrttitee",
    "prod_interrupteur": "Kytkin",
    "prod_jambon_cru": "Kuivattu kinkku",
    "prod_javel": "Valkaisuaine",
    "prod_joint": "Tiiviste",
    "prod_joint_carrelage": "Sauma",
    "prod_joint_torique": "O-rengas",
    "prod_journal": "Sanomalehti",
    "prod_jus": "Mehu",
    "prod_jus_de_fruit_naturel": "Luonnollinen hedelmämehu",
    "prod_jus_de_raisin": "Rypälemehu",
    "prod_jus_dorange": "Appelsiinimehu",
    "prod_laine_de_verre": "Lasivilla",
    "prod_lait_bio": "Luomumaito",
    "prod_lait_de_coco": "Kookosmaito",
    "prod_lait_en_poudre": "Maitojauhe",
    "prod_lambris": "Paneli",
    "prod_lame_de_scie": "Sahanterä",
    "prod_langoustines": "Langoustines",
    "prod_lapin": "Kani",
    "prod_lard": "Pehmeä pekoni",
    "prod_lasagnes": "Lasagne",
    "prod_lasure": "Lasi",
    "prod_lentilles_corail": "Punaiset linssit",
    "prod_lime": "Viila",
    "prod_limette": "Lime",
    "prod_lingettes": "Pyyhkeet",
    "prod_liquide_vaisselle": "Astianpesuaine",
    "prod_loto": "Arpajaiset",
    "prod_madeleines": "Madeleines",
    "prod_magazine": "Aikakauslehti",
    "prod_marteau": "Vasara",
    "prod_masque": "Kasvonaamio",
    "prod_masse": "Moukarivasara",
    "prod_mastic": "Kitti",
    "prod_menthe": "Minttu",
    "prod_miel_bio": "Luomuhunaja",
    "prod_miel_du_producteur": "Tuottajan hunaja",
    "prod_mouchoirs": "Nenäliinat",
    "prod_muesli_barres": "Müslipatukat",
    "prod_muesli_bio": "Luomumüsli",
    "prod_nectar": "Nektar",
    "prod_nems": "Kevätrullat",
    "prod_nettoyant_sol": "Lattianpesuaine",
    "prod_niveau": "Vesivaaka",
    "prod_noix_de_cajou": "Cashewpähkinät",
    "prod_nouilles": "Nuudelit",
    "prod_pain_bio": "Luomuleipä",
    "prod_pain_de_viande": "Lihamureke",
    "prod_palets_bretons": "Bretonin voikeksit",
    "prod_panneau_osb": "OSB-levy",
    "prod_papier_de_verre": "Hiekkapaperi",
    "prod_parfum": "Tuoksu",
    "prod_parquet": "Parketti",
    "prod_pastilles": "Pastillit",
    "prod_pate": "Paté",
    "prod_pate_carbonara": "Carbonara",
    "prod_pates_carbonara": "Carbonara-pasta",
    "prod_paumelle": "Sarana",
    "prod_peinture": "Maali",
    "prod_perceuse": "Pora",
    "prod_petit_dej": "Aamiainen",
    "prod_petit_dejeuner": "Aamiainen",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Paristo",
    "prod_pince": "Pihdit",
    "prod_pinceau": "Sivellin",
    "prod_pizza_maison": "Kotipizza",
    "prod_planche": "Lauta",
    "prod_plantes": "Kasvit",
    "prod_plantes_aromatiques": "Yrtit",
    "prod_poisson": "Kala",
    "prod_poisson_frais": "Tuore kala",
    "prod_porc": "Sianliha",
    "prod_pot": "Purkki",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Keitto",
    "prod_poudre": "Jauhe",
    "prod_poulet_fermier": "Luomukananliha",
    "prod_pousse_de_bambou": "Bambunversot",
    "prod_pousses_de_soja": "Soijanidus",
    "prod_presse": "Puristin",
    "prod_prise": "Pistorasia",
    "prod_produit_vitres": "Lasinpesuaine",
    "prod_produits_laitiers": "Maitotuotteet",
    "prod_pruneaux": "Luumut",
    "prod_pull": "Neule",
    "prod_punaises": "Nuppineulat",
    "prod_puree_d": "Sose",
    "prod_quinoa_bio": "Luomukvinoa",
    "prod_raccord": "Liitin",
    "prod_radiateur": "Patteri",
    "prod_raviolis_chinois": "Kiinalaiset dumplingit",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Sytytin kaasu",
    "prod_rhum": "Rommi",
    "prod_rideau": "Verho",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Basmatiriisi",
    "prod_riz_complet": "Täysjyväriisi",
    "prod_riz_glutineux": "Tahme riisi",
    "prod_robineterie": "Hanat",
    "prod_rouleau": "Telan",
    "prod_ruban_isolant": "Eristeteippi",
    "prod_sac_poubelle": "Roskapussit",
    "prod_salade_composee": "Salaatti",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Kastike",
    "prod_sauce_fish": "Kalakastike",
    "prod_sauce_oyster": "Osterikastike",
    "prod_saucisson_sec": "Kuivattu makkara",
    "prod_scie": "Saha",
    "prod_seitan_bio": "Luomuseitan",
    "prod_semoule": "Mannasuurimo",
    "prod_serrure": "Lukko",
    "prod_sirop": "Siirappi",
    "prod_soda_light": "Light limsa",
    "prod_soda_sans_alcool": "Limonadi",
    "prod_sorbet": "Sorbetti",
    "prod_soupe": "Keitto",
    "prod_soupe_miso": "Misokeitto",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Keitto",
    "prod_steak_de_soja": "Soijasteikki",
    "prod_tabac": "Tupakka",
    "prod_tablette": "Tabletti",
    "prod_tampons": "Tamponit",
    "prod_tasseau": "Lauta",
    "prod_terreau": "Multaa",
    "prod_terrine": "Terrine",
    "prod_timbre": "Postimerkki",
    "prod_tisane": "Yrttitee",
    "prod_tofu_bio": "Luomutofu",
    "prod_tofu_soyeux": "Silkk tofu",
    "prod_tournevis": "Ruuvimeisseli",
    "prod_tringle": "Verhotanko",
    "prod_tuyau": "Letku",
    "prod_vache_qui_rit": "The Laughing Cow",
    "prod_veau": "Vasikka",
    "prod_vermicelles": "Vermicelli",
    "prod_vermicelles_de_riz": "Riisinuudelit",
    "prod_vernis": "Lakka",
    "prod_verrue": "Syylähoito",
    "prod_viande": "Liha",
    "prod_viande_hachee_2": "Jauheliha",
    "prod_viandes_poissons": "Liha & kala",
    "prod_viennoiseries": "Leivonnaiset",
    "prod_vinaigre_de_riz": "Riisiviinietikka",
    "prod_vinaigrette": "Vinaigrette",
    "prod_vis": "Ruuvit",
    "prod_visseuse": "Ruuvinväännin",
    "prod_volaille": "Siipikarja",
    "prod_zeste": "Kuori",
}

LOCALES = {
    "de": DE,
    "nl": NL,
    "da": DA,
    "sv": SV,
    "nb": NB,
    "fi": FI,
}


def main() -> None:
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from prod_en_map import EN_PROD

    expected = set(EN_PROD)
    OUT.mkdir(parents=True, exist_ok=True)

    for loc, data in LOCALES.items():
        missing = expected - set(data)
        extra = set(data) - expected
        if missing or extra:
            raise SystemExit(f"{loc}: missing={sorted(missing)} extra={sorted(extra)}")
        ordered = {k: data[k] for k in sorted(data)}
        path = OUT / f"{loc}.json"
        path.write_text(
            json.dumps(ordered, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"{loc}.json: {len(ordered)} keys")


if __name__ == "__main__":
    main()
