#!/usr/bin/env python3
"""Generate prod_patches JSON for es, it, pt, ca, gl, eu, ro."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "prod_patches"

# fmt: off
ES = {
    "prod_adoucissant": "Suavizante",
    "prod_agneau": "Cordero",
    "prod_agrafeuse": "Grapadora",
    "prod_agraves": "Agaves",
    "prod_algues_nori": "Alga nori",
    "prod_algues_wakame": "Alga wakame",
    "prod_allumettes": "Cerillas",
    "prod_ampoule": "Bombilla",
    "prod_anchois": "Anchoas",
    "prod_andouille": "Andouille",
    "prod_aneth": "Eneldo",
    "prod_anneaux": "Anillas",
    "prod_apero_dinatoire": "Aperitivos de cena",
    "prod_baies_de_goji": "Bayas de goji",
    "prod_bain_de_bouche": "Enjuague bucal",
    "prod_bambou": "Bambú",
    "prod_batterie": "Pila",
    "prod_biberon": "Biberón",
    "prod_biscottes": "Bizcochos tostados",
    "prod_biscuits_bio": "Galletas ecológicas",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Bloc de foie gras",
    "prod_boissons": "Bebidas",
    "prod_boudin_noir": "Morcilla",
    "prod_boulangerie": "Panadería",
    "prod_boulettes": "Albóndigas",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Tornillos de carrocero",
    "prod_briquet": "Mechero",
    "prod_brochettes": "Brochetas",
    "prod_bulots": "Buccinos",
    "prod_burin": "Cincel",
    "prod_canard": "Pato",
    "prod_capres": "Alcaparras",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Cuaderno",
    "prod_carrelage": "Azulejos",
    "prod_carte_recharge": "Tarjeta de recarga",
    "prod_cartes_postales": "Postales",
    "prod_cartouche_filtre": "Cartucho de filtro",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Champiñones",
    "prod_champignons_noirs": "Setas oreja de madera",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Nata montada",
    "prod_charcuterie_artisanale": "Embutidos artesanales",
    "prod_chauffage": "Calefacción",
    "prod_chevilles": "Tacos",
    "prod_chewing_gum": "Chicle",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Chocolate con leche",
    "prod_chocolat_bio": "Chocolate ecológico",
    "prod_chocolat_blanc": "Chocolate blanco",
    "prod_chocolat_noir": "Chocolate negro",
    "prod_chou_chinois": "Col china",
    "prod_choucroute": "Chucrut",
    "prod_cidre": "Sidra",
    "prod_cigares": "Puros",
    "prod_cigarettes": "Cigarrillos",
    "prod_citron": "Limón",
    "prod_citronnelle": "Hierba limón",
    "prod_clous": "Clavos",
    "prod_colle": "Cola",
    "prod_colle_carrelage": "Adhesivo para azulejos",
    "prod_collier": "Collar",
    "prod_compote_bio": "Compota ecológica",
    "prod_confiture_bio": "Mermelada ecológica",
    "prod_confiture_dabricot": "Mermelada de albaricoque",
    "prod_confiture_de_fraises": "Mermelada de fresa",
    "prod_confiture_maison": "Mermelada casera",
    "prod_coquillages": "Marisco",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Discos de algodón",
    "prod_couches": "Pañales",
    "prod_coulis": "Coulis",
    "prod_coupe": "Copa",
    "prod_crackers_sans_sel": "Galletas saladas sin sal",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Gancho",
    "prod_curry_rouge": "Curry rojo",
    "prod_curry_vert": "Curry verde",
    "prod_cutter": "Cúter",
    "prod_digestif": "Digestivo",
    "prod_douille": "Cazo",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Endibias",
    "prod_enduit": "Masilla",
    "prod_engrais": "Abono",
    "prod_enveloppes": "Sobres",
    "prod_escalope": "Escalope",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Papel de arroz",
    "prod_fil_dentaire": "Hilo dental",
    "prod_filet": "Filete",
    "prod_fleurs": "Flores",
    "prod_fondue_savoyarde": "Fondue savoyarde",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Queso de granja",
    "prod_fruits_bio": "Fruta ecológica",
    "prod_fruits_de_mer": "Marisco",
    "prod_galettes_de_riz": "Tortitas de arroz",
    "prod_gel_douche": "Gel de ducha",
    "prod_gibier": "Carne de caza",
    "prod_gommage": "Exfoliante",
    "prod_graines": "Semillas",
    "prod_graines_de_chia": "Semillas de chía",
    "prod_graines_de_lin": "Semillas de lino",
    "prod_grattage": "Rasca y gana",
    "prod_haricots": "Judías",
    "prod_herbes": "Hierbas",
    "prod_homard": "Bogavante",
    "prod_huile_dolive_bio": "Aceite de oliva ecológico",
    "prod_infusion": "Infusión",
    "prod_interrupteur": "Interruptor",
    "prod_jambon_cru": "Jamón curado",
    "prod_javel": "Lejía",
    "prod_joint": "Junta",
    "prod_joint_carrelage": "Lechada",
    "prod_joint_torique": "Junta tórica",
    "prod_journal": "Periódico",
    "prod_jus": "Zumo",
    "prod_jus_de_fruit_naturel": "Zumo de fruta natural",
    "prod_jus_de_raisin": "Zumo de uva",
    "prod_jus_dorange": "Zumo de naranja",
    "prod_laine_de_verre": "Lana de vidrio",
    "prod_lait_bio": "Leche ecológica",
    "prod_lait_de_coco": "Leche de coco",
    "prod_lait_en_poudre": "Leche en polvo",
    "prod_lambris": "Revestimiento",
    "prod_lame_de_scie": "Hoja de sierra",
    "prod_langoustines": "Langostinos",
    "prod_lapin": "Conejo",
    "prod_lard": "Grasa de tocino",
    "prod_lasagnes": "Lasaña",
    "prod_lasure": "Lasur",
    "prod_lentilles_corail": "Lentejas rojas",
    "prod_lime": "Lima de metal",
    "prod_limette": "Lima",
    "prod_lingettes": "Toallitas",
    "prod_liquide_vaisselle": "Lavavajillas",
    "prod_loto": "Lotería",
    "prod_madeleines": "Magdalenas",
    "prod_magazine": "Revista",
    "prod_marteau": "Martillo",
    "prod_masque": "Mascarilla",
    "prod_masse": "Maza",
    "prod_mastic": "Masilla",
    "prod_menthe": "Menta",
    "prod_miel_bio": "Miel ecológica",
    "prod_miel_du_producteur": "Miel del productor",
    "prod_mouchoirs": "Pañuelos",
    "prod_muesli_barres": "Barritas de muesli",
    "prod_muesli_bio": "Muesli ecológico",
    "prod_nectar": "Néctar",
    "prod_nems": "Rollitos de primavera",
    "prod_nettoyant_sol": "Limpiador de suelos",
    "prod_niveau": "Nivel de burbuja",
    "prod_noix_de_cajou": "Anacardos",
    "prod_nouilles": "Fideos",
    "prod_pain_bio": "Pan ecológico",
    "prod_pain_de_viande": "Pastel de carne",
    "prod_palets_bretons": "Galletas bretonas",
    "prod_panneau_osb": "Panel OSB",
    "prod_papier_de_verre": "Papel de lija",
    "prod_parfum": "Perfume",
    "prod_parquet": "Parquet",
    "prod_pastilles": "Pastillas",
    "prod_pate": "Paté",
    "prod_pate_carbonara": "Pasta carbonara",
    "prod_pates_carbonara": "Pasta carbonara",
    "prod_paumelle": "Bisagra",
    "prod_peinture": "Pintura",
    "prod_perceuse": "Taladro",
    "prod_petit_dej": "Desayuno",
    "prod_petit_dejeuner": "Desayuno",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Pila",
    "prod_pince": "Alicates",
    "prod_pinceau": "Pincel",
    "prod_pizza_maison": "Pizza casera",
    "prod_planche": "Tabla",
    "prod_plantes": "Plantas",
    "prod_plantes_aromatiques": "Hierbas aromáticas",
    "prod_poisson": "Pescado",
    "prod_poisson_frais": "Pescado fresco",
    "prod_porc": "Cerdo",
    "prod_pot": "Tarro",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Potaje",
    "prod_poudre": "Polvo",
    "prod_poulet_fermier": "Pollo de corral",
    "prod_pousse_de_bambou": "Brotes de bambú",
    "prod_pousses_de_soja": "Brotes de soja",
    "prod_presse": "Prensa",
    "prod_prise": "Enchufe",
    "prod_produit_vitres": "Limpiacristales",
    "prod_produits_laitiers": "Lácteos",
    "prod_pruneaux": "Ciruelas pasas",
    "prod_pull": "Jersey",
    "prod_punaises": "Chinchetas",
    "prod_puree_d": "Puré",
    "prod_quinoa_bio": "Quinoa ecológica",
    "prod_raccord": "Racor",
    "prod_radiateur": "Radiador",
    "prod_raviolis_chinois": "Raviolis chinos",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Recarga de mechero",
    "prod_rhum": "Ron",
    "prod_rideau": "Cortina",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Arroz basmati",
    "prod_riz_complet": "Arroz integral",
    "prod_riz_glutineux": "Arroz glutinoso",
    "prod_robineterie": "Grifería",
    "prod_rouleau": "Rodillo",
    "prod_ruban_isolant": "Cinta aislante",
    "prod_sac_poubelle": "Bolsas de basura",
    "prod_salade_composee": "Ensalada mixta",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Salsa",
    "prod_sauce_fish": "Salsa de pescado",
    "prod_sauce_oyster": "Salsa de ostras",
    "prod_saucisson_sec": "Salchichón",
    "prod_scie": "Sierra",
    "prod_seitan_bio": "Seitán ecológico",
    "prod_semoule": "Sémola",
    "prod_serrure": "Cerradura",
    "prod_sirop": "Jarabe",
    "prod_soda_light": "Refresco light",
    "prod_soda_sans_alcool": "Refresco",
    "prod_sorbet": "Sorbete",
    "prod_soupe": "Sopa",
    "prod_soupe_miso": "Sopa miso",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Sopa",
    "prod_steak_de_soja": "Filete de soja",
    "prod_tabac": "Tabaco",
    "prod_tablette": "Tableta",
    "prod_tampons": "Tampones",
    "prod_tasseau": "Listón",
    "prod_terreau": "Sustrato",
    "prod_terrine": "Terrina",
    "prod_timbre": "Sello",
    "prod_tisane": "Infusión",
    "prod_tofu_bio": "Tofu ecológico",
    "prod_tofu_soyeux": "Tofu sedoso",
    "prod_tournevis": "Destornillador",
    "prod_tringle": "Barra de cortina",
    "prod_tuyau": "Manguera",
    "prod_vache_qui_rit": "La Vaca que Ríe",
    "prod_veau": "Ternera",
    "prod_vermicelles": "Fideos finos",
    "prod_vermicelles_de_riz": "Fideos de arroz",
    "prod_vernis": "Barniz",
    "prod_verrue": "Tratamiento de verrugas",
    "prod_viande": "Carne",
    "prod_viande_hachee_2": "Carne picada",
    "prod_viandes_poissons": "Carne y pescado",
    "prod_viennoiseries": "Bollería",
    "prod_vinaigre_de_riz": "Vinagre de arroz",
    "prod_vinaigrette": "Vinagreta",
    "prod_vis": "Tornillos",
    "prod_visseuse": "Atornillador",
    "prod_volaille": "Aves de corral",
    "prod_zeste": "Ralladura",
}

IT = {
    "prod_adoucissant": "Ammorbidente",
    "prod_agneau": "Agnello",
    "prod_agrafeuse": "Graffettatrice",
    "prod_agraves": "Agave",
    "prod_algues_nori": "Alga nori",
    "prod_algues_wakame": "Alga wakame",
    "prod_allumettes": "Fiammiferi",
    "prod_ampoule": "Lampadina",
    "prod_anchois": "Acciughe",
    "prod_andouille": "Andouille",
    "prod_aneth": "Aneto",
    "prod_anneaux": "Anelli",
    "prod_apero_dinatoire": "Stuzzichini per cena",
    "prod_baies_de_goji": "Bacche di goji",
    "prod_bain_de_bouche": "Collutorio",
    "prod_bambou": "Bambù",
    "prod_batterie": "Batteria",
    "prod_biberon": "Biberon",
    "prod_biscottes": "Fette biscottate",
    "prod_biscuits_bio": "Biscotti bio",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Bloc de foie gras",
    "prod_boissons": "Bevande",
    "prod_boudin_noir": "Sanguinaccio",
    "prod_boulangerie": "Panetteria",
    "prod_boulettes": "Polpette",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Bulloni",
    "prod_briquet": "Accendino",
    "prod_brochettes": "Spiedini",
    "prod_bulots": "Buccini",
    "prod_burin": "Scalpello",
    "prod_canard": "Anatra",
    "prod_capres": "Capperi",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Quaderno",
    "prod_carrelage": "Piastrelle",
    "prod_carte_recharge": "Carta ricaricabile",
    "prod_cartes_postales": "Cartoline",
    "prod_cartouche_filtre": "Cartuccia filtro",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Funghi",
    "prod_champignons_noirs": "Funghi orecchio di legno",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Panna montata",
    "prod_charcuterie_artisanale": "Salumi artigianali",
    "prod_chauffage": "Riscaldamento",
    "prod_chevilles": "Tasselli",
    "prod_chewing_gum": "Chewing gum",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Cioccolato al latte",
    "prod_chocolat_bio": "Cioccolato bio",
    "prod_chocolat_blanc": "Cioccolato bianco",
    "prod_chocolat_noir": "Cioccolato fondente",
    "prod_chou_chinois": "Cavolo cinese",
    "prod_choucroute": "Crauti",
    "prod_cidre": "Sidro",
    "prod_cigares": "Sigari",
    "prod_cigarettes": "Sigarette",
    "prod_citron": "Limone",
    "prod_citronnelle": "Citronella",
    "prod_clous": "Chiodi",
    "prod_colle": "Colla",
    "prod_colle_carrelage": "Colla per piastrelle",
    "prod_collier": "Collana",
    "prod_compote_bio": "Composta bio",
    "prod_confiture_bio": "Marmellata bio",
    "prod_confiture_dabricot": "Marmellata di albicocche",
    "prod_confiture_de_fraises": "Marmellata di fragole",
    "prod_confiture_maison": "Marmellata fatta in casa",
    "prod_coquillages": "Crostacei",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Dischetti di cotone",
    "prod_couches": "Pannolini",
    "prod_coulis": "Coulis",
    "prod_coupe": "Coppa",
    "prod_crackers_sans_sel": "Cracker senza sale",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Gancio",
    "prod_curry_rouge": "Curry rosso",
    "prod_curry_vert": "Curry verde",
    "prod_cutter": "Cutter",
    "prod_digestif": "Digestivo",
    "prod_douille": "Douille",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Indivia",
    "prod_enduit": "Stucco",
    "prod_engrais": "Concime",
    "prod_enveloppes": "Buste",
    "prod_escalope": "Scaloppina",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Carta di riso",
    "prod_fil_dentaire": "Filo interdentale",
    "prod_filet": "Filetto",
    "prod_fleurs": "Fiori",
    "prod_fondue_savoyarde": "Fonduta savoiarda",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Formaggio di fattoria",
    "prod_fruits_bio": "Frutta bio",
    "prod_fruits_de_mer": "Frutti di mare",
    "prod_galettes_de_riz": "Gallette di riso",
    "prod_gel_douche": "Bagnoschiuma",
    "prod_gibier": "Selvaggina",
    "prod_gommage": "Scrub",
    "prod_graines": "Semi",
    "prod_graines_de_chia": "Semi di chia",
    "prod_graines_de_lin": "Semi di lino",
    "prod_grattage": "Gratta e vinci",
    "prod_haricots": "Fagioli",
    "prod_herbes": "Erbe",
    "prod_homard": "Astice",
    "prod_huile_dolive_bio": "Olio d'oliva bio",
    "prod_infusion": "Tisana",
    "prod_interrupteur": "Interruttore",
    "prod_jambon_cru": "Prosciutto crudo",
    "prod_javel": "Candeggina",
    "prod_joint": "Guarnizione",
    "prod_joint_carrelage": "Stucco per piastrelle",
    "prod_joint_torique": "O-ring",
    "prod_journal": "Giornale",
    "prod_jus": "Succo",
    "prod_jus_de_fruit_naturel": "Succo di frutta naturale",
    "prod_jus_de_raisin": "Succo d'uva",
    "prod_jus_dorange": "Succo d'arancia",
    "prod_laine_de_verre": "Lana di vetro",
    "prod_lait_bio": "Latte bio",
    "prod_lait_de_coco": "Latte di cocco",
    "prod_lait_en_poudre": "Latte in polvere",
    "prod_lambris": "Perlinato",
    "prod_lame_de_scie": "Lama per sega",
    "prod_langoustines": "Langostine",
    "prod_lapin": "Coniglio",
    "prod_lard": "Lardo",
    "prod_lasagnes": "Lasagne",
    "prod_lasure": "Laccatura",
    "prod_lentilles_corail": "Lenticchie rosse",
    "prod_lime": "Lima",
    "prod_limette": "Lime",
    "prod_lingettes": "Salviette",
    "prod_liquide_vaisselle": "Detersivo piatti",
    "prod_loto": "Lotteria",
    "prod_madeleines": "Madeleines",
    "prod_magazine": "Rivista",
    "prod_marteau": "Martello",
    "prod_masque": "Maschera",
    "prod_masse": "Mazza",
    "prod_mastic": "Stucco",
    "prod_menthe": "Menta",
    "prod_miel_bio": "Miele bio",
    "prod_miel_du_producteur": "Miele del produttore",
    "prod_mouchoirs": "Fazzoletti",
    "prod_muesli_barres": "Barrette di muesli",
    "prod_muesli_bio": "Muesli bio",
    "prod_nectar": "Nettare",
    "prod_nems": "Involtini primavera",
    "prod_nettoyant_sol": "Detergente pavimenti",
    "prod_niveau": "Livella a bolla",
    "prod_noix_de_cajou": "Anacardi",
    "prod_nouilles": "Noodles",
    "prod_pain_bio": "Pane bio",
    "prod_pain_de_viande": "Polpettone",
    "prod_palets_bretons": "Biscotti bretoni",
    "prod_panneau_osb": "Pannello OSB",
    "prod_papier_de_verre": "Carta vetrata",
    "prod_parfum": "Profumo",
    "prod_parquet": "Parquet",
    "prod_pastilles": "Pastiglie",
    "prod_pate": "Paté",
    "prod_pate_carbonara": "Pasta carbonara",
    "prod_pates_carbonara": "Pasta carbonara",
    "prod_paumelle": "Cerniera",
    "prod_peinture": "Vernice",
    "prod_perceuse": "Trapano",
    "prod_petit_dej": "Colazione",
    "prod_petit_dejeuner": "Colazione",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Pila",
    "prod_pince": "Pinza",
    "prod_pinceau": "Pennello",
    "prod_pizza_maison": "Pizza fatta in casa",
    "prod_planche": "Asse",
    "prod_plantes": "Piante",
    "prod_plantes_aromatiques": "Erbe aromatiche",
    "prod_poisson": "Pesce",
    "prod_poisson_frais": "Pesce fresco",
    "prod_porc": "Maiale",
    "prod_pot": "Vaso",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Minestra",
    "prod_poudre": "Polvere",
    "prod_poulet_fermier": "Pollo ruspante",
    "prod_pousse_de_bambou": "Germogli di bambù",
    "prod_pousses_de_soja": "Germogli di soia",
    "prod_presse": "Pressa",
    "prod_prise": "Presa",
    "prod_produit_vitres": "Detergente vetri",
    "prod_produits_laitiers": "Latticini",
    "prod_pruneaux": "Prugne secche",
    "prod_pull": "Maglione",
    "prod_punaises": "Puntine da disegno",
    "prod_puree_d": "Purea",
    "prod_quinoa_bio": "Quinoa bio",
    "prod_raccord": "Raccordo",
    "prod_radiateur": "Radiatore",
    "prod_raviolis_chinois": "Ravioli cinesi",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Ricarica accendino",
    "prod_rhum": "Rum",
    "prod_rideau": "Tenda",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Riso basmati",
    "prod_riz_complet": "Riso integrale",
    "prod_riz_glutineux": "Riso glutinoso",
    "prod_robineterie": "Rubinetteria",
    "prod_rouleau": "Rullo",
    "prod_ruban_isolant": "Nastro isolante",
    "prod_sac_poubelle": "Sacchi spazzatura",
    "prod_salade_composee": "Insalata mista",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Salsa",
    "prod_sauce_fish": "Salsa di pesce",
    "prod_sauce_oyster": "Salsa di ostriche",
    "prod_saucisson_sec": "Salame",
    "prod_scie": "Sega",
    "prod_seitan_bio": "Seitan bio",
    "prod_semoule": "Semola",
    "prod_serrure": "Serratura",
    "prod_sirop": "Sciroppo",
    "prod_soda_light": "Bibita light",
    "prod_soda_sans_alcool": "Bibita analcolica",
    "prod_sorbet": "Sorbetto",
    "prod_soupe": "Zuppa",
    "prod_soupe_miso": "Zuppa miso",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Zuppa",
    "prod_steak_de_soja": "Bistecca di soia",
    "prod_tabac": "Tabacco",
    "prod_tablette": "Compressa",
    "prod_tampons": "Tamponi",
    "prod_tasseau": "Listello",
    "prod_terreau": "Terriccio",
    "prod_terrine": "Terrina",
    "prod_timbre": "Francobollo",
    "prod_tisane": "Tisana",
    "prod_tofu_bio": "Tofu bio",
    "prod_tofu_soyeux": "Tofu setoso",
    "prod_tournevis": "Cacciavite",
    "prod_tringle": "Asta per tenda",
    "prod_tuyau": "Tubo",
    "prod_vache_qui_rit": "La Vache qui Rit",
    "prod_veau": "Vitello",
    "prod_vermicelles": "Vermicelli",
    "prod_vermicelles_de_riz": "Vermicelli di riso",
    "prod_vernis": "Vernice",
    "prod_verrue": "Trattamento verruche",
    "prod_viande": "Carne",
    "prod_viande_hachee_2": "Carne macinata",
    "prod_viandes_poissons": "Carne e pesce",
    "prod_viennoiseries": "Viennoiserie",
    "prod_vinaigre_de_riz": "Aceto di riso",
    "prod_vinaigrette": "Vinaigrette",
    "prod_vis": "Viti",
    "prod_visseuse": "Avvitatore",
    "prod_volaille": "Pollame",
    "prod_zeste": "Scorza",
}

PT = {
    "prod_adoucissant": "Amaciador",
    "prod_agneau": "Cordeiro",
    "prod_agrafeuse": "Agrafeadora",
    "prod_agraves": "Agaves",
    "prod_algues_nori": "Alga nori",
    "prod_algues_wakame": "Alga wakame",
    "prod_allumettes": "Fósforos",
    "prod_ampoule": "Lâmpada",
    "prod_anchois": "Anchovas",
    "prod_andouille": "Andouille",
    "prod_aneth": "Endro",
    "prod_anneaux": "Anéis",
    "prod_apero_dinatoire": "Petiscos de jantar",
    "prod_baies_de_goji": "Bagas de goji",
    "prod_bain_de_bouche": "Elixir bucal",
    "prod_bambou": "Bambu",
    "prod_batterie": "Pilha",
    "prod_biberon": "Biberão",
    "prod_biscottes": "Tostas",
    "prod_biscuits_bio": "Bolachas biológicas",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Bloc de foie gras",
    "prod_boissons": "Bebidas",
    "prod_boudin_noir": "Morcela",
    "prod_boulangerie": "Padaria",
    "prod_boulettes": "Almôndegas",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Parafusos",
    "prod_briquet": "Isqueiro",
    "prod_brochettes": "Espetadas",
    "prod_bulots": "Búzios",
    "prod_burin": "Formão",
    "prod_canard": "Pato",
    "prod_capres": "Alcaparras",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Caderno",
    "prod_carrelage": "Azulejos",
    "prod_carte_recharge": "Cartão de recarga",
    "prod_cartes_postales": "Postais",
    "prod_cartouche_filtre": "Cartucho de filtro",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Cogumelos",
    "prod_champignons_noirs": "Cogumelos orelha-de-madeira",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Chantili",
    "prod_charcuterie_artisanale": "Enchidos artesanais",
    "prod_chauffage": "Aquecimento",
    "prod_chevilles": "Buchas",
    "prod_chewing_gum": "Pastilha elástica",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Chocolate de leite",
    "prod_chocolat_bio": "Chocolate biológico",
    "prod_chocolat_blanc": "Chocolate branco",
    "prod_chocolat_noir": "Chocolate negro",
    "prod_chou_chinois": "Couve chinesa",
    "prod_choucroute": "Chucrute",
    "prod_cidre": "Sidra",
    "prod_cigares": "Charutos",
    "prod_cigarettes": "Cigarros",
    "prod_citron": "Limão",
    "prod_citronnelle": "Capim-limão",
    "prod_clous": "Pregos",
    "prod_colle": "Cola",
    "prod_colle_carrelage": "Cola para azulejos",
    "prod_collier": "Colar",
    "prod_compote_bio": "Compota biológica",
    "prod_confiture_bio": "Doce biológico",
    "prod_confiture_dabricot": "Doce de alperce",
    "prod_confiture_de_fraises": "Doce de morango",
    "prod_confiture_maison": "Doce caseiro",
    "prod_coquillages": "Marisco",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Discos de algodão",
    "prod_couches": "Fraldas",
    "prod_coulis": "Coulis",
    "prod_coupe": "Taça",
    "prod_crackers_sans_sel": "Crackers sem sal",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Gancho",
    "prod_curry_rouge": "Caril vermelho",
    "prod_curry_vert": "Caril verde",
    "prod_cutter": "X-ato",
    "prod_digestif": "Digestivo",
    "prod_douille": "Soquete",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Endívia",
    "prod_enduit": "Massa de reboco",
    "prod_engrais": "Adubo",
    "prod_enveloppes": "Envelopes",
    "prod_escalope": "Escalope",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Papel de arroz",
    "prod_fil_dentaire": "Fio dental",
    "prod_filet": "Filete",
    "prod_fleurs": "Flores",
    "prod_fondue_savoyarde": "Fondue savoyarde",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Queijo de quinta",
    "prod_fruits_bio": "Fruta biológica",
    "prod_fruits_de_mer": "Marisco",
    "prod_galettes_de_riz": "Bolachas de arroz",
    "prod_gel_douche": "Gel de duche",
    "prod_gibier": "Caça",
    "prod_gommage": "Esfoliante",
    "prod_graines": "Sementes",
    "prod_graines_de_chia": "Sementes de chia",
    "prod_graines_de_lin": "Sementes de linhaça",
    "prod_grattage": "Raspadinha",
    "prod_haricots": "Feijão",
    "prod_herbes": "Ervas",
    "prod_homard": "Lagosta",
    "prod_huile_dolive_bio": "Azeite biológico",
    "prod_infusion": "Infusão",
    "prod_interrupteur": "Interruptor",
    "prod_jambon_cru": "Presunto",
    "prod_javel": "Lixívia",
    "prod_joint": "Vedante",
    "prod_joint_carrelage": "Rejunte",
    "prod_joint_torique": "O-ring",
    "prod_journal": "Jornal",
    "prod_jus": "Sumo",
    "prod_jus_de_fruit_naturel": "Sumo de fruta natural",
    "prod_jus_de_raisin": "Sumo de uva",
    "prod_jus_dorange": "Sumo de laranja",
    "prod_laine_de_verre": "Lã de vidro",
    "prod_lait_bio": "Leite biológico",
    "prod_lait_de_coco": "Leite de coco",
    "prod_lait_en_poudre": "Leite em pó",
    "prod_lambris": "Frisos",
    "prod_lame_de_scie": "Lâmina de serra",
    "prod_langoustines": "Lagostins",
    "prod_lapin": "Coelho",
    "prod_lard": "Banha",
    "prod_lasagnes": "Lasanha",
    "prod_lasure": "Lazur",
    "prod_lentilles_corail": "Lentilhas vermelhas",
    "prod_lime": "Lima de metal",
    "prod_limette": "Lima",
    "prod_lingettes": "Toalhitas",
    "prod_liquide_vaisselle": "Detergente da loiça",
    "prod_loto": "Lotaria",
    "prod_madeleines": "Madeleines",
    "prod_magazine": "Revista",
    "prod_marteau": "Martelo",
    "prod_masque": "Máscara",
    "prod_masse": "Marreta",
    "prod_mastic": "Massa",
    "prod_menthe": "Hortelã",
    "prod_miel_bio": "Mel biológico",
    "prod_miel_du_producteur": "Mel do produtor",
    "prod_mouchoirs": "Lenços",
    "prod_muesli_barres": "Barras de muesli",
    "prod_muesli_bio": "Muesli biológico",
    "prod_nectar": "Néctar",
    "prod_nems": "Rolinhos primavera",
    "prod_nettoyant_sol": "Limpador de chão",
    "prod_niveau": "Nível de bolha",
    "prod_noix_de_cajou": "Cajus",
    "prod_nouilles": "Massa",
    "prod_pain_bio": "Pão biológico",
    "prod_pain_de_viande": "Bolo de carne",
    "prod_palets_bretons": "Bolachas bretonas",
    "prod_panneau_osb": "Painel OSB",
    "prod_papier_de_verre": "Lixa",
    "prod_parfum": "Perfume",
    "prod_parquet": "Parquet",
    "prod_pastilles": "Pastilhas",
    "prod_pate": "Paté",
    "prod_pate_carbonara": "Massa carbonara",
    "prod_pates_carbonara": "Massa carbonara",
    "prod_paumelle": "Dobradiça",
    "prod_peinture": "Tinta",
    "prod_perceuse": "Berbequim",
    "prod_petit_dej": "Pequeno-almoço",
    "prod_petit_dejeuner": "Pequeno-almoço",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Pilha",
    "prod_pince": "Alicates",
    "prod_pinceau": "Pincel",
    "prod_pizza_maison": "Pizza caseira",
    "prod_planche": "Tábua",
    "prod_plantes": "Plantas",
    "prod_plantes_aromatiques": "Ervas aromáticas",
    "prod_poisson": "Peixe",
    "prod_poisson_frais": "Peixe fresco",
    "prod_porc": "Porco",
    "prod_pot": "Frasco",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Sopa espessa",
    "prod_poudre": "Pó",
    "prod_poulet_fermier": "Frango de quinta",
    "prod_pousse_de_bambou": "Rebentos de bambu",
    "prod_pousses_de_soja": "Rebentos de soja",
    "prod_presse": "Prensa",
    "prod_prise": "Tomada",
    "prod_produit_vitres": "Limpa-vidros",
    "prod_produits_laitiers": "Lacticínios",
    "prod_pruneaux": "Ameixas secas",
    "prod_pull": "Camisola",
    "prod_punaises": "Tachinhas",
    "prod_puree_d": "Puré",
    "prod_quinoa_bio": "Quinoa biológica",
    "prod_raccord": "União",
    "prod_radiateur": "Radiador",
    "prod_raviolis_chinois": "Raviolis chineses",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Recarga de isqueiro",
    "prod_rhum": "Rum",
    "prod_rideau": "Cortina",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Arroz basmati",
    "prod_riz_complet": "Arroz integral",
    "prod_riz_glutineux": "Arroz glutinoso",
    "prod_robineterie": "Torneiras",
    "prod_rouleau": "Rolo",
    "prod_ruban_isolant": "Fita isoladora",
    "prod_sac_poubelle": "Sacos do lixo",
    "prod_salade_composee": "Salada mista",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Molho",
    "prod_sauce_fish": "Molho de peixe",
    "prod_sauce_oyster": "Molho de ostras",
    "prod_saucisson_sec": "Salame",
    "prod_scie": "Serra",
    "prod_seitan_bio": "Seitan biológico",
    "prod_semoule": "Sêmola",
    "prod_serrure": "Fechadura",
    "prod_sirop": "Xarope",
    "prod_soda_light": "Refrigerante light",
    "prod_soda_sans_alcool": "Refrigerante",
    "prod_sorbet": "Sorbet",
    "prod_soupe": "Sopa",
    "prod_soupe_miso": "Sopa miso",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Sopa",
    "prod_steak_de_soja": "Bife de soja",
    "prod_tabac": "Tabaco",
    "prod_tablette": "Comprimido",
    "prod_tampons": "Tampões",
    "prod_tasseau": "Ripas",
    "prod_terreau": "Terra vegetal",
    "prod_terrine": "Terrina",
    "prod_timbre": "Selo",
    "prod_tisane": "Infusão",
    "prod_tofu_bio": "Tofu biológico",
    "prod_tofu_soyeux": "Tofu sedoso",
    "prod_tournevis": "Chave de fendas",
    "prod_tringle": "Varão de cortina",
    "prod_tuyau": "Mangueira",
    "prod_vache_qui_rit": "La Vache qui Rit",
    "prod_veau": "Vitela",
    "prod_vermicelles": "Aletria",
    "prod_vermicelles_de_riz": "Massa de arroz fina",
    "prod_vernis": "Verniz",
    "prod_verrue": "Tratamento de verrugas",
    "prod_viande": "Carne",
    "prod_viande_hachee_2": "Carne picada",
    "prod_viandes_poissons": "Carne e peixe",
    "prod_viennoiseries": "Viennoiserie",
    "prod_vinaigre_de_riz": "Vinagre de arroz",
    "prod_vinaigrette": "Vinagrette",
    "prod_vis": "Parafusos",
    "prod_visseuse": "Parafusadora",
    "prod_volaille": "Aves",
    "prod_zeste": "Raspas",
}

# fmt: off
CA = {
    "prod_adoucissant": "Adoixant",
    "prod_agneau": "Anyell",
    "prod_agrafeuse": "Grampadora",
    "prod_agraves": "Atzavares",
    "prod_algues_nori": "Alga nori",
    "prod_algues_wakame": "Alga wakame",
    "prod_allumettes": "Llums d'encenedor",
    "prod_ampoule": "Bombeta",
    "prod_anchois": "Anxoves",
    "prod_andouille": "Andouille",
    "prod_aneth": "Anet",
    "prod_anneaux": "Anelles",
    "prod_apero_dinatoire": "Aperitius de sopar",
    "prod_baies_de_goji": "Baies de goji",
    "prod_bain_de_bouche": "Enjuatge bucal",
    "prod_bambou": "Bambú",
    "prod_batterie": "Pila",
    "prod_biberon": "Xumet",
    "prod_biscottes": "Torrades",
    "prod_biscuits_bio": "Galetes ecològiques",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Bloc de foie gras",
    "prod_boissons": "Begudes",
    "prod_boudin_noir": "Botifarra negra",
    "prod_boulangerie": "Forn de pa",
    "prod_boulettes": "Mandonguilles",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Cargols",
    "prod_briquet": "Encenedor",
    "prod_brochettes": "Broquetes",
    "prod_bulots": "Búdions",
    "prod_burin": "Burí",
    "prod_canard": "Ànec",
    "prod_capres": "Tàperes",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Quadern",
    "prod_carrelage": "Rajoles",
    "prod_carte_recharge": "Targeta de recàrrega",
    "prod_cartes_postales": "Postals",
    "prod_cartouche_filtre": "Cartutx de filtre",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Bolets",
    "prod_champignons_noirs": "Bolets orella de fusta",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Nata muntada",
    "prod_charcuterie_artisanale": "Embotits artesans",
    "prod_chauffage": "Calefacció",
    "prod_chevilles": "Tacos",
    "prod_chewing_gum": "Xiclet",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Xocolata amb llet",
    "prod_chocolat_bio": "Xocolata ecològica",
    "prod_chocolat_blanc": "Xocolata blanca",
    "prod_chocolat_noir": "Xocolata negra",
    "prod_chou_chinois": "Col xinès",
    "prod_choucroute": "Xucrut",
    "prod_cidre": "Sidra",
    "prod_cigares": "Puros",
    "prod_cigarettes": "Cigarrets",
    "prod_citron": "Llimona",
    "prod_citronnelle": "Herba llimona",
    "prod_clous": "Claus",
    "prod_colle": "Cola",
    "prod_colle_carrelage": "Adhesiu per rajoles",
    "prod_collier": "Collaret",
    "prod_compote_bio": "Compota ecològica",
    "prod_confiture_bio": "Melmelada ecològica",
    "prod_confiture_dabricot": "Melmelada d'albercoc",
    "prod_confiture_de_fraises": "Melmelada de maduixa",
    "prod_confiture_maison": "Melmelada casolana",
    "prod_coquillages": "Marisc",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Discs de cotó",
    "prod_couches": "Bolquers",
    "prod_coulis": "Coulis",
    "prod_coupe": "Copa",
    "prod_crackers_sans_sel": "Crackers sense sal",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Ganxo",
    "prod_curry_rouge": "Curry vermell",
    "prod_curry_vert": "Curry verd",
    "prod_cutter": "Cutxillo",
    "prod_digestif": "Digestiu",
    "prod_douille": "Douille",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Endívies",
    "prod_enduit": "Massilla",
    "prod_engrais": "Adob",
    "prod_enveloppes": "Sobres",
    "prod_escalope": "Escalopa",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Paper d'arròs",
    "prod_fil_dentaire": "Fil dental",
    "prod_filet": "Filet",
    "prod_fleurs": "Flors",
    "prod_fondue_savoyarde": "Fondue savoyarde",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Formatge de masia",
    "prod_fruits_bio": "Fruita ecològica",
    "prod_fruits_de_mer": "Marisc",
    "prod_galettes_de_riz": "Galetes d'arròs",
    "prod_gel_douche": "Gel de dutxa",
    "prod_gibier": "Caça",
    "prod_gommage": "Exfoliant",
    "prod_graines": "Llavors",
    "prod_graines_de_chia": "Llavors de chía",
    "prod_graines_de_lin": "Llavors de lli",
    "prod_grattage": "Raspall",
    "prod_haricots": "Mongetes",
    "prod_herbes": "Herbes",
    "prod_homard": "Llamàntol",
    "prod_huile_dolive_bio": "Oli d'oliva ecològic",
    "prod_infusion": "Infusió",
    "prod_interrupteur": "Interruptor",
    "prod_jambon_cru": "Pernil",
    "prod_javel": "Lleixiu",
    "prod_joint": "Junta",
    "prod_joint_carrelage": "Rejunt",
    "prod_joint_torique": "Junta tòrica",
    "prod_journal": "Diari",
    "prod_jus": "Suc",
    "prod_jus_de_fruit_naturel": "Suc de fruita natural",
    "prod_jus_de_raisin": "Suc de raïm",
    "prod_jus_dorange": "Suc de taronja",
    "prod_laine_de_verre": "Llana de vidre",
    "prod_lait_bio": "Llet ecològica",
    "prod_lait_de_coco": "Llet de coco",
    "prod_lait_en_poudre": "Llet en pols",
    "prod_lambris": "Revestiment",
    "prod_lame_de_scie": "Fulla de serra",
    "prod_langoustines": "Llangostins",
    "prod_lapin": "Conill",
    "prod_lard": "Greix de porc",
    "prod_lasagnes": "Lasanya",
    "prod_lasure": "Lasure",
    "prod_lentilles_corail": "Llenties vermelles",
    "prod_lime": "Lima de metall",
    "prod_limette": "Llimona dolça",
    "prod_lingettes": "Tovalloletes",
    "prod_liquide_vaisselle": "Rentaplats",
    "prod_loto": "Loteria",
    "prod_madeleines": "Magdalenes",
    "prod_magazine": "Revista",
    "prod_marteau": "Martell",
    "prod_masque": "Mascareta",
    "prod_masse": "Maça",
    "prod_mastic": "Massilla",
    "prod_menthe": "Menta",
    "prod_miel_bio": "Mel ecològica",
    "prod_miel_du_producteur": "Mel del productor",
    "prod_mouchoirs": "Mocadors",
    "prod_muesli_barres": "Barres de muesli",
    "prod_muesli_bio": "Muesli ecològic",
    "prod_nectar": "Nèctar",
    "prod_nems": "Rotllets de primavera",
    "prod_nettoyant_sol": "Netejador de sòls",
    "prod_niveau": "Nivell de bombolla",
    "prod_noix_de_cajou": "Anacards",
    "prod_nouilles": "Fideus",
    "prod_pain_bio": "Pa ecològic",
    "prod_pain_de_viande": "Pastís de carn",
    "prod_palets_bretons": "Galetes bretones",
    "prod_panneau_osb": "Panell OSB",
    "prod_papier_de_verre": "Paper de vidre",
    "prod_parfum": "Perfum",
    "prod_parquet": "Parquet",
    "prod_pastilles": "Pastilles",
    "prod_pate": "Paté",
    "prod_pate_carbonara": "Pasta carbonara",
    "prod_pates_carbonara": "Pasta carbonara",
    "prod_paumelle": "Frontissa",
    "prod_peinture": "Pintura",
    "prod_perceuse": "Trepant",
    "prod_petit_dej": "Esmorzar",
    "prod_petit_dejeuner": "Esmorzar",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Pila",
    "prod_pince": "Alicates",
    "prod_pinceau": "Pinzell",
    "prod_pizza_maison": "Pizza casolana",
    "prod_planche": "Taula",
    "prod_plantes": "Plantes",
    "prod_plantes_aromatiques": "Herbes aromàtiques",
    "prod_poisson": "Peix",
    "prod_poisson_frais": "Peix fresc",
    "prod_porc": "Porc",
    "prod_pot": "Pot",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Potatge",
    "prod_poudre": "Pols",
    "prod_poulet_fermier": "Pollastre de pagès",
    "prod_pousse_de_bambou": "Brots de bambú",
    "prod_pousses_de_soja": "Brots de soja",
    "prod_presse": "Prensa",
    "prod_prise": "Endoll",
    "prod_produit_vitres": "Netejador de vidres",
    "prod_produits_laitiers": "Làctics",
    "prod_pruneaux": "Prunes seques",
    "prod_pull": "Jersei",
    "prod_punaises": "Xinxetes",
    "prod_puree_d": "Puré",
    "prod_quinoa_bio": "Quinoa ecològica",
    "prod_raccord": "Racor",
    "prod_radiateur": "Radiador",
    "prod_raviolis_chinois": "Raviolis xinesos",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Recàrrega d'encenedor",
    "prod_rhum": "Rom",
    "prod_rideau": "Cortina",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Arròs basmati",
    "prod_riz_complet": "Arròs integral",
    "prod_riz_glutineux": "Arròs glutinós",
    "prod_robineterie": "Aixetes",
    "prod_rouleau": "Rode",
    "prod_ruban_isolant": "Cinta aïllant",
    "prod_sac_poubelle": "Bosses d'escombraries",
    "prod_salade_composee": "Amanida mixta",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Salsa",
    "prod_sauce_fish": "Salsa de peix",
    "prod_sauce_oyster": "Salsa d'ostres",
    "prod_saucisson_sec": "Salsitxa seca",
    "prod_scie": "Serra",
    "prod_seitan_bio": "Seitan ecològic",
    "prod_semoule": "Sèmola",
    "prod_serrure": "Pany",
    "prod_sirop": "Xarop",
    "prod_soda_light": "Refresc light",
    "prod_soda_sans_alcool": "Refresc",
    "prod_sorbet": "Sorbet",
    "prod_soupe": "Sopa",
    "prod_soupe_miso": "Sopa miso",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Sopa",
    "prod_steak_de_soja": "Bistec de soja",
    "prod_tabac": "Tabac",
    "prod_tablette": "Comprimit",
    "prod_tampons": "Tampó",
    "prod_tasseau": "Listó",
    "prod_terreau": "Substrat",
    "prod_terrine": "Terrina",
    "prod_timbre": "Segell",
    "prod_tisane": "Infusió",
    "prod_tofu_bio": "Tofu ecològic",
    "prod_tofu_soyeux": "Tofu sedós",
    "prod_tournevis": "Tornavís",
    "prod_tringle": "Barra de cortina",
    "prod_tuyau": "Mànega",
    "prod_vache_qui_rit": "La Vaca que Ri",
    "prod_veau": "Vedella",
    "prod_vermicelles": "Fideus fins",
    "prod_vermicelles_de_riz": "Fideus d'arròs",
    "prod_vernis": "Barnís",
    "prod_verrue": "Tractament de verrues",
    "prod_viande": "Carn",
    "prod_viande_hachee_2": "Carn picada",
    "prod_viandes_poissons": "Carn i peix",
    "prod_viennoiseries": "Brioixeria",
    "prod_vinaigre_de_riz": "Vinagre d'arròs",
    "prod_vinaigrette": "Vinagreta",
    "prod_vis": "Cargols",
    "prod_visseuse": "Atornillador",
    "prod_volaille": "Aus de corral",
    "prod_zeste": "Raspalladura",
}

GL = {
    "prod_adoucissant": "Suavizante",
    "prod_agneau": "Cordeiro",
    "prod_agrafeuse": "Grapadora",
    "prod_agraves": "Agaves",
    "prod_algues_nori": "Alga nori",
    "prod_algues_wakame": "Alga wakame",
    "prod_allumettes": "Fósforos",
    "prod_ampoule": "Bombilla",
    "prod_anchois": "Anchoas",
    "prod_andouille": "Andouille",
    "prod_aneth": "Aneto",
    "prod_anneaux": "Aros",
    "prod_apero_dinatoire": "Aperitivos de cea",
    "prod_baies_de_goji": "Bagas de goji",
    "prod_bain_de_bouche": "Enxaguatório bucal",
    "prod_bambou": "Bambú",
    "prod_batterie": "Pila",
    "prod_biberon": "Biberón",
    "prod_biscottes": "Tostadas",
    "prod_biscuits_bio": "Galletas ecolóxicas",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Bloc de foie gras",
    "prod_boissons": "Bebidas",
    "prod_boudin_noir": "Morcilla",
    "prod_boulangerie": "Panadería",
    "prod_boulettes": "Albóndegas",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Parafusos",
    "prod_briquet": "Mechero",
    "prod_brochettes": "Brochetes",
    "prod_bulots": "Búzios",
    "prod_burin": "Formón",
    "prod_canard": "Pato",
    "prod_capres": "Alcaparras",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Caderno",
    "prod_carrelage": "Azulexos",
    "prod_carte_recharge": "Tarxeta de recarga",
    "prod_cartes_postales": "Postais",
    "prod_cartouche_filtre": "Cartucho de filtro",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Cogumelos",
    "prod_champignons_noirs": "Cogumelos orella de madeira",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Nata montada",
    "prod_charcuterie_artisanale": "Embutidos artesanais",
    "prod_chauffage": "Calefacción",
    "prod_chevilles": "Tarugos",
    "prod_chewing_gum": "Chicle",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Chocolate con leite",
    "prod_chocolat_bio": "Chocolate ecolóxico",
    "prod_chocolat_blanc": "Chocolate branco",
    "prod_chocolat_noir": "Chocolate negro",
    "prod_chou_chinois": "Repollo chinés",
    "prod_choucroute": "Chucrut",
    "prod_cidre": "Sidra",
    "prod_cigares": "Puros",
    "prod_cigarettes": "Cigarros",
    "prod_citron": "Limón",
    "prod_citronnelle": "Herba limón",
    "prod_clous": "Pregos",
    "prod_colle": "Cola",
    "prod_colle_carrelage": "Adhesivo para azulexos",
    "prod_collier": "Collar",
    "prod_compote_bio": "Compota ecolóxica",
    "prod_confiture_bio": "Marmelada ecolóxica",
    "prod_confiture_dabricot": "Marmelada de albaricoque",
    "prod_confiture_de_fraises": "Marmelada de amorodo",
    "prod_confiture_maison": "Marmelada casoeira",
    "prod_coquillages": "Marisco",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Discos de algodón",
    "prod_couches": "Cueiros",
    "prod_coulis": "Coulis",
    "prod_coupe": "Copa",
    "prod_crackers_sans_sel": "Galletas salgadas sen sal",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Gancho",
    "prod_curry_rouge": "Curry vermello",
    "prod_curry_vert": "Curry verde",
    "prod_cutter": "Cuter",
    "prod_digestif": "Digestivo",
    "prod_douille": "Soquete",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Endibias",
    "prod_enduit": "Masilla",
    "prod_engrais": "Abono",
    "prod_enveloppes": "Sobres",
    "prod_escalope": "Escalope",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Papel de arroz",
    "prod_fil_dentaire": "Fío dental",
    "prod_filet": "Filete",
    "prod_fleurs": "Flores",
    "prod_fondue_savoyarde": "Fondue savoyarde",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Queixo de granxa",
    "prod_fruits_bio": "Fruta ecolóxica",
    "prod_fruits_de_mer": "Marisco",
    "prod_galettes_de_riz": "Galetes de arroz",
    "prod_gel_douche": "Xel de ducha",
    "prod_gibier": "Carne de caza",
    "prod_gommage": "Exfoliante",
    "prod_graines": "Sementes",
    "prod_graines_de_chia": "Sementes de chía",
    "prod_graines_de_lin": "Sementes de liño",
    "prod_grattage": "Raspadita",
    "prod_haricots": "Feixóns",
    "prod_herbes": "Herbas",
    "prod_homard": "Lagosta",
    "prod_huile_dolive_bio": "Aceite de oliva ecolóxico",
    "prod_infusion": "Infusión",
    "prod_interrupteur": "Interruptor",
    "prod_jambon_cru": "Xamón curado",
    "prod_javel": "Lejía",
    "prod_joint": "Xunta",
    "prod_joint_carrelage": "Lechada",
    "prod_joint_torique": "Xunta tórica",
    "prod_journal": "Periódico",
    "prod_jus": "Zume",
    "prod_jus_de_fruit_naturel": "Zume de froita natural",
    "prod_jus_de_raisin": "Zume de uva",
    "prod_jus_dorange": "Zume de laranxa",
    "prod_laine_de_verre": "Lana de vidro",
    "prod_lait_bio": "Leite ecolóxico",
    "prod_lait_de_coco": "Leite de coco",
    "prod_lait_en_poudre": "Leite en po",
    "prod_lambris": "Revestimento",
    "prod_lame_de_scie": "Folla de serra",
    "prod_langoustines": "Lagostins",
    "prod_lapin": "Coello",
    "prod_lard": "Graxa de touciño",
    "prod_lasagnes": "Lasaña",
    "prod_lasure": "Lasur",
    "prod_lentilles_corail": "Lentellas vermellas",
    "prod_lime": "Lima de metal",
    "prod_limette": "Lima",
    "prod_lingettes": "Toalliñas",
    "prod_liquide_vaisselle": "Lavavaixillas",
    "prod_loto": "Lotaría",
    "prod_madeleines": "Magdalenas",
    "prod_magazine": "Revista",
    "prod_marteau": "Martelo",
    "prod_masque": "Mascarilla",
    "prod_masse": "Maza",
    "prod_mastic": "Masilla",
    "prod_menthe": "Menta",
    "prod_miel_bio": "Mel ecolóxico",
    "prod_miel_du_producteur": "Mel do produtor",
    "prod_mouchoirs": "Pañuelos",
    "prod_muesli_barres": "Barritas de muesli",
    "prod_muesli_bio": "Muesli ecolóxico",
    "prod_nectar": "Néctar",
    "prod_nems": "Rollos de primavera",
    "prod_nettoyant_sol": "Limpiador de chan",
    "prod_niveau": "Nivel de burbulla",
    "prod_noix_de_cajou": "Anacardos",
    "prod_nouilles": "Fideos",
    "prod_pain_bio": "Pan ecolóxico",
    "prod_pain_de_viande": "Pastel de carne",
    "prod_palets_bretons": "Galletas bretonas",
    "prod_panneau_osb": "Panel OSB",
    "prod_papier_de_verre": "Papel de lixa",
    "prod_parfum": "Perfume",
    "prod_parquet": "Parquet",
    "prod_pastilles": "Pastillas",
    "prod_pate": "Paté",
    "prod_pate_carbonara": "Pasta carbonara",
    "prod_pates_carbonara": "Pasta carbonara",
    "prod_paumelle": "Bisagra",
    "prod_peinture": "Pintura",
    "prod_perceuse": "Taladro",
    "prod_petit_dej": "Almorzo",
    "prod_petit_dejeuner": "Almorzo",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Pila",
    "prod_pince": "Alicates",
    "prod_pinceau": "Pincel",
    "prod_pizza_maison": "Pizza casoeira",
    "prod_planche": "Taboa",
    "prod_plantes": "Plantas",
    "prod_plantes_aromatiques": "Herbas aromáticas",
    "prod_poisson": "Peixe",
    "prod_poisson_frais": "Peixe fresco",
    "prod_porc": "Porco",
    "prod_pot": "Tarro",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Potaxe",
    "prod_poudre": "Polvo",
    "prod_poulet_fermier": "Galiña de granxa",
    "prod_pousse_de_bambou": "Brotes de bambú",
    "prod_pousses_de_soja": "Brotes de soja",
    "prod_presse": "Prensa",
    "prod_prise": "Enchufe",
    "prod_produit_vitres": "Limpiacristais",
    "prod_produits_laitiers": "Lácteos",
    "prod_pruneaux": "Ameixas secas",
    "prod_pull": "Jersei",
    "prod_punaises": "Chincheta",
    "prod_puree_d": "Puré",
    "prod_quinoa_bio": "Quinoa ecolóxica",
    "prod_raccord": "Racor",
    "prod_radiateur": "Radiador",
    "prod_raviolis_chinois": "Raviolis chineses",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Recarga de mechero",
    "prod_rhum": "Ron",
    "prod_rideau": "Cortina",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Arroz basmati",
    "prod_riz_complet": "Arroz integral",
    "prod_riz_glutineux": "Arroz glutinoso",
    "prod_robineterie": "Grifería",
    "prod_rouleau": "Rodillo",
    "prod_ruban_isolant": "Cinta aislante",
    "prod_sac_poubelle": "Bolsas de lixo",
    "prod_salade_composee": "Ensalada mixta",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Salsa",
    "prod_sauce_fish": "Salsa de peixe",
    "prod_sauce_oyster": "Salsa de ostras",
    "prod_saucisson_sec": "Salchichón",
    "prod_scie": "Serra",
    "prod_seitan_bio": "Seitán ecolóxico",
    "prod_semoule": "Sémola",
    "prod_serrure": "Cerradura",
    "prod_sirop": "Xarope",
    "prod_soda_light": "Refresco light",
    "prod_soda_sans_alcool": "Refresco",
    "prod_sorbet": "Sorbete",
    "prod_soupe": "Sopa",
    "prod_soupe_miso": "Sopa miso",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Sopa",
    "prod_steak_de_soja": "Filete de soja",
    "prod_tabac": "Tabaco",
    "prod_tablette": "Comprimido",
    "prod_tampons": "Tampóns",
    "prod_tasseau": "Listón",
    "prod_terreau": "Sustrato",
    "prod_terrine": "Terrina",
    "prod_timbre": "Sello",
    "prod_tisane": "Infusión",
    "prod_tofu_bio": "Tofu ecolóxico",
    "prod_tofu_soyeux": "Tofu sedoso",
    "prod_tournevis": "Destornillador",
    "prod_tringle": "Barra de cortina",
    "prod_tuyau": "Manguera",
    "prod_vache_qui_rit": "La Vaca que Rí",
    "prod_veau": "Tenreira",
    "prod_vermicelles": "Fideos finos",
    "prod_vermicelles_de_riz": "Fideos de arroz",
    "prod_vernis": "Barniz",
    "prod_verrue": "Tratamento de verrugas",
    "prod_viande": "Carne",
    "prod_viande_hachee_2": "Carne picada",
    "prod_viandes_poissons": "Carne e peixe",
    "prod_viennoiseries": "Bollería",
    "prod_vinaigre_de_riz": "Vinagre de arroz",
    "prod_vinaigrette": "Vinagreta",
    "prod_vis": "Parafusos",
    "prod_visseuse": "Atornillador",
    "prod_volaille": "Aves de corral",
    "prod_zeste": "Raspadura",
}

# fmt: off
EU = {
    "prod_adoucissant": "Leuntzailea",
    "prod_agneau": "Ardia",
    "prod_agrafeuse": "Grapagailua",
    "prod_agraves": "Agabeak",
    "prod_algues_nori": "Nori alga",
    "prod_algues_wakame": "Wakame alga",
    "prod_allumettes": "Sukaldeko ziztak",
    "prod_ampoule": "Bonbilla",
    "prod_anchois": "Antxoak",
    "prod_andouille": "Andouille",
    "prod_aneth": "Aneto",
    "prod_anneaux": "Eraztunak",
    "prod_apero_dinatoire": "Afari aperitiboak",
    "prod_baies_de_goji": "Goji baieak",
    "prod_bain_de_bouche": "Ahoa garbitzeko",
    "prod_bambou": "Banbua",
    "prod_batterie": "Pila",
    "prod_biberon": "Biberoi",
    "prod_biscottes": "Tostadak",
    "prod_biscuits_bio": "Galleta ekologikoak",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Foie gras blokea",
    "prod_boissons": "Edariak",
    "prod_boudin_noir": "Morcilla",
    "prod_boulangerie": "Ogi lantegia",
    "prod_boulettes": "Albondigak",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Torlojuak",
    "prod_briquet": "Pizgailua",
    "prod_brochettes": "Broxetak",
    "prod_bulots": "Buzioak",
    "prod_burin": "Burin",
    "prod_canard": "Ahatea",
    "prod_capres": "Alkapaarrak",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Koadernoa",
    "prod_carrelage": "Lauza",
    "prod_carte_recharge": "Kargatzeko txartela",
    "prod_cartes_postales": "Posta-txartelak",
    "prod_cartouche_filtre": "Iragazki katuxea",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Perretxikoak",
    "prod_champignons_noirs": "Egur-belarri perretxikoak",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Esne batea",
    "prod_charcuterie_artisanale": "Gose-kirol artisauak",
    "prod_chauffage": "Berogailua",
    "prod_chevilles": "Takak",
    "prod_chewing_gum": "Xikle",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Esneko txokolatea",
    "prod_chocolat_bio": "Txokolate ekologikoa",
    "prod_chocolat_blanc": "Txokolate zuria",
    "prod_chocolat_noir": "Txokolate beltza",
    "prod_chou_chinois": "Txinako aza",
    "prod_choucroute": "Chucrut",
    "prod_cidre": "Sagardo",
    "prod_cigares": "Puroak",
    "prod_cigarettes": "Zigarroak",
    "prod_citron": "Limoi",
    "prod_citronnelle": "Limon-belar",
    "prod_clous": "Hiltzak",
    "prod_colle": "Itsasgarria",
    "prod_colle_carrelage": "Lauza itsasgarria",
    "prod_collier": "Lepokoa",
    "prod_compote_bio": "Konpota ekologikoa",
    "prod_confiture_bio": "Marmelada ekologikoa",
    "prod_confiture_dabricot": "Abrikote marmelada",
    "prod_confiture_de_fraises": "Marrubi marmelada",
    "prod_confiture_maison": "Etxeko marmelada",
    "prod_coquillages": "Itsaskiak",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Kotoi diskoak",
    "prod_couches": "Napa",
    "prod_coulis": "Coulis",
    "prod_coupe": "Kopa",
    "prod_crackers_sans_sel": "Gatz gabeko cracker-ak",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Kako",
    "prod_curry_rouge": "Curry gorria",
    "prod_curry_vert": "Curry berdea",
    "prod_cutter": "Cuter",
    "prod_digestif": "Digestiboa",
    "prod_douille": "Douille",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Endibia",
    "prod_enduit": "Masilla",
    "prod_engrais": "Ongarria",
    "prod_enveloppes": "Gutun-azalak",
    "prod_escalope": "Eskalope",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Arroz-papera",
    "prod_fil_dentaire": "Hortz-haria",
    "prod_filet": "Filet",
    "prod_fleurs": "Loreak",
    "prod_fondue_savoyarde": "Fondue savoyarde",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Baserriko gazta",
    "prod_fruits_bio": "Fruta ekologikoa",
    "prod_fruits_de_mer": "Itsaskiak",
    "prod_galettes_de_riz": "Arroz-galeta",
    "prod_gel_douche": "Dutxa-gel",
    "prod_gibier": "Ehiza",
    "prod_gommage": "Eskfoliatzailea",
    "prod_graines": "Haziak",
    "prod_graines_de_chia": "Chia haziak",
    "prod_graines_de_lin": "Linaza haziak",
    "prod_grattage": "Raspadina",
    "prod_haricots": "Babarrunak",
    "prod_herbes": "Belarrak",
    "prod_homard": "Itsas txangurrua",
    "prod_huile_dolive_bio": "Oliba-olio ekologikoa",
    "prod_infusion": "Infusioa",
    "prod_interrupteur": "Etengailua",
    "prod_jambon_cru": "Txerriskia",
    "prod_javel": "Lejia",
    "prod_joint": "Junta",
    "prod_joint_carrelage": "Lauza-junta",
    "prod_joint_torique": "O-ring",
    "prod_journal": "Egunkaria",
    "prod_jus": "Zumo",
    "prod_jus_de_fruit_naturel": "Fruta-zumo naturala",
    "prod_jus_de_raisin": "Mahats-zumo",
    "prod_jus_dorange": "Laranja-zumo",
    "prod_laine_de_verre": "Beirazko lana",
    "prod_lait_bio": "Esne ekologikoa",
    "prod_lait_de_coco": "Koko-esnea",
    "prod_lait_en_poudre": "Esne hautsa",
    "prod_lambris": "Revestimendua",
    "prod_lame_de_scie": "Zerra-atera",
    "prod_langoustines": "Langostinak",
    "prod_lapin": "Untxia",
    "prod_lard": "Txerri-gantza",
    "prod_lasagnes": "Lasagna",
    "prod_lasure": "Lasur",
    "prod_lentilles_corail": "Arakil gorriak",
    "prod_lime": "Lima metalezkoa",
    "prod_limette": "Lima",
    "prod_lingettes": "Toallak",
    "prod_liquide_vaisselle": "Ontzi-garbigailua",
    "prod_loto": "Loteria",
    "prod_madeleines": "Magdalenak",
    "prod_magazine": "Aldizkaria",
    "prod_marteau": "Mailua",
    "prod_masque": "Maskara",
    "prod_masse": "Maza",
    "prod_mastic": "Masilla",
    "prod_menthe": "Menda",
    "prod_miel_bio": "Eztia ekologikoa",
    "prod_miel_du_producteur": "Ekoizlearen eztia",
    "prod_mouchoirs": "Pañueloak",
    "prod_muesli_barres": "Muesli barra",
    "prod_muesli_bio": "Muesli ekologikoa",
    "prod_nectar": "Nektar",
    "prod_nems": "Udaberri roll-ak",
    "prod_nettoyant_sol": "Lur garbigailua",
    "prod_niveau": "Maila",
    "prod_noix_de_cajou": "Anakardoak",
    "prod_nouilles": "Fideoak",
    "prod_pain_bio": "Ogi ekologikoa",
    "prod_pain_de_viande": "Haragi-pastela",
    "prod_palets_bretons": "Galleta bretonak",
    "prod_panneau_osb": "OSB panela",
    "prod_papier_de_verre": "Lixatze-papera",
    "prod_parfum": "Perfume",
    "prod_parquet": "Parquet",
    "prod_pastilles": "Pastilla",
    "prod_pate": "Paté",
    "prod_pate_carbonara": "Carbonara pasta",
    "prod_pates_carbonara": "Carbonara pasta",
    "prod_paumelle": "Bisagra",
    "prod_peinture": "Pintura",
    "prod_perceuse": "Taladroa",
    "prod_petit_dej": "Gosaria",
    "prod_petit_dejeuner": "Gosaria",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Pila",
    "prod_pince": "Alicateak",
    "prod_pinceau": "Brotxa",
    "prod_pizza_maison": "Etxeko pizza",
    "prod_planche": "Ohola",
    "prod_plantes": "Landareak",
    "prod_plantes_aromatiques": "Belar aromatikoak",
    "prod_poisson": "Arraina",
    "prod_poisson_frais": "Arrain freskoa",
    "prod_porc": "Txerria",
    "prod_pot": "Potea",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Zopa",
    "prod_poudre": "Hautsa",
    "prod_poulet_fermier": "Baso-oilarra",
    "prod_pousse_de_bambou": "Banbu-brotesak",
    "prod_pousses_de_soja": "Soja-brotesak",
    "prod_presse": "Prensa",
    "prod_prise": "Entxufea",
    "prod_produit_vitres": "Beiraren garbigailua",
    "prod_produits_laitiers": "Esnekiak",
    "prod_pruneaux": "Aran pasa",
    "prod_pull": "Jertsea",
    "prod_punaises": "Chincheta",
    "prod_puree_d": "Puré",
    "prod_quinoa_bio": "Quinoa ekologikoa",
    "prod_raccord": "Konexioa",
    "prod_radiateur": "Erradiadorea",
    "prod_raviolis_chinois": "Ravioli txinatarrak",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Pizgailu kargatzea",
    "prod_rhum": "Rum",
    "prod_rideau": "Gortina",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Arroz basmati",
    "prod_riz_complet": "Arroz integral",
    "prod_riz_glutineux": "Arroz glutinoso",
    "prod_robineterie": "Grifak",
    "prod_rouleau": "Rodillo",
    "prod_ruban_isolant": "Zinta isolatzailea",
    "prod_sac_poubelle": "Zabor-poltsak",
    "prod_salade_composee": "Entsalada mistoa",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Salsa",
    "prod_sauce_fish": "Arrain-salsa",
    "prod_sauce_oyster": "Ostra-salsa",
    "prod_saucisson_sec": "Salchichón",
    "prod_scie": "Zerra",
    "prod_seitan_bio": "Seitan ekologikoa",
    "prod_semoule": "Semola",
    "prod_serrure": "Sarraila",
    "prod_sirop": "Xarope",
    "prod_soda_light": "Refresko light",
    "prod_soda_sans_alcool": "Refresko",
    "prod_sorbet": "Sorbete",
    "prod_soupe": "Zopa",
    "prod_soupe_miso": "Miso zopa",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Zopa",
    "prod_steak_de_soja": "Soja filetea",
    "prod_tabac": "Tabakoa",
    "prod_tablette": "Pilula",
    "prod_tampons": "Tampoi",
    "prod_tasseau": "Listoi",
    "prod_terreau": "Lur-substratua",
    "prod_terrine": "Terrina",
    "prod_timbre": "Selo",
    "prod_tisane": "Infusioa",
    "prod_tofu_bio": "Tofu ekologikoa",
    "prod_tofu_soyeux": "Tofu sedoso",
    "prod_tournevis": "Destornillador",
    "prod_tringle": "Gortina-barra",
    "prod_tuyau": "Manguera",
    "prod_vache_qui_rit": "La Vache qui Rit",
    "prod_veau": "Txahal",
    "prod_vermicelles": "Fideo finoak",
    "prod_vermicelles_de_riz": "Arroz-fideoak",
    "prod_vernis": "Barniz",
    "prod_verrue": "Orratz-tratamendua",
    "prod_viande": "Haragia",
    "prod_viande_hachee_2": "Haragi txikia",
    "prod_viandes_poissons": "Haragia eta arraina",
    "prod_viennoiseries": "Bollería",
    "prod_vinaigre_de_riz": "Arroz-vinagre",
    "prod_vinaigrette": "Vinagreta",
    "prod_vis": "Torlojuak",
    "prod_visseuse": "Atornillador",
    "prod_volaille": "Hegaztiak",
    "prod_zeste": "Azala",
}

RO = {
    "prod_adoucissant": "Balsam de rufe",
    "prod_agneau": "Miel",
    "prod_agrafeuse": "Capsator",
    "prod_agraves": "Agave",
    "prod_algues_nori": "Alge nori",
    "prod_algues_wakame": "Alge wakame",
    "prod_allumettes": "Chibrituri",
    "prod_ampoule": "Bec",
    "prod_anchois": "Anșoa",
    "prod_andouille": "Andouille",
    "prod_aneth": "Mărar",
    "prod_anneaux": "Inele",
    "prod_apero_dinatoire": "Aperitive de cină",
    "prod_baies_de_goji": "Fructe de goji",
    "prod_bain_de_bouche": "Apă de gură",
    "prod_bambou": "Bambus",
    "prod_batterie": "Baterie",
    "prod_biberon": "Biberon",
    "prod_biscottes": "Pesmeți",
    "prod_biscuits_bio": "Biscuiți bio",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Bloc de foie gras",
    "prod_boissons": "Băuturi",
    "prod_boudin_noir": "Cârnați negri",
    "prod_boulangerie": "Brutărie",
    "prod_boulettes": "Chiftele",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Bolțuri",
    "prod_briquet": "Brichetă",
    "prod_brochettes": "Frigărui",
    "prod_bulots": "Melci de mare",
    "prod_burin": "Dalta",
    "prod_canard": "Rață",
    "prod_capres": "Capere",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Caiet",
    "prod_carrelage": "Gresie",
    "prod_carte_recharge": "Card de reîncărcare",
    "prod_cartes_postales": "Cartoline poștale",
    "prod_cartouche_filtre": "Cartuș filtru",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Ciuperci",
    "prod_champignons_noirs": "Ciuperci urechi de lemn",
    "prod_champignons_shiitake": "Shiitake",
    "prod_chantilly": "Frișcă bătută",
    "prod_charcuterie_artisanale": "Mezeluri artizanale",
    "prod_chauffage": "Încălzire",
    "prod_chevilles": "Dibluri",
    "prod_chewing_gum": "Gumă de mestecat",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Ciocolată cu lapte",
    "prod_chocolat_bio": "Ciocolată bio",
    "prod_chocolat_blanc": "Ciocolată albă",
    "prod_chocolat_noir": "Ciocolată neagră",
    "prod_chou_chinois": "Varză chinezească",
    "prod_choucroute": "Varză murată",
    "prod_cidre": "Cidru",
    "prod_cigares": "Trabucuri",
    "prod_cigarettes": "Țigări",
    "prod_citron": "Lămâie",
    "prod_citronnelle": "Lemongrass",
    "prod_clous": "Cuie",
    "prod_colle": "Adeziv",
    "prod_colle_carrelage": "Adeziv pentru gresie",
    "prod_collier": "Colier",
    "prod_compote_bio": "Compot bio",
    "prod_confiture_bio": "Gem bio",
    "prod_confiture_dabricot": "Gem de caise",
    "prod_confiture_de_fraises": "Gem de căpșuni",
    "prod_confiture_maison": "Gem de casă",
    "prod_coquillages": "Fructe de mare",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Discuri de bumbac",
    "prod_couches": "Scutece",
    "prod_coulis": "Coulis",
    "prod_coupe": "Cupă",
    "prod_crackers_sans_sel": "Crackers fără sare",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Cârlig",
    "prod_curry_rouge": "Curry roșu",
    "prod_curry_vert": "Curry verde",
    "prod_cutter": "Cuter",
    "prod_digestif": "Digestiv",
    "prod_douille": "Douille",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Endivie",
    "prod_enduit": "Chit",
    "prod_engrais": "Îngrășământ",
    "prod_enveloppes": "Plicuri",
    "prod_escalope": "Escalop",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Hârtie de orez",
    "prod_fil_dentaire": "Ață dentară",
    "prod_filet": "File",
    "prod_fleurs": "Flori",
    "prod_fondue_savoyarde": "Fondue savoyarde",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Brânză de fermă",
    "prod_fruits_bio": "Fructe bio",
    "prod_fruits_de_mer": "Fructe de mare",
    "prod_galettes_de_riz": "Turtițe de orez",
    "prod_gel_douche": "Gel de duș",
    "prod_gibier": "Vânat",
    "prod_gommage": "Scrub",
    "prod_graines": "Semințe",
    "prod_graines_de_chia": "Semințe de chia",
    "prod_graines_de_lin": "Semințe de in",
    "prod_grattage": "Răzuieli",
    "prod_haricots": "Fasole",
    "prod_herbes": "Ierburi",
    "prod_homard": "Homar",
    "prod_huile_dolive_bio": "Ulei de măsline bio",
    "prod_infusion": "Infuzie",
    "prod_interrupteur": "Întrerupător",
    "prod_jambon_cru": "Șuncă crudă",
    "prod_javel": "Înălbitor",
    "prod_joint": "Garnitură",
    "prod_joint_carrelage": "Chit rosturi",
    "prod_joint_torique": "O-ring",
    "prod_journal": "Ziar",
    "prod_jus": "Suc",
    "prod_jus_de_fruit_naturel": "Suc natural de fructe",
    "prod_jus_de_raisin": "Suc de struguri",
    "prod_jus_dorange": "Suc de portocale",
    "prod_laine_de_verre": "Vată de sticlă",
    "prod_lait_bio": "Lapte bio",
    "prod_lait_de_coco": "Lapte de cocos",
    "prod_lait_en_poudre": "Lapte praf",
    "prod_lambris": "Lambriu",
    "prod_lame_de_scie": "Lamă de ferăstrău",
    "prod_langoustines": "Langustine",
    "prod_lapin": "Iepure",
    "prod_lard": "Slănină",
    "prod_lasagnes": "Lasagna",
    "prod_lasure": "Lazură",
    "prod_lentilles_corail": "Linte roșie",
    "prod_lime": "Pilă",
    "prod_limette": "Lime",
    "prod_lingettes": "Șervețele umede",
    "prod_liquide_vaisselle": "Detergent de vase",
    "prod_loto": "Loto",
    "prod_madeleines": "Madeleines",
    "prod_magazine": "Revistă",
    "prod_marteau": "Ciocan",
    "prod_masque": "Mască",
    "prod_masse": "Baros",
    "prod_mastic": "Chit",
    "prod_menthe": "Mentă",
    "prod_miel_bio": "Miere bio",
    "prod_miel_du_producteur": "Miere de la producător",
    "prod_mouchoirs": "Șervețele",
    "prod_muesli_barres": "Batoane de muesli",
    "prod_muesli_bio": "Muesli bio",
    "prod_nectar": "Nectar",
    "prod_nems": "Rulouri de primăvară",
    "prod_nettoyant_sol": "Detergent de pardoseli",
    "prod_niveau": "Nivelă cu bulă",
    "prod_noix_de_cajou": "Caju",
    "prod_nouilles": "Tăiței",
    "prod_pain_bio": "Pâine bio",
    "prod_pain_de_viande": "Drob",
    "prod_palets_bretons": "Biscuiți bretoni",
    "prod_panneau_osb": "Placă OSB",
    "prod_papier_de_verre": "Hârtie abrazivă",
    "prod_parfum": "Parfum",
    "prod_parquet": "Parchet",
    "prod_pastilles": "Pastile",
    "prod_pate": "Paté",
    "prod_pate_carbonara": "Paste carbonara",
    "prod_pates_carbonara": "Paste carbonara",
    "prod_paumelle": "Balamale",
    "prod_peinture": "Vopsea",
    "prod_perceuse": "Bormașină",
    "prod_petit_dej": "Mic dejun",
    "prod_petit_dejeuner": "Mic dejun",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Pilă",
    "prod_pince": "Clește",
    "prod_pinceau": "Pensulă",
    "prod_pizza_maison": "Pizza de casă",
    "prod_planche": "Scândură",
    "prod_plantes": "Plante",
    "prod_plantes_aromatiques": "Ierburi aromatice",
    "prod_poisson": "Pește",
    "prod_poisson_frais": "Pește proaspăt",
    "prod_porc": "Porc",
    "prod_pot": "Borcan",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Supă cremă",
    "prod_poudre": "Pudră",
    "prod_poulet_fermier": "Pui de curte",
    "prod_pousse_de_bambou": "Lăstari de bambus",
    "prod_pousses_de_soja": "Germeni de soia",
    "prod_presse": "Presă",
    "prod_prise": "Priză",
    "prod_produit_vitres": "Detergent geamuri",
    "prod_produits_laitiers": "Lactate",
    "prod_pruneaux": "Prune uscate",
    "prod_pull": "Pulover",
    "prod_punaises": "Pioneze",
    "prod_puree_d": "Piure",
    "prod_quinoa_bio": "Quinoa bio",
    "prod_raccord": "Racord",
    "prod_radiateur": "Radiator",
    "prod_raviolis_chinois": "Ravioli chinezești",
    "prod_razor": "Razor",
    "prod_recharge_briquet": "Reîncărcare brichetă",
    "prod_rhum": "Rom",
    "prod_rideau": "Perdea",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Orez basmati",
    "prod_riz_complet": "Orez brun",
    "prod_riz_glutineux": "Orez lipicios",
    "prod_robineterie": "Robinete",
    "prod_rouleau": "Trafalet",
    "prod_ruban_isolant": "Bandă izolatoare",
    "prod_sac_poubelle": "Saci de gunoi",
    "prod_salade_composee": "Salată mixtă",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Sos",
    "prod_sauce_fish": "Sos de pește",
    "prod_sauce_oyster": "Sos de stridii",
    "prod_saucisson_sec": "Salam uscat",
    "prod_scie": "Ferăstrău",
    "prod_seitan_bio": "Seitan bio",
    "prod_semoule": "Semolină",
    "prod_serrure": "Broască",
    "prod_sirop": "Sirop",
    "prod_soda_light": "Suc light",
    "prod_soda_sans_alcool": "Suc răcoritor",
    "prod_sorbet": "Sorbet",
    "prod_soupe": "Supă",
    "prod_soupe_miso": "Supă miso",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Supă",
    "prod_steak_de_soja": "Friptură de soia",
    "prod_tabac": "Tutun",
    "prod_tablette": "Pastilă",
    "prod_tampons": "Tampoane",
    "prod_tasseau": "Chirpici",
    "prod_terreau": "Pământ de flori",
    "prod_terrine": "Terină",
    "prod_timbre": "Timbre",
    "prod_tisane": "Ceai de plante",
    "prod_tofu_bio": "Tofu bio",
    "prod_tofu_soyeux": "Tofu mătăsos",
    "prod_tournevis": "Șurubelniță",
    "prod_tringle": "Galerie perdea",
    "prod_tuyau": "Furtun",
    "prod_vache_qui_rit": "La Vache qui Rit",
    "prod_veau": "Vițel",
    "prod_vermicelles": "Vermicelli",
    "prod_vermicelles_de_riz": "Tăiței de orez",
    "prod_vernis": "Lac",
    "prod_verrue": "Tratament negi",
    "prod_viande": "Carne",
    "prod_viande_hachee_2": "Carne tocată",
    "prod_viandes_poissons": "Carne și pește",
    "prod_viennoiseries": "Viennoiserie",
    "prod_vinaigre_de_riz": "Oțet de orez",
    "prod_vinaigrette": "Vinaigrette",
    "prod_vis": "Șuruburi",
    "prod_visseuse": "Șurubelniță electrică",
    "prod_volaille": "Pui",
    "prod_zeste": "Coajă rasă",
}
# fmt: on

LOCALES = {
    "es": ES,
    "it": IT,
    "pt": PT,
    "ca": CA,
    "gl": GL,
    "eu": EU,
    "ro": RO,
}


def main() -> None:
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from prod_en_map import EN_PROD

    expected = set(EN_PROD)
    OUT.mkdir(parents=True, exist_ok=True)

    for loc, data in LOCALES.items():
        missing = expected - set(data)
        extra = set(data) - expected
        if missing or extra:
            raise SystemExit(f"{loc}: missing={sorted(missing)} extra={sorted(extra)}")
        ordered = {k: data[k] for k in sorted(data)}
        path = OUT / f"{loc}.json"
        path.write_text(
            json.dumps(ordered, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"{loc}.json: {len(ordered)} keys")


if __name__ == "__main__":
    main()

