#!/usr/bin/env python3
"""Fix remaining bad grocery l10n: bio≠biography, leftover French, mixed scripts."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "lib" / "l10n"

# Organic products — full native set (overwrite garbage + half-French).
BIO: dict[str, dict[str, str]] = {
    "ja": {
        "prod_biscuits_bio": "オーガニックビスケット",
        "prod_cafe_bio": "オーガニックコーヒー",
        "prod_chocolat_bio": "オーガニックチョコレート",
        "prod_compote_bio": "オーガニックフルーツピューレ",
        "prod_confiture_bio": "オーガニックジャム",
        "prod_fruits_bio": "オーガニックフルーツ",
        "prod_huile_dolive_bio": "オーガニックオリーブオイル",
        "prod_lait_bio": "オーガニック牛乳",
        "prod_legumes_bio": "オーガニック野菜",
        "prod_miel_bio": "オーガニックはちみつ",
        "prod_muesli_bio": "オーガニックミューズリー",
        "prod_oeufs_bio": "オーガニック卵",
        "prod_pain_bio": "オーガニックパン",
        "prod_quinoa_bio": "オーガニックキヌア",
        "prod_seitan_bio": "オーガニックセイタン",
        "prod_the_bio": "オーガニック茶",
        "prod_tofu_bio": "オーガニック豆腐",
    },
    "ko": {
        "prod_biscuits_bio": "유기농 비스킷",
        "prod_cafe_bio": "유기농 커피",
        "prod_chocolat_bio": "유기농 초콜릿",
        "prod_compote_bio": "유기농 과일 퓨레",
        "prod_confiture_bio": "유기농 잼",
        "prod_fruits_bio": "유기농 과일",
        "prod_huile_dolive_bio": "유기농 올리브유",
        "prod_lait_bio": "유기농 우유",
        "prod_legumes_bio": "유기농 야채",
        "prod_miel_bio": "유기농 꿀",
        "prod_muesli_bio": "유기농 뮤즐리",
        "prod_oeufs_bio": "유기농 계란",
        "prod_pain_bio": "유기농 빵",
        "prod_quinoa_bio": "유기농 퀴노아",
        "prod_seitan_bio": "유기농 세이탄",
        "prod_the_bio": "유기농 차",
        "prod_tofu_bio": "유기농 두부",
    },
    "zh": {
        "prod_biscuits_bio": "有机饼干",
        "prod_cafe_bio": "有机咖啡",
        "prod_chocolat_bio": "有机巧克力",
        "prod_compote_bio": "有机果泥",
        "prod_confiture_bio": "有机果酱",
        "prod_fruits_bio": "有机水果",
        "prod_huile_dolive_bio": "有机橄榄油",
        "prod_lait_bio": "有机牛奶",
        "prod_legumes_bio": "有机蔬菜",
        "prod_miel_bio": "有机蜂蜜",
        "prod_muesli_bio": "有机麦片",
        "prod_oeufs_bio": "有机鸡蛋",
        "prod_pain_bio": "有机面包",
        "prod_quinoa_bio": "有机藜麦",
        "prod_seitan_bio": "有机面筋",
        "prod_the_bio": "有机茶",
        "prod_tofu_bio": "有机豆腐",
    },
    "ar": {
        "prod_biscuits_bio": "بسكويت عضوي",
        "prod_cafe_bio": "قهوة عضوية",
        "prod_chocolat_bio": "شوكولاتة عضوية",
        "prod_compote_bio": "مهروس فواكه عضوي",
        "prod_confiture_bio": "مربى عضوي",
        "prod_fruits_bio": "فواكه عضوية",
        "prod_huile_dolive_bio": "زيت زيتون عضوي",
        "prod_lait_bio": "حليب عضوي",
        "prod_legumes_bio": "خضار عضوية",
        "prod_miel_bio": "عسل عضوي",
        "prod_muesli_bio": "موسلي عضوي",
        "prod_oeufs_bio": "بيض عضوي",
        "prod_pain_bio": "خبز عضوي",
        "prod_quinoa_bio": "كينوا عضوي",
        "prod_seitan_bio": "سيتان عضوي",
        "prod_the_bio": "شاي عضوي",
        "prod_tofu_bio": "توفو عضوي",
    },
    "he": {
        "prod_biscuits_bio": "ביסקוויטים אורגניים",
        "prod_cafe_bio": "קפה אורגני",
        "prod_chocolat_bio": "שוקולד אורגני",
        "prod_compote_bio": "מחית פירות אורגנית",
        "prod_confiture_bio": "ריבה אורגנית",
        "prod_fruits_bio": "פירות אורגניים",
        "prod_huile_dolive_bio": "שמן זית אורגני",
        "prod_lait_bio": "חלב אורגני",
        "prod_legumes_bio": "ירקות אורגניים",
        "prod_miel_bio": "דבש אורגני",
        "prod_muesli_bio": "מוזלי אורגני",
        "prod_oeufs_bio": "ביצים אורגניות",
        "prod_pain_bio": "לחם אורגני",
        "prod_quinoa_bio": "קינואה אורגנית",
        "prod_seitan_bio": "סייטן אורגני",
        "prod_the_bio": "תה אורגני",
        "prod_tofu_bio": "טופו אורגני",
    },
    "th": {
        "prod_biscuits_bio": "บิสกิตออร์แกนิก",
        "prod_cafe_bio": "กาแฟออร์แกนิก",
        "prod_chocolat_bio": "ช็อกโกแลตออร์แกนิก",
        "prod_compote_bio": "ผลไม้บดออร์แกนิก",
        "prod_confiture_bio": "แยมออร์แกนิก",
        "prod_fruits_bio": "ผลไม้ออร์แกนิก",
        "prod_huile_dolive_bio": "น้ำมันมะกอกออร์แกนิก",
        "prod_lait_bio": "นมออร์แกนิก",
        "prod_legumes_bio": "ผักออร์แกนิก",
        "prod_miel_bio": "น้ำผึ้งออร์แกนิก",
        "prod_muesli_bio": "มูสลี่ออร์แกนิก",
        "prod_oeufs_bio": "ไข่ออร์แกนิก",
        "prod_pain_bio": "ขนมปังออร์แกนิก",
        "prod_quinoa_bio": "ควินัวออร์แกนิก",
        "prod_seitan_bio": "เซตันออร์แกนิก",
        "prod_the_bio": "ชาออร์แกนิก",
        "prod_tofu_bio": "เต้าหู้ออร์แกนิก",
    },
    "hi": {
        "prod_biscuits_bio": "जैविक बिस्कुट",
        "prod_cafe_bio": "जैविक कॉफ़ी",
        "prod_chocolat_bio": "जैविक चॉकलेट",
        "prod_compote_bio": "जैविक फ्रूट प्यूरी",
        "prod_confiture_bio": "जैविक जैम",
        "prod_fruits_bio": "जैविक फल",
        "prod_huile_dolive_bio": "जैविक जैतून का तेल",
        "prod_lait_bio": "जैविक दूध",
        "prod_legumes_bio": "जैविक सब्ज़ियाँ",
        "prod_miel_bio": "जैविक शहद",
        "prod_muesli_bio": "जैविक म्यूज़ली",
        "prod_oeufs_bio": "जैविक अंडे",
        "prod_pain_bio": "जैविक ब्रेड",
        "prod_quinoa_bio": "जैविक क्विनोआ",
        "prod_seitan_bio": "जैविक सीतान",
        "prod_the_bio": "जैविक चाय",
        "prod_tofu_bio": "जैविक टोफू",
    },
    "ru": {
        "prod_biscuits_bio": "Органическое печенье",
        "prod_cafe_bio": "Органический кофе",
        "prod_chocolat_bio": "Органический шоколад",
        "prod_compote_bio": "Органическое пюре",
        "prod_confiture_bio": "Органический джем",
        "prod_fruits_bio": "Органические фрукты",
        "prod_huile_dolive_bio": "Органическое оливковое масло",
        "prod_lait_bio": "Органическое молоко",
        "prod_legumes_bio": "Органические овощи",
        "prod_miel_bio": "Органический мёд",
        "prod_muesli_bio": "Органические мюсли",
        "prod_oeufs_bio": "Органические яйца",
        "prod_pain_bio": "Органический хлеб",
        "prod_quinoa_bio": "Органическая киноа",
        "prod_seitan_bio": "Органический сейтан",
        "prod_the_bio": "Органический чай",
        "prod_tofu_bio": "Органический тофу",
    },
    "uk": {
        "prod_biscuits_bio": "Органічне печиво",
        "prod_cafe_bio": "Органічна кава",
        "prod_chocolat_bio": "Органічний шоколад",
        "prod_compote_bio": "Органічне пюре",
        "prod_confiture_bio": "Органічний джем",
        "prod_fruits_bio": "Органічні фрукти",
        "prod_huile_dolive_bio": "Органічна оливкова олія",
        "prod_lait_bio": "Органічне молоко",
        "prod_legumes_bio": "Органічні овочі",
        "prod_miel_bio": "Органічний мед",
        "prod_muesli_bio": "Органічні мюслі",
        "prod_oeufs_bio": "Органічні яйця",
        "prod_pain_bio": "Органічний хліб",
        "prod_quinoa_bio": "Органічна кіноа",
        "prod_seitan_bio": "Органічний сейтан",
        "prod_the_bio": "Органічний чай",
        "prod_tofu_bio": "Органічне тофу",
    },
    "el": {
        "prod_biscuits_bio": "Βιολογικά μπισκότα",
        "prod_cafe_bio": "Βιολογικός καφές",
        "prod_chocolat_bio": "Βιολογική σοκολάτα",
        "prod_compote_bio": "Βιολογική κομπόστα",
        "prod_confiture_bio": "Βιολογική μαρμελάδα",
        "prod_fruits_bio": "Βιολογικά φρούτα",
        "prod_huile_dolive_bio": "Βιολογικό ελαιόλαδο",
        "prod_lait_bio": "Βιολογικό γάλα",
        "prod_legumes_bio": "Βιολογικά λαχανικά",
        "prod_miel_bio": "Βιολογικό μέλι",
        "prod_muesli_bio": "Βιολογικό μούσλι",
        "prod_oeufs_bio": "Βιολογικά αυγά",
        "prod_pain_bio": "Βιολογικό ψωμί",
        "prod_quinoa_bio": "Βιολογική κινόα",
        "prod_seitan_bio": "Βιολογικό σεϊτάν",
        "prod_the_bio": "Βιολογικό τσάι",
        "prod_tofu_bio": "Βιολογικό τόφου",
    },
    "es": {
        "prod_biscuits_bio": "Galletas ecológicas",
        "prod_cafe_bio": "Café ecológico",
        "prod_chocolat_bio": "Chocolate ecológico",
        "prod_compote_bio": "Compota ecológica",
        "prod_confiture_bio": "Mermelada ecológica",
        "prod_fruits_bio": "Fruta ecológica",
        "prod_huile_dolive_bio": "Aceite de oliva ecológico",
        "prod_lait_bio": "Leche ecológica",
        "prod_legumes_bio": "Verduras ecológicas",
        "prod_miel_bio": "Miel ecológica",
        "prod_muesli_bio": "Muesli ecológico",
        "prod_oeufs_bio": "Huevos ecológicos",
        "prod_pain_bio": "Pan ecológico",
        "prod_quinoa_bio": "Quinoa ecológica",
        "prod_seitan_bio": "Seitán ecológico",
        "prod_the_bio": "Té ecológico",
        "prod_tofu_bio": "Tofu ecológico",
    },
    "pt": {
        "prod_biscuits_bio": "Bolachas biológicas",
        "prod_cafe_bio": "Café biológico",
        "prod_chocolat_bio": "Chocolate biológico",
        "prod_compote_bio": "Compota biológica",
        "prod_confiture_bio": "Doce biológico",
        "prod_fruits_bio": "Fruta biológica",
        "prod_huile_dolive_bio": "Azeite biológico",
        "prod_lait_bio": "Leite biológico",
        "prod_legumes_bio": "Legumes biológicos",
        "prod_miel_bio": "Mel biológico",
        "prod_muesli_bio": "Muesli biológico",
        "prod_oeufs_bio": "Ovos biológicos",
        "prod_pain_bio": "Pão biológico",
        "prod_quinoa_bio": "Quinoa biológica",
        "prod_seitan_bio": "Seitan biológico",
        "prod_the_bio": "Chá biológico",
        "prod_tofu_bio": "Tofu biológico",
    },
    "id": {
        "prod_biscuits_bio": "Biskuit organik",
        "prod_cafe_bio": "Kopi organik",
        "prod_chocolat_bio": "Cokelat organik",
        "prod_compote_bio": "Pure buah organik",
        "prod_confiture_bio": "Selai organik",
        "prod_fruits_bio": "Buah organik",
        "prod_huile_dolive_bio": "Minyak zaitun organik",
        "prod_lait_bio": "Susu organik",
        "prod_legumes_bio": "Sayuran organik",
        "prod_miel_bio": "Madu organik",
        "prod_muesli_bio": "Muesli organik",
        "prod_oeufs_bio": "Telur organik",
        "prod_pain_bio": "Roti organik",
        "prod_quinoa_bio": "Quinoa organik",
        "prod_seitan_bio": "Seitan organik",
        "prod_the_bio": "Teh organik",
        "prod_tofu_bio": "Tahu organik",
    },
    "pl": {
        "prod_biscuits_bio": "Ekologiczne ciasteczka",
        "prod_cafe_bio": "Kawa ekologiczna",
        "prod_chocolat_bio": "Czekolada ekologiczna",
        "prod_compote_bio": "Mus owocowy ekologiczny",
        "prod_confiture_bio": "Dżem ekologiczny",
        "prod_fruits_bio": "Owoce ekologiczne",
        "prod_huile_dolive_bio": "Oliwa ekologiczna",
        "prod_lait_bio": "Mleko ekologiczne",
        "prod_legumes_bio": "Warzywa ekologiczne",
        "prod_miel_bio": "Miód ekologiczny",
        "prod_muesli_bio": "Musli ekologiczne",
        "prod_oeufs_bio": "Jajka ekologiczne",
        "prod_pain_bio": "Chleb ekologiczny",
        "prod_quinoa_bio": "Komosa ekologiczna",
        "prod_seitan_bio": "Seitan ekologiczny",
        "prod_the_bio": "Herbata ekologiczna",
        "prod_tofu_bio": "Tofu ekologiczne",
    },
    "lt": {
        "prod_biscuits_bio": "Ekologiški sausainiai",
        "prod_cafe_bio": "Ekologiška kava",
        "prod_chocolat_bio": "Ekologiškas šokoladas",
        "prod_compote_bio": "Ekologiška tyrelė",
        "prod_confiture_bio": "Ekologiška uogienė",
        "prod_fruits_bio": "Ekologiški vaisiai",
        "prod_huile_dolive_bio": "Ekologiškas alyvuogių aliejus",
        "prod_lait_bio": "Ekologiškas pienas",
        "prod_legumes_bio": "Ekologiškos daržovės",
        "prod_miel_bio": "Ekologiškas medus",
        "prod_muesli_bio": "Ekologiški musliai",
        "prod_oeufs_bio": "Ekologiški kiaušiniai",
        "prod_pain_bio": "Ekologiška duona",
        "prod_quinoa_bio": "Ekologiška bolivinė balanda",
        "prod_seitan_bio": "Ekologiškas seitanas",
        "prod_the_bio": "Ekologiška arbata",
        "prod_tofu_bio": "Ekologiškas tofu",
    },
    "ms": {
        "prod_biscuits_bio": "Biskut organik",
        "prod_cafe_bio": "Kopi organik",
        "prod_chocolat_bio": "Coklat organik",
        "prod_compote_bio": "Puri buah organik",
        "prod_confiture_bio": "Jem organik",
        "prod_fruits_bio": "Buah organik",
        "prod_huile_dolive_bio": "Minyak zaitun organik",
        "prod_lait_bio": "Susu organik",
        "prod_legumes_bio": "Sayuran organik",
        "prod_miel_bio": "Madu organik",
        "prod_muesli_bio": "Muesli organik",
        "prod_oeufs_bio": "Telur organik",
        "prod_pain_bio": "Roti organik",
        "prod_quinoa_bio": "Quinoa organik",
        "prod_seitan_bio": "Seitan organik",
        "prod_the_bio": "Teh organik",
        "prod_tofu_bio": "Tauhu organik",
    },
    "gl": {
        "prod_biscuits_bio": "Biscoitos ecolóxicos",
        "prod_cafe_bio": "Café ecolóxico",
        "prod_chocolat_bio": "Chocolate ecolóxico",
        "prod_compote_bio": "Compota ecolóxica",
        "prod_confiture_bio": "Marmelada ecolóxica",
        "prod_fruits_bio": "Froita ecolóxica",
        "prod_huile_dolive_bio": "Aceite de oliva ecolóxico",
        "prod_lait_bio": "Leite ecolóxico",
        "prod_legumes_bio": "Verduras ecolóxicas",
        "prod_miel_bio": "Mel ecolóxico",
        "prod_muesli_bio": "Muesli ecolóxico",
        "prod_oeufs_bio": "Ovos ecolóxicos",
        "prod_pain_bio": "Pan ecolóxico",
        "prod_quinoa_bio": "Quinoa ecolóxica",
        "prod_seitan_bio": "Seitán ecolóxico",
        "prod_the_bio": "Té ecolóxico",
        "prod_tofu_bio": "Tofu ecolóxico",
    },
    "ca": {
        "prod_biscuits_bio": "Galetes ecològiques",
        "prod_cafe_bio": "Cafè ecològic",
        "prod_chocolat_bio": "Xocolata ecològica",
        "prod_compote_bio": "Compota ecològica",
        "prod_confiture_bio": "Melmelada ecològica",
        "prod_fruits_bio": "Fruita ecològica",
        "prod_huile_dolive_bio": "Oli d’oliva ecològic",
        "prod_lait_bio": "Llet ecològica",
        "prod_legumes_bio": "Verdures ecològiques",
        "prod_miel_bio": "Mel ecològica",
        "prod_muesli_bio": "Muesli ecològic",
        "prod_oeufs_bio": "Ous ecològics",
        "prod_pain_bio": "Pa ecològic",
        "prod_quinoa_bio": "Quinoa ecològica",
        "prod_seitan_bio": "Seitan ecològic",
        "prod_the_bio": "Te ecològic",
        "prod_tofu_bio": "Tofu ecològic",
    },
    "tr": {
        "prod_biscuits_bio": "Organik bisküvi",
        "prod_cafe_bio": "Organik kahve",
        "prod_chocolat_bio": "Organik çikolata",
        "prod_compote_bio": "Organik meyve püresi",
        "prod_confiture_bio": "Organik reçel",
        "prod_fruits_bio": "Organik meyve",
        "prod_huile_dolive_bio": "Organik zeytinyağı",
        "prod_lait_bio": "Organik süt",
        "prod_legumes_bio": "Organik sebze",
        "prod_miel_bio": "Organik bal",
        "prod_muesli_bio": "Organik müsli",
        "prod_oeufs_bio": "Organik yumurta",
        "prod_pain_bio": "Organik ekmek",
        "prod_quinoa_bio": "Organik kinoa",
        "prod_seitan_bio": "Organik seitan",
        "prod_the_bio": "Organik çay",
        "prod_tofu_bio": "Organik tofu",
    },
    "vi": {
        "prod_biscuits_bio": "Bánh quy hữu cơ",
        "prod_cafe_bio": "Cà phê hữu cơ",
        "prod_chocolat_bio": "Sô cô la hữu cơ",
        "prod_compote_bio": "Puree trái cây hữu cơ",
        "prod_confiture_bio": "Mứt hữu cơ",
        "prod_fruits_bio": "Trái cây hữu cơ",
        "prod_huile_dolive_bio": "Dầu ô liu hữu cơ",
        "prod_lait_bio": "Sữa hữu cơ",
        "prod_legumes_bio": "Rau hữu cơ",
        "prod_miel_bio": "Mật ong hữu cơ",
        "prod_muesli_bio": "Muesli hữu cơ",
        "prod_oeufs_bio": "Trứng hữu cơ",
        "prod_pain_bio": "Bánh mì hữu cơ",
        "prod_quinoa_bio": "Diêm mạch hữu cơ",
        "prod_seitan_bio": "Seitan hữu cơ",
        "prod_the_bio": "Trà hữu cơ",
        "prod_tofu_bio": "Đậu phụ hữu cơ",
    },
    "bg": {
        "prod_biscuits_bio": "Био бисквити",
        "prod_cafe_bio": "Био кафе",
        "prod_chocolat_bio": "Био шоколад",
        "prod_compote_bio": "Био компот",
        "prod_confiture_bio": "Био сладко",
        "prod_fruits_bio": "Био плодове",
        "prod_huile_dolive_bio": "Био зехтин",
        "prod_lait_bio": "Био мляко",
        "prod_legumes_bio": "Био зеленчуци",
        "prod_miel_bio": "Био мед",
        "prod_muesli_bio": "Био мюсли",
        "prod_oeufs_bio": "Био яйца",
        "prod_pain_bio": "Био хляб",
        "prod_quinoa_bio": "Био киноа",
        "prod_seitan_bio": "Био сейтан",
        "prod_the_bio": "Био чай",
        "prod_tofu_bio": "Био тофу",
    },
    "sv": {
        "prod_biscuits_bio": "Ekologiska kex",
        "prod_cafe_bio": "Ekologiskt kaffe",
        "prod_chocolat_bio": "Ekologisk choklad",
        "prod_compote_bio": "Ekologisk fruktmos",
        "prod_confiture_bio": "Ekologisk sylt",
        "prod_fruits_bio": "Ekologisk frukt",
        "prod_huile_dolive_bio": "Ekologisk olivolja",
        "prod_lait_bio": "Ekologisk mjölk",
        "prod_legumes_bio": "Ekologiska grönsaker",
        "prod_miel_bio": "Ekologisk honung",
        "prod_muesli_bio": "Ekologisk müsli",
        "prod_oeufs_bio": "Ekologiska ägg",
        "prod_pain_bio": "Ekologiskt bröd",
        "prod_quinoa_bio": "Ekologisk quinoa",
        "prod_seitan_bio": "Ekologisk seitan",
        "prod_the_bio": "Ekologiskt te",
        "prod_tofu_bio": "Ekologisk tofu",
    },
    "it": {
        "prod_biscuits_bio": "Biscotti bio",
        "prod_cafe_bio": "Caffè biologico",
        "prod_chocolat_bio": "Cioccolato biologico",
        "prod_compote_bio": "Composta biologica",
        "prod_confiture_bio": "Marmellata bio",
        "prod_fruits_bio": "Frutta bio",
        "prod_huile_dolive_bio": "Olio d’oliva bio",
        "prod_lait_bio": "Latte bio",
        "prod_legumes_bio": "Verdure biologiche",
        "prod_miel_bio": "Miele bio",
        "prod_muesli_bio": "Muesli biologico",
        "prod_oeufs_bio": "Uova biologiche",
        "prod_pain_bio": "Pane biologico",
        "prod_quinoa_bio": "Quinoa biologica",
        "prod_seitan_bio": "Seitan biologico",
        "prod_the_bio": "Tè biologico",
        "prod_tofu_bio": "Tofu biologico",
    },
    "nl": {
        "prod_biscuits_bio": "Biologische koekjes",
        "prod_cafe_bio": "Biologische koffie",
        "prod_chocolat_bio": "Biologische chocolade",
        "prod_compote_bio": "Biologische compote",
        "prod_confiture_bio": "Biologische jam",
        "prod_fruits_bio": "Biologisch fruit",
        "prod_huile_dolive_bio": "Biologische olijfolie",
        "prod_lait_bio": "Biologische melk",
        "prod_legumes_bio": "Biologische groenten",
        "prod_miel_bio": "Biologische honing",
        "prod_muesli_bio": "Biologische muesli",
        "prod_oeufs_bio": "Biologische eieren",
        "prod_pain_bio": "Biologisch brood",
        "prod_quinoa_bio": "Biologische quinoa",
        "prod_seitan_bio": "Biologische seitan",
        "prod_the_bio": "Biologische thee",
        "prod_tofu_bio": "Biologische tofu",
    },
    "de": {
        "prod_pain_bio": "Bio-Brot",
    },
    "ro": {
        "prod_pain_bio": "Pâine eco",
        "prod_muesli_bio": "Muesli eco",
        "prod_seitan_bio": "Seitan eco",
        "prod_quinoa_bio": "Quinoa eco",
        "prod_tofu_bio": "Tofu eco",
        "prod_jus_de_fruit_naturel": "Suc natural de fructe",
        "prod_fromage_blanc": "Brânză proaspătă",
    },
    "fi": {
        "prod_pain_bio": "Luomuleipä",
        "prod_jus_de_fruit_naturel": "Luonnollinen hedelmämehu",
        "prod_fromage_blanc": "Tuorejuusto",
        "prod_jus_de_raisin": "Rypälemehu",
    },
    "hu": {
        "prod_fromage_blanc": "Friss sajt",
        "prod_jus_de_raisin": "Szőlőlé",
    },
    "da": {
        "prod_fromage_blanc": "Fromage frais",
        "prod_jus_de_raisin": "Druesaft",
        "prod_pain_bio": "Økologisk brød",
    },
    "nb": {
        "prod_fromage_blanc": "Ferskost",
        "prod_jus_de_raisin": "Druesaft",
        "prod_pain_bio": "Økologisk brød",
        "prod_joint_carrelage": "Flisfuge",
    },
    "sk": {
        "prod_jus_de_raisin": "Hroznový džús",
        "prod_pain_bio": "Bio chlieb",
        "prod_huile_dolive_bio": "Bio olivový olej",
    },
    "cs": {
        "prod_pain_bio": "Bio chléb",
        "prod_huile_dolive_bio": "Bio olivový olej",
    },
    "sl": {
        "prod_fromage_blanc": "Sveži sir",
        "prod_miel_du_producteur": "Med od pridelovalca",
        "prod_pain_bio": "Eko kruh",
    },
    "hr": {
        "prod_fromage_blanc": "Svježi sir",
        "prod_miel_du_producteur": "Med od proizvođača",
        "prod_pain_bio": "Eko kruh",
    },
    "et": {
        "prod_fromage_blanc": "Kohupiimajuust",
        "prod_jus_de_raisin": "Viinamarjamahl",
        "prod_pain_bio": "Maheleib",
    },
    "lv": {
        "prod_fromage_blanc": "Svaigais siers",
        "prod_jus_de_raisin": "Vīnogu sula",
        "prod_colle_carrelage": "Flīžu līme",
        "prod_pain_bio": "Bioloģiskā maize",
    },
}

# Extra leftovers (not in BIO table).
EXTRA: dict[str, dict[str, str]] = {
    "ar": {
        "prod_verrue": "علاج الثآليل",
        "prod_fromage_blanc": "جبن أبيض طري",
        "prod_jus_de_raisin": "عصير عنب",
        "prod_jus_de_fruit_naturel": "عصير فواكه طبيعي",
        "prod_carrelage": "بلاط",
    },
    "ja": {
        "prod_fromage_blanc": "フロマージュ・ブラン",
        "prod_jus_de_raisin": "グレープジュース",
        "prod_jus_de_fruit_naturel": "天然フルーツジュース",
        "prod_jus_de_fruit": "フルーツジュース",
        "prod_confiture_dabricot": "アプリコットジャム",
        "prod_confiture_de_fraises": "イチゴジャム",
        "prod_miel_du_producteur": "生産者のはちみつ",
        "prod_carrelage": "タイル",
        "prod_lait_de_coco": "ココナッツミルク",
        "prod_myrtilles": "ブルーベリー",
        "prod_poulpe": "タコ",
        "prod_morue": "タラ",
        "prod_drop": "リコリス",
    },
    "ko": {
        "prod_vache_qui_rit": "라 바슈 키 리",
        "prod_fromage_blanc": "프로마주 블랑",
        "prod_jus_de_raisin": "포도 주스",
        "prod_jus_de_fruit_naturel": "천연 과일 주스",
        "prod_carrelage": "타일",
        "prod_lait_de_coco": "코코넛 밀크",
    },
    "zh": {
        "prod_fromage_blanc": "白奶酪",
        "prod_jus_de_raisin": "葡萄汁",
        "prod_jus_de_fruit_naturel": "天然果汁",
        "prod_carrelage": "瓷砖",
        "prod_lait_de_coco": "椰奶",
    },
    "vi": {
        "prod_miel_du_producteur": "Mật ong của nhà sản xuất",
        "prod_fromage_blanc": "Phô mai tươi",
        "prod_jus_de_raisin": "Nước nho",
        "prod_jus_de_fruit_naturel": "Nước ép trái cây tự nhiên",
        "prod_confiture_de_fraises": "Mứt dâu",
    },
    "it": {
        "prod_fromage_blanc": "Fiocchi di latte",
        "prod_jus_de_raisin": "Succo d’uva",
        "prod_jus_de_fruit_naturel": "Succo di frutta naturale",
        "prod_lait_de_coco": "Latte di cocco",
        "prod_abricot": "Albicocca",
    },
    "nl": {
        "prod_fromage_blanc": "Fromage frais",
        "prod_confiture_dabricot": "Abrikozenjam",
        "prod_jus_de_raisin": "Druivensap",
        "prod_confiture_de_fraises": "Aardbeienjam",
        "prod_yaourt_nature": "Naturel yoghurt",
    },
    "pl": {
        "prod_miel_du_producteur": "Miód od producenta",
        "prod_fromage_blanc": "Ser twarogowy",
        "prod_confiture_dabricot": "Dżem morelowy",
        "prod_jus_de_raisin": "Sok winogronowy",
        "prod_jus_de_fruit_naturel": "Naturalny sok owocowy",
        "prod_fromage_fermier": "Ser zagrodowy",
    },
    "pt": {
        "prod_confiture_dabricot": "Doce de alperce",
        "prod_jus_de_raisin": "Sumo de uva",
        "prod_colle_carrelage": "Cola para azulejos",
        "prod_joint_carrelage": "Betume para azulejos",
        "prod_carrelage": "Azulejos",
    },
    "de": {
        "prod_fromage_blanc": "Speisequark",
        "prod_jus_de_raisin": "Traubensaft",
    },
    "es": {
        "prod_miel_du_producteur": "Miel del productor",
        "prod_fromage_blanc": "Queso fresco",
        "prod_jus_de_raisin": "Zumo de uva",
    },
    "ca": {
        "prod_miel_du_producteur": "Mel del productor",
        "prod_fromage_blanc": "Formatge fresc",
        "prod_jus_de_raisin": "Suc de raïm",
        "prod_joint_carrelage": "Junta de rajola",
        "prod_abricot": "Albercoc",
    },
    "eu": {
        "prod_fromage_blanc": "Gazta freskoa",
        "prod_joint_carrelage": "Baldosa-junta",
        "prod_abricot": "Abrikota",
    },
    "gl": {
        "prod_fromage_blanc": "Queixo fresco",
        "prod_jus_de_raisin": "Zume de uva",
    },
    "ms": {
        "prod_fromage_blanc": "Keju putih lembut",
        "prod_jus": "Jus",
        "prod_jus_de_raisin": "Jus anggur",
        "prod_joint_carrelage": "Grout jubin",
        "prod_parfum": "Minyak wangi",
    },
    "id": {
        "prod_parfum": "Parfum",
        "prod_fromage_blanc": "Keju putih lembut",
        "prod_jus_de_raisin": "Jus anggur",
    },
    "tr": {
        "prod_jambon": "Jambon",
        "prod_biberon": "Biberon",
        "prod_fromage_blanc": "Taze peynir",
        "prod_jus_de_raisin": "Üzüm suyu",
        "prod_confiture_de_fraises": "Çilek reçeli",
    },
    "bg": {
        "prod_miel_du_producteur": "Мед от производител",
        "prod_fromage_blanc": "Прясно сирене",
    },
    "sv": {
        "prod_fromage_blanc": "Färskost",
        "prod_confiture_dabricot": "Aprikosmarmelad",
        "prod_jus_de_raisin": "Druvsaft",
    },
    "lt": {
        "prod_fromage_blanc": "Šviežias sūris",
        "prod_jus_de_raisin": "Vynuogių sultys",
        "prod_jus_de_fruit_naturel": "Natūralios vaisių sultys",
    },
    "hu": {
        "prod_fromage_blanc": "Friss sajt",
        "prod_jus_de_raisin": "Szőlőlé",
    },
}


def replace_value(text: str, key: str, new_value: str) -> tuple[str, bool]:
    escaped = json.dumps(new_value, ensure_ascii=False)[1:-1]
    pattern = re.compile(rf'("{re.escape(key)}":\s*")(?:\\.|[^"\\])*(")')
    found = False

    def repl(m: re.Match[str]) -> str:
        nonlocal found
        found = True
        return m.group(1) + escaped + m.group(2)

    return pattern.sub(repl, text, count=1), found


def main() -> None:
    total = 0
    missing = 0
    for arb in sorted(ROOT.glob("app_*.arb")):
        loc = arb.stem.split("_", 1)[1]
        updates: dict[str, str] = {}
        updates.update(BIO.get(loc, {}))
        updates.update(EXTRA.get(loc, {}))
        if not updates:
            continue
        text = arb.read_text(encoding="utf-8")
        orig = text
        for key, value in updates.items():
            text, ok = replace_value(text, key, value)
            if ok:
                total += 1
            else:
                missing += 1
                print(f"  missing {loc}.{key}")
        if text != orig:
            arb.write_text(text, encoding="utf-8")
            print(f"{loc}: {len(updates)} keys")
    print(f"replacements: {total}  missing: {missing}")


if __name__ == "__main__":
    main()
