#!/usr/bin/env python3
"""In-place ARB fixes: leftover English UI + botched product names. Does not rewrite whole files."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "lib" / "l10n"

# UI leftover English → native. Keys present in all locales.
UI: dict[str, dict[str, str]] = {
    "de": {
        "styleFilled": "Klassisches Rechteck",
        "legendLabel": "Oben in der Liste",
        "categoriesHint": "Oben in der Liste: sichtbare Laden-Punkte mit Namen. Im Formular nennst du den Laden nur beim Hinzufügen.",
        "tooltipDetails": "Details",
        "aboutCreator": "Urheber",
        "aboutPrivacy": "Datenschutz",
        "aboutLicense": "Lizenz",
        "aboutCredits": "Credits",
        "pasteTooltip": "Einfügen",
        "dictateTooltip": "Diktieren",
        "profileBrandHint": "Marke…",
        "profileHintCity": "Stadt",
        "tooltipDelete": "Löschen",
        "tooltipEdit": "Bearbeiten",
        "tooltipPostpone": "Verschieben",
        "changePhotoLabel": "Ändern",
        "timeLabelShort": "Uhrzeit",
        "dateLabelShort": "Datum",
        "photoLabel": "Foto",
    },
    "es": {
        "styleFilled": "Rectángulo clásico",
        "legendLabel": "Arriba de la lista",
        "categoriesHint": "Arriba de la lista: pastillas de tienda con su nombre. En el formulario, nombra la tienda solo al añadir.",
        "tooltipDetails": "Detalles",
        "aboutCreator": "Creador",
        "aboutPrivacy": "Privacidad",
        "aboutLicense": "Licencia",
        "aboutCredits": "Créditos",
        "pasteTooltip": "Pegar",
        "dictateTooltip": "Dictar",
        "profileBrandHint": "Marca…",
        "profileHintCity": "Ciudad",
        "tooltipDelete": "Eliminar",
        "tooltipEdit": "Editar",
        "tooltipPostpone": "Posponer",
        "changePhotoLabel": "Cambiar",
        "timeLabelShort": "Hora",
        "dateLabelShort": "Fecha",
        "photoLabel": "Foto",
    },
    "it": {
        "styleFilled": "Rettangolo classico",
        "legendLabel": "In cima alla lista",
        "categoriesHint": "In cima alla lista: pastiglie negozio con il nome. Nel modulo indichi il negozio solo all’aggiunta.",
        "tooltipDetails": "Dettagli",
        "aboutCreator": "Autore",
        "aboutPrivacy": "Privacy",
        "aboutLicense": "Licenza",
        "aboutCredits": "Crediti",
        "pasteTooltip": "Incolla",
        "dictateTooltip": "Detta",
        "profileBrandHint": "Marca…",
        "profileHintCity": "Città",
        "tooltipDelete": "Elimina",
        "tooltipEdit": "Modifica",
        "tooltipPostpone": "Rinvia",
        "changePhotoLabel": "Cambia",
        "timeLabelShort": "Ora",
        "dateLabelShort": "Data",
        "photoLabel": "Foto",
    },
    "pt": {
        "styleFilled": "Retângulo clássico",
        "legendLabel": "No topo da lista",
        "categoriesHint": "No topo da lista: pastilhas de loja com o nome. No formulário, nomeia a loja só ao adicionar.",
        "tooltipDetails": "Detalhes",
        "aboutCreator": "Criador",
        "aboutPrivacy": "Privacidade",
        "aboutLicense": "Licença",
        "aboutCredits": "Créditos",
        "pasteTooltip": "Colar",
        "dictateTooltip": "Ditar",
        "profileBrandHint": "Marca…",
        "profileHintCity": "Cidade",
        "tooltipDelete": "Eliminar",
        "tooltipEdit": "Editar",
        "tooltipPostpone": "Adiar",
        "changePhotoLabel": "Alterar",
        "timeLabelShort": "Hora",
        "dateLabelShort": "Data",
        "photoLabel": "Foto",
    },
    "nl": {
        "styleFilled": "Klassieke rechthoek",
        "legendLabel": "Bovenaan de lijst",
        "categoriesHint": "Bovenaan de lijst: winkelchips met naam. In het formulier noem je de winkel alleen bij het toevoegen.",
        "tooltipDetails": "Details",
        "aboutCreator": "Maker",
        "aboutPrivacy": "Privacy",
        "aboutLicense": "Licentie",
        "aboutCredits": "Credits",
        "pasteTooltip": "Plakken",
        "dictateTooltip": "Dicteren",
        "profileBrandHint": "Merk…",
        "profileHintCity": "Stad",
        "tooltipDelete": "Verwijderen",
        "tooltipEdit": "Bewerken",
        "tooltipPostpone": "Uitstellen",
        "changePhotoLabel": "Wijzigen",
        "timeLabelShort": "Tijd",
        "dateLabelShort": "Datum",
        "photoLabel": "Foto",
    },
    "pl": {
        "styleFilled": "Klasyczny prostokąt",
        "legendLabel": "Na górze listy",
        "categoriesHint": "Na górze listy: chipsy sklepów z nazwą. W formularzu podajesz sklep tylko przy dodawaniu.",
        "tooltipDetails": "Szczegóły",
        "aboutCreator": "Twórca",
        "aboutPrivacy": "Prywatność",
        "aboutLicense": "Licencja",
        "aboutCredits": "Autorzy",
        "pasteTooltip": "Wklej",
        "dictateTooltip": "Dyktuj",
        "profileBrandHint": "Marka…",
        "profileHintCity": "Miasto",
        "tooltipDelete": "Usuń",
        "tooltipEdit": "Edytuj",
        "tooltipPostpone": "Odłóż",
        "changePhotoLabel": "Zmień",
        "timeLabelShort": "Godzina",
        "dateLabelShort": "Data",
        "photoLabel": "Zdjęcie",
    },
    "cs": {
        "styleFilled": "Klasický obdélník",
        "legendLabel": "Nahoře na seznamu",
        "categoriesHint": "Nahoře na seznamu: obchody s názvem. Ve formuláři obchod pojmenuješ jen při přidání.",
        "tooltipDetails": "Podrobnosti",
        "aboutCreator": "Autor",
        "aboutPrivacy": "Soukromí",
        "aboutLicense": "Licence",
        "aboutCredits": "Kredity",
        "pasteTooltip": "Vložit",
        "dictateTooltip": "Diktovat",
        "profileBrandHint": "Značka…",
        "profileHintCity": "Město",
        "tooltipDelete": "Smazat",
        "tooltipEdit": "Upravit",
        "tooltipPostpone": "Odložit",
        "changePhotoLabel": "Změnit",
        "timeLabelShort": "Čas",
        "dateLabelShort": "Datum",
        "photoLabel": "Foto",
    },
    "sk": {
        "styleFilled": "Klasický obdĺžnik",
        "legendLabel": "Hore na zozname",
        "categoriesHint": "Hore na zozname: obchody s názvom. Vo formulári obchod pomenuješ len pri pridaní.",
        "tooltipDetails": "Podrobnosti",
        "aboutCreator": "Autor",
        "aboutPrivacy": "Súkromie",
        "aboutLicense": "Licencia",
        "aboutCredits": "Kredity",
        "pasteTooltip": "Prilepiť",
        "dictateTooltip": "Diktovať",
        "profileBrandHint": "Značka…",
        "profileHintCity": "Mesto",
        "tooltipDelete": "Odstrániť",
        "tooltipEdit": "Upraviť",
        "tooltipPostpone": "Odložiť",
        "changePhotoLabel": "Zmeniť",
        "timeLabelShort": "Čas",
        "dateLabelShort": "Dátum",
        "photoLabel": "Foto",
    },
    "sl": {
        "styleFilled": "Klasičen pravokotnik",
        "legendLabel": "Na vrhu seznama",
        "categoriesHint": "Na vrhu seznama: trgovine z imenom. V obrazcu trgovino poimenuješ samo ob dodajanju.",
        "tooltipDetails": "Podrobnosti",
        "aboutCreator": "Avtor",
        "aboutPrivacy": "Zasebnost",
        "aboutLicense": "Licenca",
        "aboutCredits": "Zasluge",
        "pasteTooltip": "Prilepi",
        "dictateTooltip": "Narekuje",
        "profileBrandHint": "Znamka…",
        "profileHintCity": "Mesto",
        "tooltipDelete": "Izbriši",
        "tooltipEdit": "Uredi",
        "tooltipPostpone": "Preloži",
        "changePhotoLabel": "Spremeni",
        "timeLabelShort": "Ura",
        "dateLabelShort": "Datum",
        "photoLabel": "Fotografija",
    },
    "hr": {
        "styleFilled": "Klasični pravokutnik",
        "legendLabel": "Na vrhu popisa",
        "categoriesHint": "Na vrhu popisa: trgovine s imenom. U obrascu trgovinu imenuješ samo pri dodavanju.",
        "tooltipDetails": "Detalji",
        "aboutCreator": "Autor",
        "aboutPrivacy": "Privatnost",
        "aboutLicense": "Licenca",
        "aboutCredits": "Zasluge",
        "pasteTooltip": "Zalijepi",
        "dictateTooltip": "Diktiraj",
        "profileBrandHint": "Marka…",
        "profileHintCity": "Grad",
        "tooltipDelete": "Izbriši",
        "tooltipEdit": "Uredi",
        "tooltipPostpone": "Odgodi",
        "changePhotoLabel": "Promijeni",
        "timeLabelShort": "Vrijeme",
        "dateLabelShort": "Datum",
        "photoLabel": "Fotografija",
    },
    "sr": {
        "styleFilled": "Класични правоугаоник",
        "legendLabel": "На врху листе",
        "categoriesHint": "На врху листе: продавнице са именом. У формулару продавницу именујеш само при додавању.",
        "tooltipDetails": "Детаљи",
        "aboutCreator": "Аутор",
        "aboutPrivacy": "Приватност",
        "aboutLicense": "Лиценца",
        "aboutCredits": "Заслуге",
        "pasteTooltip": "Налепи",
        "dictateTooltip": "Диктирај",
        "profileBrandHint": "Марка…",
        "profileHintCity": "Град",
        "tooltipDelete": "Обриши",
        "tooltipEdit": "Измени",
        "tooltipPostpone": "Одложи",
        "changePhotoLabel": "Промени",
        "timeLabelShort": "Време",
        "dateLabelShort": "Датум",
        "photoLabel": "Фотографија",
    },
    "ro": {
        "styleFilled": "Dreptunghi clasic",
        "legendLabel": "Sus în listă",
        "categoriesHint": "Sus în listă: magazine cu nume. În formular numești magazinul doar la adăugare.",
        "tooltipDetails": "Detalii",
        "aboutCreator": "Autor",
        "aboutPrivacy": "Confidențialitate",
        "aboutLicense": "Licență",
        "aboutCredits": "Credite",
        "pasteTooltip": "Lipește",
        "dictateTooltip": "Dictează",
        "profileBrandHint": "Marcă…",
        "profileHintCity": "Oraș",
        "tooltipDelete": "Șterge",
        "tooltipEdit": "Editează",
        "tooltipPostpone": "Amână",
        "changePhotoLabel": "Schimbă",
        "timeLabelShort": "Oră",
        "dateLabelShort": "Dată",
        "photoLabel": "Foto",
    },
    "hu": {
        "styleFilled": "Klasszikus téglalap",
        "legendLabel": "A lista tetején",
        "categoriesHint": "A lista tetején: boltok a nevükkel. Az űrlapon csak hozzáadáskor nevezed el a boltot.",
        "tooltipDetails": "Részletek",
        "aboutCreator": "Készítő",
        "aboutPrivacy": "Adatvédelem",
        "aboutLicense": "Licenc",
        "aboutCredits": "Köszönet",
        "pasteTooltip": "Beillesztés",
        "dictateTooltip": "Diktálás",
        "profileBrandHint": "Márka…",
        "profileHintCity": "Város",
        "tooltipDelete": "Törlés",
        "tooltipEdit": "Szerkesztés",
        "tooltipPostpone": "Elhalasztás",
        "changePhotoLabel": "Csere",
        "timeLabelShort": "Idő",
        "dateLabelShort": "Dátum",
        "photoLabel": "Fotó",
    },
    "tr": {
        "styleFilled": "Klasik dikdörtgen",
        "legendLabel": "Listenin üstü",
        "categoriesHint": "Listenin üstünde: adıyla mağaza etiketleri. Formda mağazayı yalnızca eklerken adlandırırsın.",
        "tooltipDetails": "Ayrıntılar",
        "aboutCreator": "Oluşturan",
        "aboutPrivacy": "Gizlilik",
        "aboutLicense": "Lisans",
        "aboutCredits": "Künye",
        "pasteTooltip": "Yapıştır",
        "dictateTooltip": "Dikte et",
        "profileBrandHint": "Marka…",
        "profileHintCity": "Şehir",
        "tooltipDelete": "Sil",
        "tooltipEdit": "Düzenle",
        "tooltipPostpone": "Ertele",
        "changePhotoLabel": "Değiştir",
        "timeLabelShort": "Saat",
        "dateLabelShort": "Tarih",
        "photoLabel": "Fotoğraf",
    },
    "da": {
        "styleFilled": "Klassisk rektangel",
        "legendLabel": "Øverst på listen",
        "categoriesHint": "Øverst på listen: butiksprikker med navn. I formularen navngiver du butikken kun ved tilføjelse.",
        "tooltipDetails": "Detaljer",
        "aboutCreator": "Ophavsmand",
        "aboutPrivacy": "Privatliv",
        "aboutLicense": "Licens",
        "aboutCredits": "Credits",
        "pasteTooltip": "Sæt ind",
        "dictateTooltip": "Dikter",
        "profileBrandHint": "Mærke…",
        "profileHintCity": "By",
        "tooltipDelete": "Slet",
        "tooltipEdit": "Rediger",
        "tooltipPostpone": "Udskyd",
        "changePhotoLabel": "Skift",
        "timeLabelShort": "Tid",
        "dateLabelShort": "Dato",
        "photoLabel": "Foto",
    },
    "sv": {
        "styleFilled": "Klassisk rektangel",
        "legendLabel": "Högst upp på listan",
        "categoriesHint": "Högst upp på listan: butiksmarkörer med namn. I formuläret namnger du butiken bara vid tillägg.",
        "tooltipDetails": "Detaljer",
        "aboutCreator": "Skapare",
        "aboutPrivacy": "Integritet",
        "aboutLicense": "Licens",
        "aboutCredits": "Medverkande",
        "pasteTooltip": "Klistra in",
        "dictateTooltip": "Diktera",
        "profileBrandHint": "Märke…",
        "profileHintCity": "Stad",
        "tooltipDelete": "Ta bort",
        "tooltipEdit": "Redigera",
        "tooltipPostpone": "Skjut upp",
        "changePhotoLabel": "Ändra",
        "timeLabelShort": "Tid",
        "dateLabelShort": "Datum",
        "photoLabel": "Foto",
    },
    "nb": {
        "styleFilled": "Klassisk rektangel",
        "legendLabel": "Øverst på listen",
        "categoriesHint": "Øverst på listen: butikkmerker med navn. I skjemaet navngir du butikken bare ved tillegg.",
        "tooltipDetails": "Detaljer",
        "aboutCreator": "Opphaver",
        "aboutPrivacy": "Personvern",
        "aboutLicense": "Lisens",
        "aboutCredits": "Bidragsytere",
        "pasteTooltip": "Lim inn",
        "dictateTooltip": "Dikter",
        "profileBrandHint": "Merke…",
        "profileHintCity": "By",
        "tooltipDelete": "Slett",
        "tooltipEdit": "Rediger",
        "tooltipPostpone": "Utsett",
        "changePhotoLabel": "Endre",
        "timeLabelShort": "Tid",
        "dateLabelShort": "Dato",
        "photoLabel": "Foto",
    },
    "fi": {
        "styleFilled": "Klassinen suorakulmio",
        "legendLabel": "Listan yläosa",
        "categoriesHint": "Listan yläosassa: kauppojen merkit nimineen. Lomakkeessa nimeät kaupan vain lisätessä.",
        "tooltipDetails": "Tiedot",
        "aboutCreator": "Tekijä",
        "aboutPrivacy": "Tietosuoja",
        "aboutLicense": "Lisenssi",
        "aboutCredits": "Tekijätiedot",
        "pasteTooltip": "Liitä",
        "dictateTooltip": "Diktoi",
        "profileBrandHint": "Merkki…",
        "profileHintCity": "Kaupunki",
        "tooltipDelete": "Poista",
        "tooltipEdit": "Muokkaa",
        "tooltipPostpone": "Siirrä",
        "changePhotoLabel": "Vaihda",
        "timeLabelShort": "Aika",
        "dateLabelShort": "Päivä",
        "photoLabel": "Kuva",
    },
    "et": {
        "styleFilled": "Klassikaline ristkülik",
        "legendLabel": "Nimekirja ülaosas",
        "categoriesHint": "Nimekirja ülaosas: poed nimega. Vormis nimetad poe ainult lisamisel.",
        "tooltipDetails": "Üksikasjad",
        "aboutCreator": "Autor",
        "aboutPrivacy": "Privaatsus",
        "aboutLicense": "Litsents",
        "aboutCredits": "Tänuavaldused",
        "pasteTooltip": "Kleebi",
        "dictateTooltip": "Dikteeri",
        "profileBrandHint": "Kaubamärk…",
        "profileHintCity": "Linn",
        "tooltipDelete": "Kustuta",
        "tooltipEdit": "Muuda",
        "tooltipPostpone": "Lükka edasi",
        "changePhotoLabel": "Vaheta",
        "timeLabelShort": "Kellaaeg",
        "dateLabelShort": "Kuupäev",
        "photoLabel": "Foto",
    },
    "lv": {
        "styleFilled": "Klasisks taisnstūris",
        "legendLabel": "Saraksta augšā",
        "categoriesHint": "Saraksta augšā: veikali ar nosaukumu. Formā veikalu nosauc tikai pievienojot.",
        "tooltipDetails": "Detaļas",
        "aboutCreator": "Autors",
        "aboutPrivacy": "Privātums",
        "aboutLicense": "Licence",
        "aboutCredits": "Autortiesības",
        "pasteTooltip": "Ielīmēt",
        "dictateTooltip": "Diktēt",
        "profileBrandHint": "Zīmols…",
        "profileHintCity": "Pilsēta",
        "tooltipDelete": "Dzēst",
        "tooltipEdit": "Rediģēt",
        "tooltipPostpone": "Atlikt",
        "changePhotoLabel": "Mainīt",
        "timeLabelShort": "Laiks",
        "dateLabelShort": "Datums",
        "photoLabel": "Foto",
    },
    "lt": {
        "styleFilled": "Klasikinis stačiakampis",
        "legendLabel": "Sąrašo viršuje",
        "categoriesHint": "Sąrašo viršuje: parduotuvės su pavadinimu. Formoje parduotuvę įvardiji tik pridėdamas.",
        "tooltipDetails": "Išsamiau",
        "aboutCreator": "Autorius",
        "aboutPrivacy": "Privatumas",
        "aboutLicense": "Licencija",
        "aboutCredits": "Padėkos",
        "pasteTooltip": "Įklijuoti",
        "dictateTooltip": "Diktuoti",
        "profileBrandHint": "Prekės ženklas…",
        "profileHintCity": "Miestas",
        "tooltipDelete": "Ištrinti",
        "tooltipEdit": "Redaguoti",
        "tooltipPostpone": "Atidėti",
        "changePhotoLabel": "Keisti",
        "timeLabelShort": "Laikas",
        "dateLabelShort": "Data",
        "photoLabel": "Nuotrauka",
    },
    "el": {
        "styleFilled": "Κλασικό ορθογώνιο",
        "legendLabel": "Στην κορυφή της λίστας",
        "categoriesHint": "Στην κορυφή: καταστήματα με όνομα. Στη φόρμα ονομάζεις το κατάστημα μόνο στην προσθήκη.",
        "tooltipDetails": "Λεπτομέρειες",
        "aboutCreator": "Δημιουργός",
        "aboutPrivacy": "Απόρρητο",
        "aboutLicense": "Άδεια",
        "aboutCredits": "Συντελεστές",
        "pasteTooltip": "Επικόλληση",
        "dictateTooltip": "Υπαγόρευση",
        "profileBrandHint": "Μάρκα…",
        "profileHintCity": "Πόλη",
        "tooltipDelete": "Διαγραφή",
        "tooltipEdit": "Επεξεργασία",
        "tooltipPostpone": "Αναβολή",
        "changePhotoLabel": "Αλλαγή",
        "timeLabelShort": "Ώρα",
        "dateLabelShort": "Ημερομηνία",
        "photoLabel": "Φωτογραφία",
    },
    "bg": {
        "styleFilled": "Класически правоъгълник",
        "legendLabel": "Горе в списъка",
        "categoriesHint": "Горе в списъка: магазини с име. Във формуляра именуваш магазина само при добавяне.",
        "tooltipDetails": "Подробности",
        "aboutCreator": "Автор",
        "aboutPrivacy": "Поверителност",
        "aboutLicense": "Лиценз",
        "aboutCredits": "Заслуги",
        "pasteTooltip": "Постави",
        "dictateTooltip": "Диктувай",
        "profileBrandHint": "Марка…",
        "profileHintCity": "Град",
        "tooltipDelete": "Изтрий",
        "tooltipEdit": "Редактирай",
        "tooltipPostpone": "Отложи",
        "changePhotoLabel": "Смени",
        "timeLabelShort": "Час",
        "dateLabelShort": "Дата",
        "photoLabel": "Снимка",
    },
    "uk": {
        "styleFilled": "Класичний прямокутник",
        "legendLabel": "Вгорі списку",
        "categoriesHint": "Вгорі списку: магазини з назвою. У формі називаєш магазин лише під час додавання.",
        "tooltipDetails": "Подробиці",
        "aboutCreator": "Автор",
        "aboutPrivacy": "Конфіденційність",
        "aboutLicense": "Ліцензія",
        "aboutCredits": "Автори",
        "pasteTooltip": "Вставити",
        "dictateTooltip": "Диктувати",
        "profileBrandHint": "Бренд…",
        "profileHintCity": "Місто",
        "tooltipDelete": "Видалити",
        "tooltipEdit": "Редагувати",
        "tooltipPostpone": "Відкласти",
        "changePhotoLabel": "Змінити",
        "timeLabelShort": "Час",
        "dateLabelShort": "Дата",
        "photoLabel": "Фото",
    },
    "ru": {
        "styleFilled": "Классический прямоугольник",
        "legendLabel": "Вверху списка",
        "categoriesHint": "Вверху списка: магазины с названием. В форме магазин указываешь только при добавлении.",
        "tooltipDetails": "Подробности",
        "aboutCreator": "Автор",
        "aboutPrivacy": "Конфиденциальность",
        "aboutLicense": "Лицензия",
        "aboutCredits": "Авторы",
        "pasteTooltip": "Вставить",
        "dictateTooltip": "Диктовать",
        "profileBrandHint": "Бренд…",
        "profileHintCity": "Город",
        "tooltipDelete": "Удалить",
        "tooltipEdit": "Изменить",
        "tooltipPostpone": "Отложить",
        "changePhotoLabel": "Сменить",
        "timeLabelShort": "Время",
        "dateLabelShort": "Дата",
        "photoLabel": "Фото",
    },
    "ja": {
        "styleFilled": "標準の四角",
        "legendLabel": "リスト上部",
        "categoriesHint": "リスト上部に店名付きのマーク。フォームでは追加するときだけ店名を付けます。",
        "tooltipDetails": "詳細",
        "aboutCreator": "作者",
        "aboutPrivacy": "プライバシー",
        "aboutLicense": "ライセンス",
        "aboutCredits": "クレジット",
        "pasteTooltip": "貼り付け",
        "dictateTooltip": "音声入力",
        "profileBrandHint": "ブランド…",
        "profileHintCity": "市区町村",
        "tooltipDelete": "削除",
        "tooltipEdit": "編集",
        "tooltipPostpone": "延期",
        "changePhotoLabel": "変更",
        "timeLabelShort": "時刻",
        "dateLabelShort": "日付",
        "photoLabel": "写真",
    },
    "ko": {
        "styleFilled": "기본 사각형",
        "legendLabel": "목록 위",
        "categoriesHint": "목록 위에 가게 이름 표시. 폼에서는 추가할 때만 가게 이름을 적습니다.",
        "tooltipDetails": "자세히",
        "aboutCreator": "제작자",
        "aboutPrivacy": "개인정보",
        "aboutLicense": "라이선스",
        "aboutCredits": "크레딧",
        "pasteTooltip": "붙여넣기",
        "dictateTooltip": "받아쓰기",
        "profileBrandHint": "브랜드…",
        "profileHintCity": "도시",
        "tooltipDelete": "삭제",
        "tooltipEdit": "수정",
        "tooltipPostpone": "미루기",
        "changePhotoLabel": "바꾸기",
        "timeLabelShort": "시간",
        "dateLabelShort": "날짜",
        "photoLabel": "사진",
    },
    "zh": {
        "styleFilled": "经典方块",
        "legendLabel": "清单顶部",
        "categoriesHint": "清单顶部显示带店名的标记。表单里只在添加时填写店名。",
        "tooltipDetails": "详情",
        "aboutCreator": "作者",
        "aboutPrivacy": "隐私",
        "aboutLicense": "许可",
        "aboutCredits": "鸣谢",
        "pasteTooltip": "粘贴",
        "dictateTooltip": "语音输入",
        "profileBrandHint": "品牌…",
        "profileHintCity": "城市",
        "tooltipDelete": "删除",
        "tooltipEdit": "编辑",
        "tooltipPostpone": "推迟",
        "changePhotoLabel": "更换",
        "timeLabelShort": "时间",
        "dateLabelShort": "日期",
        "photoLabel": "照片",
    },
    "ar": {
        "styleFilled": "مستطيل تقليدي",
        "legendLabel": "أعلى القائمة",
        "categoriesHint": "أعلى القائمة: متاجر بأسمائها. في النموذج تسمّي المتجر عند الإضافة فقط.",
        "tooltipDetails": "التفاصيل",
        "aboutCreator": "المؤلف",
        "aboutPrivacy": "الخصوصية",
        "aboutLicense": "الترخيص",
        "aboutCredits": "الحقوق",
        "pasteTooltip": "لصق",
        "dictateTooltip": "إملاء",
        "profileBrandHint": "العلامة…",
        "profileHintCity": "المدينة",
        "tooltipDelete": "حذف",
        "tooltipEdit": "تعديل",
        "tooltipPostpone": "تأجيل",
        "changePhotoLabel": "تغيير",
        "timeLabelShort": "الوقت",
        "dateLabelShort": "التاريخ",
        "photoLabel": "صورة",
    },
    "he": {
        "styleFilled": "מלבן קלאסי",
        "legendLabel": "בראש הרשימה",
        "categoriesHint": "בראש הרשימה: חנויות עם שם. בטופס נותנים שם לחנות רק בהוספה.",
        "tooltipDetails": "פרטים",
        "aboutCreator": "יוצר",
        "aboutPrivacy": "פרטיות",
        "aboutLicense": "רישיון",
        "aboutCredits": "קרדיטים",
        "pasteTooltip": "הדבק",
        "dictateTooltip": "הכתבה",
        "profileBrandHint": "מותג…",
        "profileHintCity": "עיר",
        "tooltipDelete": "מחק",
        "tooltipEdit": "ערוך",
        "tooltipPostpone": "דחה",
        "changePhotoLabel": "החלף",
        "timeLabelShort": "שעה",
        "dateLabelShort": "תאריך",
        "photoLabel": "תמונה",
    },
    "th": {
        "styleFilled": "สี่เหลี่ยมคลาสสิก",
        "legendLabel": "ด้านบนรายการ",
        "categoriesHint": "ด้านบนรายการ: ร้านค้าพร้อมชื่อ ในแบบฟอร์มตั้งชื่อร้านตอนเพิ่มเท่านั้น",
        "tooltipDetails": "รายละเอียด",
        "aboutCreator": "ผู้สร้าง",
        "aboutPrivacy": "ความเป็นส่วนตัว",
        "aboutLicense": "สัญญาอนุญาต",
        "aboutCredits": "เครดิต",
        "pasteTooltip": "วาง",
        "dictateTooltip": "พูดใส่",
        "profileBrandHint": "แบรนด์…",
        "profileHintCity": "เมือง",
        "tooltipDelete": "ลบ",
        "tooltipEdit": "แก้ไข",
        "tooltipPostpone": "เลื่อน",
        "changePhotoLabel": "เปลี่ยน",
        "timeLabelShort": "เวลา",
        "dateLabelShort": "วันที่",
        "photoLabel": "รูป",
    },
    "hi": {
        "styleFilled": "क्लासिक आयत",
        "legendLabel": "सूची के ऊपर",
        "categoriesHint": "सूची के ऊपर: नाम वाली दुकानें। फ़ॉर्म में दुकान का नाम केवल जोड़ते समय लिखें।",
        "tooltipDetails": "विवरण",
        "aboutCreator": "निर्माता",
        "aboutPrivacy": "गोपनीयता",
        "aboutLicense": "लाइसेंस",
        "aboutCredits": "श्रेय",
        "pasteTooltip": "चिपकाएँ",
        "dictateTooltip": "बोलकर लिखें",
        "profileBrandHint": "ब्रांड…",
        "profileHintCity": "शहर",
        "tooltipDelete": "हटाएँ",
        "tooltipEdit": "संपादित करें",
        "tooltipPostpone": "स्थगित करें",
        "changePhotoLabel": "बदलें",
        "timeLabelShort": "समय",
        "dateLabelShort": "तारीख",
        "photoLabel": "फ़ोटो",
    },
    "id": {
        "styleFilled": "Persegi panjang klasik",
        "legendLabel": "Atas daftar",
        "categoriesHint": "Di atas daftar: toko beserta nama. Di formulir, beri nama toko hanya saat menambah.",
        "tooltipDetails": "Detail",
        "aboutCreator": "Pembuat",
        "aboutPrivacy": "Privasi",
        "aboutLicense": "Lisensi",
        "aboutCredits": "Kredit",
        "pasteTooltip": "Tempel",
        "dictateTooltip": "Dikte",
        "profileBrandHint": "Merek…",
        "profileHintCity": "Kota",
        "tooltipDelete": "Hapus",
        "tooltipEdit": "Edit",
        "tooltipPostpone": "Tunda",
        "changePhotoLabel": "Ubah",
        "timeLabelShort": "Waktu",
        "dateLabelShort": "Tanggal",
        "photoLabel": "Foto",
    },
    "ms": {
        "styleFilled": "Segi empat tepat klasik",
        "legendLabel": "Atas senarai",
        "categoriesHint": "Di atas senarai: kedai dengan nama. Dalam borang, namakan kedai hanya semasa menambah.",
        "tooltipDetails": "Butiran",
        "aboutCreator": "Pencipta",
        "aboutPrivacy": "Privasi",
        "aboutLicense": "Lesen",
        "aboutCredits": "Kredit",
        "pasteTooltip": "Tampal",
        "dictateTooltip": "Imlak",
        "profileBrandHint": "Jenama…",
        "profileHintCity": "Bandar",
        "tooltipDelete": "Padam",
        "tooltipEdit": "Sunting",
        "tooltipPostpone": "Tangguh",
        "changePhotoLabel": "Tukar",
        "timeLabelShort": "Masa",
        "dateLabelShort": "Tarikh",
        "photoLabel": "Foto",
    },
    "vi": {
        "styleFilled": "Hình chữ nhật cổ điển",
        "legendLabel": "Đầu danh sách",
        "categoriesHint": "Đầu danh sách: cửa hàng kèm tên. Trong biểu mẫu, đặt tên cửa hàng chỉ khi thêm.",
        "tooltipDetails": "Chi tiết",
        "aboutCreator": "Tác giả",
        "aboutPrivacy": "Quyền riêng tư",
        "aboutLicense": "Giấy phép",
        "aboutCredits": "Ghi công",
        "pasteTooltip": "Dán",
        "dictateTooltip": "Đọc chính tả",
        "profileBrandHint": "Thương hiệu…",
        "profileHintCity": "Thành phố",
        "tooltipDelete": "Xóa",
        "tooltipEdit": "Sửa",
        "tooltipPostpone": "Hoãn",
        "changePhotoLabel": "Đổi",
        "timeLabelShort": "Giờ",
        "dateLabelShort": "Ngày",
        "photoLabel": "Ảnh",
    },
    "ca": {
        "styleFilled": "Rectangle clàssic",
        "legendLabel": "A dalt de la llista",
        "categoriesHint": "A dalt de la llista: botigues amb nom. Al formulari, anomena la botiga només en afegir.",
        "tooltipDetails": "Detalls",
        "aboutCreator": "Creador",
        "aboutPrivacy": "Privadesa",
        "aboutLicense": "Llicència",
        "aboutCredits": "Crèdits",
        "pasteTooltip": "Enganxa",
        "dictateTooltip": "Dicta",
        "profileBrandHint": "Marca…",
        "profileHintCity": "Ciutat",
        "tooltipDelete": "Suprimeix",
        "tooltipEdit": "Edita",
        "tooltipPostpone": "Ajorna",
        "changePhotoLabel": "Canvia",
        "timeLabelShort": "Hora",
        "dateLabelShort": "Data",
        "photoLabel": "Foto",
    },
    "eu": {
        "styleFilled": "Laukizuzen klasikoa",
        "legendLabel": "Zerrendaren goian",
        "categoriesHint": "Zerrendaren goian: dendak izenarekin. Inprimakian denda gehitzean bakarrik izendatzen duzu.",
        "tooltipDetails": "Xehetasunak",
        "aboutCreator": "Sortzailea",
        "aboutPrivacy": "Pribatutasuna",
        "aboutLicense": "Lizentzia",
        "aboutCredits": "Kredituak",
        "pasteTooltip": "Itsatsi",
        "dictateTooltip": "Diktatu",
        "profileBrandHint": "Marka…",
        "profileHintCity": "Hiria",
        "tooltipDelete": "Ezabatu",
        "tooltipEdit": "Editatu",
        "tooltipPostpone": "Atzeratu",
        "changePhotoLabel": "Aldatu",
        "timeLabelShort": "Ordua",
        "dateLabelShort": "Data",
        "photoLabel": "Argazkia",
    },
    "gl": {
        "styleFilled": "Rectángulo clásico",
        "legendLabel": "Arriba da lista",
        "categoriesHint": "Arriba da lista: tendas co nome. No formulario nomeas a tenda só ao engadir.",
        "tooltipDetails": "Detalles",
        "aboutCreator": "Creador",
        "aboutPrivacy": "Privacidade",
        "aboutLicense": "Licenza",
        "aboutCredits": "Créditos",
        "pasteTooltip": "Pegar",
        "dictateTooltip": "Ditar",
        "profileBrandHint": "Marca…",
        "profileHintCity": "Cidade",
        "tooltipDelete": "Eliminar",
        "tooltipEdit": "Editar",
        "tooltipPostpone": "Aprazar",
        "changePhotoLabel": "Cambiar",
        "timeLabelShort": "Hora",
        "dateLabelShort": "Data",
        "photoLabel": "Foto",
    },
}

# Product keys: locale → value (skip loc if already good; we overwrite always for consistency)
PRODUCTS: dict[str, dict[str, str]] = {
    "prod_jus_dorange": {
        "de": "Orangensaft", "es": "Zumo de naranja", "it": "Succo d’arancia",
        "pt": "Sumo de laranja", "nl": "Sinaasappelsap", "pl": "Sok pomarańczowy",
        "cs": "Pomerančový džus", "sk": "Pomarančový džús", "sl": "Pomarančni sok",
        "hr": "Sok od naranče", "sr": "Сок од поморанџе", "ro": "Suc de portocale",
        "hu": "Narancslé", "tr": "Portakal suyu", "da": "Appelsinjuice",
        "sv": "Apelsinjuice", "nb": "Appelsinjuice", "fi": "Appelsiinimehu",
        "et": "Apelsinimahl", "lv": "Apelsīnu sula", "lt": "Apelsinų sultys",
        "el": "Χυμός πορτοκαλιού", "bg": "Портокалов сок", "uk": "Апельсиновий сік",
        "ru": "Апельсиновый сок", "ja": "オレンジジュース", "ko": "오렌지 주스",
        "zh": "橙汁", "ar": "عصير برتقال", "he": "מיץ תפוזים", "th": "น้ำส้ม",
        "hi": "संतरे का रस", "id": "Jus jeruk", "ms": "Jus oren", "vi": "Nước cam",
        "ca": "Suc de taronja", "eu": "Laranja zukua", "gl": "Zume de laranxa",
        "fr": "Jus d'orange",
    },
    "prod_miel_bio": {
        "de": "Bio-Honig", "es": "Miel ecológica", "it": "Miele bio",
        "pt": "Mel biológico", "nl": "Biologische honing", "pl": "Miód ekologiczny",
        "cs": "Bio med", "sk": "Bio med", "sl": "Eko med", "hr": "Eko med",
        "sr": "Органски мед", "ro": "Miere eco", "hu": "Bio méz", "tr": "Organik bal",
        "da": "Økologisk honning", "sv": "Ekologisk honung", "nb": "Økologisk honning",
        "fi": "Luomuhunaja", "et": "Mahemesi", "lv": "Bioloģiskais medus",
        "lt": "Ekologiškas medus", "el": "Βιολογικό μέλι", "bg": "Био мед",
        "uk": "Органічний мед", "ru": "Органический мёд", "ja": "オーガニックはちみつ",
        "ko": "유기농 꿀", "zh": "有机蜂蜜", "ar": "عسل عضوي", "he": "דבש אורגני",
        "th": "น้ำผึ้งออร์แกนิก", "hi": "जैविक शहद", "id": "Madu organik",
        "ms": "Madu organik", "vi": "Mật ong hữu cơ", "ca": "Mel ecològica",
        "eu": "Eztia ekologikoa", "gl": "Mel ecolóxico",
    },
    "prod_apero_dinatoire": {
        "de": "Abendessensnacks", "es": "Aperitivos de cena", "it": "Stuzzichini da cena",
        "pt": "Petiscos de jantar", "nl": "Dinerhapjes", "pl": "Przekąski na kolację",
        "cs": "Občerstvení na večeři", "sk": "Občerstvenie na večeru",
        "sl": "Prigrizki za večerjo", "hr": "Grickalice za večeru",
        "sr": "Закуске за вечеру", "ro": "Aperitive de cină", "hu": "Vacsoraparti harapnivalók",
        "tr": "Akşam yemeği atıştırmalıkları", "da": "Middagssnacks", "sv": "Middagssnacks",
        "nb": "Middagssnacks", "fi": "Iltapalat", "et": "Õhtusöögi suupisted",
        "lv": "Vakariņu uzkodas", "lt": "Vakarienės užkandžiai", "el": "Σνακ για δείπνο",
        "bg": "Предястия за вечеря", "uk": "Закуски до вечері", "ru": "Закуски к ужину",
        "ja": "ホームパーティーのつまみ", "ko": "저녁 파티 안주", "zh": "正餐小食",
        "ar": "مقبلات العشاء", "he": "נשנושי ערב", "th": "ของว่างปาร์ตี้เย็น",
        "hi": "डिनर पार्टी स्नैक्स", "id": "Camilan makan malam",
        "ms": "Snek majlis makan malam", "vi": "Đồ nhắm bữa tối",
        "ca": "Aperitius de sopar", "eu": "Afari aperitiboak", "gl": "Aperitivos de cea",
        "fr": "Apéro dînatoire",
    },
    "prod_stylo": {
        "de": "Kugelschreiber", "es": "Bolígrafo", "it": "Penna", "pt": "Caneta",
        "nl": "Pen", "pl": "Długopis", "cs": "Propiska", "sk": "Pero", "sl": "Kemični svinčnik",
        "hr": "Kemijska olovka", "sr": "Хемијска оловка", "ro": "Pix", "hu": "Toll",
        "tr": "Kalem", "da": "Kuglepen", "sv": "Penna", "nb": "Penn", "fi": "Kuulakärkikynä",
        "et": "Pastakas", "lv": "Pildspalva", "lt": "Tušinukas", "el": "Στυλό",
        "bg": "Химикалка", "uk": "Ручка", "ru": "Ручка", "ja": "ペン", "ko": "펜",
        "zh": "笔", "ar": "قلم", "he": "עט", "th": "ปากกา", "hi": "पेन", "id": "Pulpen",
        "ms": "Pen", "vi": "Bút", "ca": "Bolígraf", "eu": "Bolaluma", "gl": "Bolígrafo",
    },
    "prod_tabac": {
        "hi": "तम्बाकू", "ar": "تبغ", "ja": "たばこ", "ko": "담배", "th": "ยาสูบ",
        "sr": "Дуван", "bg": "тютюн",
    },
}

EXTRA: dict[str, dict[str, str]] = {
    "ko": {
        "prod_miel_du_producteur": "생산자 꿀",
        "prod_anneaux": "링",
        "prod_jus_de_fruit_naturel": "천연 과일 주스",
        "prod_carrelage": "타일",
        "prod_fromage_blanc": "프로마주 블랑",
        "prod_steak_de_soja": "콩고기 스테이크",
    },
    "zh": {
        "prod_allumettes": "火柴",
        "prod_miel_bio": "有机蜂蜜",
    },
    "th": {
        "prod_lait_en_poudre": "นมผง",
        "prod_confiture_dabricot": "แยมแอปริคอต",
        "prod_confiture_de_fraises": "แยมสตรอว์เบอร์รี",
        "prod_confiture_maison": "แยมโฮมเมด",
        "prod_herbes_de_provence": "สมุนไพรโปรวองซ์",
        "prod_fromage_blanc": "ฟรอมัจบล็อง",
        "prod_steak_de_soja": "สเต๊กถั่วเหลือง",
    },
    "ru": {
        "prod_lait_en_poudre": "Сухое молоко",
        "prod_fromage_blanc": "Творожный сыр",
        "prod_steak_de_soja": "Соевый стейк",
        "prod_vache_qui_rit": "Весёлая коровка",
    },
    "uk": {
        "prod_miel_du_producteur": "Мед від виробника",
        "prod_herbes_de_provence": "Прованські трави",
        "prod_fromage_blanc": "Сир фромаж блан",
        "prod_steak_de_soja": "Соєвий стейк",
        "prod_jus_dorange": "Апельсиновий сік",
    },
    "ar": {
        "prod_adoucissant": "منعم أقمشة",
        "prod_fromage_blanc": "جبن أبيض طري",
        "prod_steak_de_soja": "ستيك الصويا",
    },
    "he": {
        "prod_fromage_blanc": "פרומאז' בלאן",
        "prod_steak_de_soja": "סטייק סויה",
        "prod_miel_bio": "דבש אורגני",
    },
    "el": {
        "prod_fromage_blanc": "Λευκό τυρί στραγγιστό",
        "prod_jus_de_fruit_naturel": "Φυσικός χυμός φρούτων",
        "prod_steak_de_soja": "Σογιστέικ",
        "prod_eau_de_toilette": "Κολόνια",
    },
    "ja": {
        "prod_fromage_blanc": "フロマージュ・ブラン",
        "prod_steak_de_soja": "大豆ステーキ",
        "prod_tabac": "たばこ",
    },
    "en": {
        "quickAddExampleHint": "Ex: Apple | List Tesco: Apple, milk",
        "prod_jus_dorange": "Orange juice",
    },
}


def replace_value(text: str, key: str, new_value: str) -> tuple[str, bool]:
    escaped = json.dumps(new_value, ensure_ascii=False)[1:-1]
    pattern = re.compile(rf'("{re.escape(key)}":\s*")(?:\\.|[^"\\])*(")')
    found = False

    def repl(m: re.Match[str]) -> str:
        nonlocal found
        found = True
        return m.group(1) + escaped + m.group(2)

    new_text = pattern.sub(repl, text, count=1)
    return new_text, found


def main() -> None:
    total = 0
    missing = 0
    for arb in sorted(ROOT.glob("app_*.arb")):
        loc = arb.stem.split("_", 1)[1]
        text = arb.read_text(encoding="utf-8")
        orig = text
        updates: dict[str, str] = {}
        updates.update(UI.get(loc, {}))
        for key, per_loc in PRODUCTS.items():
            if loc in per_loc:
                updates[key] = per_loc[loc]
        updates.update(EXTRA.get(loc, {}))
        for key, value in updates.items():
            text, ok = replace_value(text, key, value)
            if ok:
                total += 1
            else:
                missing += 1
                print(f"  missing {loc}.{key}")
        if text != orig:
            arb.write_text(text, encoding="utf-8")
            print(f"{loc}: wrote")
    print(f"replacements attempted lines: {total}  missing: {missing}")


if __name__ == "__main__":
    main()
