# English labels for prod_* still identical to French (loanwords kept).
EN_PROD = {
    "prod_adoucissant": "Fabric softener",
    "prod_agneau": "Lamb",
    "prod_agrafeuse": "Stapler",
    "prod_agraves": "Agaves",
    "prod_algues_nori": "Nori seaweed",
    "prod_algues_wakame": "Wakame seaweed",
    "prod_allumettes": "Matches",
    "prod_ampoule": "Light bulb",
    "prod_anchois": "Anchovies",
    "prod_andouille": "Andouille sausage",
    "prod_aneth": "Dill",
    "prod_anneaux": "Rings",
    "prod_apero_dinatoire": "Dinner party snacks",
    "prod_baies_de_goji": "Goji berries",
    "prod_bain_de_bouche": "Mouthwash",
    "prod_bambou": "Bamboo",
    "prod_batterie": "Battery",
    "prod_biberon": "Baby bottle",
    "prod_biscottes": "Rusks",
    "prod_biscuits_bio": "Organic biscuits",
    "prod_blanquette": "Blanquette",
    "prod_bloc_de_foie_gras": "Foie gras block",
    "prod_boissons": "Drinks",
    "prod_boudin_noir": "Black pudding",
    "prod_boulangerie": "Bakery",
    "prod_boulettes": "Meatballs",
    "prod_boulgour": "Bulgur",
    "prod_boulons": "Bolts",
    "prod_briquet": "Lighter",
    "prod_brochettes": "Skewers",
    "prod_bulots": "Whelks",
    "prod_burin": "Chisel",
    "prod_canard": "Duck",
    "prod_capres": "Capers",
    "prod_caprice_des_dieux": "Caprice des Dieux",
    "prod_carnet": "Notebook",
    "prod_carrelage": "Tiles",
    "prod_carte_recharge": "Top-up card",
    "prod_cartes_postales": "Postcards",
    "prod_cartouche_filtre": "Filter cartridge",
    "prod_caviar_daubergine": "Baba ganoush",
    "prod_champignons": "Mushrooms",
    "prod_champignons_noirs": "Wood ear mushrooms",
    "prod_champignons_shiitake": "Shiitake mushrooms",
    "prod_chantilly": "Whipped cream",
    "prod_charcuterie_artisanale": "Artisan cold cuts",
    "prod_chauffage": "Heating",
    "prod_chevilles": "Wall plugs",
    "prod_chipolatas": "Chipolatas",
    "prod_chocolat_au_lait": "Milk chocolate",
    "prod_chocolat_bio": "Organic chocolate",
    "prod_chocolat_blanc": "White chocolate",
    "prod_chocolat_noir": "Dark chocolate",
    "prod_chou_chinois": "Napa cabbage",
    "prod_choucroute": "Sauerkraut",
    "prod_cidre": "Cider",
    "prod_cigares": "Cigars",
    "prod_cigarettes": "Cigarettes",
    "prod_citron": "Lemon",
    "prod_citronnelle": "Lemongrass",
    "prod_clous": "Nails",
    "prod_colle": "Glue",
    "prod_colle_carrelage": "Tile adhesive",
    "prod_collier": "Necklace",
    "prod_compote_bio": "Organic fruit purée",
    "prod_confiture_bio": "Organic jam",
    "prod_confiture_dabricot": "Apricot jam",
    "prod_confiture_de_fraises": "Strawberry jam",
    "prod_confiture_maison": "Homemade jam",
    "prod_coquillages": "Shellfish",
    "prod_cordon_bleu": "Cordon bleu",
    "prod_cotons": "Cotton pads",
    "prod_couches": "Nappies",
    "prod_coulis": "Coulis",
    "prod_coupe": "Cup",
    "prod_crackers_sans_sel": "Unsalted crackers",
    "prod_cremant": "Crémant",
    "prod_crepes": "Crêpes",
    "prod_crochet": "Hook",
    "prod_curry_rouge": "Red curry",
    "prod_curry_vert": "Green curry",
    "prod_cutter": "Utility knife",
    "prod_digestif": "Digestif",
    "prod_douille": "Socket",
    "prod_eau_de_toilette": "Eau de toilette",
    "prod_endives": "Chicory",
    "prod_enduit": "Filler",
    "prod_engrais": "Fertilizer",
    "prod_enveloppes": "Envelopes",
    "prod_escalope": "Escalope",
    "prod_faisselle": "Faisselle",
    "prod_feuilles_de_riz": "Rice paper",
    "prod_fil_dentaire": "Dental floss",
    "prod_filet": "Fillet",
    "prod_fleurs": "Flowers",
    "prod_fondue_savoyarde": "Savoyard fondue",
    "prod_fromage_blanc": "Fromage blanc",
    "prod_fromage_fermier": "Farmhouse cheese",
    "prod_fruits_bio": "Organic fruit",
    "prod_fruits_de_mer": "Seafood",
    "prod_galettes_de_riz": "Rice cakes",
    "prod_gel_douche": "Shower gel",
    "prod_gibier": "Game meat",
    "prod_gommage": "Scrub",
    "prod_graines": "Seeds",
    "prod_graines_de_chia": "Chia seeds",
    "prod_graines_de_lin": "Flax seeds",
    "prod_grattage": "Scratch card",
    "prod_haricots": "Beans",
    "prod_herbes": "Herbs",
    "prod_homard": "Lobster",
    "prod_huile_dolive_bio": "Organic olive oil",
    "prod_infusion": "Herbal tea",
    "prod_interrupteur": "Light switch",
    "prod_jambon_cru": "Cured ham",
    "prod_javel": "Bleach",
    "prod_joint": "Seal",
    "prod_joint_carrelage": "Tile grout",
    "prod_joint_torique": "O-ring",
    "prod_journal": "Newspaper",
    "prod_jus": "Juice",
    "prod_jus_de_fruit_naturel": "Natural fruit juice",
    "prod_jus_de_raisin": "Grape juice",
    "prod_jus_dorange": "Orange juice",
    "prod_laine_de_verre": "Glass wool",
    "prod_lait_bio": "Organic milk",
    "prod_lait_de_coco": "Coconut milk",
    "prod_lait_en_poudre": "Powdered milk",
    "prod_lambris": "Panelling",
    "prod_lame_de_scie": "Saw blade",
    "prod_langoustines": "Langoustines",
    "prod_lapin": "Rabbit",
    "prod_lard": "Bacon fat",
    "prod_lasagnes": "Lasagne",
    "prod_lasure": "Wood stain",
    "prod_lentilles_corail": "Red lentils",
    "prod_lime": "File",
    "prod_limette": "Lime",
    "prod_lingettes": "Wipes",
    "prod_liquide_vaisselle": "Washing-up liquid",
    "prod_loto": "Lottery",
    "prod_madeleines": "Madeleines",
    "prod_magazine": "Magazine",
    "prod_marteau": "Hammer",
    "prod_masque": "Face mask",
    "prod_masse": "Sledgehammer",
    "prod_mastic": "Putty",
    "prod_menthe": "Mint",
    "prod_miel_bio": "Organic honey",
    "prod_miel_du_producteur": "Producer honey",
    "prod_mouchoirs": "Tissues",
    "prod_muesli_barres": "Muesli bars",
    "prod_muesli_bio": "Organic muesli",
    "prod_nectar": "Nectar",
    "prod_nems": "Spring rolls",
    "prod_nettoyant_sol": "Floor cleaner",
    "prod_niveau": "Spirit level",
    "prod_noix_de_cajou": "Cashew nuts",
    "prod_nouilles": "Noodles",
    "prod_pain_bio": "Organic bread",
    "prod_pain_de_viande": "Meatloaf",
    "prod_palets_bretons": "Breton butter biscuits",
    "prod_panneau_osb": "OSB board",
    "prod_papier_de_verre": "Sandpaper",
    "prod_parfum": "Perfume",
    "prod_parquet": "Parquet",
    "prod_pastilles": "Lozenges",
    "prod_pate": "Pâté",
    "prod_pate_carbonara": "Carbonara pasta",
    "prod_pates_carbonara": "Carbonara pasta",
    "prod_paumelle": "Hinge",
    "prod_peinture": "Paint",
    "prod_perceuse": "Drill",
    "prod_petit_dej": "Breakfast",
    "prod_petit_dejeuner": "Breakfast",
    "prod_petit_suisse": "Petit-suisse",
    "prod_pile": "Battery",
    "prod_pince": "Pliers",
    "prod_pinceau": "Paintbrush",
    "prod_pizza_maison": "Homemade pizza",
    "prod_planche": "Board",
    "prod_plantes": "Plants",
    "prod_plantes_aromatiques": "Aromatic herbs",
    "prod_poisson": "Fish",
    "prod_poisson_frais": "Fresh fish",
    "prod_porc": "Pork",
    "prod_pot": "Jar",
    "prod_pot_au_feu": "Pot-au-feu",
    "prod_potage": "Thick soup",
    "prod_poudre": "Powder",
    "prod_poulet_fermier": "Free-range chicken",
    "prod_pousse_de_bambou": "Bamboo shoots",
    "prod_pousses_de_soja": "Bean sprouts",
    "prod_presse": "Press",
    "prod_prise": "Socket",
    "prod_produit_vitres": "Glass cleaner",
    "prod_produits_laitiers": "Dairy",
    "prod_pruneaux": "Prunes",
    "prod_pull": "Jumper",
    "prod_punaises": "Drawing pins",
    "prod_puree_d": "Mash",
    "prod_quinoa_bio": "Organic quinoa",
    "prod_raccord": "Fitting",
    "prod_radiateur": "Radiator",
    "prod_raviolis_chinois": "Chinese dumplings",
    "prod_recharge_briquet": "Lighter refill",
    "prod_rhum": "Rum",
    "prod_rideau": "Curtain",
    "prod_rillettes": "Rillettes",
    "prod_riz_basmati": "Basmati rice",
    "prod_riz_complet": "Brown rice",
    "prod_riz_glutineux": "Sticky rice",
    "prod_robineterie": "Taps",
    "prod_rouleau": "Roller",
    "prod_ruban_isolant": "Electrical tape",
    "prod_sac_poubelle": "Bin bags",
    "prod_salade_composee": "Mixed salad",
    "prod_samoussas": "Samosas",
    "prod_sauce": "Sauce",
    "prod_sauce_fish": "Fish sauce",
    "prod_sauce_oyster": "Oyster sauce",
    "prod_saucisson_sec": "Dry sausage",
    "prod_scie": "Saw",
    "prod_semoule": "Semolina",
    "prod_serrure": "Lock",
    "prod_sirop": "Syrup",
    "prod_soda_light": "Diet soda",
    "prod_soda_sans_alcool": "Soft drink",
    "prod_sorbet": "Sorbet",
    "prod_soupe": "Soup",
    "prod_soupe_miso": "Miso soup",
    "prod_soupe_pho": "Pho",
    "prod_soupe_potage": "Soup",
    "prod_steak_de_soja": "Soy steak",
    "prod_tabac": "Tobacco",
    "prod_tablette": "Tablet",
    "prod_tampons": "Tampons",
    "prod_tasseau": "Batten",
    "prod_terreau": "Potting soil",
    "prod_terrine": "Terrine",
    "prod_timbre": "Stamp",
    "prod_tisane": "Herbal tea",
    "prod_tofu_bio": "Organic tofu",
    "prod_tofu_soyeux": "Silken tofu",
    "prod_tournevis": "Screwdriver",
    "prod_tringle": "Curtain rod",
    "prod_tuyau": "Hose",
    "prod_vache_qui_rit": "The Laughing Cow",
    "prod_veau": "Veal",
    "prod_vermicelles": "Vermicelli",
    "prod_vermicelles_de_riz": "Rice vermicelli",
    "prod_vernis": "Varnish",
    "prod_verrue": "Wart treatment",
    "prod_viande": "Meat",
    "prod_viande_hachee_2": "Minced meat",
    "prod_viandes_poissons": "Meat & fish",
    "prod_viennoiseries": "Pastries",
    "prod_vinaigre_de_riz": "Rice vinegar",
    "prod_vinaigrette": "Vinaigrette",
    "prod_vis": "Screws",
    "prod_visseuse": "Screw gun",
    "prod_volaille": "Poultry",
    "prod_zeste": "Zest",
    "prod_chewing_gum": "Chewing gum",
    "prod_seitan_bio": "Organic seitan",
    "prod_razor": "Razor",
}
