# -*- coding: utf-8 -*-
"""Catalogues et repas régionaux : noms FR canoniques + traductions natives."""
from __future__ import annotations

# Traductions d'un produit : "fr" obligatoire, "en" recommandé.
# Locales absentes → anglais, puis français.

PRODUCTS: list[dict[str, str]] = [
    # —— Japon ——
    {"fr": "Riz rond", "en": "Short-grain rice", "ja": "白米", "ko": "쌀", "zh": "圆粒米", "ru": "Круглый рис", "ar": "أرز قصير الحبة", "de": "Rundkornreis", "es": "Arroz redondo", "it": "Riso tondo", "pt": "Arroz redondo", "hi": "छोटे दाने वाला चावल", "th": "ข้าวเมล็ดสั้น", "vi": "Gạo hạt tròn", "tr": "Yuvarlak pirinç", "el": "Στρογγυλό ρύζι", "he": "אורז עגול", "uk": "Круглий рис", "pl": "Ryż okrągłoziarnisty", "id": "Beras bulat", "nl": "Rondkorrelrijst", "sv": "Rundkornigt ris"},
    {"fr": "Nouilles ramen", "en": "Ramen noodles", "ja": "ラーメン麺", "ko": "라멘 면", "zh": "拉面", "ru": "Лапша рамен", "ar": "نودلز رامن", "de": "Ramen-Nudeln", "es": "Fideos ramen", "it": "Noodles ramen", "pt": "Macarrão ramen", "hi": "रामेन नूडल्स", "th": "บะหมี่ราเมน", "vi": "Mì ramen", "tr": "Ramen eriştesi", "he": "נודלס ראמן", "uk": "Локшина рамен", "pl": "Makaron ramen", "id": "Mie ramen"},
    {"fr": "Gyoza", "en": "Gyoza", "ja": "餃子", "ko": "교자", "zh": "煎饺", "ru": "Гёдза", "ar": "غيوزا", "de": "Gyoza", "es": "Gyoza", "hi": "ग्योजा", "th": "เกี๊ยวซ่า", "vi": "Há cảo gyoza", "tr": "Gyoza", "he": "גיוזה", "uk": "Гедза", "id": "Gyoza"},
    {"fr": "Feuilles de gyoza", "en": "Gyoza wrappers", "ja": "餃子の皮", "ko": "만두피", "zh": "饺子皮", "ru": "Тесто для гёдза", "ar": "عجين الغيوزا", "de": "Gyoza-Teigblätter", "es": "Obleas para gyoza", "it": "Sfoglie per gyoza", "pt": "Massa para gyoza", "hi": "ग्योजा रैपर", "th": "แผ่นเกี๊ยวซ่า", "vi": "Vỏ há cảo", "he": "בצק לגיוזה"},
    {"fr": "Onigiri", "en": "Onigiri", "ja": "おにぎり", "ko": "오니기리", "zh": "饭团", "ru": "Онигири", "ar": "أونيغيري", "de": "Onigiri", "es": "Onigiri", "hi": "ओनिगिरी", "th": "โอนิกิริ", "vi": "Cơm nắm", "tr": "Onigiri", "he": "אוניגירי", "uk": "Онігірі", "id": "Onigiri"},
    {"fr": "Yakitori", "en": "Yakitori", "ja": "焼き鳥", "ko": "야키토리", "zh": "烤鸡肉串", "ru": "Якитори", "ar": "ياكيتوري", "de": "Yakitori", "es": "Yakitori", "hi": "याकितोरी", "th": "ยากิโทริ", "vi": "Xiên gà nướng", "he": "יאקיטורי"},
    {"fr": "Miso", "en": "Miso", "ja": "味噌", "ko": "미소", "zh": "味噌", "ru": "Мисо", "ar": "ميسو", "de": "Miso", "es": "Miso", "hi": "मिसो", "th": "มิโซะ", "vi": "Miso", "tr": "Miso", "he": "מיסו", "uk": "Місо", "id": "Miso"},
    {"fr": "Natto", "en": "Natto", "ja": "納豆", "ko": "낫토", "zh": "纳豆", "ru": "Натто", "ar": "ناتو", "de": "Natto", "es": "Natto", "hi": "नट्टो", "th": "นัตโตะ", "vi": "Natto", "he": "נאטו"},
    {"fr": "Kombu", "en": "Kombu", "ja": "昆布", "ko": "다시마", "zh": "昆布", "ru": "Комбу", "ar": "كومبو", "de": "Kombu", "es": "Kombu", "hi": "कोम्बु", "th": "คอมบุ", "vi": "Tảo kombu", "he": "קומבו"},
    {"fr": "Katsuobushi", "en": "Katsuobushi", "ja": "鰹節", "ko": "가쓰오부시", "zh": "木鱼花", "ru": "Кацуобуси", "ar": "كاتسووبوشي", "de": "Katsuobushi", "es": "Katsuobushi", "hi": "कात्सुओबुशी", "th": "คัตสึโอบูชิ", "vi": "Cá ngừ bào", "he": "קצואובושי"},
    {"fr": "Udon", "en": "Udon", "ja": "うどん", "ko": "우동", "zh": "乌冬面", "ru": "Удон", "ar": "أودون", "de": "Udon", "es": "Udon", "hi": "उडोन", "th": "อูด้ง", "vi": "Mì udon", "he": "אודון", "id": "Udon"},
    {"fr": "Soba", "en": "Soba", "ja": "そば", "ko": "소바", "zh": "荞麦面", "ru": "Соба", "ar": "سوبا", "de": "Soba", "es": "Soba", "hi": "सोबा", "th": "โซบะ", "vi": "Mì soba", "he": "סובה"},
    {"fr": "Furikake", "en": "Furikake", "ja": "ふりかけ", "ko": "후리카케", "zh": "拌饭料", "ru": "Фурикакэ", "ar": "فوريكاكي", "de": "Furikake", "es": "Furikake", "hi": "फुरिकाके", "th": "ฟุริคาเคะ", "vi": "Furikake", "he": "פוריקקה"},
    {"fr": "Umeboshi", "en": "Umeboshi", "ja": "梅干し", "ko": "우메보시", "zh": "梅干", "ru": "Умэбоси", "ar": "أوميبوشي", "de": "Umeboshi", "es": "Umeboshi", "hi": "उमेबोशी", "th": "อุเมะโบชิ", "vi": "Mơ muối", "he": "אומבושי"},
    {"fr": "Daikon", "en": "Daikon", "ja": "大根", "ko": "다이콘", "zh": "白萝卜", "ru": "Дайкон", "ar": "دايكون", "de": "Daikon", "es": "Daikon", "hi": "डाइकन", "th": "ไดคอน", "vi": "Củ cải trắng", "he": "דייקון", "pl": "Daikon"},
    {"fr": "Shiso", "en": "Shiso", "ja": "しそ", "ko": "시소", "zh": "紫苏", "ru": "Шисо", "ar": "شيسو", "de": "Shiso", "es": "Shiso", "hi": "शिसो", "th": "ชิโซะ", "vi": "Tía tô Nhật", "he": "שיסו"},
    {"fr": "Matcha", "en": "Matcha", "ja": "抹茶", "ko": "말차", "zh": "抹茶", "ru": "Матча", "ar": "ماتشا", "de": "Matcha", "es": "Matcha", "hi": "माचा", "th": "มัทฉะ", "vi": "Matcha", "tr": "Matcha", "he": "מאצ'ה", "id": "Matcha"},
    {"fr": "Mochi", "en": "Mochi", "ja": "餅", "ko": "모찌", "zh": "麻糬", "ru": "Моти", "ar": "موتشي", "de": "Mochi", "es": "Mochi", "hi": "मोची", "th": "โมจิ", "vi": "Bánh mochi", "he": "מוצ'י", "id": "Mochi"},
    {"fr": "Ponzu", "en": "Ponzu", "ja": "ポン酢", "ko": "폰즈", "zh": "柚子醋", "ru": "Пондзу", "ar": "بونزو", "de": "Ponzu", "es": "Ponzu", "hi": "पोंजु", "th": "พอนซึ", "vi": "Sốt ponzu", "he": "פונזו"},
    {"fr": "Sashimi", "en": "Sashimi", "ja": "刺身", "ko": "사시미", "zh": "生鱼片", "ru": "Сашими", "ar": "ساشيمي", "de": "Sashimi", "es": "Sashimi", "hi": "साशिमी", "th": "ซาชิมิ", "vi": "Sashimi", "he": "סשימי"},
    {"fr": "Ciboule", "en": "Spring onion", "ja": "ねぎ", "ko": "대파", "zh": "葱", "ru": "Зелёный лук", "ar": "بصل أخضر", "de": "Frühlingszwiebeln", "es": "Cebolleta", "it": "Cipollotto", "pt": "Cebolinha", "hi": "हरा प्याज", "th": "ต้นหอม", "vi": "Hành lá", "tr": "Taze soğan", "el": "Φρέσκο κρεμμύδι", "he": "בצל ירוק", "uk": "Зелена цибуля", "pl": "Szczypiorek", "id": "Daun bawang", "nl": "Lente-ui", "sv": "Salladslök"},
    {"fr": "Panko", "en": "Panko", "ja": "パン粉", "ko": "빵가루", "zh": "パン粉", "ru": "Панко", "ar": "بانكو", "de": "Panko", "es": "Panko", "hi": "पैंको", "th": "ปังโกะ", "vi": "Bột chiên panko", "he": "פנקו"},
    {"fr": "Sauce teriyaki", "en": "Teriyaki sauce", "ja": "照り焼きのたれ", "ko": "데리야키 소스", "zh": "照烧酱", "ru": "Соус терияки", "ar": "صلصة ترياكي", "de": "Teriyaki-Sauce", "es": "Salsa teriyaki", "it": "Salsa teriyaki", "pt": "Molho teriyaki", "hi": "टेरियाकी सॉस", "th": "ซอสเทริยากิ", "vi": "Sốt teriyaki", "he": "רוטב טריאקי"},
    {"fr": "Sauce tonkatsu", "en": "Tonkatsu sauce", "ja": "とんかつソース", "ko": "돈카츠 소스", "zh": "猪排酱", "ru": "Соус тонкэцу", "ar": "صلصة تونكاتسو", "de": "Tonkatsu-Sauce", "es": "Salsa tonkatsu", "hi": "टोनकात्सु सॉस", "th": "ซอสทงคัตสึ", "vi": "Sốt tonkatsu", "he": "רוטב טונקטסו"},
    {"fr": "Shiitake", "en": "Shiitake", "ja": "しいたけ", "ko": "표고버섯", "zh": "香菇", "ru": "Шиитаке", "ar": "شيتاكي", "de": "Shiitake", "es": "Shiitake", "hi": "शीताके", "th": "เห็ดชิทาเกะ", "vi": "Nấm shiitake", "he": "שיטאקה", "id": "Jamur shiitake"},
    {"fr": "Enoki", "en": "Enoki", "ja": "えのき", "ko": "팽이버섯", "zh": "金针菇", "ru": "Эноки", "ar": "إنوكي", "de": "Enoki", "es": "Enoki", "hi": "एनोकी", "th": "เห็ดเอโนกิ", "vi": "Nấm kim châm", "he": "אנוקי"},
    {"fr": "Yuzu", "en": "Yuzu", "ja": "ゆず", "ko": "유자", "zh": "柚子", "ru": "Юдзу", "ar": "يوزو", "de": "Yuzu", "es": "Yuzu", "hi": "यूजु", "th": "ยูซุ", "vi": "Quả yuzu", "he": "יוזו"},
    {"fr": "Konjac", "en": "Konjac", "ja": "こんにゃく", "ko": "곤약", "zh": "魔芋", "ru": "Конняку", "ar": "كونجاك", "de": "Konjak", "es": "Konjac", "hi": "कोनजाक", "th": "คอนเนียกุ", "vi": "Konjac", "he": "קוניאק"},
    {"fr": "Thé sencha", "en": "Sencha tea", "ja": "煎茶", "ko": "센차", "zh": "煎茶", "ru": "Сентя", "ar": "شاي سنشا", "de": "Sencha-Tee", "es": "Té sencha", "hi": "सेंचा चाय", "th": "ชาเซนฉะ", "vi": "Trà sencha", "he": "תה סנצ'ה"},
    {"fr": "Shochu", "en": "Shochu", "ja": "焼酎", "ko": "소주 (일본)", "zh": "烧酒", "ru": "Сётю", "ar": "شوتشو", "de": "Shōchū", "es": "Shochu", "hi": "शोचू", "th": "โชชู", "vi": "Rượu shochu", "he": "שוצ'ו"},
    {"fr": "Kamaboko", "en": "Kamaboko", "ja": "かまぼこ", "ko": "가마보코", "zh": "鱼糕", "ru": "Камабоко", "ar": "كامابوكو", "de": "Kamaboko", "es": "Kamaboko", "hi": "कामाबोको", "th": "คามาโบโกะ", "vi": "Chả cá kamaboko", "he": "קמבוקו"},
    {"fr": "Takuan", "en": "Takuan", "ja": "たくあん", "ko": "단무지", "zh": "泽庵腌萝卜", "ru": "Такуан", "ar": "تاكوان", "de": "Takuan", "es": "Takuan", "hi": "ताकुआन", "th": "ทาควัน", "vi": "Củ cải muối", "he": "טקואן"},
    # —— Corée ——
    {"fr": "Bulgogi", "en": "Bulgogi", "ja": "プルコギ", "ko": "불고기", "zh": "烤肉（韩式）", "ru": "Пулькоги", "ar": "بولغوجي", "de": "Bulgogi", "es": "Bulgogi", "hi": "बुलगोगी", "th": "บูลโกกิ", "vi": "Bulgogi", "he": "בולגוגי"},
    {"fr": "Gochujang", "en": "Gochujang", "ja": "コチュジャン", "ko": "고추장", "zh": "韩式辣椒酱", "ru": "Кочхуджан", "ar": "غوتشوجانغ", "de": "Gochujang", "es": "Gochujang", "hi": "गोचुजांग", "th": "โกชูจัง", "vi": "Tương ớt gochujang", "he": "גוצ'וג'אנג"},
    {"fr": "Gochugaru", "en": "Gochugaru", "ja": "コチュガル", "ko": "고춧가루", "zh": "韩式辣椒粉", "ru": "Кочхугару", "ar": "غوتشوغارو", "de": "Gochugaru", "es": "Gochugaru", "hi": "गोचुगरु", "th": "โกชูการู", "vi": "Ớt bột Hàn", "he": "גוצ'וגארו"},
    {"fr": "Soju", "en": "Soju", "ja": "ソジュ", "ko": "소주", "zh": "烧酒（韩国）", "ru": "Соджу", "ar": "سوجو", "de": "Soju", "es": "Soju", "hi": "सोजू", "th": "โซจู", "vi": "Soju", "he": "סוג'ו"},
    {"fr": "Doenjang", "en": "Doenjang", "ja": "テンジャン", "ko": "된장", "zh": "大酱", "ru": "Твенджан", "ar": "دونجانغ", "de": "Doenjang", "es": "Doenjang", "hi": "दोएनजांग", "th": "เดนจัง", "vi": "Tương doenjang", "he": "דואנג'אנג"},
    {"fr": "Samgyeopsal", "en": "Samgyeopsal", "ja": "サムギョプサル", "ko": "삼겹살", "zh": "五花肉（韩式）", "ru": "Самгёпсаль", "ar": "سامغيوبسال", "de": "Samgyeopsal", "es": "Samgyeopsal", "hi": "सम्ग्योपसाल", "th": "ซัมเกียปซัล", "vi": "Ba chỉ nướng", "he": "סמגיופסאל"},
    {"fr": "Tteokbokki", "en": "Tteokbokki", "ja": "トッポッキ", "ko": "떡볶이", "zh": "炒年糕", "ru": "Ттокпокки", "ar": "توكبوكي", "de": "Tteokbokki", "es": "Tteokbokki", "hi": "टोकबोक्की", "th": "ต็อกบกกี", "vi": "Bánh gạo cay", "he": "טוקבוקי"},
    {"fr": "Tteok", "en": "Tteok (rice cakes)", "ja": "トック", "ko": "떡", "zh": "年糕", "ru": "Тток", "ar": "توك", "de": "Tteok", "es": "Tteok", "hi": "टोक", "th": "ต็อก", "vi": "Bánh gạo", "he": "טוק"},
    {"fr": "Japchae", "en": "Japchae", "ja": "チャプチェ", "ko": "잡채", "zh": "杂菜", "ru": "Чапчхе", "ar": "جابتشاي", "de": "Japchae", "es": "Japchae", "hi": "जपचाए", "th": "จับแช", "vi": "Miến japchae", "he": "ג'פצ'ה"},
    {"fr": "Galbi", "en": "Galbi", "ja": "カルビ", "ko": "갈비", "zh": "烤排骨", "ru": "Кальби", "ar": "غالبي", "de": "Galbi", "es": "Galbi", "hi": "गाल्बी", "th": "กัลบิ", "vi": "Sườn nướng Hàn", "he": "גלבי"},
    {"fr": "Ssamjang", "en": "Ssamjang", "ja": "サムジャン", "ko": "쌈장", "zh": "包饭酱", "ru": "Ссамджан", "ar": "سامجانغ", "de": "Ssamjang", "es": "Ssamjang", "hi": "स्सामजांग", "th": "ซัมจัง", "vi": "Tương ssamjang", "he": "סאמג'אנג"},
    {"fr": "Feuilles de périlla", "en": "Perilla leaves", "ja": "エゴマの葉", "ko": "깻잎", "zh": "苏子叶", "ru": "Листья периллы", "ar": "أوراق البيريلا", "de": "Perillablätter", "es": "Hojas de perilla", "hi": "पेरिला पत्ते", "th": "ใบชिसोเกาหลี", "vi": "Lá tía tô Hàn", "he": "עלי פרילה"},
    {"fr": "Radis coréen", "en": "Korean radish", "ja": "ム", "ko": "무", "zh": "韩国萝卜", "ru": "Корейская редька", "ar": "فجل كوري", "de": "Koreanischer Rettich", "es": "Rábano coreano", "hi": "कोरियाई मूली", "th": "หัวไชเท้าเกาหลี", "vi": "Củ cải Hàn", "he": "צנון קוריאני"},
    {"fr": "Mandu", "en": "Mandu", "ja": "マンドゥ", "ko": "만두", "zh": "韩式饺子", "ru": "Манду", "ar": "ماندو", "de": "Mandu", "es": "Mandu", "hi": "मांडू", "th": "มันดู", "vi": "Mandu", "he": "מנדו"},
    {"fr": "Ramyeon", "en": "Ramyeon", "ja": "ラミョン", "ko": "라면", "zh": "拉面（韩国）", "ru": "Рамён", "ar": "راميون", "de": "Ramyeon", "es": "Ramyeon", "hi": "राम्योन", "th": "รามยอน", "vi": "Ramyeon", "he": "רמיון"},
    {"fr": "Makgeolli", "en": "Makgeolli", "ja": "マッコリ", "ko": "막걸리", "zh": "米酒", "ru": "Макколли", "ar": "ماكغولي", "de": "Makgeolli", "es": "Makgeolli", "hi": "माकगोल्ली", "th": "มักกอลลี", "vi": "Rượu makgeolli", "he": "מקגולי"},
    {"fr": "Banchan", "en": "Banchan", "ja": "バンチャン", "ko": "반찬", "zh": "小菜", "ru": "Панчхан", "ar": "بانتشان", "de": "Banchan", "es": "Banchan", "hi": "बानचान", "th": "บันชัน", "vi": "Banchan", "he": "באנצ'אן"},
    {"fr": "Galette de poisson", "en": "Fish cake", "ja": "おでん種", "ko": "어묵", "zh": "鱼饼", "ru": "Рыбные котлеты", "ar": "كعكة السمك", "de": "Fischkuchen", "es": "Pastel de pescado", "hi": "फिश केक", "th": "ลูกชิ้นปลา", "vi": "Chả cá", "he": "עוגת דג", "id": "Bakso ikan"},
    {"fr": "Nouilles de patate douce", "en": "Sweet potato noodles", "ja": "春雨（韓国）", "ko": "당면", "zh": "红薯粉条", "ru": "Лапша из батата", "ar": "نودلز البطاطا الحلوة", "de": "Süßkartoffelnudeln", "es": "Fideos de boniato", "hi": "शकरकंद नूडल्स", "th": "วุ้นเส้น", "vi": "Miến khoai lang", "he": "אטריות בטטה"},
    {"fr": "Huile de périlla", "en": "Perilla oil", "ja": "エゴマ油", "ko": "들기름", "zh": "苏子油", "ru": "Масло периллы", "ar": "زيت البيريلا", "de": "Perillaöl", "es": "Aceite de perilla", "hi": "पेरिला तेल", "th": "น้ำมันชिसो", "vi": "Dầu tía tô", "he": "שמן פרילה"},
    {"fr": "Poire asiatique", "en": "Asian pear", "ja": "梨", "ko": "배", "zh": "雪梨", "ru": "Азиатская груша", "ar": "كمثرى آسيوية", "de": "Nashi-Birne", "es": "Pera asiática", "hi": "नाशपाती एशियाई", "th": "สาลี่", "vi": "Lê châu Á", "he": "אגס אסייתי"},
    {"fr": "Germes de soja", "en": "Soybean sprouts", "ja": "豆もやし", "ko": "콩나물", "zh": "黄豆芽", "ru": "Ростки сои", "ar": "براعم الصويا", "de": "Sojasprossen", "es": "Brotes de soja", "it": "Germogli di soia", "pt": "Brotos de soja", "hi": "सोयाबीन अंकुर", "th": "ถั่วงอก", "vi": "Giá đỗ", "tr": "Soya filizi", "he": "נבטי סויה", "id": "Tauge"},
    {"fr": "Gim", "en": "Gim (Korean seaweed)", "ja": "韓国のり", "ko": "김", "zh": "海苔（韩国）", "ru": "Ким", "ar": "كيم", "de": "Gim", "es": "Gim", "hi": "गिम्", "th": "กิม", "vi": "Rong biển gim", "he": "גים"},
    {"fr": "Sundubu", "en": "Sundubu (soft tofu)", "ja": "スンドゥブ", "ko": "순두부", "zh": "嫩豆腐", "ru": "Сундубу", "ar": "سندوبو", "de": "Sundubu", "es": "Sundubu", "hi": "सुन्दुबु", "th": "ซุนดูบู", "vi": "Đậu phụ mềm", "he": "סונדובו"},
    {"fr": "Poisson séché", "en": "Dried fish", "ja": "干物", "ko": "마른 생선", "zh": "鱼干", "ru": "Вяленая рыба", "ar": "سمك مجفف", "de": "Trockenfisch", "es": "Pescado seco", "hi": "सूखी मछली", "th": "ปลาแห้ง", "vi": "Cá khô", "he": "דג מיובש", "id": "Ikan kering"},
    # —— Russie / Ukraine ——
    {"fr": "Betterave", "en": "Beetroot", "ja": "ビーツ", "ko": "비트", "zh": "甜菜根", "ru": "Свёкла", "ar": "شمندر", "de": "Rote Bete", "es": "Remolacha", "it": "Barbabietola", "pt": "Beterraba", "hi": "चुकंदर", "th": "บีทรูท", "vi": "Củ dền", "tr": "Pancar", "el": "Παντζάρι", "he": "סלק", "uk": "Буряк", "pl": "Burak", "id": "Bit", "nl": "Biet", "sv": "Rödbeta"},
    {"fr": "Smetana", "en": "Smetana", "ja": "スメタナ", "ko": "스메타나", "zh": "斯美塔纳", "ru": "Сметана", "ar": "سميتانا", "de": "Smetana", "es": "Smetana", "hi": "स्मेटाना", "uk": "Сметана", "pl": "Śmietana", "he": "סמטנה", "bg": "Сметана"},
    {"fr": "Sarrasin", "en": "Buckwheat", "ja": "そばの実", "ko": "메밀", "zh": "荞麦", "ru": "Гречка", "ar": "حنطة سوداء", "de": "Buchweizen", "es": "Alforfón", "it": "Grano saraceno", "pt": "Trigo sarraceno", "hi": "कुट्टू", "th": "บัควีท", "vi": "Kiểu mạch", "tr": "Karabuğday", "el": "Φαγόπυρο", "he": "כוסמת", "uk": "Гречка", "pl": "Gryka", "nl": "Boekweit", "sv": "Bovete"},
    {"fr": "Pelmeni", "en": "Pelmeni", "ja": "ペリメニ", "ko": "펠메니", "zh": "俄罗斯饺子", "ru": "Пельмени", "ar": "بيلمني", "de": "Pelmeni", "es": "Pelmeni", "hi": "पेलमेनी", "uk": "Пельмені", "pl": "Pierogi syberyjskie", "he": "פלמני"},
    {"fr": "Pain noir", "en": "Black bread", "ja": "黒パン", "ko": "흑빵", "zh": "黑面包", "ru": "Чёрный хлеб", "ar": "خبز أسود", "de": "Schwarzbrot", "es": "Pan negro", "it": "Pane nero", "pt": "Pão preto", "hi": "काली रोटी", "uk": "Чорний хліб", "pl": "Chleb żytni", "he": "לחם שחור", "nl": "Zwart brood", "sv": "Rågbröd"},
    {"fr": "Hareng", "en": "Herring", "ja": "ニシン", "ko": "청어", "zh": "鲱鱼", "ru": "Селёдка", "ar": "رنجة", "de": "Hering", "es": "Arenque", "it": "Aringa", "pt": "Arenque", "hi": "हेरिंग", "th": "เฮอร์ริง", "vi": "Cá trích", "tr": "Ringa", "el": "Ρέγγα", "he": "הרינג", "uk": "Оселедець", "pl": "Śledź", "nl": "Haring", "sv": "Sill"},
    {"fr": "Kvas", "en": "Kvass", "ja": "クヴァス", "ko": "크바스", "zh": "克瓦斯", "ru": "Квас", "ar": "كفاس", "de": "Kwass", "es": "Kvas", "hi": "क्वास", "uk": "Квас", "pl": "Kwas chlebowy", "he": "קוואס"},
    {"fr": "Chou fermenté", "en": "Sauerkraut", "ja": "発酵キャベツ", "ko": "발효 양배추", "zh": "酸菜", "ru": "Квашеная капуста", "ar": "ملفوف مخمر", "de": "Sauerkraut", "es": "Chucrut", "it": "Crauti", "pt": "Chucrute", "hi": "सॉरक्राउट", "uk": "Квашена капуста", "pl": "Kapusta kiszona", "he": "כרוב כבוש", "nl": "Zuurkool", "sv": "Surkål"},
    {"fr": "Kéfir", "en": "Kefir", "ja": "ケフィア", "ko": "케피르", "zh": "开菲尔", "ru": "Кефир", "ar": "كفير", "de": "Kefir", "es": "Kéfir", "it": "Kefir", "pt": "Kefir", "hi": "केफिर", "th": "คีเฟอร์", "vi": "Kefir", "tr": "Kefir", "he": "קפיר", "uk": "Кефір", "pl": "Kefir", "nl": "Kefir", "sv": "Kefir"},
    {"fr": "Tvorog", "en": "Tvorog", "ja": "トヴォログ", "ko": "트보로그", "zh": "俄罗斯奶酪", "ru": "Творог", "ar": "تفوروغ", "de": "Tworog", "es": "Tvorog", "hi": "त्वोरोग", "uk": "Сир кисломолочний", "pl": "Twaróg", "he": "טוורוג"},
    {"fr": "Blinis", "en": "Blinis", "ja": "ブリニ", "ko": "블리니", "zh": "俄式薄饼", "ru": "Блины", "ar": "بليني", "de": "Blinis", "es": "Blinis", "hi": "ब्लिनी", "uk": "Млинці", "pl": "Bliny", "he": "בליני"},
    {"fr": "Huile de tournesol", "en": "Sunflower oil", "ja": "ひまわり油", "ko": "해바라기유", "zh": "葵花籽油", "ru": "Подсолнечное масло", "ar": "زيت عباد الشمس", "de": "Sonnenblumenöl", "es": "Aceite de girasol", "it": "Olio di girasole", "pt": "Óleo de girassol", "hi": "सूरजमुखी तेल", "th": "น้ำมันทานตะวัน", "vi": "Dầu hướng dương", "tr": "Ayçiçek yağı", "el": "Ηλιέλαιο", "he": "שמן חמניות", "uk": "Соняшникова олія", "pl": "Olej słonecznikowy", "id": "Minyak bunga matahari", "nl": "Zonnebloemolie", "sv": "Solrosolja"},
    {"fr": "Raifort", "en": "Horseradish", "ja": "ホースラディッシュ", "ko": "호스래디시", "zh": "辣根", "ru": "Хрен", "ar": "فجل حار", "de": "Meerrettich", "es": "Rábano picante", "it": "Rafano", "pt": "Rábano-de-cavalo", "hi": "हॉर्सरैडिश", "uk": "Хрін", "pl": "Chrzan", "he": "חזרת", "nl": "Mierikswortel", "sv": "Pepparrot"},
    {"fr": "Vodka", "en": "Vodka", "ja": "ウォッカ", "ko": "보드카", "zh": "伏特加", "ru": "Водка", "ar": "فودكا", "de": "Wodka", "es": "Vodka", "it": "Vodka", "pt": "Vodka", "hi": "वोदका", "th": "วอดก้า", "vi": "Vodka", "tr": "Votka", "el": "Βότκα", "he": "וודקה", "uk": "Горілка", "pl": "Wódka", "nl": "Wodka", "sv": "Vodka"},
    {"fr": "Caviar", "en": "Caviar", "ja": "キャビア", "ko": "캐비아", "zh": "鱼子酱", "ru": "Икра", "ar": "كافيار", "de": "Kaviar", "es": "Caviar", "it": "Caviale", "pt": "Caviar", "hi": "कैवियार", "uk": "Ікра", "pl": "Kawior", "he": "קוויאר"},
    {"fr": "Vareniki", "en": "Vareniki", "ja": "ヴァレニキ", "ko": "바레니키", "zh": "乌克兰饺子", "ru": "Вареники", "ar": "فارينيكي", "de": "Wareniki", "es": "Vareniki", "hi": "वारेनिकी", "uk": "Вареники", "pl": "Vareniki", "he": "וארניקי"},
    {"fr": "Adjika", "en": "Adjika", "ja": "アジカ", "ko": "아지카", "zh": "阿吉卡酱", "ru": "Аджика", "ar": "أديكا", "de": "Adschika", "es": "Adjika", "hi": "अजिका", "uk": "Аджика", "he": "אג'יקה"},
    {"fr": "Graines de tournesol", "en": "Sunflower seeds", "ja": "ひまわりの種", "ko": "해바라기씨", "zh": "葵花籽", "ru": "Семечки", "ar": "بذور عباد الشمس", "de": "Sonnenblumenkerne", "es": "Pipas de girasol", "it": "Semi di girasole", "pt": "Sementes de girassol", "hi": "सूरजमुखी के बीज", "uk": "Насіння соняшника", "pl": "Pestki słonecznika", "he": "גרעיני חמנייה", "nl": "Zonnebloempitten", "sv": "Solrosfrön"},
    {"fr": "Chachlik", "en": "Shashlik", "ja": "シャシリク", "ko": "샤슬릭", "zh": "俄式烤肉串", "ru": "Шашлык", "ar": "شاشليك", "de": "Schaschlik", "es": "Shashlik", "hi": "शाशलिक", "uk": "Шашлик", "pl": "Szaszłyk", "he": "ששליק", "tr": "Şaşlık"},
    {"fr": "Pain de seigle", "en": "Rye bread", "ja": "ライ麦パン", "ko": "호밀빵", "zh": "黑麦面包", "ru": "Ржаной хлеб", "ar": "خبز الجاودار", "de": "Roggenbrot", "es": "Pan de centeno", "it": "Pane di segale", "pt": "Pão de centeio", "hi": "राई की रोटी", "uk": "Житній хліб", "pl": "Chleb żytni", "he": "לחם שיפון", "nl": "Roggebrood", "sv": "Rågbröd", "da": "Rugbrød", "fi": "Ruisleipä", "nb": "Rugbrød"},
    # —— Maghreb / Machrek ——
    {"fr": "Couscous", "en": "Couscous", "ja": "クスクス", "ko": "쿠스쿠스", "zh": "库斯库斯", "ru": "Кускус", "ar": "كسكس", "de": "Couscous", "es": "Cuscús", "it": "Couscous", "pt": "Cuscuz", "hi": "कस्कस", "th": "คูสคูส", "vi": "Couscous", "tr": "Kuskus", "el": "Κουσκούς", "he": "קוסקוס", "uk": "Кускус", "id": "Kuskus"},
    {"fr": "Tajine", "en": "Tagine", "ja": "タジン", "ko": "타진", "zh": "塔吉锅菜", "ru": "Тажин", "ar": "طاجين", "de": "Tajine", "es": "Tayín", "it": "Tajine", "pt": "Tajine", "hi": "ताजिन", "th": "ทาจีน", "vi": "Tajine", "tr": "Tacine", "he": "טאג'ין"},
    {"fr": "Harissa", "en": "Harissa", "ja": "ハリッサ", "ko": "하리사", "zh": "哈里萨辣椒酱", "ru": "Харисса", "ar": "هريسة", "de": "Harissa", "es": "Harissa", "it": "Harissa", "pt": "Harissa", "hi": "हरीसा", "th": "ฮาริสซา", "vi": "Harissa", "tr": "Harissa", "he": "חריסה"},
    {"fr": "Citrons confits", "en": "Preserved lemons", "ja": "塩レモン", "ko": "절인 레몬", "zh": "腌柠檬", "ru": "Солёные лимоны", "ar": "ليمون مخلل", "de": "Salzzitronen", "es": "Limones confitados", "it": "Limoni in salamoia", "pt": "Limões em conserva", "hi": "अचार नींबू", "th": "เลมอนดอง", "vi": "Chanh muối", "tr": "Tuzlu limon", "he": "לימונים כבושים"},
    {"fr": "Labneh", "en": "Labneh", "ja": "ラブネ", "ko": "라브네", "zh": "拉布涅", "ru": "Лабне", "ar": "لبنة", "de": "Labneh", "es": "Labneh", "hi": "लबनेह", "th": "ลาบเนห์", "vi": "Labneh", "tr": "Labne", "el": "Λαμπνέ", "he": "לבנה"},
    {"fr": "Pain pita", "en": "Pita bread", "ja": "ピタパン", "ko": "피타", "zh": "皮塔饼", "ru": "Пита", "ar": "خبز بيتا", "de": "Pitabrot", "es": "Pan pita", "it": "Pane pita", "pt": "Pão pita", "hi": "पीटा ब्रेड", "th": "ขนมปังพิตา", "vi": "Bánh pita", "tr": "Pide ekmeği", "el": "Πίτα", "he": "פיתה"},
    {"fr": "Falafel", "en": "Falafel", "ja": "ファラフェル", "ko": "팔라펠", "zh": "法拉费", "ru": "Фалафель", "ar": "فلافل", "de": "Falafel", "es": "Falafel", "it": "Falafel", "pt": "Falafel", "hi": "फलाफेल", "th": "ฟาลาเฟล", "vi": "Falafel", "tr": "Falafel", "el": "Φαλάφελ", "he": "פלאפל"},
    {"fr": "Ras el hanout", "en": "Ras el hanout", "ja": "ラス・エル・ハヌート", "ko": "라스 엘 하누트", "zh": "摩洛哥香料", "ru": "Рас-эль-ханут", "ar": "رأس الحانوت", "de": "Ras el-Hanout", "es": "Ras el hanout", "hi": "रस एल हनूत", "he": "ראס אל חנות", "nl": "Ras el hanout"},
    {"fr": "Zaatar", "en": "Za'atar", "ja": "ザアタル", "ko": "자타르", "zh": "扎塔尔", "ru": "Заатар", "ar": "زعتر", "de": "Za'atar", "es": "Zaatar", "hi": "ज़ातर", "th": "ซาตาร์", "vi": "Zaatar", "tr": "Zaatar", "el": "Ζάαταρ", "he": "זעתר"},
    {"fr": "Sumac", "en": "Sumac", "ja": "スマック", "ko": "수맥", "zh": "苏玛克", "ru": "Сумах", "ar": "سماق", "de": "Sumach", "es": "Zumaque", "it": "Sommacco", "pt": "Sumagre", "hi": "सुमाक", "tr": "Sumak", "el": "Σουμάκι", "he": "סומאק"},
    {"fr": "Mélasse de grenade", "en": "Pomegranate molasses", "ja": "ザクロ蜜", "ko": "석류 당밀", "zh": "石榴糖浆", "ru": "Гранатовый соус", "ar": "دبس الرمان", "de": "Granatapfelsirup", "es": "Melaza de granada", "hi": "अनार गुड़", "tr": "Nar ekşisi", "el": "Πετιμέζι ροδιού", "he": "דבש רימונים"},
    {"fr": "Freekeh", "en": "Freekeh", "ja": "フリーケ", "ko": "프리케", "zh": "弗里keh小麦", "ru": "Фрика", "ar": "فريكة", "de": "Freekeh", "es": "Freekeh", "hi": "फ्रीkeh", "tr": "Firik", "he": "פריקה"},
    {"fr": "Fèves", "en": "Fava beans", "ja": "空豆", "ko": "잠두", "zh": "蚕豆", "ru": "Бобы", "ar": "فول", "de": "Dicke Bohnen", "es": "Habas", "it": "Fave", "pt": "Favas", "hi": "फली", "th": "ถั่วปากอ้า", "vi": "Đậu tằm", "tr": "Bakla", "el": "Κουκιά", "he": "פול", "uk": "Боби"},
    {"fr": "Eau de fleur d'oranger", "en": "Orange blossom water", "ja": "オレンジフラワーウォーター", "ko": "오렌지 꽃 워터", "zh": "橙花水", "ru": "Цветочная вода", "ar": "ماء الزهر", "de": "Orangenblütenwasser", "es": "Agua de azahar", "it": "Acqua di fiori d'arancio", "pt": "Água de flor de laranjeira", "hi": "नारंगी फूल जल", "tr": "Portakal çiçeği suyu", "he": "מי זהר"},
    {"fr": "Eau de rose", "en": "Rose water", "ja": "ローズウォーター", "ko": "장미수", "zh": "玫瑰水", "ru": "Розовая вода", "ar": "ماء الورد", "de": "Rosenwasser", "es": "Agua de rosas", "it": "Acqua di rose", "pt": "Água de rosas", "hi": "गुलाब जल", "th": "น้ำกุหลาบ", "vi": "Nước hoa hồng", "tr": "Gül suyu", "el": "Ροδόνερο", "he": "מי ורדים"},
    {"fr": "Maamoul", "en": "Maamoul", "ja": "マームール", "ko": "마물", "zh": "马穆勒", "ru": "Мамуль", "ar": "معمول", "de": "Maamoul", "es": "Maamoul", "hi": "मामूल", "he": "מעמול", "tr": "Maamoul"},
    {"fr": "Baklava", "en": "Baklava", "ja": "バクラヴァ", "ko": "바클라바", "zh": "果仁蜜饼", "ru": "Пахлава", "ar": "بقلاوة", "de": "Baklava", "es": "Baklava", "it": "Baklava", "pt": "Baklava", "hi": "बाकलवा", "th": "บากลาวา", "vi": "Baklava", "tr": "Baklava", "el": "Μπακλαβάς", "he": "בקלאווה", "uk": "Пахлава"},
    {"fr": "Boulgour", "en": "Bulgur", "ja": "ブルグル", "ko": "불거", "zh": "布尔古尔", "ru": "Булгур", "ar": "برغل", "de": "Bulgur", "es": "Bulgur", "it": "Bulgur", "pt": "Bulgur", "hi": "बुलगर", "tr": "Bulgur", "el": "Πλιγούρι", "he": "בורגול"},
    {"fr": "Feuilles de brick", "en": "Brick pastry", "ja": "ブリック生地", "ko": "브릭 페이스트리", "zh": "薄饼皮", "ru": "Тесто брик", "ar": "ورق البريك", "de": "Brick-Teig", "es": "Hojas de brick", "it": "Sfoglie brick", "pt": "Massa brick", "hi": "ब्रिक पेस्ट्री", "he": "בצק בריק"},
    {"fr": "Safran", "en": "Saffron", "ja": "サフラン", "ko": "사프란", "zh": "藏红花", "ru": "Шафран", "ar": "زعفران", "de": "Safran", "es": "Azafrán", "it": "Zafferano", "pt": "Açafrão", "hi": "केसर", "th": "หญ้าฝรั่น", "vi": "Nghệ tây", "tr": "Safran", "el": "Σαφράν", "he": "זעפרן", "uk": "Шафран", "pl": "Szafran", "id": "Safron", "nl": "Saffraan", "sv": "Saffran"},
    {"fr": "Cumin", "en": "Cumin", "ja": "クミン", "ko": "쿠민", "zh": "孜然", "ru": "Зира", "ar": "كمون", "de": "Kreuzkümmel", "es": "Comino", "it": "Cumino", "pt": "Cominho", "hi": "जीरा", "th": "ยี่หร่า", "vi": "Thì là Ai Cập", "tr": "Kimyon", "el": "Κύμινο", "he": "כמון", "uk": "Кмин", "pl": "Kmin", "id": "Jintan", "nl": "Komijn", "sv": "Spiskummin"},
    {"fr": "Thé à la menthe", "en": "Mint tea", "ja": "ミントティー", "ko": "민트티", "zh": "薄荷茶", "ru": "Мятный чай", "ar": "أتاي", "de": "Minztee", "es": "Té de menta", "it": "Tè alla menta", "pt": "Chá de hortelã", "hi": "पुदीना चाय", "th": "ชามินต์", "vi": "Trà bạc hà", "tr": "Nane çayı", "he": "תה נענע"},
    {"fr": "Amlou", "en": "Amlou", "ja": "アムルー", "ko": "아믈루", "zh": "阿姆卢", "ru": "Амлу", "ar": "أملو", "de": "Amlou", "es": "Amlou", "hi": "अमलू", "he": "אמלו"},
    {"fr": "Msemen", "en": "Msemen", "ja": "ムセメン", "ko": "므세멘", "zh": "姆塞门", "ru": "Мсемен", "ar": "مسمن", "de": "Msemen", "es": "Msemen", "hi": "म्सेमेन", "he": "מסמן"},
    {"fr": "Khobz", "en": "Khobz", "ja": "ホブズ", "ko": "홉즈", "zh": "霍布兹面包", "ru": "Хобз", "ar": "خبز", "de": "Khobz", "es": "Khobz", "hi": "खोब्ज़", "he": "חובז"},
    {"fr": "Arak", "en": "Arak", "ja": "アラック", "ko": "아라크", "zh": "阿拉克", "ru": "Арак", "ar": "عرق", "de": "Arak", "es": "Arak", "hi": "अरक", "tr": "Rakı", "he": "ערק"},
    {"fr": "Smen", "en": "Smen", "ja": "スメン", "ko": "스멘", "zh": "斯曼黄油", "ru": "Смен", "ar": "سمن", "de": "Smen", "es": "Smen", "hi": "स्मेन", "he": "סמן"},
    {"fr": "Pastilla", "en": "Pastilla", "ja": "パスティラ", "ko": "파스티야", "zh": "巴斯蒂拉", "ru": "Пастилья", "ar": "بسطيلة", "de": "Pastilla", "es": "Pastela", "hi": "पस्तीला", "he": "בסטיליה"},
    # —— Chine ——
    {"fr": "Nouilles chinoises", "en": "Chinese noodles", "ja": "中華麺", "ko": "중화면", "zh": "面条", "ru": "Китайская лапша", "ar": "نودلز صينية", "de": "Chinesische Nudeln", "es": "Fideos chinos", "hi": "चीनी नूडल्स", "th": "บะหมี่จีน", "vi": "Mì Trung Quốc", "he": "אטריות סיניות", "id": "Mie Tionghoa"},
    {"fr": "Sauce d'huître", "en": "Oyster sauce", "ja": "オイスターソース", "ko": "굴소스", "zh": "蚝油", "ru": "Устричный соус", "ar": "صلصة المحار", "de": "Austernsauce", "es": "Salsa de ostras", "it": "Salsa di ostriche", "pt": "Molho de ostra", "hi": "ऑयस्टर सॉस", "th": "ซอสหอยนางรม", "vi": "Dầu hào", "tr": "İstiridye sosu", "he": "רוטב צדפות", "id": "Saus tiram"},
    {"fr": "Pak choi", "en": "Pak choi", "ja": "チンゲン菜", "ko": "청경채", "zh": "白菜（小白菜）", "ru": "Пак-чой", "ar": "باك تشوي", "de": "Pak Choi", "es": "Pak choi", "it": "Pak choi", "pt": "Pak choi", "hi": "पैक चोई", "th": "ผักกาดขาว", "vi": "Cải thìa", "he": "פק צ'וי", "id": "Sawi hijau", "nl": "Paksoi"},
    {"fr": "Anis étoilé", "en": "Star anise", "ja": "八角", "ko": "팔각", "zh": "八角", "ru": "Бадьян", "ar": "يانسون نجمي", "de": "Sternanis", "es": "Anís estrellado", "it": "Anice stellato", "pt": "Anis-estrelado", "hi": "चक्र फूल", "th": "โป๊ยกั๊ก", "vi": "Hồi", "tr": "Yıldız anason", "he": "כוכב אניס", "id": "Bunga lawang"},
    {"fr": "Baozi", "en": "Baozi", "ja": "包子", "ko": "바오즈", "zh": "包子", "ru": "Баоцзы", "ar": "باوزي", "de": "Baozi", "es": "Baozi", "hi": "बाओजी", "th": "ซาลาเปา", "vi": "Bánh bao", "he": "באו דזה", "id": "Bakpao"},
    {"fr": "Wonton", "en": "Wonton", "ja": "ワンタン", "ko": "원톤", "zh": "馄饨", "ru": "Вонтоны", "ar": "ونتون", "de": "Wantan", "es": "Wonton", "hi": "वॉन्टन", "th": "เกี๊ยว", "vi": "Hoành thánh", "he": "וונטון", "id": "Wonton"},
    {"fr": "Vin de Shaoxing", "en": "Shaoxing wine", "ja": "紹興酒", "ko": "샤오싱주", "zh": "绍兴酒", "ru": "Шаосинское вино", "ar": "نبيذ شاوشينغ", "de": "Shaoxing-Wein", "es": "Vino de Shaoxing", "hi": "शाओशिंग वाइन", "th": "เหล้าข้าวเส้าซิง", "vi": "Rượu Thiệu Hưng", "he": "יין שאושינג"},
    {"fr": "Cinq-épices", "en": "Five-spice powder", "ja": "五香粉", "ko": "오향분", "zh": "五香粉", "ru": "Смесь пяти специй", "ar": "بهارات خمس", "de": "Fünf-Gewürze-Pulver", "es": "Cinco especias", "hi": "पांच मसाले", "th": "ผงเครื่องเทศห้าอย่าง", "vi": "Ngũ vị hương", "he": "חמישה תבלינים", "id": "Bubuk lima rempah"},
    {"fr": "Huile de piment", "en": "Chili oil", "ja": "ラー油", "ko": "고추기름", "zh": "辣椒油", "ru": "Перечное масло", "ar": "زيت الفلفل", "de": "Chiliöl", "es": "Aceite de chile", "it": "Olio al peperoncino", "pt": "Óleo de pimenta", "hi": "मिर्च तेल", "th": "น้ำมันพริก", "vi": "Dầu ớt", "tr": "Acı biber yağı", "he": "שמן צ'ילי", "id": "Minyak cabai"},
    {"fr": "Doubanjiang", "en": "Doubanjiang", "ja": "トウバンジャン", "ko": "두반장", "zh": "豆瓣酱", "ru": "Добаньцзян", "ar": "دوبانجيانغ", "de": "Doubanjiang", "es": "Doubanjiang", "hi": "डोबानजियांग", "th": "โต่วบานเจียง", "vi": "Tương đậu", "he": "דובנג'יאנג"},
    {"fr": "Sauce hoisin", "en": "Hoisin sauce", "ja": "海鮮醤", "ko": "호이신 소스", "zh": "海鲜酱", "ru": "Соус хойсин", "ar": "صلصة هويسين", "de": "Hoisin-Sauce", "es": "Salsa hoisin", "hi": "हॉइसिन सॉस", "th": "ซอสฮอยซิน", "vi": "Tương hoisin", "he": "רוטב הויזין", "id": "Saus hoisin"},
    {"fr": "Oreilles de Judas", "en": "Wood ear mushrooms", "ja": "きくらげ", "ko": "목이버섯", "zh": "木耳", "ru": "Муэр", "ar": "فطر أذن الخشب", "de": "Judasohr", "es": "Oreja de Judas", "hi": "वुड ईयर मशरूम", "th": "เห็ดหูหนู", "vi": "Mộc nhĩ", "he": "פטריות אוזן", "id": "Jamur kuping"},
    {"fr": "Liseron d'eau", "en": "Water spinach", "ja": "空心菜", "ko": "공심채", "zh": "空心菜", "ru": "Ипомея водная", "ar": "سبانخ الماء", "de": "Wasserspinat", "es": "Espinaca de agua", "hi": "वॉटर स्पिनच", "th": "ผักบุ้ง", "vi": "Rau muống", "he": "תרד מים", "id": "Kangkung"},
    {"fr": "Litchi", "en": "Lychee", "ja": "ライチ", "ko": "리치", "zh": "荔枝", "ru": "Личи", "ar": "ليتشي", "de": "Litschi", "es": "Lichi", "it": "Litchi", "pt": "Lichia", "hi": "लीची", "th": "ลิ้นจี่", "vi": "Vải", "tr": "Liçi", "he": "ליצ'י", "id": "Leci"},
    {"fr": "Saucisse chinoise", "en": "Chinese sausage", "ja": "臘腸", "ko": "중국 소시지", "zh": "腊肠", "ru": "Китайская колбаса", "ar": "سجق صيني", "de": "Chinesische Wurst", "es": "Salchicha china", "hi": "चीनी सॉसेज", "th": "กุนเชียง", "vi": "Lạp xưởng", "he": "נקניק סיני", "id": "Lap cheong"},
    {"fr": "Farine de riz", "en": "Rice flour", "ja": "米粉", "ko": "쌀가루", "zh": "米粉（面粉）", "ru": "Рисовая мука", "ar": "دقيق الأرز", "de": "Reismehl", "es": "Harina de arroz", "it": "Farina di riso", "pt": "Farinha de arroz", "hi": "चावल का आटा", "th": "แป้งข้าวเจ้า", "vi": "Bột gạo", "tr": "Pirinç unu", "he": "קמח אורז", "id": "Tepung beras", "nl": "Rijstmeel"},
    # —— Inde ——
    {"fr": "Garam masala", "en": "Garam masala", "ja": "ガラムマサラ", "ko": "가람 마살라", "zh": "加拉姆马萨拉", "ru": "Гарам масала", "ar": "جارام ماسالا", "de": "Garam Masala", "es": "Garam masala", "hi": "गरम मसाला", "th": "การัมมาซาลา", "vi": "Garam masala", "tr": "Garam masala", "he": "גאראם מסאלה", "id": "Garam masala"},
    {"fr": "Curcuma", "en": "Turmeric", "ja": "ターメリック", "ko": "강황", "zh": "姜黄", "ru": "Куркума", "ar": "كركم", "de": "Kurkuma", "es": "Cúrcuma", "it": "Curcuma", "pt": "Açafrão-da-terra", "hi": "हल्दी", "th": "ขมิ้น", "vi": "Nghệ", "tr": "Zerdeçal", "el": "Κουρκουμάς", "he": "כורכום", "uk": "Куркума", "pl": "Kurkuma", "id": "Kunyit", "nl": "Kurkuma", "sv": "Gurkmeja"},
    {"fr": "Cardamome", "en": "Cardamom", "ja": "カルダモン", "ko": "카다멈", "zh": "豆蔻", "ru": "Кардамон", "ar": "هيل", "de": "Kardamom", "es": "Cardamomo", "it": "Cardamomo", "pt": "Cardamomo", "hi": "इलायची", "th": "กระวาน", "vi": "Thảo quả", "tr": "Kakule", "el": "Κάρδαμο", "he": "הל", "id": "Kapulaga", "nl": "Kardemom", "sv": "Kardemumma"},
    {"fr": "Ghee", "en": "Ghee", "ja": "ギー", "ko": "기", "zh": "酥油", "ru": "Гхи", "ar": "سمن هندي", "de": "Ghee", "es": "Ghee", "hi": "घी", "th": "กี", "vi": "Bơ ghee", "tr": "Ghee", "he": "גיהי", "id": "Ghee"},
    {"fr": "Naan", "en": "Naan", "ja": "ナン", "ko": "난", "zh": "烤饼", "ru": "Наан", "ar": "نان", "de": "Naan", "es": "Naan", "hi": "नान", "th": "นาน", "vi": "Bánh naan", "tr": "Naan", "he": "נאן", "id": "Naan"},
    {"fr": "Chapati", "en": "Chapati", "ja": "チャパティ", "ko": "차파티", "zh": "恰巴提", "ru": "Чапати", "ar": "تشاباتي", "de": "Chapati", "es": "Chapati", "hi": "चपाती", "th": "ชาปาติ", "vi": "Bánh chapati", "he": "צ'פאטי", "id": "Chapati"},
    {"fr": "Paneer", "en": "Paneer", "ja": "パニール", "ko": "파니르", "zh": "帕尼尔", "ru": "Панир", "ar": "بانير", "de": "Paneer", "es": "Paneer", "hi": "पनीर", "th": "พนีร", "vi": "Pho mát paneer", "he": "פניר", "id": "Paneer"},
    {"fr": "Chutney", "en": "Chutney", "ja": "チャツネ", "ko": "처트니", "zh": "酸辣酱", "ru": "Чатни", "ar": "تشاتني", "de": "Chutney", "es": "Chutney", "hi": "चटनी", "th": "ชัทนีย์", "vi": "Chutney", "he": "צ'אטני", "id": "Chutney"},
    {"fr": "Lassi", "en": "Lassi", "ja": "ラッシー", "ko": "라씨", "zh": "拉西", "ru": "Ласси", "ar": "لاسي", "de": "Lassi", "es": "Lassi", "hi": "लस्सी", "th": "ลัสซี", "vi": "Lassi", "he": "לאסי", "id": "Lassi"},
    {"fr": "Fenugrec", "en": "Fenugreek", "ja": "フェヌグリーク", "ko": "호로파", "zh": "胡芦巴", "ru": "Пажитник", "ar": "حلبة", "de": "Bockshornklee", "es": "Fenogreco", "it": "Fieno greco", "pt": "Feno-grego", "hi": "मेथी", "th": "ลูกซัด", "vi": "Cỏ ca ri", "tr": "Çemen otu", "he": "גרגרנית", "id": "Klabet"},
    {"fr": "Feuilles de curry", "en": "Curry leaves", "ja": "カレーリーフ", "ko": "커리 잎", "zh": "咖喱叶", "ru": "Листья карри", "ar": "أوراق الكاري", "de": "Curryblätter", "es": "Hojas de curry", "hi": "करी पत्ता", "th": "ใบกะหรี่", "vi": "Lá cà ri", "he": "עלי קארי", "id": "Daun kari"},
    {"fr": "Gombo", "en": "Okra", "ja": "オクラ", "ko": "오크라", "zh": "秋葵", "ru": "Бамия", "ar": "بامية", "de": "Okra", "es": "Quingombó", "it": "Gombo", "pt": "Quiabo", "hi": "भिंडी", "th": "กระเจี๊ยบเขียว", "vi": "Đậu bắp", "tr": "Bamya", "el": "Μπάμια", "he": "במיה", "id": "Okra"},
    {"fr": "Tamarin", "en": "Tamarind", "ja": "タマリンド", "ko": "타마린드", "zh": "罗望子", "ru": "Тамаринд", "ar": "تمر هندي", "de": "Tamarinde", "es": "Tamarindo", "it": "Tamarindo", "pt": "Tamarindo", "hi": "इमली", "th": "มะขาม", "vi": "Me", "tr": "Demirhindi", "he": "תמרינדי", "id": "Asam jawa"},
    {"fr": "Papadum", "en": "Papadum", "ja": "パパド", "ko": "파파드", "zh": "帕帕德", "ru": "Пападам", "ar": "بابادوم", "de": "Papadum", "es": "Papadum", "hi": "पापड़", "th": "ปาปัด", "vi": "Bánh papad", "he": "פפאדם", "id": "Papadum"},
    {"fr": "Asafoetida", "en": "Asafoetida", "ja": "アサフェティダ", "ko": "아사포에티다", "zh": "阿魏", "ru": "Асафетида", "ar": "حلتيت", "de": "Asant", "es": "Asafétida", "hi": "हींग", "th": "มหาหิงค์", "vi": "Asafoetida", "he": "אסאפוטידה", "id": "Asafoetida"},
    {"fr": "Huile de moutarde", "en": "Mustard oil", "ja": "マスタードオイル", "ko": "머스터드 오일", "zh": "芥末油", "ru": "Горчичное масло", "ar": "زيت الخردل", "de": "Senföl", "es": "Aceite de mostaza", "hi": "सरसों का तेल", "th": "น้ำมันมัสตาร์ด", "vi": "Dầu mù tạt", "he": "שמן חרדל", "id": "Minyak mustard"},
    {"fr": "Masala chai", "en": "Masala chai", "ja": "マサラチャイ", "ko": "마살라 차이", "zh": "马萨拉茶", "ru": "Масала чай", "ar": "شاي ماسالا", "de": "Masala Chai", "es": "Masala chai", "hi": "मसाला चाय", "th": "ชามาซาลา", "vi": "Trà masala", "he": "צ'אי מסאלה", "id": "Masala chai"},
    # —— Thaïlande / Vietnam ——
    {"fr": "Galanga", "en": "Galangal", "ja": "ガランガル", "ko": "갈랑갈", "zh": "高良姜", "ru": "Галангал", "ar": "خولنجان", "de": "Galgant", "es": "Galangal", "hi": "गलंगल", "th": "ข่า", "vi": "Riềng", "he": "גלנגל", "id": "Lengkuas"},
    {"fr": "Feuilles de kaffir", "en": "Kaffir lime leaves", "ja": "コブミカンの葉", "ko": "카피르 라임 잎", "zh": "青柠叶", "ru": "Листья кафир-лайма", "ar": "ورق الكافير", "de": "Kaffirlimettenblätter", "es": "Hojas de lima kaffir", "hi": "काफिर नीबू पत्ते", "th": "ใบมะกรูด", "vi": "Lá chanh", "he": "עלי ליים", "id": "Daun jeruk purut"},
    {"fr": "Basilic thaï", "en": "Thai basil", "ja": "タイバジル", "ko": "타이 바질", "zh": "泰式罗勒", "ru": "Тайский базилик", "ar": "ريحان تايلاندي", "de": "Thai-Basilikum", "es": "Albahaca tailandesa", "hi": "थाई तुलसी", "th": "โหระพา", "vi": "Húng quế", "he": "בזיליקום תאילנדי", "id": "Kemangi"},
    {"fr": "Sucre de palme", "en": "Palm sugar", "ja": "パームシュガー", "ko": "야자당", "zh": "棕榈糖", "ru": "Пальмовый сахар", "ar": "سكر النخيل", "de": "Palmzucker", "es": "Azúcar de palma", "hi": "ताड़ चीनी", "th": "น้ำตาลปี๊บ", "vi": "Đường thốt nốt", "he": "סוכר דקלים", "id": "Gula aren"},
    {"fr": "Pâte de crevettes", "en": "Shrimp paste", "ja": "シュリンプペースト", "ko": "새우 페이스트", "zh": "虾酱", "ru": "Креветочная паста", "ar": "معجون الروبيان", "de": "Garnelenpaste", "es": "Pasta de camarón", "hi": "झींगा पेस्ट", "th": "กะปิ", "vi": "Mắm tôm", "he": "משחת שרימפס", "id": "Terasi"},
    {"fr": "Nouilles de riz", "en": "Rice noodles", "ja": "米粉麺", "ko": "쌀국수", "zh": "米粉", "ru": "Рисовая лапша", "ar": "نودلز الأرز", "de": "Reisnudeln", "es": "Fideos de arroz", "it": "Noodles di riso", "pt": "Macarrão de arroz", "hi": "चावल नूडल्स", "th": "ก๋วยเตี๋ยว", "vi": "Bún / phở", "tr": "Pirinç eriştesi", "he": "אטריות אורז", "id": "Mie beras"},
    {"fr": "Mangue verte", "en": "Green mango", "ja": "青マンゴー", "ko": "풋망고", "zh": "青芒果", "ru": "Зелёное манго", "ar": "مانجو أخضر", "de": "Grüne Mango", "es": "Mango verde", "hi": "कच्चा आम", "th": "มะม่วงดิบ", "vi": "Xoài xanh", "he": "מנגו ירוק", "id": "Mangga muda"},
    {"fr": "Citron vert", "en": "Lime", "ja": "ライム", "ko": "라임", "zh": "青柠", "ru": "Лайм", "ar": "ليمون أخضر", "de": "Limette", "es": "Lima", "it": "Lime", "pt": "Lima", "hi": "नीबू", "th": "มะนาว", "vi": "Chanh", "tr": "Misket limonu", "el": "Λάιμ", "he": "ליים", "uk": "Лайм", "pl": "Limonka", "id": "Jeruk nipis", "nl": "Limoen", "sv": "Lime"},
    {"fr": "Piment oiseau", "en": "Bird's eye chili", "ja": "プリッキーヌー", "ko": "새눈고추", "zh": "小米椒", "ru": "Перец птичий глаз", "ar": "فلفل حار صغير", "de": "Vogelaugen-Chili", "es": "Chile de ojo de pájaro", "hi": "बर्ड आई मिर्च", "th": "พริกขี้หนู", "vi": "Ớt hiểm", "he": "צ'ילי ציפור", "id": "Cabai rawit"},
    {"fr": "Papaye verte", "en": "Green papaya", "ja": "青パパイヤ", "ko": "풋파파야", "zh": "青木瓜", "ru": "Зелёная папайя", "ar": "بابايا خضراء", "de": "Grüne Papaya", "es": "Papaya verde", "hi": "कच्चा पपीता", "th": "มะละกอดิบ", "vi": "Đu đủ xanh", "he": "פפאיה ירוקה", "id": "Pepaya muda"},
    {"fr": "Nouilles pho", "en": "Pho noodles", "ja": "フォーの麺", "ko": "퍼 면", "zh": "河粉", "ru": "Лапша фо", "ar": "نودلز فو", "de": "Pho-Nudeln", "es": "Fideos pho", "hi": "फो नूडल्स", "th": "เส้นโฟ", "vi": "Bánh phở", "he": "אטריות פו"},
    {"fr": "Feuilles de riz", "en": "Rice paper", "ja": "ライスペーパー", "ko": "라이스페이퍼", "zh": "米纸", "ru": "Рисовая бумага", "ar": "ورق الأرز", "de": "Reispapier", "es": "Papel de arroz", "hi": "राइस पेपर", "th": "แผ่นข้าว", "vi": "Bánh tráng", "he": "נייר אורז", "id": "Kulit lumpia beras"},
    {"fr": "Banh mi", "en": "Banh mi", "ja": "バインミー", "ko": "반미", "zh": "越南三明治", "ru": "Бань ми", "ar": "بان مي", "de": "Banh Mi", "es": "Banh mi", "hi": "बान्ह मी", "th": "บานห์มี", "vi": "Bánh mì", "he": "באן מי"},
    # —— Turquie / Grèce ——
    {"fr": "Yaourt grec", "en": "Greek yogurt", "ja": "ギリシャヨーグルト", "ko": "그릭 요거트", "zh": "希腊酸奶", "ru": "Греческий йогурт", "ar": "زبادي يوناني", "de": "Griechischer Joghurt", "es": "Yogur griego", "it": "Yogurt greco", "pt": "Iogurte grego", "hi": "ग्रीक दही", "th": "กรีกโยเกิร์ต", "vi": "Sữa chua Hy Lạp", "tr": "Süzme yoğurt", "el": "Ελληνικό γιαούρτι", "he": "יוגורט יווני", "uk": "Грецький йогурт", "pl": "Jogurt grecki", "nl": "Griekse yoghurt", "sv": "Grekisk yoghurt"},
    {"fr": "Halloumi", "en": "Halloumi", "ja": "ハルーミ", "ko": "할루미", "zh": "哈罗米", "ru": "Халлуми", "ar": "حلوم", "de": "Halloumi", "es": "Halloumi", "it": "Halloumi", "pt": "Halloumi", "hi": "हलूमी", "tr": "Hellim", "el": "Χαλλούμι", "he": "חלומי"},
    {"fr": "Feuilles de vigne", "en": "Grape leaves", "ja": "ブドウの葉", "ko": "포도잎", "zh": "葡萄叶", "ru": "Виноградные листья", "ar": "ورق العنب", "de": "Weinblätter", "es": "Hojas de parra", "it": "Foglie di vite", "pt": "Folhas de videira", "hi": "अंगूर के पत्ते", "tr": "Asma yaprağı", "el": "Αμπελόφυλλα", "he": "עלי גפן"},
    {"fr": "Viande kebab", "en": "Kebab meat", "ja": "ケバブ肉", "ko": "케밥 고기", "zh": "烤肉串肉", "ru": "Мясо для кебаба", "ar": "لحم كباب", "de": "Kebabfleisch", "es": "Carne de kebab", "hi": "कबाब गोश्त", "th": "เนื้อเคบับ", "vi": "Thịt kebab", "tr": "Kebap eti", "el": "Κρέας κεμπάπ", "he": "בשר קבב"},
    {"fr": "Sucuk", "en": "Sucuk", "ja": "スジュク", "ko": "수죽", "zh": "苏朱克香肠", "ru": "Суджук", "ar": "سجق", "de": "Sucuk", "es": "Sucuk", "hi": "सुचुक", "tr": "Sucuk", "el": "Σουτζούκι", "he": "סוג'וק"},
    {"fr": "Simit", "en": "Simit", "ja": "シミット", "ko": "시미트", "zh": "芝麻圈面包", "ru": "Симит", "ar": "سميط", "de": "Simit", "es": "Simit", "hi": "सिमित", "tr": "Simit", "el": "Σιμίτι", "he": "סימיט"},
    {"fr": "Ayran", "en": "Ayran", "ja": "アイラン", "ko": "아이란", "zh": "艾兰", "ru": "Айран", "ar": "عيران", "de": "Ayran", "es": "Ayran", "hi": "अयран", "tr": "Ayran", "el": "Αϊράνι", "he": "איירן"},
    {"fr": "Raki", "en": "Raki", "ja": "ラキ", "ko": "라키", "zh": "拉克酒", "ru": "Раки", "ar": "راكي", "de": "Raki", "es": "Raki", "hi": "राकी", "tr": "Rakı", "el": "Ρακί", "he": "ראקי"},
    {"fr": "Ouzo", "en": "Ouzo", "ja": "ウーゾ", "ko": "우조", "zh": "乌佐", "ru": "Узо", "ar": "أوزو", "de": "Ouzo", "es": "Ouzo", "hi": "ओउज़ो", "tr": "Uzo", "el": "Ούζο", "he": "אוזו"},
    {"fr": "Tzatziki", "en": "Tzatziki", "ja": "ザジキ", "ko": "짜지키", "zh": "酸奶黄瓜酱", "ru": "Дзадзики", "ar": "تزاتزيكي", "de": "Tzatziki", "es": "Tzatziki", "it": "Tzatziki", "pt": "Tzatziki", "hi": "त्जात्जिकी", "tr": "Cacık", "el": "Τζατζίκι", "he": "צזיקי"},
    {"fr": "Olives kalamata", "en": "Kalamata olives", "ja": "カラマタオリーブ", "ko": "칼라마타 올리브", "zh": "卡拉马塔橄榄", "ru": "Оливки каламата", "ar": "زيتون كلاماتا", "de": "Kalamata-Oliven", "es": "Aceitunas kalamata", "hi": "कलामाता जैतून", "tr": "Kalamata zeytini", "el": "Ελιές Καλαμών", "he": "זיתי קלמטה"},
    {"fr": "Yufka", "en": "Yufka", "ja": "ユフカ", "ko": "유프카", "zh": "尤夫卡", "ru": "Юфка", "ar": "يوفكا", "de": "Yufka", "es": "Yufka", "hi": "युफ्का", "tr": "Yufka", "el": "Γιούφκα", "he": "יופקה"},
    # —— Europe / Amériques / Asie du Sud-Est ——
    {"fr": "Bretzel", "en": "Pretzel", "ja": "プレッツェル", "ko": "프레첼", "zh": "椒盐卷饼", "ru": "Брецель", "ar": "بريتزل", "de": "Brezel", "es": "Pretzel", "it": "Pretzel", "pt": "Pretzel", "hi": "प्रेट्ज़ेल", "nl": "Pretzel", "pl": "Precel", "sv": "Kringla", "he": "בייגלה"},
    {"fr": "Quark", "en": "Quark", "ja": "クヴァルク", "ko": "쿼크", "zh": "夸克奶酪", "ru": "Кварк", "ar": "كوارك", "de": "Quark", "es": "Quark", "it": "Quark", "pt": "Quark", "hi": "क्वार्क", "nl": "Kwark", "pl": "Twaróg", "sv": "Kvarg", "he": "קווארק"},
    {"fr": "Spätzle", "en": "Spätzle", "ja": "シュペッツレ", "ko": "슈페츨레", "zh": "鸡蛋面疙瘩", "ru": "Шпецле", "ar": "شبيتزله", "de": "Spätzle", "es": "Spätzle", "nl": "Spätzle", "pl": "Spätzle", "he": "שפצלֶה"},
    {"fr": "Chorizo", "en": "Chorizo", "ja": "チョリソ", "ko": "초리조", "zh": "乔里佐", "ru": "Чорисо", "ar": "تشوريزو", "de": "Chorizo", "es": "Chorizo", "it": "Chorizo", "pt": "Chouriço", "hi": "चोरिज़ो", "th": "โชริโซ", "vi": "Xúc xích chorizo", "he": "צ'וריסו"},
    {"fr": "Jambon serrano", "en": "Serrano ham", "ja": "ハモンセラーノ", "ko": "세라노 햄", "zh": "塞拉诺火腿", "ru": "Хамон серрано", "ar": "جامون سيرانو", "de": "Serrano-Schinken", "es": "Jamón serrano", "it": "Prosciutto serrano", "pt": "Presunto serrano", "hi": "सेरानो हैम", "he": "חמון סראנו"},
    {"fr": "Jalapeños", "en": "Jalapeños", "ja": "ハラペーニョ", "ko": "할라페뇨", "zh": "墨西哥辣椒", "ru": "Халапеньо", "ar": "هالابينو", "de": "Jalapeños", "es": "Jalapeños", "it": "Jalapeños", "pt": "Jalapeños", "hi": "हलापेन्यो", "th": "ฮาลาเปโน", "vi": "Ớt jalapeño", "he": "חלאפניו"},
    {"fr": "Paprika fumé", "en": "Smoked paprika", "ja": "スモークパプリカ", "ko": "훈제 파프리카", "zh": "烟熏辣椒粉", "ru": "Копчёная паприка", "ar": "بابريكا مدخنة", "de": "Geräuchertes Paprikapulver", "es": "Pimentón ahumado", "it": "Paprika affumicata", "pt": "Pimentão defumado", "hi": "स्मोकड पपरिका", "he": "פפריקה מעושנת"},
    {"fr": "Queso fresco", "en": "Queso fresco", "ja": "ケソ・フレスコ", "ko": "케소 프레스코", "zh": "鲜奶酪", "ru": "Кесо фреско", "ar": "كيسو فريسكو", "de": "Queso fresco", "es": "Queso fresco", "pt": "Queijo fresco", "hi": "क्वेसो फ्रेस्को", "he": "קסו פרסקו"},
    {"fr": "Haricots noirs", "en": "Black beans", "ja": "黒インゲン", "ko": "검은콩", "zh": "黑豆", "ru": "Чёрная фасоль", "ar": "فاصولياء سوداء", "de": "Schwarze Bohnen", "es": "Frijoles negros", "it": "Fagioli neri", "pt": "Feijão preto", "hi": "काली फलियाँ", "th": "ถั่วดำ", "vi": "Đậu đen", "he": "שעועית שחורה", "id": "Kacang hitam"},
    {"fr": "Banane plantain", "en": "Plantain", "ja": "プランテン", "ko": "플랜틴", "zh": "大蕉", "ru": "Плантан", "ar": "موز الجنة", "de": "Kochbanane", "es": "Plátano macho", "it": "Platano", "pt": "Banana-da-terra", "hi": "प्लांटेन", "th": "กล้วยดิบ", "vi": "Chuối già", "he": "פלנטיין", "id": "Pisang tanduk"},
    {"fr": "Manchego", "en": "Manchego", "ja": "マンチェゴ", "ko": "만체고", "zh": "曼chego奶酪", "ru": "Манчего", "ar": "مانتشيغو", "de": "Manchego", "es": "Manchego", "it": "Manchego", "pt": "Manchego", "hi": "मान्चेगो", "he": "מנצ'גו"},
    {"fr": "Burrata", "en": "Burrata", "ja": "ブラータ", "ko": "부라타", "zh": "布拉塔", "ru": "Буррата", "ar": "بوراتا", "de": "Burrata", "es": "Burrata", "it": "Burrata", "pt": "Burrata", "hi": "बुराटा", "he": "בוראטה"},
    {"fr": "Prosciutto", "en": "Prosciutto", "ja": "プロシュット", "ko": "프로슈토", "zh": "帕尔马火腿", "ru": "Прошутто", "ar": "بروشوتو", "de": "Prosciutto", "es": "Prosciutto", "it": "Prosciutto", "pt": "Presunto cru", "hi": "प्रोशूटो", "he": "פרושוטו"},
    {"fr": "Passata", "en": "Passata", "ja": "パッサータ", "ko": "파사타", "zh": "番茄泥", "ru": "Пассата", "ar": "باساتا", "de": "Passata", "es": "Passata", "it": "Passata", "pt": "Passata", "hi": "पसाता", "he": "פאסאטה"},
    {"fr": "Pancetta", "en": "Pancetta", "ja": "パンチェッタ", "ko": "판체타", "zh": "意式培根", "ru": "Панчетта", "ar": "بانتشيتا", "de": "Pancetta", "es": "Pancetta", "it": "Pancetta", "pt": "Pancetta", "hi": "पन्चेट्टा", "he": "פנצ'טה"},
    {"fr": "Pecorino", "en": "Pecorino", "ja": "ペコリーノ", "ko": "페코리노", "zh": "佩科里诺", "ru": "Пекорино", "ar": "بيكورينو", "de": "Pecorino", "es": "Pecorino", "it": "Pecorino", "pt": "Pecorino", "hi": "पेकोरिनो", "he": "פקורינו"},
    {"fr": "Ricotta", "en": "Ricotta", "ja": "リコッタ", "ko": "리코타", "zh": "里科塔", "ru": "Рикотта", "ar": "ريكوتا", "de": "Ricotta", "es": "Ricotta", "it": "Ricotta", "pt": "Ricota", "hi": "रिकोटा", "he": "ריקוטה"},
    {"fr": "Mascarpone", "en": "Mascarpone", "ja": "マスカルポーネ", "ko": "마스카포네", "zh": "马斯卡彭", "ru": "Маскарпоне", "ar": "ماسكاربوني", "de": "Mascarpone", "es": "Mascarpone", "it": "Mascarpone", "pt": "Mascarpone", "hi": "मास्करपोन", "he": "מסקרפונה"},
    {"fr": "Gnocchi", "en": "Gnocchi", "ja": "ニョッキ", "ko": "뇨키", "zh": "意大利团子", "ru": "Ньокки", "ar": "نيوكي", "de": "Gnocchi", "es": "Ñoquis", "it": "Gnocchi", "pt": "Nhoque", "hi": "न्योकी", "he": "ניוקי"},
    {"fr": "Polenta", "en": "Polenta", "ja": "ポレンタ", "ko": "폴렌타", "zh": "玉米粥", "ru": "Полента", "ar": "بولينتا", "de": "Polenta", "es": "Polenta", "it": "Polenta", "pt": "Polenta", "hi": "पोलेंटा", "he": "פולנטה"},
    {"fr": "Vinaigre balsamique", "en": "Balsamic vinegar", "ja": "バルサミコ酢", "ko": "발사믹 식초", "zh": "香醋", "ru": "Бальзамический уксус", "ar": "خل بلسمي", "de": "Balsamico", "es": "Vinagre balsámico", "it": "Aceto balsamico", "pt": "Vinagre balsâmico", "hi": "बाल्समिक सिरका", "th": "บัลซามิก", "vi": "Giấm balsamic", "he": "חומץ בלסמי", "nl": "Balsamicoazijn"},
    {"fr": "Ciabatta", "en": "Ciabatta", "ja": "チャバタ", "ko": "치아바타", "zh": "夏巴塔", "ru": "Чиабатта", "ar": "شياباتا", "de": "Ciabatta", "es": "Ciabatta", "it": "Ciabatta", "pt": "Ciabatta", "hi": "चियाबट्टा", "he": "צ'באטה"},
    {"fr": "Pierogi", "en": "Pierogi", "ja": "ピエロギ", "ko": "피에로기", "zh": "波兰饺子", "ru": "Пироги", "ar": "بيروغي", "de": "Piroggen", "es": "Pierogi", "hi": "पिएरोगी", "pl": "Pierogi", "uk": "Вареники", "cs": "Pirohy", "he": "פירוגי"},
    {"fr": "Kabanos", "en": "Kabanos", "ja": "カバーノス", "ko": "카바노스", "zh": "卡巴诺斯香肠", "ru": "Кабаносы", "ar": "كابانوس", "de": "Kabanos", "es": "Kabanos", "pl": "Kabanosy", "he": "קבנוס"},
    {"fr": "Saucisse polonaise", "en": "Kielbasa", "ja": "キエルバサ", "ko": "킬바사", "zh": "波兰香肠", "ru": "Келбаса", "ar": "كيلباسا", "de": "Kielbasa", "es": "Kielbasa", "pl": "Kiełbasa", "he": "קיילבסה"},
    {"fr": "Sambal", "en": "Sambal", "ja": "サンバル", "ko": "삼발", "zh": "叁巴酱", "ru": "Самбал", "ar": "سامبال", "de": "Sambal", "es": "Sambal", "hi": "संबल", "th": "ซัมบัล", "vi": "Sambal", "id": "Sambal", "ms": "Sambal", "he": "סמבל"},
    {"fr": "Kecap manis", "en": "Kecap manis", "ja": "ケチャップマニス", "ko": "케찹 마니스", "zh": "甜酱油", "ru": "Кечап манис", "ar": "كيتشاب مانيس", "de": "Kecap manis", "es": "Kecap manis", "hi": "केचप मानिस", "id": "Kecap manis", "ms": "Kicap manis", "he": "קצ'אפ מניס"},
    {"fr": "Saté", "en": "Satay", "ja": "サテ", "ko": "사테", "zh": "沙嗲", "ru": "Сате", "ar": "ساتيه", "de": "Satay", "es": "Satay", "hi": "सते", "th": "สะเต๊ะ", "vi": "Sate", "id": "Sate", "ms": "Satay", "he": "סאטה"},
    {"fr": "Pandan", "en": "Pandan", "ja": "パンダン", "ko": "판단", "zh": "香兰叶", "ru": "Пандан", "ar": "باندان", "de": "Pandan", "es": "Pandan", "hi": "पंडान", "th": "ใบเตย", "vi": "Lá dứa", "id": "Pandan", "ms": "Pandan", "he": "פנדן"},
    {"fr": "Krupuk", "en": "Krupuk", "ja": "クルプック", "ko": "크루푹", "zh": "虾片", "ru": "Крупук", "ar": "كروبك", "de": "Krupuk", "es": "Krupuk", "id": "Kerupuk", "ms": "Keropok", "he": "קרופוק"},
    {"fr": "Knäckebröd", "en": "Crispbread", "ja": "クリスプブレッド", "ko": "크리스프브레드", "zh": "脆饼", "ru": "Хлебцы", "ar": "خبز مقرمش", "de": "Knäckebrot", "es": "Pan crujiente", "sv": "Knäckebröd", "da": "Knækbrød", "nb": "Knekkebrød", "fi": "Näkkileipä", "nl": "Knäckebröd", "pl": "Pieczywo chrupkie", "he": "לחם פריך"},
    {"fr": "Airelles", "en": "Lingonberries", "ja": "リンゴンベリー", "ko": "링곤베리", "zh": "越橘", "ru": "Брусника", "ar": "توت عنب الدب", "de": "Preiselbeeren", "es": "Arándanos rojos", "sv": "Lingon", "da": "Tyttebær", "nb": "Tyttebær", "fi": "Puolukat", "pl": "Borówki brusznice", "he": "לינגונברי"},
    {"fr": "Gravlax", "en": "Gravlax", "ja": "グラブラックス", "ko": "그라블락스", "zh": "渍三文鱼", "ru": "Гравлакс", "ar": "غرافلaks", "de": "Gravlax", "es": "Gravlax", "sv": "Gravad lax", "da": "Gravad laks", "nb": "Gravlaks", "fi": "Graavilohi", "he": "גרבלקס"},
    {"fr": "Brunost", "en": "Brown cheese", "ja": "ブラウンチーズ", "ko": "브라운 치즈", "zh": "棕色奶酪", "ru": "Брюност", "ar": "جبن بني", "de": "Braunkäse", "es": "Queso marrón", "nb": "Brunost", "sv": "Mesost", "da": "Myseost", "fi": "Mesjuusto", "he": "גבינה חומה"},
    {"fr": "Hareng mariné", "en": "Pickled herring", "ja": "マリネニシン", "ko": "절인 청어", "zh": "腌鲱鱼", "ru": "Маринованная селёдка", "ar": "رنجة متبلة", "de": "Matjes", "es": "Arenque en escabeche", "sv": "Inlagd sill", "da": "Sild i lage", "nb": "Sildesalat", "fi": "Silli", "nl": "Zure haring", "pl": "Śledź marynowany", "he": "הרינג כבוש"},
    {"fr": "Boulettes de viande", "en": "Meatballs", "ja": "ミートボール", "ko": "미트볼", "zh": "肉丸", "ru": "Фрикадельки", "ar": "كرات اللحم", "de": "Fleischbällchen", "es": "Albóndigas", "it": "Polpette", "pt": "Almôndegas", "hi": "मीटबॉल", "sv": "Köttbullar", "da": "Frikadeller", "nb": "Kjøttkaker", "fi": "Lihapullat", "nl": "Gehaktballen", "pl": "Klopsiki", "he": "קציצות"},
    {"fr": "Baked beans", "en": "Baked beans", "ja": "ベイクドビーンズ", "ko": "베이크드빈", "zh": "焗豆", "ru": "Фасоль в томате", "ar": "فاصولياء مطبوخة", "de": "Baked Beans", "es": "Judías horneadas", "hi": "बेक्ड बीन्स", "he": "שעועית אפויה"},
    {"fr": "Digestives", "en": "Digestive biscuits", "ja": "ダイジェスティブ", "ko": "다이제스티브", "zh": "消化饼干", "ru": "Печенье digestive", "ar": "بسكويت دايجستف", "de": "Digestive-Kekse", "es": "Galletas digestive", "hi": "डाइजेस्टिव बिस्कुट", "he": "ביסקוויט דייג'סטיב"},
    {"fr": "Flocons d'avoine", "en": "Oats / porridge", "ja": "オートミール", "ko": "오트밀", "zh": "燕麦", "ru": "Овсянка", "ar": "شوفان", "de": "Haferflocken", "es": "Copos de avena", "it": "Fiocchi d'avena", "pt": "Aveia", "hi": "जई", "th": "ข้าวโอ๊ต", "vi": "Yến mạch", "tr": "Yulaf", "el": "Βρώμη", "he": "שיבולת שועל", "uk": "Вівсянка", "pl": "Płatki owsiane", "id": "Havermout", "nl": "Havermout", "sv": "Havregryn"},
    {"fr": "Cidre", "en": "Cider", "ja": "サイダー（リンゴ酒）", "ko": "사이다 (사과주)", "zh": "苹果酒", "ru": "Сидр", "ar": "سيدر", "de": "Cidre", "es": "Sidra", "it": "Sidro", "pt": "Sidra", "hi": "सेब की शराब", "he": "סיידר", "nl": "Cider", "sv": "Cider"},
    {"fr": "Herbes de Provence", "en": "Herbes de Provence", "ja": "エルブ・ド・プロヴァンス", "ko": "프로방스 허브", "zh": "普罗旺斯香草", "ru": "Прованские травы", "ar": "أعشاب بروفانس", "de": "Kräuter der Provence", "es": "Hierbas provenzales", "it": "Erbe di Provenza", "pt": "Ervas de Provença", "hi": "प्रोवेंस जड़ी-बूटियाँ", "he": "עשבי פרובנס", "nl": "Provençaalse kruiden"},
    {"fr": "Magret de canard", "en": "Duck breast", "ja": "鴨の胸肉", "ko": "오리 가슴살", "zh": "鸭胸", "ru": "Утиная грудка", "ar": "صدر البط", "de": "Entenbrust", "es": "Magret de pato", "it": "Petto d'anatra", "pt": "Peito de pato", "hi": "बत्तख का सीना", "he": "חזה ברווז"},
    {"fr": "Ajvar", "en": "Ajvar", "ja": "アイヴァール", "ko": "아이바르", "zh": "艾瓦尔酱", "ru": "Айвар", "ar": "أجفار", "de": "Ajvar", "es": "Ajvar", "hi": "अजवार", "hr": "Ajvar", "sr": "Ајвар", "sl": "Ajvar", "ro": "Zacuscă", "he": "אייוור", "hu": "Ajvár"},
    {"fr": "Burek", "en": "Burek", "ja": "ブレク", "ko": "부렉", "zh": "布雷克饼", "ru": "Бурек", "ar": "بوريك", "de": "Börek", "es": "Burek", "hi": "बुरेक", "hr": "Burek", "sr": "Бурек", "tr": "Börek", "he": "בורקס"},
    {"fr": "Kajmak", "en": "Kajmak", "ja": "カイマク", "ko": "카이막", "zh": "卡伊马克", "ru": "Каймак", "ar": "قيمق", "de": "Kajmak", "hr": "Kajmak", "sr": "Кајмак", "tr": "Kaymak", "he": "קיימק"},
]

# Emojis par nom FR (catalogue).
EMOJI: dict[str, str] = {
    "Riz rond": "🍚", "Nouilles ramen": "🍜", "Gyoza": "🥟", "Feuilles de gyoza": "🥟",
    "Onigiri": "🍙", "Yakitori": "🍢", "Miso": "🥣", "Natto": "🫘", "Kombu": "🌿",
    "Katsuobushi": "🐟", "Udon": "🍜", "Soba": "🍜", "Furikake": "🧂", "Umeboshi": "🍑",
    "Daikon": "🥬", "Shiso": "🍃", "Matcha": "🍵", "Mochi": "🍡", "Ponzu": "🍋",
    "Sashimi": "🍣", "Ciboule": "🧅", "Panko": "🍞", "Sauce teriyaki": "🍶",
    "Sauce tonkatsu": "🍶", "Shiitake": "🍄", "Enoki": "🍄", "Yuzu": "🍋",
    "Konjac": "⬜", "Thé sencha": "🍵", "Shochu": "🍶", "Kamaboko": "🍥", "Takuan": "🟡",
    "Bulgogi": "🥩", "Gochujang": "🌶️", "Gochugaru": "🌶️", "Soju": "🍶", "Doenjang": "🥣",
    "Samgyeopsal": "🥓", "Tteokbokki": "🌶️", "Tteok": "🍡", "Japchae": "🍜", "Galbi": "🥩",
    "Ssamjang": "🥣", "Feuilles de périlla": "🍃", "Radis coréen": "🥬", "Mandu": "🥟",
    "Ramyeon": "🍜", "Makgeolli": "🥛", "Banchan": "🥗", "Galette de poisson": "🐟",
    "Nouilles de patate douce": "🍜", "Huile de périlla": "🛢️", "Poire asiatique": "🍐",
    "Germes de soja": "🌱", "Gim": "🍙", "Sundubu": "🍲", "Poisson séché": "🐟",
    "Betterave": "🟣", "Smetana": "🥛", "Sarrasin": "🌾", "Pelmeni": "🥟", "Pain noir": "🍞",
    "Hareng": "🐟", "Kvas": "🥤", "Chou fermenté": "🥬", "Kéfir": "🥛", "Tvorog": "🧀",
    "Blinis": "🥞", "Huile de tournesol": "🌻", "Raifort": "🌱", "Vodka": "🥃",
    "Caviar": "🖤", "Vareniki": "🥟", "Adjika": "🌶️", "Graines de tournesol": "🌻",
    "Chachlik": "🍢", "Pain de seigle": "🍞", "Couscous": "🌾", "Tajine": "🍲",
    "Harissa": "🌶️", "Citrons confits": "🍋", "Labneh": "🥛", "Pain pita": "🫓",
    "Falafel": "🧆", "Ras el hanout": "🧂", "Zaatar": "🌿", "Sumac": "🔴",
    "Mélasse de grenade": "🍷", "Freekeh": "🌾", "Fèves": "🫘",
    "Eau de fleur d'oranger": "🌸", "Eau de rose": "🌹", "Maamoul": "🍪", "Baklava": "🧁",
    "Boulgour": "🌾", "Feuilles de brick": "🫓", "Safran": "🟡", "Cumin": "🧂",
    "Thé à la menthe": "🍵", "Amlou": "🥜", "Msemen": "🫓", "Khobz": "🍞", "Arak": "🥃",
    "Smen": "🧈", "Pastilla": "🥧", "Nouilles chinoises": "🍜", "Sauce d'huître": "🦪",
    "Pak choi": "🥬", "Anis étoilé": "⭐", "Baozi": "🥟", "Wonton": "🥟",
    "Vin de Shaoxing": "🍶", "Cinq-épices": "🧂", "Huile de piment": "🌶️",
    "Doubanjiang": "🌶️", "Sauce hoisin": "🥫", "Oreilles de Judas": "🍄",
    "Liseron d'eau": "🥬", "Litchi": "🍒", "Saucisse chinoise": "🌭", "Farine de riz": "🌾",
    "Garam masala": "🧂", "Curcuma": "🟡", "Cardamome": "🟢", "Ghee": "🧈", "Naan": "🫓",
    "Chapati": "🫓", "Paneer": "🧀", "Chutney": "🥭", "Lassi": "🥛", "Fenugrec": "🌱",
    "Feuilles de curry": "🍃", "Gombo": "🟢", "Tamarin": "🟤", "Papadum": "🍪",
    "Asafoetida": "🧂", "Huile de moutarde": "🛢️", "Masala chai": "🍵", "Galanga": "🫚",
    "Feuilles de kaffir": "🍃", "Basilic thaï": "🌿", "Sucre de palme": "🍯",
    "Pâte de crevettes": "🦐", "Nouilles de riz": "🍜", "Mangue verte": "🥭",
    "Citron vert": "🍋", "Piment oiseau": "🌶️", "Papaye verte": "🟢", "Nouilles pho": "🍜",
    "Feuilles de riz": "🫓", "Banh mi": "🥖", "Yaourt grec": "🥛", "Halloumi": "🧀",
    "Feuilles de vigne": "🍃", "Viande kebab": "🥙", "Sucuk": "🌭", "Simit": "🥯",
    "Ayran": "🥛", "Raki": "🥃", "Ouzo": "🥃", "Tzatziki": "🥒", "Olives kalamata": "🫒",
    "Yufka": "🫓", "Bretzel": "🥨", "Quark": "🧀", "Spätzle": "🍝", "Chorizo": "🌭",
    "Jambon serrano": "🥓", "Jalapeños": "🌶️", "Paprika fumé": "🌶️", "Queso fresco": "🧀",
    "Haricots noirs": "🫘", "Banane plantain": "🍌", "Manchego": "🧀", "Burrata": "🧀",
    "Prosciutto": "🥓", "Passata": "🍅", "Pancetta": "🥓", "Pecorino": "🧀",
    "Ricotta": "🧀", "Mascarpone": "🧀", "Gnocchi": "🍝", "Polenta": "🌽",
    "Vinaigre balsamique": "🍾", "Ciabatta": "🍞", "Pierogi": "🥟", "Kabanos": "🌭",
    "Saucisse polonaise": "🌭", "Sambal": "🌶️", "Kecap manis": "🥫", "Saté": "🍢",
    "Pandan": "🍃", "Krupuk": "🍘", "Knäckebröd": "🍞", "Airelles": "🔴", "Gravlax": "🐟",
    "Brunost": "🧀", "Hareng mariné": "🐟", "Boulettes de viande": "🍖",
    "Baked beans": "🥫", "Digestives": "🍪", "Flocons d'avoine": "🥣", "Cidre": "🍎",
    "Herbes de Provence": "🌿", "Magret de canard": "🦆", "Ajvar": "🌶️", "Burek": "🥧",
    "Kajmak": "🥛",
    # existants souvent utilisés
    "Algues nori": "🍙", "Algues wakame": "🌿", "Wasabi": "🟢", "Sauce soja": "🍶",
    "Mirin": "🍶", "Saké": "🍶", "Dashi": "🥣", "Tempura": "🍤", "Edamame": "🟢",
    "Tofu": "⬜", "Gingembre mariné": "🩷", "Gingembre": "🫚", "Huile de sésame": "🛢️",
    "Sésame": "⚪", "Kimchi": "🥬", "Chou chinois": "🥬", "Aneth": "🌿", "Cornichons": "🥒",
    "Houmous": "🫘", "Tahini": "🥜", "Dattes": "🌴", "Menthe": "🌿", "Merguez": "🌭",
    "Semoule": "🌾", "Pois chiches": "🫘", "Agneau": "🍖", "Olives": "🫒",
    "Huile d'olive": "🫒", "Citronnelle": "🌿", "Lait de coco": "🥥", "Nuoc-mâm": "🐟",
    "Riz glutineux": "🍚", "Riz basmati": "🍚", "Riz thaï": "🍚", "Curry rouge": "🌶️",
    "Curry vert": "🌶️", "Feta": "🧀", "Mozzarella": "🧀", "Parmesan": "🧀",
    "Tortillas": "🫓", "Avocats": "🥑", "Coriandre fraîche": "🌿", "Camembert": "🧀",
    "Roquefort": "🧀", "Comté": "🧀", "Choucroute": "🥬", "Bacon": "🥓", "Cheddar": "🧀",
    "Saumon fumé": "🐟", "Tempeh": "🫘", "Dim sum": "🥟", "Ail": "🧄", "Thé": "🍵",
    "Café": "☕", "Œufs": "🥚", "Pain": "🍞", "Beurre": "🧈", "Confiture": "🍯",
    "Lait": "🥛", "Yaourt": "🥛", "Pommes de terre": "🥔", "Chou": "🥬",
    "Mayonnaise": "🫙", "Poulet": "🍗", "Saumon": "🐟", "Crevettes": "🦐",
    "Lentilles corail": "🟠", "Épinards": "🥬", "Concombre": "🥒", "Tomates": "🍅",
    "Oignons": "🧅", "Aubergine": "🍆", "Poivrons": "🫑", "Basilic": "🌿",
}

# Profil → liste « Spécialités » (noms FR).
LOCAL_LISTS: dict[str, list[str]] = {
    "ja": [
        "Riz rond", "Algues nori", "Wasabi", "Sauce soja", "Mirin", "Saké",
        "Nouilles ramen", "Gyoza", "Onigiri", "Yakitori", "Miso", "Natto",
        "Kombu", "Katsuobushi", "Udon", "Soba", "Furikake", "Umeboshi",
        "Daikon", "Shiso", "Matcha", "Mochi", "Ponzu", "Sashimi", "Ciboule",
        "Panko", "Sauce teriyaki", "Vinaigre de riz", "Shiitake", "Enoki",
        "Yuzu", "Konjac", "Edamame", "Tofu", "Dashi", "Tempura",
        "Gingembre mariné", "Algues wakame", "Thé sencha", "Shochu",
        "Kamaboko", "Takuan",
    ],
    "ko": [
        "Riz rond", "Kimchi", "Bulgogi", "Gochujang", "Gochugaru", "Soju",
        "Doenjang", "Samgyeopsal", "Tteokbokki", "Tteok", "Japchae", "Galbi",
        "Ssamjang", "Feuilles de périlla", "Radis coréen", "Mandu", "Ramyeon",
        "Makgeolli", "Banchan", "Galette de poisson", "Nouilles de patate douce",
        "Huile de sésame", "Huile de périlla", "Poire asiatique", "Germes de soja",
        "Gim", "Tofu", "Chou chinois", "Ail", "Gingembre", "Sauce soja",
        "Sésame", "Poisson séché", "Sundubu", "Ciboule", "Aneth",
    ],
    "zh": [
        "Riz rond", "Nouilles chinoises", "Sauce soja", "Sauce d'huître",
        "Pak choi", "Gingembre", "Ciboule", "Anis étoilé", "Baozi", "Wonton",
        "Vin de Shaoxing", "Cinq-épices", "Huile de piment", "Doubanjiang",
        "Sauce hoisin", "Oreilles de Judas", "Liseron d'eau", "Litchi",
        "Saucisse chinoise", "Farine de riz", "Tofu", "Edamame", "Shiitake",
        "Dim sum", "Germes de soja", "Huile de sésame", "Vinaigre de riz",
        "Algues nori",
    ],
    "ru": [
        "Betterave", "Smetana", "Aneth", "Sarrasin", "Pelmeni", "Pain noir",
        "Hareng", "Kvas", "Chou fermenté", "Kéfir", "Tvorog", "Blinis",
        "Huile de tournesol", "Raifort", "Vodka", "Caviar", "Vareniki",
        "Adjika", "Graines de tournesol", "Chachlik", "Cornichons", "Chou",
        "Pommes de terre", "Pain de seigle", "Saumon fumé", "Mayonnaise",
        "Aneth", "Ail",
    ],
    "ar": [
        "Couscous", "Semoule", "Tajine", "Harissa", "Citrons confits", "Dattes",
        "Menthe", "Houmous", "Falafel", "Labneh", "Pain pita", "Ras el hanout",
        "Zaatar", "Sumac", "Mélasse de grenade", "Freekeh", "Fèves",
        "Eau de fleur d'oranger", "Eau de rose", "Maamoul", "Baklava",
        "Merguez", "Agneau", "Pois chiches", "Tahini", "Boulgour",
        "Feuilles de brick", "Safran", "Cumin", "Thé à la menthe", "Olives",
        "Huile d'olive", "Amlou", "Msemen", "Khobz", "Pastilla",
    ],
    "he": [
        "Houmous", "Falafel", "Pain pita", "Labneh", "Tahini", "Zaatar",
        "Sumac", "Mélasse de grenade", "Pois chiches", "Dattes", "Menthe",
        "Couscous", "Boulgour", "Halloumi", "Feta", "Olives kalamata",
        "Huile d'olive", "Citrons confits", "Feuilles de vigne", "Baklava",
        "Agneau", "Yaourt grec", "Cumin", "Safran", "Citron vert",
    ],
    "hi": [
        "Riz basmati", "Lentilles corail", "Garam masala", "Curcuma", "Cumin",
        "Cardamome", "Ghee", "Naan", "Chapati", "Paneer", "Chutney", "Lassi",
        "Fenugrec", "Feuilles de curry", "Gombo", "Tamarin", "Papadum",
        "Asafoetida", "Huile de moutarde", "Masala chai", "Yaourt", "Ail",
        "Gingembre", "Oignons", "Tomates", "Coriandre fraîche",
    ],
    "th": [
        "Riz thaï", "Riz glutineux", "Lait de coco", "Galanga", "Citronnelle",
        "Feuilles de kaffir", "Curry rouge", "Curry vert", "Nuoc-mâm",
        "Nouilles de riz", "Basilic thaï", "Sucre de palme", "Pâte de crevettes",
        "Mangue verte", "Citron vert", "Piment oiseau", "Papaye verte",
        "Coriandre fraîche", "Ciboule", "Sauce d'huître", "Germes de soja",
    ],
    "vi": [
        "Nouilles pho", "Nuoc-mâm", "Feuilles de riz", "Citronnelle",
        "Herbes", "Coriandre fraîche", "Menthe", "Basilic thaï", "Citron vert",
        "Germes de soja", "Banh mi", "Pâte de crevettes", "Anis étoilé",
        "Nouilles de riz", "Poisson séché", "Ciboule", "Gingembre", "Ail",
        "Sauce hoisin", "Huile de piment",
    ],
    "tr": [
        "Viande kebab", "Yaourt grec", "Sucuk", "Simit", "Ayran", "Raki",
        "Yufka", "Feuilles de vigne", "Baklava", "Boulgour", "Sumac",
        "Mélasse de grenade", "Aubergine", "Agneau", "Halloumi", "Olives",
        "Huile d'olive", "Thé", "Cumin", "Poivrons", "Tomates", "Ail",
    ],
    "el": [
        "Feta", "Yaourt grec", "Pain pita", "Halloumi", "Feuilles de vigne",
        "Tzatziki", "Ouzo", "Olives kalamata", "Huile d'olive", "Aubergine",
        "Agneau", "Citron", "Ail", "Origan" if False else "Herbes",
        "Concombre", "Tomates", "Baklava", "Safran",
    ],
    "es": [
        "Chorizo", "Jambon serrano", "Huile d'olive", "Paprika fumé",
        "Manchego", "Ail", "Tomates", "Poivrons", "Pois chiches", "Safran",
        "Riz rond", "Olives", "Citron vert", "Avocats", "Coriandre fraîche",
        "Jalapeños", "Tortillas", "Queso fresco", "Haricots noirs",
        "Banane plantain",
    ],
    "pt": [
        "Haricots noirs", "Riz rond", "Ail", "Coriandre fraîche", "Citron vert",
        "Banane plantain", "Huile d'olive", "Café", "Pain", "Saumon",
        "Chorizo", "Manioc" if False else "Farine", "Lait de coco", "Tamarin",
        "Avocats", "Tomates", "Oignons", "Poivrons",
    ],
    "it": [
        "Mozzarella", "Parmesan", "Burrata", "Prosciutto", "Passata",
        "Pancetta", "Pecorino", "Ricotta", "Mascarpone", "Pesto", "Gnocchi",
        "Polenta", "Vinaigre balsamique", "Ciabatta", "Basilic", "Huile d'olive",
        "Tomates", "Ail", "Olives",
    ],
    "de": [
        "Pain de seigle", "Bretzel", "Quark", "Spätzle", "Choucroute",
        "Moutarde", "Beurre", "Lait", "Pommes de terre", "Saumon fumé",
        "Hareng", "Pain noir", "Boulettes de viande", "Aneth", "Cornichons",
        "Fromage", "Bière",
    ],
    "nordic": [
        "Saumon fumé", "Hareng mariné", "Knäckebröd", "Betterave", "Aneth",
        "Boulettes de viande", "Airelles", "Pommes de terre", "Pain de seigle",
        "Gravlax", "Brunost", "Beurre", "Lait", "Café", "Flocons d'avoine",
    ],
    "pl": [
        "Pierogi", "Saucisse polonaise", "Kabanos", "Chou fermenté", "Smetana",
        "Betterave", "Aneth", "Pain de seigle", "Raifort", "Sarrasin",
        "Pommes de terre", "Chou", "Cornichons", "Kéfir", "Tvorog",
    ],
    "balkan": [
        "Ajvar", "Burek", "Kajmak", "Viande kebab", "Poivrons", "Yaourt",
        "Pain pita", "Agneau", "Ail", "Tomates", "Huile d'olive", "Feta",
        "Baklava", "Aubergine",
    ],
    "id": [
        "Riz rond", "Sambal", "Tempeh", "Kecap manis", "Saté", "Pandan",
        "Krupuk", "Lait de coco", "Citronnelle", "Galanga", "Pâte de crevettes",
        "Piment oiseau", "Tofu", "Germes de soja", "Citron vert", "Ciboule",
        "Nouilles de riz",
    ],
    "en": [
        "Bacon", "Baked beans", "Cheddar", "Thé", "Digestives", "Flocons d'avoine",
        "Pain", "Beurre", "Lait", "Pommes de terre", "Poulet", "Saucisses" if False else "Steak",
        "Pâtes", "Riz", "Tomates", "Oignons", "Cidre", "Saumon fumé",
    ],
    "fr": [
        "Camembert", "Roquefort", "Comté", "Herbes de Provence", "Baguette",
        "Magret de canard", "Cornichons", "Crème fraîche", "Vin", "Huile d'olive",
        "Moutarde", "Thé", "Café", "Beurre", "Jambon",
    ],
}

# Nettoyage des sentinelles `if False`.
LOCAL_LISTS["el"] = [
    "Feta", "Yaourt grec", "Pain pita", "Halloumi", "Feuilles de vigne",
    "Tzatziki", "Ouzo", "Olives kalamata", "Huile d'olive", "Aubergine",
    "Agneau", "Citrons", "Ail", "Herbes", "Concombre", "Tomates", "Baklava", "Safran",
]
LOCAL_LISTS["pt"] = [
    "Haricots noirs", "Riz rond", "Ail", "Coriandre fraîche", "Citron vert",
    "Banane plantain", "Huile d'olive", "Café", "Pain", "Farine",
    "Lait de coco", "Tamarin", "Avocats", "Tomates", "Oignons", "Poivrons",
    "Bananes", "Manioc" if False else "Sucre",
]
LOCAL_LISTS["pt"] = [
    "Haricots noirs", "Riz rond", "Ail", "Coriandre fraîche", "Citron vert",
    "Banane plantain", "Huile d'olive", "Café", "Pain", "Farine",
    "Lait de coco", "Tamarin", "Avocats", "Tomates", "Oignons", "Poivrons",
    "Bananes", "Sucre",
]
LOCAL_LISTS["en"] = [
    "Bacon", "Baked beans", "Cheddar", "Thé", "Digestives", "Flocons d'avoine",
    "Pain", "Beurre", "Lait", "Pommes de terre", "Poulet", "Steak",
    "Pâtes", "Riz", "Tomates", "Oignons", "Cidre", "Saumon fumé",
]
LOCAL_LISTS["de"] = [
    "Pain de seigle", "Bretzel", "Quark", "Spätzle", "Choucroute",
    "Moutarde", "Beurre", "Lait", "Pommes de terre", "Saumon fumé",
    "Hareng", "Pain noir", "Boulettes de viande", "Aneth", "Cornichons",
    "Fromage", "Bière",
]

# Extras à fusionner dans les rayons existants (en plus de Spécialités).
EXTRAS: dict[str, dict[str, list[str]]] = {
    "ja": {
        "fruits": ["Daikon", "Shiso", "Yuzu", "Ciboule", "Shiitake", "Enoki", "Gingembre"],
        "dairy": ["Tofu", "Tofu soyeux", "Natto", "Edamame"],
        "bakery": ["Onigiri", "Mochi", "Panko"],
        "meat": ["Sashimi", "Yakitori", "Saumon", "Crevettes", "Kamaboko"],
        "grocery": ["Riz rond", "Sauce soja", "Miso", "Mirin", "Nouilles ramen", "Udon", "Soba", "Algues nori", "Wasabi", "Dashi", "Kombu", "Furikake", "Umeboshi", "Vinaigre de riz"],
        "beverages": ["Thé sencha", "Saké", "Matcha", "Shochu"],
        "frozen": ["Gyoza", "Edamame", "Tempura"],
    },
    "ko": {
        "fruits": ["Chou chinois", "Radis coréen", "Feuilles de périlla", "Poire asiatique", "Germes de soja", "Ciboule", "Ail"],
        "dairy": ["Tofu", "Sundubu", "Kimchi"],
        "bakery": ["Tteok", "Gim"],
        "meat": ["Bulgogi", "Samgyeopsal", "Galbi", "Mandu", "Galette de poisson", "Poisson séché"],
        "grocery": ["Riz rond", "Gochujang", "Gochugaru", "Doenjang", "Ssamjang", "Huile de sésame", "Nouilles de patate douce", "Ramyeon", "Sauce soja"],
        "beverages": ["Soju", "Makgeolli"],
        "frozen": ["Mandu", "Ramyeon", "Tteokbokki"],
    },
    "zh": {
        "fruits": ["Pak choi", "Gingembre", "Ciboule", "Liseron d'eau", "Litchi", "Shiitake"],
        "dairy": ["Tofu", "Edamame"],
        "bakery": ["Baozi", "Farine de riz"],
        "meat": ["Wonton", "Saucisse chinoise", "Crevettes", "Canard"],
        "grocery": ["Nouilles chinoises", "Sauce soja", "Sauce d'huître", "Cinq-épices", "Anis étoilé", "Doubanjiang", "Huile de piment", "Sauce hoisin"],
        "beverages": ["Thé", "Vin de Shaoxing"],
        "frozen": ["Dim sum", "Wonton", "Baozi"],
    },
    "ru": {
        "fruits": ["Betterave", "Aneth", "Chou", "Pommes de terre", "Raifort"],
        "dairy": ["Smetana", "Kéfir", "Tvorog"],
        "bakery": ["Pain noir", "Pain de seigle", "Blinis"],
        "meat": ["Hareng", "Chachlik", "Saumon fumé"],
        "grocery": ["Sarrasin", "Huile de tournesol", "Chou fermenté", "Adjika", "Graines de tournesol", "Mayonnaise"],
        "beverages": ["Kvas", "Vodka", "Kéfir"],
        "frozen": ["Pelmeni", "Vareniki", "Blinis"],
    },
    "ar": {
        "fruits": ["Dattes", "Menthe", "Citrons confits", "Citrons", "Tomates", "Ail"],
        "dairy": ["Labneh", "Yaourt"],
        "bakery": ["Pain pita", "Khobz", "Msemen", "Feuilles de brick"],
        "meat": ["Agneau", "Merguez", "Poulet"],
        "grocery": ["Couscous", "Semoule", "Harissa", "Ras el hanout", "Zaatar", "Pois chiches", "Tahini", "Boulgour", "Cumin", "Safran", "Huile d'olive"],
        "beverages": ["Thé à la menthe", "Eau de rose", "Eau de fleur d'oranger"],
        "frozen": ["Feuilles de brick", "Falafel"],
    },
    "he": {
        "fruits": ["Dattes", "Citron vert", "Concombre", "Tomates"],
        "dairy": ["Labneh", "Halloumi", "Feta", "Yaourt grec"],
        "bakery": ["Pain pita"],
        "meat": ["Agneau", "Poulet"],
        "grocery": ["Houmous", "Tahini", "Zaatar", "Sumac", "Pois chiches", "Couscous", "Huile d'olive"],
        "beverages": ["Thé à la menthe"],
    },
    "hi": {
        "fruits": ["Gombo", "Coriandre fraîche", "Gingembre", "Ail", "Oignons", "Tomates"],
        "dairy": ["Paneer", "Yaourt", "Ghee", "Lassi"],
        "bakery": ["Naan", "Chapati", "Papadum"],
        "meat": ["Poulet", "Agneau"],
        "grocery": ["Riz basmati", "Lentilles corail", "Garam masala", "Curcuma", "Cumin", "Cardamome", "Fenugrec", "Tamarin", "Huile de moutarde"],
        "beverages": ["Masala chai", "Lassi"],
    },
    "th": {
        "fruits": ["Citronnelle", "Galanga", "Feuilles de kaffir", "Basilic thaï", "Citron vert", "Mangue verte", "Papaye verte", "Piment oiseau"],
        "grocery": ["Riz thaï", "Riz glutineux", "Lait de coco", "Curry rouge", "Curry vert", "Nuoc-mâm", "Nouilles de riz", "Sucre de palme", "Pâte de crevettes"],
        "meat": ["Crevettes", "Poulet", "Poisson"],
        "beverages": ["Lait de coco", "Thé"],
    },
    "vi": {
        "fruits": ["Citronnelle", "Coriandre fraîche", "Menthe", "Basilic thaï", "Citron vert", "Germes de soja"],
        "bakery": ["Banh mi", "Feuilles de riz"],
        "meat": ["Poulet", "Bœuf", "Crevettes"],
        "grocery": ["Nouilles pho", "Nuoc-mâm", "Nouilles de riz", "Anis étoilé", "Sauce hoisin"],
    },
    "tr": {
        "fruits": ["Aubergine", "Poivrons", "Tomates", "Ail"],
        "dairy": ["Yaourt grec", "Halloumi"],
        "bakery": ["Simit", "Yufka", "Pain pita"],
        "meat": ["Viande kebab", "Sucuk", "Agneau"],
        "grocery": ["Boulgour", "Sumac", "Mélasse de grenade", "Huile d'olive"],
        "beverages": ["Ayran", "Thé", "Raki"],
    },
    "el": {
        "fruits": ["Concombre", "Tomates", "Aubergine", "Citrons"],
        "dairy": ["Feta", "Yaourt grec", "Halloumi"],
        "bakery": ["Pain pita"],
        "meat": ["Agneau", "Poulet"],
        "grocery": ["Olives kalamata", "Huile d'olive", "Tzatziki"],
        "beverages": ["Ouzo"],
    },
    "es": {
        "fruits": ["Avocats", "Citron vert", "Coriandre fraîche", "Poivrons", "Tomates", "Ail"],
        "dairy": ["Manchego", "Queso fresco"],
        "bakery": ["Tortillas", "Pain"],
        "meat": ["Chorizo", "Jambon serrano", "Poulet"],
        "grocery": ["Huile d'olive", "Paprika fumé", "Pois chiches", "Safran", "Haricots noirs"],
    },
    "pt": {
        "fruits": ["Citron vert", "Coriandre fraîche", "Avocats", "Banane plantain", "Bananes"],
        "grocery": ["Haricots noirs", "Riz rond", "Lait de coco", "Café", "Farine"],
        "meat": ["Poulet", "Bœuf"],
    },
    "it": {
        "fruits": ["Tomates", "Basilic", "Ail", "Olives"],
        "dairy": ["Mozzarella", "Parmesan", "Burrata", "Ricotta", "Mascarpone", "Pecorino"],
        "bakery": ["Ciabatta", "Gnocchi"],
        "meat": ["Prosciutto", "Pancetta"],
        "grocery": ["Passata", "Pesto", "Polenta", "Vinaigre balsamique", "Huile d'olive"],
    },
    "de": {
        "fruits": ["Pommes de terre", "Choucroute", "Aneth"],
        "dairy": ["Quark", "Beurre", "Lait", "Fromage"],
        "bakery": ["Pain de seigle", "Bretzel", "Pain noir"],
        "meat": ["Saumon fumé", "Hareng", "Boulettes de viande"],
        "grocery": ["Spätzle", "Moutarde", "Cornichons"],
        "beverages": ["Bière"],
    },
    "nordic": {
        "fruits": ["Betterave", "Aneth", "Airelles", "Pommes de terre"],
        "dairy": ["Brunost", "Beurre", "Lait"],
        "bakery": ["Knäckebröd", "Pain de seigle"],
        "meat": ["Saumon fumé", "Hareng mariné", "Gravlax", "Boulettes de viande"],
        "grocery": ["Flocons d'avoine"],
        "beverages": ["Café"],
    },
    "pl": {
        "fruits": ["Betterave", "Aneth", "Chou", "Pommes de terre"],
        "dairy": ["Smetana", "Kéfir", "Tvorog"],
        "bakery": ["Pain de seigle"],
        "meat": ["Saucisse polonaise", "Kabanos"],
        "grocery": ["Chou fermenté", "Sarrasin", "Raifort", "Cornichons"],
        "frozen": ["Pierogi"],
    },
    "balkan": {
        "fruits": ["Poivrons", "Tomates", "Ail", "Aubergine"],
        "dairy": ["Kajmak", "Yaourt", "Feta"],
        "bakery": ["Burek", "Pain pita"],
        "meat": ["Viande kebab", "Agneau"],
        "grocery": ["Ajvar", "Huile d'olive"],
    },
    "id": {
        "fruits": ["Citronnelle", "Galanga", "Pandan", "Citron vert", "Piment oiseau", "Ciboule"],
        "dairy": ["Tempeh", "Tofu"],
        "meat": ["Saté", "Poulet"],
        "grocery": ["Riz rond", "Sambal", "Kecap manis", "Lait de coco", "Pâte de crevettes", "Krupuk"],
    },
    "en": {
        "dairy": ["Cheddar", "Beurre", "Lait"],
        "bakery": ["Pain", "Digestives"],
        "meat": ["Bacon", "Poulet", "Steak", "Saumon fumé"],
        "grocery": ["Baked beans", "Flocons d'avoine", "Thé", "Pâtes"],
        "beverages": ["Thé", "Cidre"],
    },
    "fr": {
        "dairy": ["Camembert", "Roquefort", "Comté", "Crème fraîche"],
        "bakery": ["Baguette", "Croissants"],
        "meat": ["Magret de canard", "Jambon"],
        "grocery": ["Herbes de Provence", "Moutarde", "Huile d'olive", "Cornichons"],
        "beverages": ["Vin", "Café"],
    },
}

# Articles de base à masquer (porc, etc.).
HIDE: dict[str, dict[str, list[str]]] = {
    "ar": {"meat": ["Jambon", "Bacon"], "bakery": ["Croissants"]},
    "he": {"meat": ["Jambon", "Bacon"], "bakery": ["Croissants"]},
}

# Langue UI → profil catalogue.
LANG_TO_PROFILE: dict[str, str] = {
    "ja": "ja", "ko": "ko", "zh": "zh",
    "ru": "ru", "uk": "ru", "bg": "ru",
    "ar": "ar", "he": "he",
    "hi": "hi", "th": "th", "vi": "vi",
    "tr": "tr", "el": "el",
    "es": "es", "ca": "es", "eu": "es", "gl": "es",
    "pt": "pt", "it": "it",
    "de": "de", "nl": "de",
    "da": "nordic", "sv": "nordic", "nb": "nordic", "fi": "nordic",
    "pl": "pl", "cs": "pl", "sk": "pl", "hu": "pl",
    "hr": "balkan", "sr": "balkan", "sl": "balkan", "ro": "balkan",
    "lv": "nordic", "lt": "nordic", "et": "nordic",
    "id": "id", "ms": "id",
    "fr": "fr", "en": "en",
}

CATALOG_CAT_LOCAL = {
    "fr": "Spécialités",
    "en": "Local favourites",
    "zh": "地方特色",
    "es": "Especialidades",
    "hi": "स्थानीय पसंदीदा",
    "ar": "تخصصات محلية",
    "pt": "Especialidades",
    "ru": "Местные продукты",
    "ja": "おなじみの食材",
    "de": "Typische Zutaten",
    "ko": "우리 식재료",
    "it": "Specialità",
    "id": "Hidangan khas",
    "nl": "Streekspecialiteiten",
    "tr": "Yöresel lezzetler",
    "pl": "Specjały regionalne",
    "vi": "Đặc sản địa phương",
    "uk": "Місцеві продукти",
    "th": "ของขึ้นชื่อ",
    "sv": "Lokala favoriter",
    "ro": "Specialități locale",
    "hu": "Helyi kedvencek",
    "cs": "Místní speciality",
    "el": "Τοπικά προϊόντα",
    "he": "מוצרים מקומיים",
    "da": "Lokale favoritter",
    "fi": "Paikalliset herkut",
    "nb": "Lokale favoritter",
    "sk": "Miestne špeciality",
    "bg": "Местни продукти",
    "lv": "Vietējie produkti",
    "lt": "Vietiniai produktai",
    "et": "Kohalikud tooted",
    "ca": "Especialitats",
    "eu": "Bertako espezialitateak",
    "gl": "Especialidades",
    "hr": "Lokalni specijaliteti",
    "sr": "Локални специјалитети",
    "sl": "Krajevne dobrote",
    "ms": "Kegemaran tempatan",
}

# Repas : id, labels par locale, keywords, profils (vide = tous), items FR, colorIndex.
MEALS: list[dict] = [
    {
        "id": "sushi",
        "labels": {"fr": "Sushi / sashimi", "en": "Sushi / sashimi", "ja": "寿司・刺身", "ko": "스시 / 사시미", "zh": "寿司 / 生鱼片", "ru": "Суши / сашими", "ar": "سوشي"},
        "keywords": ["sushi", "sashimi", "寿司", "刺身", "스시", "사시미", "суши"],
        "profiles": ["ja"],
        "color": 3,
        "items": ["Riz rond", "Algues nori", "Wasabi", "Sauce soja", "Sashimi", "Gingembre mariné", "Vinaigre de riz", "Avocats", "Concombre"],
    },
    {
        "id": "ramen",
        "labels": {"fr": "Ramen", "en": "Ramen", "ja": "ラーメン", "ko": "라멘", "zh": "拉面", "ru": "Рамен"},
        "keywords": ["ramen", "ラーメン", "らーめん", "라멘", "рамен"],
        "profiles": ["ja"],
        "color": 3,
        "items": ["Nouilles ramen", "Bouillon", "Miso", "Sauce soja", "Ciboule", "Œufs", "Algues nori", "Menma" if False else "Chou", "Porc" if False else "Poulet"],
    },
    {
        "id": "gyoza",
        "labels": {"fr": "Gyoza", "en": "Gyoza", "ja": "餃子", "ko": "교자"},
        "keywords": ["gyoza", "gyoza", "餃子", "饺子", "교자", "гёдза"],
        "profiles": ["ja"],
        "color": 3,
        "items": ["Feuilles de gyoza", "Viande hachée", "Chou", "Ciboule", "Gingembre", "Ail", "Sauce soja", "Huile de sésame"],
    },
    {
        "id": "onigiri",
        "labels": {"fr": "Onigiri", "en": "Onigiri", "ja": "おにぎり", "ko": "오니기리"},
        "keywords": ["onigiri", "おにぎり", "饭团", "오니기리"],
        "profiles": ["ja"],
        "color": 8,
        "items": ["Riz rond", "Algues nori", "Umeboshi", "Thon" if False else "Saumon", "Furikake", "Sel"],
    },
    {
        "id": "yakitori",
        "labels": {"fr": "Yakitori", "en": "Yakitori", "ja": "焼き鳥"},
        "keywords": ["yakitori", "焼き鳥", "야키토리", "brochettes"],
        "profiles": ["ja"],
        "color": 3,
        "items": ["Poulet", "Ciboule", "Sauce teriyaki", "Sauce soja", "Mirin", "Saké"],
    },
    {
        "id": "miso_soup",
        "labels": {"fr": "Soupe miso", "en": "Miso soup", "ja": "味噌汁", "ko": "미소된장국"},
        "keywords": ["miso", "味噌汁", "みそ汁", "미소국"],
        "profiles": ["ja"],
        "color": 1,
        "items": ["Miso", "Dashi", "Tofu", "Algues wakame", "Ciboule"],
    },
    {
        "id": "bulgogi",
        "labels": {"fr": "Bulgogi", "en": "Bulgogi", "ja": "プルコギ", "ko": "불고기"},
        "keywords": ["bulgogi", "불고기", "プルコギ", "бульгоги"],
        "profiles": ["ko"],
        "color": 3,
        "items": ["Bœuf", "Sauce soja", "Huile de sésame", "Ail", "Poire asiatique", "Ciboule", "Sésame", "Riz rond"],
    },
    {
        "id": "kimchi_jjigae",
        "labels": {"fr": "Kimchi jjigae", "en": "Kimchi stew", "ko": "김치찌개", "ja": "キムチチゲ"},
        "keywords": ["kimchi", "jjigae", "김치찌개", "김치", "кимчи"],
        "profiles": ["ko"],
        "color": 0,
        "items": ["Kimchi", "Tofu", "Ciboule", "Ail", "Gochugaru", "Doenjang", "Bouillon"],
    },
    {
        "id": "samgyeopsal",
        "labels": {"fr": "Samgyeopsal", "en": "Samgyeopsal", "ko": "삼겹살"},
        "keywords": ["samgyeopsal", "삼겹살", "サムギョプサル"],
        "profiles": ["ko"],
        "color": 3,
        "items": ["Samgyeopsal", "Feuilles de périlla", "Ssamjang", "Ail", "Kimchi", "Riz rond", "Banchan", "Soju"],
    },
    {
        "id": "tteokbokki",
        "labels": {"fr": "Tteokbokki", "en": "Tteokbokki", "ko": "떡볶이"},
        "keywords": ["tteokbokki", "tteok", "떡볶이", "떡"],
        "profiles": ["ko"],
        "color": 0,
        "items": ["Tteok", "Gochujang", "Gochugaru", "Galette de poisson", "Ciboule", "Sucre", "Sauce soja"],
    },
    {
        "id": "bibimbap",
        "labels": {"fr": "Bibimbap", "en": "Bibimbap", "ko": "비빔밥"},
        "keywords": ["bibimbap", "비빔밥", "ビビンバ"],
        "profiles": ["ko"],
        "color": 1,
        "items": ["Riz rond", "Gochujang", "Épinards", "Germes de soja", "Carottes", "Œufs", "Huile de sésame", "Bœuf"],
    },
    {
        "id": "bortsch",
        "labels": {"fr": "Bortsch", "en": "Borscht", "ru": "Борщ", "uk": "Борщ", "pl": "Barszcz"},
        "keywords": ["bortsch", "borscht", "борщ", "borshch", "barszcz"],
        "profiles": ["ru", "pl"],
        "color": 1,
        "items": ["Betterave", "Chou", "Carottes", "Pommes de terre", "Aneth", "Smetana", "Bouillon", "Ail"],
    },
    {
        "id": "chachlik",
        "labels": {"fr": "Chachlik", "en": "Shashlik", "ru": "Шашлык", "uk": "Шашлик", "de": "Schaschlik"},
        "keywords": ["chachlik", "shashlik", "шашлык", "шашлик", "schaschlik", "szaszlyk"],
        "profiles": ["ru"],
        "color": 3,
        "items": ["Chachlik", "Oignons", "Adjika", "Pain noir", "Aneth", "Huile de tournesol"],
    },
    {
        "id": "pelmeni",
        "labels": {"fr": "Pelmeni", "en": "Pelmeni", "ru": "Пельмени"},
        "keywords": ["pelmeni", "пельмени", "вареники"],
        "profiles": ["ru"],
        "color": 3,
        "items": ["Pelmeni", "Smetana", "Aneth", "Beurre", "Raifort"],
    },
    {
        "id": "blinis",
        "labels": {"fr": "Blinis", "en": "Blinis", "ru": "Блины"},
        "keywords": ["blini", "blinis", "блины", "млинці"],
        "profiles": ["ru"],
        "color": 2,
        "items": ["Blinis", "Smetana", "Saumon fumé", "Hareng", "Aneth", "Kéfir"],
    },
    {
        "id": "couscous",
        "labels": {"fr": "Couscous", "en": "Couscous", "ar": "كسكس", "fr2": "Couscous"},
        "keywords": ["couscous", "كسكس", "كسكسي", "seksu"],
        "profiles": ["ar", "fr"],
        "color": 1,
        "items": ["Semoule", "Pois chiches", "Carottes", "Courgettes", "Merguez", "Agneau", "Harissa", "Navets" if False else "Oignons"],
    },
    {
        "id": "tajine",
        "labels": {"fr": "Tajine", "en": "Tagine", "ar": "طاجين"},
        "keywords": ["tajine", "tagine", "طاجين", "طاجن"],
        "profiles": ["ar", "fr"],
        "color": 3,
        "items": ["Agneau", "Citrons confits", "Olives", "Ras el hanout", "Safran", "Ail", "Oignons", "Huile d'olive"],
    },
    {
        "id": "houmous_meal",
        "labels": {"fr": "Houmous & mezze", "en": "Hummus & mezze", "ar": "حمص ومزة", "he": "חומוס ומזה"},
        "keywords": ["houmous", "hummus", "mezze", "حمص", "חומוס", "falafel"],
        "profiles": ["ar", "he", "el", "tr"],
        "color": 1,
        "items": ["Pois chiches", "Tahini", "Citron", "Ail", "Huile d'olive", "Pain pita", "Falafel", "Labneh", "Olives"],
    },
    {
        "id": "falafel",
        "labels": {"fr": "Falafel", "en": "Falafel", "ar": "فلافل", "he": "פלאפל"},
        "keywords": ["falafel", "فلافل", "פלאפל"],
        "profiles": ["ar", "he"],
        "color": 1,
        "items": ["Pois chiches", "Ail", "Coriandre fraîche", "Cumin", "Pain pita", "Tahini", "Tomates", "Concombre"],
    },
    {
        "id": "mapo_tofu",
        "labels": {"fr": "Mapo tofu", "en": "Mapo tofu", "zh": "麻婆豆腐", "ja": "麻婆豆腐"},
        "keywords": ["mapo", "麻婆", "마파두부"],
        "profiles": ["zh"],
        "color": 0,
        "items": ["Tofu", "Viande hachée", "Doubanjiang", "Ail", "Gingembre", "Ciboule", "Huile de piment", "Sauce soja"],
    },
    {
        "id": "dumplings",
        "labels": {"fr": "Raviolis / jiaozi", "en": "Dumplings", "zh": "饺子", "ja": "餃子"},
        "keywords": ["dumpling", "jiaozi", "饺子", "만두", "wonton"],
        "profiles": ["zh"],
        "color": 3,
        "items": ["Feuilles de gyoza", "Chou chinois", "Ciboule", "Gingembre", "Viande hachée", "Sauce soja", "Vinaigre de riz"],
    },
    {
        "id": "curry_in",
        "labels": {"fr": "Curry", "en": "Curry", "hi": "करी"},
        "keywords": ["curry", "करी", "कड़ी", "masala"],
        "profiles": ["hi"],
        "color": 8,
        "items": ["Riz basmati", "Garam masala", "Curcuma", "Cumin", "Ghee", "Oignons", "Tomates", "Ail", "Gingembre", "Yaourt"],
    },
    {
        "id": "dal",
        "labels": {"fr": "Dal", "en": "Dal", "hi": "दाल"},
        "keywords": ["dal", "daal", "दाल", "lentilles"],
        "profiles": ["hi"],
        "color": 8,
        "items": ["Lentilles corail", "Curcuma", "Cumin", "Ail", "Gingembre", "Ghee", "Asafoetida", "Feuilles de curry"],
    },
    {
        "id": "pad_thai",
        "labels": {"fr": "Pad thaï", "en": "Pad Thai", "th": "ผัดไทย"},
        "keywords": ["pad thai", "padthai", "ผัดไทย"],
        "profiles": ["th"],
        "color": 8,
        "items": ["Nouilles de riz", "Tamarin", "Nuoc-mâm", "Sucre de palme", "Crevettes", "Ciboule", "Germes de soja", "Cacahuètes", "Citron vert", "Œufs"],
    },
    {
        "id": "tom_yum",
        "labels": {"fr": "Tom yum", "en": "Tom yum", "th": "ต้มยำ"},
        "keywords": ["tom yum", "tomyum", "ต้มยำ"],
        "profiles": ["th"],
        "color": 0,
        "items": ["Citronnelle", "Galanga", "Feuilles de kaffir", "Citron vert", "Piment oiseau", "Nuoc-mâm", "Crevettes", "Champignons" if False else "Shiitake"],
    },
    {
        "id": "pho",
        "labels": {"fr": "Phở", "en": "Pho", "vi": "Phở"},
        "keywords": ["pho", "phở", "vietnam"],
        "profiles": ["vi"],
        "color": 1,
        "items": ["Nouilles pho", "Bœuf", "Anis étoilé", "Gingembre", "Ciboule", "Germes de soja", "Coriandre fraîche", "Citron vert", "Nuoc-mâm"],
    },
    {
        "id": "kebab",
        "labels": {"fr": "Kebab", "en": "Kebab", "tr": "Kebap", "el": "Κεμπάπ"},
        "keywords": ["kebab", "kebap", "döner", "gyros", "شاورما"],
        "profiles": ["tr", "el", "ar", "de"],
        "color": 3,
        "items": ["Viande kebab", "Pain pita", "Tomates", "Oignons", "Yaourt", "Salade", "Poivrons"],
    },
    {
        "id": "meze",
        "labels": {"fr": "Mezzé", "en": "Meze", "tr": "Meze", "el": "Μεζές", "he": "מזה"},
        "keywords": ["meze", "mezze", "μεζέ", "מזה"],
        "profiles": ["tr", "el", "he"],
        "color": 1,
        "items": ["Houmous", "Tzatziki", "Feuilles de vigne", "Feta", "Olives kalamata", "Pain pita", "Aubergine", "Huile d'olive"],
    },
    {
        "id": "paella",
        "labels": {"fr": "Paella", "en": "Paella", "es": "Paella"},
        "keywords": ["paella", "paella"],
        "profiles": ["es"],
        "color": 8,
        "items": ["Riz rond", "Safran", "Crevettes", "Poulet", "Poivrons", "Tomates", "Ail", "Huile d'olive", "Citron"],
    },
    {
        "id": "gazpacho",
        "labels": {"fr": "Gaspacho", "en": "Gazpacho", "es": "Gazpacho"},
        "keywords": ["gazpacho", "gaspacho"],
        "profiles": ["es"],
        "color": 1,
        "items": ["Tomates", "Concombre", "Poivrons", "Ail", "Huile d'olive", "Pain", "Vinaigre"],
    },
    {
        "id": "risotto",
        "labels": {"fr": "Risotto", "en": "Risotto", "it": "Risotto"},
        "keywords": ["risotto"],
        "profiles": ["it"],
        "color": 2,
        "items": ["Riz rond", "Parmesan", "Beurre", "Oignons", "Bouillon", "Vin blanc"],
    },
    {
        "id": "schnitzel",
        "labels": {"fr": "Schnitzel", "en": "Schnitzel", "de": "Schnitzel"},
        "keywords": ["schnitzel", "escalope"],
        "profiles": ["de"],
        "color": 3,
        "items": ["Poulet", "Panko", "Œufs", "Farine", "Citron", "Pommes de terre"],
    },
    {
        "id": "pierogi_meal",
        "labels": {"fr": "Pierogi", "en": "Pierogi", "pl": "Pierogi"},
        "keywords": ["pierogi", "pirohy", "варeники"],
        "profiles": ["pl"],
        "color": 2,
        "items": ["Pierogi", "Smetana", "Oignons", "Beurre", "Chou fermenté"],
    },
    {
        "id": "nasi_goreng",
        "labels": {"fr": "Nasi goreng", "en": "Nasi goreng", "id": "Nasi goreng", "ms": "Nasi goreng"},
        "keywords": ["nasi goreng", "nasi", "nasi goreng"],
        "profiles": ["id"],
        "color": 8,
        "items": ["Riz rond", "Kecap manis", "Sambal", "Ail", "Ciboule", "Œufs", "Saté", "Krupuk"],
    },
    {
        "id": "satay",
        "labels": {"fr": "Saté", "en": "Satay", "id": "Sate", "ms": "Satay"},
        "keywords": ["sate", "satay", "saté"],
        "profiles": ["id"],
        "color": 3,
        "items": ["Saté", "Cacahuètes", "Kecap manis", "Citronnelle", "Ail", "Sambal", "Riz rond"],
    },
    {
        "id": "kottbullar",
        "labels": {"fr": "Boulettes", "en": "Meatballs", "sv": "Köttbullar", "nb": "Kjøttkaker"},
        "keywords": ["kottbullar", "köttbullar", "meatballs", "frikadeller"],
        "profiles": ["nordic"],
        "color": 3,
        "items": ["Boulettes de viande", "Pommes de terre", "Airelles", "Aneth", "Beurre", "Crème fraîche"],
    },
    {
        "id": "full_english",
        "labels": {"fr": "English breakfast", "en": "Full English", "en2": "Full English"},
        "keywords": ["english breakfast", "full english", "fry up"],
        "profiles": ["en"],
        "color": 3,
        "items": ["Bacon", "Œufs", "Baked beans", "Tomates", "Pain", "Beurre", "Thé"],
    },
]

BREAKFAST: dict[str, list[str]] = {
    "ja": ["Riz rond", "Miso", "Algues nori", "Natto", "Umeboshi", "Thé sencha", "Œufs", "Saumon"],
    "ko": ["Riz rond", "Kimchi", "Banchan", "Œufs", "Soupe" if False else "Doenjang", "Gim", "Thé"],
    "zh": ["Riz rond", "Bouillon", "Ciboule", "Œufs", "Thé", "Baozi", "Lait de soja" if False else "Tofu"],
    "ru": ["Sarrasin", "Tvorog", "Kéfir", "Blinis", "Pain noir", "Beurre", "Thé"],
    "ar": ["Khobz", "Huile d'olive", "Labneh", "Dattes", "Olives", "Thé à la menthe", "Msemen", "Amlou"],
    "he": ["Pain pita", "Houmous", "Labneh", "Olives", "Œufs", "Salade", "Thé"],
    "hi": ["Chapati", "Yaourt", "Lentilles corail", "Masala chai", "Œufs", "Chutney"],
    "th": ["Riz thaï", "Riz glutineux", "Lait de coco", "Œufs", "Nuoc-mâm", "Citronnelle"],
    "vi": ["Nouilles pho", "Banh mi", "Café", "Œufs", "Nuoc-mâm"],
    "tr": ["Simit", "Yaourt grec", "Fromage", "Olives", "Thé", "Œufs", "Sucuk"],
    "el": ["Yaourt grec", "Miel", "Pain", "Feta", "Olives kalamata", "Café"],
    "es": ["Pain", "Tomates", "Huile d'olive", "Café", "Jambon serrano", "Œufs"],
    "pt": ["Pain", "Café", "Beurre", "Fromage", "Fruits"],
    "it": ["Café", "Brioche", "Jam" if False else "Confiture", "Lait"],
    "de": ["Pain de seigle", "Beurre", "Confiture", "Fromage", "Café", "Œufs"],
    "nordic": ["Knäckebröd", "Beurre", "Fromage", "Café", "Flocons d'avoine", "Saumon fumé"],
    "pl": ["Pain de seigle", "Tvorog", "Beurre", "Confiture", "Thé", "Œufs"],
    "balkan": ["Pain", "Kajmak", "Ajvar", "Œufs", "Yaourt", "Café"],
    "id": ["Riz rond", "Œufs", "Sambal", "Thé", "Tempeh"],
    "en": ["Pain", "Beurre", "Œufs", "Bacon", "Thé", "Lait", "Flocons d'avoine"],
    "fr": ["Pain", "Beurre", "Confiture", "Café", "Lait", "Jus d'orange", "Œufs"],
}

BREAKFAST["ko"] = ["Riz rond", "Kimchi", "Banchan", "Œufs", "Doenjang", "Gim", "Thé"]
BREAKFAST["zh"] = ["Riz rond", "Bouillon", "Ciboule", "Œufs", "Thé", "Baozi", "Tofu"]
BREAKFAST["it"] = ["Café", "Brioche", "Confiture", "Lait"]

# Nettoyage items repas (sentinelles).
for _m in MEALS:
    _m["items"] = [x for x in _m["items"] if isinstance(x, str)]
    if _m["id"] == "ramen":
        _m["items"] = ["Nouilles ramen", "Bouillon", "Miso", "Sauce soja", "Ciboule", "Œufs", "Algues nori", "Poulet"]
    if _m["id"] == "onigiri":
        _m["items"] = ["Riz rond", "Algues nori", "Umeboshi", "Saumon", "Furikake", "Sel"]
    if _m["id"] == "couscous":
        _m["items"] = ["Semoule", "Pois chiches", "Carottes", "Courgettes", "Merguez", "Agneau", "Harissa", "Oignons"]
    if _m["id"] == "tom_yum":
        _m["items"] = ["Citronnelle", "Galanga", "Feuilles de kaffir", "Citron vert", "Piment oiseau", "Nuoc-mâm", "Crevettes", "Shiitake"]

BREAKFAST_KEYWORDS = {
    "ja": ["asagohan", "朝食", "朝ごはん", "breakfast"],
    "ko": ["아침", "아침식사", "breakfast"],
    "ru": ["завтрак", "сніданок"],
    "ar": ["فطور", "افطار", "إفطار"],
    "zh": ["早餐", "早饭"],
    "hi": ["नाश्ता"],
    "th": ["อาหารเช้า"],
    "vi": ["bữa sáng"],
    "he": ["ארוחת בוקר"],
    "tr": ["kahvaltı"],
    "el": ["πρωινό"],
}

UNIVERSAL_MEAL_IDS = ["pizza", "salade", "soupe", "burger", "tacos"]
WESTERN_MEAL_IDS = ["raclette", "apero", "barbecue", "carbonara", "fondue", "crepes"]


def _merge_europe() -> None:
    from regional_europe_data import apply_europe
    apply_europe(
        PRODUCTS,
        LOCAL_LISTS,
        EXTRAS,
        LANG_TO_PROFILE,
        MEALS,
        BREAKFAST,
        EMOJI,
        BREAKFAST_KEYWORDS,
    )


_merge_europe()
